### ISSUE TITLE
[KED-2956] When `before_node_run` hook mutates the catalog, the immediate node doesn't get the updated catalog

### ISSUE THREAD

**Issue by lorenabalan** [kedro-org/kedro#1033]
## Description
First raised by @maria-olivia-lihn, who found it while working in Databricks, Python 3.8, Kedro 0.17.5.

## Context
_How has this bug affected you? What were you trying to accomplish?_

Mutate the catalog (i.e. update parameters) dynamically inside a node hook - `before_node_run`.

## Steps to Reproduce
1. `kedro new -s pandas-iris`

The structure of the pipeline looks like this:
<img src="https://user-images.githubusercontent.com/6642900/148373315-ea65e0e0-96fd-435f-a575-62bb3ab6497e.png"  height="650">

2. update `hooks.py` with the following:

```python
    @hook_impl
    def before_node_run(self, node, catalog):
        if node.name == "train":
            new_parameter = MemoryDataSet(data=0.05)
            catalog.add("params:example_learning_rate", new_parameter, replace=True)

        logger.info("CONTENTS OF params:example_learning_rate")
        logger.info(catalog.load("params:example_learning_rate"))
```

Make sure there's a logger at the top of the file
```python
logger = logging.getLogger(__name__)
```

3. update the signature of the node function `train_model` in `src/package_name/data_science/nodes.py` and add a logging statement:

```python
def train_model(
    train_x: pd.DataFrame, train_y: pd.DataFrame, num_iter, lr,
) -> np.ndarray:
    """Node for training a simple multi-class logistic regression model. The
    number of training iterations as well as the learning rate are taken from
    conf/project/parameters.yml. All of the data as well as the parameters
    will be provided to this function at the time of execution.
    """
    log.info("VALUE OF example_learning_rate is %f", lr)
    X = train_x.to_numpy()
    Y = train_y.to_numpy()
```

`log` comes from `log = logging.getLogger(__name__)` which I've moved to the top from inside `report_accuracy()`.

4. update the pipeline definition in `src/package_name/data_science/pipeline.py` for the following `node`

```python
node(
    train_model,
    ["example_train_x", "example_train_y", "params:example_num_train_iter", "params:example_learning_rate"],
    "example_model",
    name="train",
),
```

5. `kedro run`

## Expected Result

`train` node would log `VALUE OF example_learning_rate is 0.05` (update value from the hook).

## Actual Result

`train` node logs `VALUE OF example_learning_rate is 0.01` (original value in `parameters.yml`.

## Workaround 

Moving the mutating behaviour to a node upstream, e.g. `split`, ensures that nodes downstream actually get the updated version of the catalog object.

Not entirely sure what's going on yet, if it's a back-to-pass-by-reference-basics journey or not, needs more investigation.

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.5
* Python version used (`python -V`): 3.7
* Operating system and version: Mac

**Comment by hec10r** [comment]
This is not a bug, it was explicitly designed to work this way. The idea, according to what I understand, is that you don't want to modify the catalog for all the nodes, so this hook doesn't aim to mutate the _global_ catalog, but return a new one for certain nodes.  [See](https://github.com/quantumblacklabs/kedro/blob/0.17.5/kedro/runner/runner.py#L232).

For your use case, see [this](https://kedro.readthedocs.io/en/latest/07_extend_kedro/02_hooks.html#modify-node-inputs-using-before-node-run-hook):
![image](https://user-images.githubusercontent.com/53947956/141724403-a378f169-b723-4af5-970b-aa22f12b732e.png)

**Comment by lorenabalan** [comment]
Hey @hec10r thanks for jumping in. I'm aware of this side of the implementation (returning a dict to update a node's inputs), however my understanding is that this is only for one node, not for all references of that parameter downstream. My understanding was, and @maria-olivia-lihn can keep me honest here, that the update should trickle down to downstream nodes, and `after_catalog_created` was too early in the execution timeline for this to happen. 

Tagging @limdauto who might have more context around the design as well.

**Comment by hec10r** [comment]
If you want to change the parameters for a set of nodes, maybe using a `tag` is the best way?

**Comment by lorenabalan** [comment]
So after coming back to this, I could see more clearly what is happening. 

If we look at [these lines in the runner code](https://github.com/quantumblacklabs/kedro/blob/main/kedro/runner/runner.py#L261-L280), we can see that the `inputs` are already loaded by the time we reach `_collect_input_from_hook`, where the `before_node_run` hook [is called](https://github.com/quantumblacklabs/kedro/blob/main/kedro/runner/runner.py#L207). Therefore, the `train` node won't have access to the updated catalog (unless the relevant inputs are returned by the hook as a dictionary), but the downstream nodes will. So @hec10r was also right that part of this was intentionally designed.

So the solution is to simply make the node hook also return `{"params:example_learning_rate": 0.05}`.

I will caveat this with the fact that hooks with side effects are generally **discouraged**, as it makes the pipelines harder to reason about. The suggestions at the time were:
a) use `after_catalog_created` instead (but that was too early in the execution timeline, as mentioned above)
b) use datasets instead of parameters - write to a dataset that can be used as a dependency to a node downstream; I remember @maria-olivia-lihn had a reason for why that wouldn't fit the use case - would you mind reminding me here if you can recall?

**Comment by maria-olivia-lihn** [comment]
Thanks @lorenabalan. Using a dataset is not the best idea as the parameters have to either be computed from a dataset which is product of a previous node, or using another input. To make it more clear: we need the option to set the parameter "last_date" either automatically from an output dataset (using last data available) or using input from execution (depending on "automatic" parameter). Once the "last_date" is set, we need to calculate "start_date" as 6 months before "last_date" and an additional parameter which is 2 months before "last_date". 
At the time, I couldn't figure out how to do this using datasets so I thought it would be easier to use hooks and parameters. Right now i changed the hooks execution to one node before and everything runs in place.

**Comment by lorenabalan** [comment]
Thank you @maria-olivia-lihn for providing more context. And by "input from execution" do you mean a parameter that's passed to `kedro run` or something else?

**Comment by maria-olivia-lihn** [comment]
Parameters in kedro run

**Comment by lorenabalan** [comment]
Thanks for clarifying. For the purpose of this issue, I'm going to close it as not a bug. However feel free to raise the question about your particular use case either in a GitHub discussion or, maybe even better, on our Discord channels, to engage our community, as they might have come across a similar pattern before.
