### ISSUE TITLE
Custom file name part for versioned datasets

### ISSUE THREAD

**Issue by clstaudt** [kedro-org/kedro#1069]
## Description
Is it possible to modify the file naming of versioned data sets to add a user-defined string (e.g. a git commit hash)?

## Context
I need a solution to link pipeline output to a version of the pipeline, not just a date/time.

## Possible Implementation

user-defined function for file name formatting for versioned data sets.

## Possible Alternatives

Circumventing the data catalog for file creation - not preferred.

**Comment by datajoely** [comment]
Ho @clstaudt interesting question. I think I've managed to do this by tweaking the `save_version` passed to the data catalog on registration:

![image](https://user-images.githubusercontent.com/35801847/143438150-bd000492-e5be-4eb7-9ef9-94ae39cb323d.png)

This then writes a new versioned dataset with the following filename (you can see previous runs without this):

![image](https://user-images.githubusercontent.com/35801847/143438228-3f9d8c7d-9df4-4dad-a856-1b43c84684a2.png)

Now there is one thing to be aware of - the naming of versioned dataset must be alphabetically sortable. This is why I've prepended the hash with the original timestamp. If you just use the hash Kedro will lose its place.

**Comment by MerelTheisenQB** [comment]
Hi @clstaudt do you need more help with this issue or can we close it?

**Comment by clstaudt** [comment]
@MerelTheisenQB  Thanks. I believe I would need more help: It's not immediately clear to me how to apply the solution proposed by @datajoely. Where do I find the `register_catalog` function? It is not in my Kedro-based project.

**Comment by datajoely** [comment]
Hi @clstaudt  - I should have asked what version of Kedro you're running. In a newer version of Kedro this will be in `settings.py`

**Comment by clstaudt** [comment]
Thanks @datajoely. I'm running an older version of Kedro but planning to migrate the project in April. Then I will be able to test the solution.

**Comment by datajoely** [comment]
Awesome! With each `x.x.0` release we include a [migration guide](https://github.com/kedro-org/kedro/releases/tag/0.17.0) (this is the 0.16.x -> 0.17.x guide for reference)

**Comment by MerelTheisenQB** [comment]
Closing this for now as the requested functionality is already available. @clstaudt feel free to open a new issue if you're still having problems after upgrading to a newer Kedro version!
