### ISSUE TITLE
Running `kedro install` , `kedro ipython` or `kedro jupyter notebook` from my project root, I get `No such command` errors

### ISSUE THREAD

**Issue by AndrewLaganaro** [kedro-org/kedro#1091]
## Description
When running `kedro install` , `kedro ipython` or `kedro jupyter notebook` from my project root, I get `No such command` errors.

## Context
I've just intalled kedro on a new env and I'm trying to use it on a notebook.` jupyter notebook` command works normally, opening a fully functional notebook instance. Same doesn't happens with  `kedro jupyter notebook`

## Steps to Reproduce
1. Created new conda env, installed jupyter notebook and kedro
2. use `kedro jupyter notebook` or `kedro install`

## Expected Result
Kedro with notebook should open
## Actual Result
An error occurs:
```
Usage: kedro [OPTIONS] COMMAND [ARGS]...
Try 'kedro -h' for help
No such command 'jupyter'
```

```
Usage: kedro [OPTIONS] COMMAND [ARGS]...
Try 'kedro -h' for help
No such command 'install'
```
## Your Environment
* Kedro: 0.17.5
* Python: 3.6.12
* OS: Windows 10

**Comment by datajoely** [comment]
Hi @AndrewLaganaro if you type `which python` does it point to the conda environment you created? Also if you do `pip freeze` can you see Kedro in the active python environment? 

This error usually means that something is up with the active environment.

**Comment by shawnboltz** [comment]
I'm having the same issue in a new conda environment (Installed about a month ago, just barely got around to using it today). I was able to use `kedro run` to run a pipeline just fine, but now I'm not able to launch `kedro jupyter lab`, saying that it doesn't recognize `jupyter` (jupyter is installed in the environment and I can run it separately).

Kedro: 0.17.0
Python: 3.8.12
OS: Ubuntu 16.04

Relevant lines from `pip freeze`:
jupyter @ file:///home/conda/feedstock_root/build_artifacts/jupyter_1637233111631/work
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1640335223713/work
jupyter-console @ file:///home/conda/feedstock_root/build_artifacts/jupyter_console_1616560109969/work
jupyter-core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1636814262349/work
jupyter-server @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_1635811281209/work
jupyterlab==0.31.1
jupyterlab-launcher==0.10.5
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1601375948261/work
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1632590716858/work
jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1631590465624/work
kedro==0.17.0

**Comment by datajoely** [comment]
Hi @shawnboltz - this is a bit peculiar. Two quick questions - are you tied to this environment and are you tied to v0.17.0 as that's quite old now. If possible can we try with a new env and the latest version ok Kedro?

**Comment by shawnboltz** [comment]
Hi @datajoely, I can do some testing with a new environment no problem and will give that a shot. As far as the kedro version, I'll have to see what all has changed. I have some custom hooks that I use that tend to break pretty badly between updates and this is for a project that I just need to do really quick.

But I will try and see how things go.

**Comment by shawnboltz** [comment]
All right @datajoely, I just created a new environment using Python 3.8.12 and Kedro 0.17.6 and I am getting the same error. Here are the lines from `pip freeze` again, if that helps at all:
jupyter @ file:///home/conda/feedstock_root/build_artifacts/jupyter_1637233111631/work
jupyter-client==6.1.12
jupyter-console @ file:///home/conda/feedstock_root/build_artifacts/jupyter_console_1616560109969/work
jupyter-core @ file:///home/conda/feedstock_root/build_artifacts/jupyter_core_1636814262349/work
jupyter-server @ file:///home/conda/feedstock_root/build_artifacts/jupyter_server_1639084645710/work
jupyterlab @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_1641589478886/work
jupyterlab-pygments @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_pygments_1601375948261/work
jupyterlab-server @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_server_1641592475363/work
jupyterlab-widgets @ file:///home/conda/feedstock_root/build_artifacts/jupyterlab_widgets_1631590465624/work
kedro==0.17.6

**Comment by AntonyMilneQB** [comment]
Hi @shawnboltz, this is a weird one. Just to diagnose a bit further please can you try each of the following, and tell me whether it works or if not paste the full error message here?
1. `kedro ipython`
2. `kedro jupyter`
3. `kedro jupyter notebook`
4. `kedro jupyter lab`

**Comment by shawnboltz** [comment]
@AntonyMilneQB, it is weird indeed. I feel like it's probably user error because I'm dusting it off after not having used it in a few months... and today it is actually working in both the new test environment and the original environment for reasons I can't explain.

For completeness, here are the outputs using my new environment:
```
(kedro_test_environment) user@computer:~/path/to/kedro/project$ kedro ipython
-------------------------------------------------------------------------------
Starting a Kedro session with the following variables in scope
startup_error, context
Use the line magic %reload_kedro to refresh them
or to see the error message if they are undefined
-------------------------------------------------------------------------------
ipython
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.31.0 -- An enhanced Interactive Python. Type '?' for help.
{error from my project hooks complaining about a package I haven't installed in this environment yet}
```

```
(kedro_test_environment) user@computer:~/path/to/kedro/project$ kedro jupyter
Usage: kedro jupyter [OPTIONS] COMMAND [ARGS]...

  Open Jupyter Notebook / Lab with project specific variables loaded, or
  convert notebooks into Kedro code.

Options:
  -h, --help  Show this message and exit.

Commands:
  convert   Convert selected or all notebooks found in a Kedro project to...
  lab       Open Jupyter Lab with project specific variables loaded.
  notebook  Open Jupyter Notebook with project specific variables loaded.
```

```
(kedro_test_environment) user@computer:~/path/to/kedro/project$ kedro jupyter notebook
{error from my project hooks complaining about a package I haven't installed in this environment yet}
```

```
(kedro_test_environment) user@computer:~/path/to/kedro/project$ kedro jupyter lab
{error from my project hooks complaining about a package I haven't installed in this environment yet}
```

```
(kedro_test_environment) user@computer:~/path/to/kedro/project$ which jupyter
/home/user/anaconda3/envs/kedro_test_environment/bin/jupyter
```

```
(kedro_test_environment) user@computer:~/path/to/kedro/project$ which kedro
/home/user/anaconda3/envs/kedro_test_environment/bin/kedro
```

From the original environment (no idea what is different from before...):
```
(original_environment) user@computer:~/path/to/kedro/project$ kedro ipython
-------------------------------------------------------------------------------
Starting a Kedro session with the following variables in scope
startup_error, context
Use the line magic %reload_kedro to refresh them
or to see the error message if they are undefined
-------------------------------------------------------------------------------
ipython
Python 3.8.12 | packaged by conda-forge | (default, Oct 12 2021, 21:59:51) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.29.0 -- An enhanced Interactive Python. Type '?' for help.
```

```
(original_environment) user@computer:~/path/to/kedro/project$ kedro jupyter
Usage: kedro jupyter [OPTIONS] COMMAND [ARGS]...

  Open Jupyter Notebook / Lab with project specific variables loaded, or
  convert notebooks into Kedro code.

Options:
  -h, --help  Show this message and exit.

Commands:
  convert   Convert selected or all notebooks found in a Kedro project to...
  lab       Open Jupyter Lab with project specific variables loaded.
  notebook  Open Jupyter Notebook with project specific variables loaded.
```

```
(original_environment) user@computer:~/path/to/kedro/project$ kedro jupyter notebook
-------------------------------------------------------------------------------
Starting a Kedro session with the following variables in scope
startup_error, context
Use the line magic %reload_kedro to refresh them
or to see the error message if they are undefined
The choice of kernels is limited to the default one.
(restart with --all-kernels to get access to others)
-------------------------------------------------------------------------------
/home/user/anaconda3/envs/original_environment/bin/python -m jupyter notebook --ip 127.0.0.1 --MappingKernelManager.cull_idle_timeout=30 --MappingKernelManager.cull_interval=30 --NotebookApp.kernel_spec_manager_class=kedro.framework.cli.jupyter.SingleKernelSpecManager '--KernelSpecManager.default_kernel_name='"'"'KedroProject"'"''
{normal startup information}
```

etc.

I suppose I will keep you posted if the error shows up again?

Thanks for your help.

**Comment by datajoely** [comment]
Do shout if it plays up again @shawnboltz - for now we'll close the issue :)

**Comment by machiel-jumbo** [comment]
My user error was not running kedro from the root of the project. Kedro still runs from any location, but only from the project root you'll get the full set of commands.

**Comment by brusmichal** [comment]
For anyone who might come across this issue. Remove kedro with pip, restart, and then reinstall it with conda "conda install -c conda-forge kedro" (if that's what you're using). It worked for me.
