### ISSUE TITLE
Overriding `cli.py` CLI commands is not well-documented

### ISSUE THREAD

**Issue by deepyaman** [kedro-org/kedro#1133]
I understand that this saves space, but I feel like it would be very confusing to somebody less familiar with Kedro to figure out what to do here. This is especially true given `cli.py` has not been included as part of the project template since 0.17.5, and I don't see step-by-step documentation on how to set something like this up (e.g. I know I can go back to 0.17.4 template to find something like what I need).

_Originally posted by @deepyaman in https://github.com/quantumblacklabs/kedro/pull/1131#discussion_r775738911_

**Comment by datajoely** [comment]
You're absolutely right- I thought this was already in there - we don't even have any messages in `cli.py`. I'll create a ticket for this.

**Comment by datajoely** [comment]
I can't remember one, there is a chance this was scoped up with the Rich stuff

**Comment by stichbury** [comment]
This is the second-oldest docs ticket outstanding and I wanted to check if it's still valid @deepyaman @datajoely and @noklam 

Please can you let me know and whether this is something to prioritise

**Comment by datajoely** [comment]
I think a `kedro init` workflow would be the right solution here

**Comment by noklam** [comment]
I think this is still valid. #2384 is a proposal to remove it, there is no consensus yet and I don't think we are gonna remove it without introducing a new tooling. i.e.`kedro init` or other alternative. 

If we want to do this as a short/mid term effort, the minimal things we need to do is put the template in docs and explain how it could be modified.

I have an example here:
- Extend as plugin - https://github.com/noklam/kedro_gallery/blob/master/kedro-cli-plugin/setup.py
- Overriding CLI commands - https://github.com/noklam/kedro_gallery/tree/master/kedro_cli_extension

See:
- #2384

**Comment by noklam** [comment]
Cc @amandakys as I think the `kedro init` conversation is closely related to the ongoing plugin user research.

**Comment by stichbury** [comment]
I'm revisiting this and I still struggle to see this as a docs ticket. It looks as if there's discussion of alternative approaches that would replace use of `cli.py` customisation. But even if there weren't, there is agreement this is a niche use-case.

I'm reluctant to prioritise writing new docs but if there's example code as in @noklam's comment above, we could add a short description and link to that, as long as we have confirmation it works on Kedro v0.19. I don't see any major docs work beyond flagging this example however.

**Comment by AhdraMeraliQB** [comment]
Closed as documented in https://docs.kedro.org/en/stable/extend_kedro/common_use_cases.html
