### ISSUE TITLE
Add more YAML examples to dataset API docs

### ISSUE THREAD

**Issue by datajoely** [kedro-org/kedro#1155]
## Introduction

In issue #938 lots of datasets received a neat update that embedded YAML. As of today there are still several datasets that have yet to be updated.

I've attempted to order them into priority categories:

**Priority 1:**
`api.APIDataSet`
`tracking.JSONDataSet`
`tracking.MetricsDataSet`
`j̶s̶o̶n̶.̶J̶S̶O̶N̶D̶a̶t̶a̶S̶e̶t̶` (#1178 thanks @punitvara ! )

**Priority 2:**
`dask.ParquetDataSet`
`email.EmailMessageDataSet`
`plotly.JSONDataSet`
`plotly.PlotlyDataSet`
`matplotlib.MatplotlibWriter`
`networkx.NetworkXDataSet`
`text.TextDataSet`
`yaml.YAMLDataSet`
`pillow.ImageDataSet`

**Priority 3:**
`pandas.FeatherDataSet`
`tensorflow.TensorFlowModelDataset`
`biosequence.BioSequenceDataSet`
`geopandas.GeoJSONDataSet`
`holoviews.HoloviewsWriter`

## How to update the docs

The following rst block is how you embed highlighted YAML in the Python doc strings:

```rst
 .. code-block:: yaml
        >>> # AppendableExcelDataSet creates a new sheet for every dataset
        >>> # ExcelDataSet restricts one dataset per file as it is overwritten
        >>>
        >>> preprocessed_companies:
        >>>   type: pandas.AppendableExcelDataSet
        >>>   filepath: data/02_intermediate/preprocessed.xlsx # assumes file already exists
        >>>   save_args:
        >>>     sheet_name: preprocessed_companies
        >>>   load_args:
        >>>     sheet_name: preprocessed_companies
        >>>
        >>> preprocessed_shuttles:
        >>>   type: pandas.AppendableExcelDataSet
        >>>   filepath: data/02_intermediate/preprocessed.xlsx
        >>>   save_args:
        >>>     sheet_name: preprocessed_shuttles
        >>>   load_args:
        >>>     sheet_name: preprocessed_shuttles
```

**Comment by punitvara** [comment]
ok I am new to this project. But I am trying to get sense around here and push commits soon.

**Comment by punitvara** [comment]
@datajoely  I have raised a draft PR. Can you please review and let me know if there is any improvement needed ?

**Comment by datajoely** [comment]
This is actually done
