### ISSUE TITLE
Using kedro for a data dictionary

### ISSUE THREAD

**Issue by eepgwde** [kedro-org/kedro#1234]
## Description
Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

Most Data Warehouses have a painstakingly generated and curated data dictionary. Every field of every table is politely described, its usages are located and it is possible to edit descriptions and add caveats.

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

Kedro has a very good catalog for tables and pipelines. But nothing for columns or schema or metadata.

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

Would it be possible to add a "metadata" pipeline that can go through all the tables that currently exist and catalog their columns.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

Altova and other companies do have software solutions for databases and spreadsheets. These work by using some XML schema extraction and building a nested DOM.

**Comment by MerelTheisenQB** [comment]
Closing this ticket now in favour of continuing the discussion in https://github.com/kedro-org/kedro/issues/1076
