### ISSUE TITLE
[KED-2889] Investigation into migrating from Circle CI to GitHub Actions

### ISSUE THREAD

**Issue by idanov** [kedro-org/kedro#1251]
(transfer from Jira, created by @datajoely) Identify if this is simpler for the team maintaining one piece of software versus two different systems.

https://docs.github.com/en/actions/migrating-to-github-actions/migrating-from-circleci-to-github-actions

The output of this should be an analysis / proposal on what to do vs not to do.

**Comment by merelcht** [comment]
Closing in favour of https://github.com/kedro-org/kedro/issues/2153
