### ISSUE TITLE
Incorrect url on the spaceflight tutorial dataset

### ISSUE THREAD

**Issue by ruffyleaf** [kedro-org/kedro#1266]
## Description
https://kedro.readthedocs.io/en/stable/03_tutorial/03_set_up_data.html

The links to the datasets are incorrect.

## Context
trying to curl the datasets, but get a 404.

## Steps to Reproduce
click on link or curl the dataset

## Expected Result
view of the datafiles or download of the files to local machine.

## Actual Result
404

**Comment by AntonyMilneQB** [comment]
Hello @ruffyleaf and thanks for the report. You'll find the link is correct on the latest branch of our documentation: https://kedro.readthedocs.io/en/latest/03_tutorial/03_set_up_data.html

This will become the stable branch that you were looking at as soon as 0.17.7 is released (which should be very soon).
