### ISSUE TITLE
[KED-2692] Better default names during `kedro new`

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro#1272]
`kedro new` user experience is currently great when the Project Name given contains spaces, i.e. the suggested default values for Repository Name and Python Package Name follow the convention we suggest. Example:

![image-2021-06-09-12-05-51-393](https://user-images.githubusercontent.com/49397448/154981675-27f69d10-bfa9-49f1-b4b0-771021e0e05f.png)

However, when the Project Name given contains other symbols (e.g. hyphens), the suggested defaults will give invalid names, and pressing enter multiple times will result in an error. Example:

![image-2021-06-09-12-05-39-507](https://user-images.githubusercontent.com/49397448/154981665-151987e5-4728-4ccf-a60b-5e22f9da0e0f.png)

**Comment by noklam** [comment]
The root cause of this issue is our cookiecutters incorrectly configure and fail to convert the hyphens for python package.

![Screenshot 2022-03-22 at 17 58 09](https://user-images.githubusercontent.com/18221871/159545821-2e017d0b-6611-4d43-9fd9-996ceb373cf8.png)
