### ISSUE TITLE
Add a video dataset

### ISSUE THREAD

**Issue by daniel-falk** [kedro-org/kedro#1295]
## Description
I am working on a video dataset that is capable of loading and saving video files. I would be happy to contribute with this to the community. I currently have a working implementation of it, but there are some more work needed and I would like to hear your comments and see if anyone else is interested in helping with the finalization of it.

The current status is:

- [x] Load video files
- [x] Save video files from other VideoDataSet
- [x] Save video files from list of frames
- [x] Save video files from generator yielding frames
- [ ] Make it work with fsspec
- [ ] Verify functionality with different formats
- [ ] Write unittests
- [ ] Test it with versioned dataset, partitioned dataset etc

## Context
When working with computer vision pipelines on video it is in many cases much more effective to read the frames directly from the video. This removes the need for manual preprocessing to extract the frames and it takes much less space on the disk if the frames are encoded in a video file (with inter frame compression) than to store separate frames as images. One of the few cases where this is not the best way is when accessing the frames frequently, e.g. when training models, then it is inefficient to decode the video each time. In this later case we can however still use the video dataset as a preprocessing node in the pipeline to unpack the frames to an intermediate dataset.

## Possible Implementation
My implementation of the VideoDataSet can be seen at this link together with a pipeline using it in a few different ways.
https://github.com/daniel-falk/kedro-video-example

## Possible Alternatives
I have not yet figured out how to use the OpenCV video writer together with fsspec. There are however other options available for writing video files.

There is a need to spend some time thinking about the file suffixes and the fourcc codes in the video (codec).

To save video now we need to import the video class from the dataset file, this does not feel like the same design pattern as the other datasets. Perhaps there is a better way to design it?

**Comment by datajoely** [comment]
@daniel-falk this looks really really great - one idea on how you could get it to write to `fssepc` is to use a `NamedTemporaryFile`, it's not a perfect solution but I think it could work.

https://stackoverflow.com/a/69671122/2010808

**Comment by datajoely** [comment]
Hi @daniel-falk - makes a lot of sense and thank you for testing all of that! 

I think we should be practical here and maybe make your constructor something like this:

```python

 def __init__(self, filepath: str, fsspec_write:bool=False):

```
That way we can support both approaches, defaulting to the simplest and document the limitation in the docstring? Wdyt?

**Comment by datajoely** [comment]
All around amazing work - I wouldn't overdo, the `self._protocol` works for us elsewhere. 

I'd raise the PR against the core Kedro repo and continue development there. 

Thanks again for the contribution!

**Comment by daniel-falk** [comment]
There is now a PR for the VideoDataSet: https://github.com/kedro-org/kedro/pull/1312
