### ISSUE TITLE
[KED-2422] Provide useful error message when trying to run specific nodes within namespaces

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro#1301]
(transfer from Jira, created by @datajoely)

### Description
Responded to wizard thread on slack.

The user was trying to run `kedro run -n [node_name]` this was not working for the user since they were trying to run a node that actually lived within a namespace so he actually needed to address it via `modular_pipleine.node_name` 

The error message that the user gets when the node is not found is this one:

```
lib/python3.8/site-packages/kedro/pipeline/pipeline.py:415 

ValueError: Pipeline does not contain nodes named [xxx]
```

Whilst not incorrect, there is no prompt to get the names of the nodes that are in scope to identify if there is (a) A typo (b) what the accepted options will be

As we do more modular pipelines I expect this issue to come up more. Even offering an equivalent of catalog list for nodes would be useful.

If you do the following the namespaces of the specific nodes are not present:

kedro pipeline describe _default_
Nodes:

```
load data (<lambda>) Set Timestep (set_timestep) 
get_batches_time_series (get_batches_time_series) 
load_regressor (load_regressor) 
add_transformers (add_transformers) <Lambda> (<lambda>) plot_all_batches_profiles (plot_all_batches_profiles) 
<Lambda> (<lambda>) 
generate_features (generate_features) 
plot_all_features_overview (plot_all_features_overview) 
Set Batch Type (set_batch_type) 
generate performance report (generate_performance_report) 
```

But to run a particular node you need to specify a namespace:

```
ValueError: Pipeline does not contain nodes named ['generate_performance_report'].
```

Instead you have to specify:

```
kedro run --node train.train_model.generate_performance_report
```

### Proposed solution
So can we include the namespaces in the ValueError?

**Comment by datajoely** [comment]
We could also say the node name `'generate_performance_report' is available under the following namespaces ['a', 'b', 'c'], did you mean to specify any of those?`?
