### ISSUE TITLE
Kedro build-reqs (pip-compile) dont find versions compatible with jupyter-client

### ISSUE THREAD

**Issue by Felipeasg** [kedro-org/kedro#1323]
## Description
When using pip-tools to build requirements.in it cannot find a version compatible for jupyter-client.
The problem is that kedro requires that jupyter_client<7.0,>=5.1 and  jupyter-console==6.4.3 requires that jupyter_client>=7.0.0

## Context
When generating new requirements.txt after add more dependencies to my datascience project.

## Steps to Reproduce
1. Create and load a virtual environment here I will use conda
```
$ conda create -n test_kedro
$ conda activate test_kedro
```
2. Create a requirements.in with the following content
`requirements.in`
```
black==21.5b1
flake8>=3.7.9, <4.0
ipython~=7.10
ipython~=7.16.3; python_version == '3.6'
ipython>=7.31.1, <8.0; python_version > '3.6'
isort~=5.0
jupyter~=1.0
jupyter_client>=5.1, <7.0
jupyterlab~=3.0
kedro==0.17.7
kedro-telemetry~=0.1.0
nbstripout~=0.4
pytest-cov~=3.0
pytest-mock>=1.7.1, <2.0
pytest~=6.2
wheel>=0.35, <0.37
```
3. Install pip-compile in the environment created
```
$ pip install pip-tools
``` 
5. Compile requirements.in

```
$ python -m piptools compile -q src/requirements.in
```

## Expected Result

The expected result is the generation of requirements.txt file whithout dependencies conflicts

## Actual Result

The actual result is a conflict between kedro and jupyter dependencies.

```
There are incompatible versions in the resolved dependencies:
  jupyter_client<7.0,>=5.1 (from -r src/requirements.in (line 8))
  jupyter-client>=5.3.4 (from notebook==6.4.8->jupyter==1.0.0->-r src/requirements.in (line 7))
  jupyter-client>=6.1.1 (from jupyter-server==1.13.5->jupyterlab==3.3.0->-r src/requirements.in (line 9))
  jupyter-client>=4.1 (from qtconsole==5.2.2->jupyter==1.0.0->-r src/requirements.in (line 7))
  jupyter-client<7.0,>=5.1 (from kedro==0.17.7->-r src/requirements.in (line 10))
  jupyter-client<8.0 (from ipykernel==6.9.1->jupyter==1.0.0->-r src/requirements.in (line 7))
  jupyter-client>=7.0.0 (from jupyter-console==6.4.3->jupyter==1.0.0->-r src/requirements.in (line 7))
```

Where kedro dependencies ([requirements.txt](https://github.com/kedro-org/kedro/blob/main/requirements.txt#L9)) 
`jupyter-client<7.0,>=5.1 (from kedro==0.17.7->-r src/requirements.in (line 10))`

Are incompatible with jupyter dependencies:
`jupyter-client>=5.3.4 (from notebook==6.4.8->jupyter==1.0.0->-r src/requirements.in (line 7))`

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* pip-tools version `pip-tools==6.5.1`
* python version `Python 3.8.12`
* Operating system and version: `18.04.2-Ubuntu`

**Comment by datajoely** [comment]
hi @Felipeasg this started today - there is a fix in the works https://github.com/kedro-org/kedro/pull/1322

**Comment by Felipeasg** [comment]
Hi @datajoely. I looked at the issues and forgeted to look in pull-requests. 
Thanks by the quick response.

**Comment by datajoely** [comment]
Hi @Felipeasg not at all! We rely on the community to tell us when these things change 💪
