### ISSUE TITLE
Add support for Python 3.9

### ISSUE THREAD

**Issue by pjamargh** [kedro-org/kedro#1332]
## Description
I would like Kedro to be able to run on Python 3.9

## Context
It is common to have 3.9 as the base Python version on modern Linux distros (e.g. Ubuntu).

## Possible Implementation
Probably this just involves updating setup.py to allow installation on Python 3.9.

## Possible Alternatives
I considered downgrading the Python interpreter to 3.8.

**Comment by datajoely** [comment]
Hi @pjamargh 3.9 and 3.10 support is coming very soon in the forthcoming 0.18.0 release. That being said the two approaches we recommend today:

(1) Use a virtual environment to manage your Kedro project, I always have this command handy`conda create -n "spaceflights" python=3.8 -y`

(2) You can actually force python to install Kedro on any version of python using [these steps](https://github.com/kedro-org/kedro/discussions/1117#discussioncomment-1822667). The only thing that breaks in 3.9+ is the default engine for `pandas.ExcelDataSet` so you just need to install / provide `openpyxl` to get it working.

**Comment by aagaard** [comment]
When using Poetry I can't use this method. Any suggestions on how to do in that case?

**Comment by datajoely** [comment]
Hi @aagaard with 0.18.0 so close to be released I would recommend you just use a 3.8 venv for the time being.

**Comment by pjamargh** [comment]
Thanks for the information!

**Comment by lorenabalan** [comment]
Closing this as resolved, already available on `develop` and will be available in the upcoming release soon.
