### ISSUE TITLE
Extended support for plotly diagrams + Improved scope documentation of kedro's plotly support

### ISSUE THREAD

**Issue by cverluise-qb** [kedro-org/kedro#1337]
Hey team, 

thanks for the great tool.

Although related to `kedro-viz` as well, I'm posting the feature request here because the feature seems to be ultimately related to Kedro's support for extended `plotly.*Dataset`

## Description

I am trying to:
1. save a sankey diagram in Kedro
1. visualise a sankey diagram in Kedro viz. 
[note: turns out that this is not possible]

## Context

- The best way to visualize the output of the pipeline is a Sankey diagram.
- Unfortunately, neither`Plotly.JSONDataset` nor `plotly.PlotlyDataSet` support this kind of diagram

**tl;dr**: Currently Kedro Viz is limited to the basic diagrams that plotly.js includes in its basic version. 

## Possible Implementation

Overall, **my request** is:
- extend kedro's support non basic `plotly.*Dataset` (e.g. `HTMLdataset`)
- extend kedro-viz support accordingly
Seems to me that supporting (plotly) html dataset would make kedro/kedro viz much more versatile for diagram vi

## Possible Alternatives
**In the meantimes**, that would be nice to make clear in Kedro's doc that the plotly support is still limited and clearly state what can and cannot be done.

## Checklist

- [x] Include labels so that we can categorise your feature request

**Comment by datajoely** [comment]
Hi @cverluise-qb sorry to be a pain - would you raise this against https://github.com/kedro-org/kedro-viz
