### ISSUE TITLE
Add abfss in the list of cloud protocols

### ISSUE THREAD

**Issue by philomine** [kedro-org/kedro#1344]
## Description
abfss is not in the list of cloud protocols in the module kedro/io/core.py.

## Context
I'm currently testing kedro on my project and I am facing an issue when trying to load an ExcelDataSet from an abfss cloud storage.

This works
```{python}
import pandas as pd
pd.read_excel("abfss://container/path/to/excel/file.xlsx", engine="openpyxl")
```

This doesn't
```{python}
from kedro.extras.datasets.pandas import ExcelDataSet
dataset = ExcelDataSet(filepath="abfss://container/path/to/excel/file.xlsx", load_args={"engine": "openpyxl"})
dataset.load()
```

## Possible Implementation
Simply add abfss to the list of cloud protocols.

Currently, in [kedro/io/core.py, line 31](https://github.com/kedro-org/kedro/blob/main/kedro/io/core.py):
```{python}
CLOUD_PROTOCOLS = ("s3", "gcs", "gs", "adl", "abfs")
```

Update with
```{python}
CLOUD_PROTOCOLS = ("s3", "gcs", "gs", "adl", "abfs", "abfss")
```

This solution worked with my issue.

## Possible Alternatives
If adding abfss to the list of cloud protocols is not an option to fix this issue, I can provide more information on my issue.

**Comment by MerelTheisenQB** [comment]
Hi @philomine, thanks for reporting this! This sounds like a very reasonable solution and we'd very much welcome a contribution PR for it 🙂

**Comment by MerelTheisenQB** [comment]
@datajoely We can definitely look at optimising the list of allowed protocols, but currently we have separation between "cloud" and "http" protocols, so it would require a bigger change to handle a generic list like the one above. Also, it doesn't look like `abfss` is included, so we'd have to add that anyway.

**Comment by datajoely** [comment]
Good point - looking into it, it looks like they only make this available via plug-in mechanism once `adlfs` is installed (which I haven't got in this env) 
https://github.com/fsspec/adlfs/blob/fbe43c601e7b162b7a2bf93f7f8b699c747b70e6/setup.py#L40

**Comment by philomine** [comment]
Thanks for your fast answer! I'll open a PR then :)
