### ISSUE TITLE
`preprocess_companies` type hint for return value not updated

### ISSUE THREAD

**Issue by chsafouane** [kedro-org/kedro#1358]
## Description
In the [Set Up experiment tracking tutorial](https://kedro.readthedocs.io/en/stable/03_tutorial/07_set_up_experiment_tracking.html#set-up-your-nodes-and-pipelines-to-log-metrics), the return value of the `preprocess_companies` function is modified but not its type hint.

## Context
__Before updating the example__ to include tracking, the code looks like this:

```python
def preprocess_companies(companies: pd.DataFrame) -> pd.DataFrame:
    """Preprocesses the data for companies.

    Args:
        companies: Raw data.
    Returns:
        Preprocessed data, with `company_rating` converted to a float and
        `iata_approved` converted to boolean.
    """
    companies["iata_approved"] = _is_true(companies["iata_approved"])
    companies["company_rating"] = _parse_percentage(companies["company_rating"])
    return companies
```

__After updating the example__ to take into account the tracking functionality, the code looks like this:

```python
def preprocess_companies(companies: pd.DataFrame) -> pd.DataFrame:
    """Preprocesses the data for companies.

    Args:
        companies: Raw data.
    Returns:
        Preprocessed data, with `company_rating` converted to a float and
        `iata_approved` converted to boolean.
    """
    companies["iata_approved"] = _is_true(companies["iata_approved"])
    companies["company_rating"] = _parse_percentage(companies["company_rating"])
    return companies, {"columns": companies.columns.tolist(), "data_type": "companies"}
```

In the updated example, the return value changed but not the type hint. The new return value should have a type of `tuple[pd.DataFrame, dict]` (or `Tuple[pd.DataFrame, Dict]` for versions of Python prior to 3.9).

Thanks

**Comment by MerelTheisenQB** [comment]
Hi @chsafouane , great spot! 🕵️‍♂️  Would you be okay opening a PR for it? 🙂
