### ISSUE TITLE
Remove recommendations for Databricks Connect in Kedro docs databricks section

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#1381]
## Description

There has been communication from the Databricks team that Databricks Connect will be sunset. It plays a major part of our workflow with Databricks. This section in the documentation will have to be removed and we will await news on the new workflow that this team is suggesting. 

## Possible Implementation

The changes affect the [Databricks Deployment Guide](https://kedro.readthedocs.io/en/stable/10_deployment/08_databricks.html).

**Comment by MerelTheisenQB** [comment]
Resolved in https://github.com/kedro-org/kedro/pull/1376
