### ISSUE TITLE
Release `kedro-plugins`

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro#1386]
### kedro-telemetry

- [x] Add compatibility with Kedro `0.18.0`
- [x] Add compatibility with python 3.9 + 3.10
- [x] Remove support for python 3.6
- [x] Release with version `0.2.0`

### kedro-docker

- [x] Add compatibility with Kedro `0.18.0`
- [x] Add compatibility with python 3.9 + 3.10
- [x] Remove support for python 3.6
- [x] Release with version `0.3.0`

### kedro-airflow

- [x] Add compatibility with Kedro `0.18.0`
- [x] Add compatibility with python 3.9 + 3.10
- [x] Remove support for python 3.6
- [x] Release with version `0.5.0`

**Comment by AntonyMilneQB** [comment]
Going to keep track of this here also:

### kedro-viz

- [x] Ensure compatible requirements with kedro project template: https://github.com/kedro-org/kedro-viz/pull/804
- [ ] _After kedro-telemetry_ is released, make sure `main` is building correctly (need to wait until kedro-telemetry is released to get compatible requirements)
- [ ] Extend support to Python 3.9 + 3.10: https://github.com/kedro-org/kedro-viz/issues/793
- [ ] Update demo project to 0.18: https://github.com/kedro-org/kedro-viz/issues/806

**Comment by MerelTheisenQB** [comment]
All plugins have been released. The further updates required for `kedro-viz` will be completed in later sprints.
