### ISSUE TITLE
Versioned datasets don't work with Prefect

### ISSUE THREAD

**Issue by ardoi** [kedro-org/kedro#1388]
## Description
Versioned datasets used as outputs causes node to fail when scheduling runs with Prefect.

## Context
I'm trying to run a Kedro pipeline in Prefect. Because some of the output datasets used by nodes in the pipeline are versioned, running the node fails. 

## Steps to Reproduce
1. Follow the [Prefect deployment guide](https://kedro.readthedocs.io/en/stable/10_deployment/05_prefect.html) to set up Prefect and register the pipeline with Prefect. As a side note, the script on the current page doesn't work for me and I had to [update](https://github.com/kedro-org/kedro/pull/1379) one of the imports.
2. Running the pipeline in Prefect works once. Running it a second time or scheduling runs fails with a DataSetError.

## Expected Result
Pipeline should be able to run when triggered after the first time.

## Actual Result
Execution fails with the error. 
```
kedro.io.core.DataSetError: Save path `/a/b/c/2022-03-29T14.20.46.529Z/xyz` 
for ParquetDataSet(filepath=/a/b/c/xyz, load_args={}, protocol=file, save_args={}, 
version=Version(load=None, save='2022-03-29T14.20.46.529Z')) 
must not exist if versioning is enabled. 
```
It seems the Dataset is reusing the timestamp from when the `register_prefect_flow.py` is executed instead of the actual run time of the pipeline. In this case I ran the registration script at 14:20 and triggered the pipeline to be run at 14:23 but the timestamp in the error message above corresponds to the script run time and not trigger time. 

I looked around in Kedro code a bit and it seems the [function](https://github.com/kedro-org/kedro/blob/f11d29d44fee234e0bd45df86356c3aabca3f2fa/kedro/io/core.py#L546) generating the timestamp is cached, but not sure if that's all there is to it. 

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.7
* Python version used (`python -V`): 3.8.12
* Operating system and version: MacOS 11.6.4
* Prefect version: 1.1.0

**Comment by avan-sh** [comment]
Hi @ardoi, 

I remember the same issue from one of the discord discussions. One working solution that we got to is [here](https://github.com/avan-sh/spaceflights-prefect) in the `prefect_flow.py`. 
This approach requires writing all datasets that are reused by another nodes back to disk. 

This also requires enabling `ShelveStore` in your `settings.py` [file](https://github.com/avan-sh/spaceflights-prefect/blob/main/src/sf_prefect/settings.py)

@noklam Initial analysis for this bug was that the advised approach in docs creates a kedro session once and reuses it for every sub-sequent run.

**Comment by noklam** [comment]
Thank you @avan-sh  for the initial analysis, with recent changes on session, it's likely we have to revisit and update the doc.

**Comment by avan-sh** [comment]
This might still be relevant. I think the pr only updates the documentation to latest prefect version and doesn't fix the issue on versioned datasets.

**Comment by MerelTheisenQB** [comment]
> This might still be relevant. I think the pr only updates the documentation to latest prefect version and doesn't fix the issue on versioned datasets.

Thanks @avan-sh! I'll re-open this issue. Github tries to be too smart sometimes 😉

**Comment by MerelTheisenQB** [comment]
@ardoi and @avan-sh there's now a PR open that addressed this issue: https://github.com/kedro-org/kedro/pull/1775 would be awesome to get your review on that!
