### ISSUE TITLE
Redirect broken URLs

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#1389]
We're breaking a lot of URLs in 0.18.0 because we're removing the chapter numbering. This ticket involves creating redirects for every affected page 🥴

It has to be done via ReadTheDocs and you may need to request access to this: https://readthedocs.org/dashboard/kedro/redirects/

Follow these instructions: https://docs.readthedocs.io/en/stable/user-defined-redirects.html

**Comment by MerelTheisenQB** [comment]
This was completed by @SajidAlamQB
