### ISSUE TITLE
Project templating using TemplatedConfigLoader raises ValidationError in 0.18.0

### ISSUE THREAD

**Issue by patrikhardin** [kedro-org/kedro#1402]
## Description
When following the guide for [Template configuration](https://kedro.readthedocs.io/en/stable/kedro_project_setup/configuration.html#template-configuration), Kedro 0.18.0 raises ValidationError as `kedro.config.templated_config.TemplatedConfigLoader` is not recognized as a subclass of `kedro.config.config.ConfigLoader`.

## Context
This bug hinders me from using the `TemplatedConfigLoader`, according to the documentation.

## Steps to Reproduce
1. Create new Kedro project
```
kedro new --starter=pandas-iris
cd new-kedro-project
```
2. Create and activate venv. Install requirements.
```
python -m venv my_venv
source my_venv/bin/activate
pip install -r src/requirements.txt
```
3. Open the `settings.py` file.
```
nano src/new_kedro_project/settings.py
```
Uncomment lines 28,29,31,32,33 as suggested in the guide. Expected config:
```
# Class that manages how configuration is loaded.
from kedro.config import TemplatedConfigLoader
CONFIG_LOADER_CLASS = TemplatedConfigLoader
# Keyword arguments to pass to the `CONFIG_LOADER_CLASS` constructor.
CONFIG_LOADER_ARGS = {
    "globals_pattern": "*globals.yml",
}
```
4. Run the default pipeline
```
kedro run
```

## Expected Result
Defeault pipeline should run with global config keys overwritten.

## Actual Result
ValidationError is raised.

```
Traceback (most recent call last):
  File "/usr/local/bin/kedro", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/kedro/framework/cli/cli.py", line 205, in main
    cli_collection = KedroCLI(project_path=Path.cwd())
  File "/usr/local/lib/python3.9/site-packages/kedro/framework/cli/cli.py", line 114, in __init__
    self._metadata = bootstrap_project(project_path)
  File "/usr/local/lib/python3.9/site-packages/kedro/framework/startup.py", line 155, in bootstrap_project
    configure_project(metadata.package_name)
  File "/usr/local/lib/python3.9/site-packages/kedro/framework/project/__init__.py", line 166, in configure_project
    settings.configure(settings_module)
  File "/usr/local/lib/python3.9/site-packages/dynaconf/base.py", line 182, in configure
    self._wrapped = Settings(settings_module=settings_module, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dynaconf/base.py", line 235, in __init__
    self.validators.validate(
  File "/usr/local/lib/python3.9/site-packages/dynaconf/validator.py", line 417, in validate
    validator.validate(self.settings, only=only, exclude=exclude)
  File "/usr/local/lib/python3.9/site-packages/kedro/framework/project/__init__.py", line 35, in validate
    raise ValidationError(
dynaconf.validator.ValidationError: Invalid value `kedro.config.templated_config.TemplatedConfigLoader` received for setting `CONFIG_LOADER_CLASS`. It must be a subclass of `kedro.config.config.ConfigLoader`.
```

## Your Environment
* Kedro version used (`pip show kedro` or `kedro -V`): `0.18.0`
* Python version used (`python -V`): `3.9.10`
* Operating system and version: `macOS 12.3`

**Comment by datajoely** [comment]
Hi @patrikhardin thanks for raising this - we're looking into it. As part of 0.18.x there is a new `AbstractConfigLoader`.

**Comment by AntonyMilneQB** [comment]
Thanks @patrikhardin. This is indeed a mistake where we should have specified `AbstractConfigLoader` instead [here](https://github.com/kedro-org/kedro/blob/main/kedro/framework/project/__init__.py#L61). Not quite sure how this got through our tests, sorry about that 🤔 

For the time being, here's a super hacky fix. Use the following in settings.py:
```
# Class that manages how configuration is loaded.
from kedro.config import TemplatedConfigLoader, ConfigLoader
ConfigLoader.__subclasses__ = lambda: [TemplatedConfigLoader]
CONFIG_LOADER_CLASS = TemplatedConfigLoader
# Keyword arguments to pass to the `CONFIG_LOADER_CLASS` constructor.
CONFIG_LOADER_ARGS = {
    "globals_pattern": "*globals.yml",
}
```

This will trick the validation code into thinking that `TemplatedConfigLoader` is a subclass of `ConfigLoader`.

**Comment by AntonyMilneQB** [comment]
Here's a new version of test_settings.py that picks up on this and also does some more thorough testing of other settings:  https://gist.github.com/AntonyMilneQB/50159cbbde40399fc6d9094fef3b0fee

The problem is that it's not immediately possible to get both tests passing simultaneously. Changing `ConfigLoader` to `AbstractConfigLoader` doesn't work because then it will change the default value for `CONFIG_LOADER_CLASS` to `AbstractConfigLoader`, which isn't what we want. Basically `_IsSubclassValidator` is designed to treat `default` as the thing that must be the superclass also. We need to modify this somehow:
* make it so we can specify `default` and the superclass independently
* or change the validation so that it just checks that the class specified shares some non-trivial parent class with `default` (sounds less rigorous but maybe easier to implement?)

**Comment by noklam** [comment]
Related thread on Discord:

https://discord.com/channels/778216384475693066/846330075535769601/963057365282877440
https://discord.com/channels/778216384475693066/778998585454755870/961547016708702209
https://discord.com/channels/778216384475693066/846330075535769601/960753695870570516
