### ISSUE TITLE
Point users to Kedro-Telemetry in Kedro-Plugins

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#1403]
When we moved to the Linux Foundation, we created a new repository called [`kedro-plugins`](https://github.com/kedro-org/kedro-plugins) which became the new home of [`kedro-telemetry`](https://github.com/kedro-org/kedro-plugins/tree/main/kedro-telemetry). We did this because we were tired of responding to GitHub across all three (formally) seperate repositories; now users just have to come to once place and it's easier for us to keep track of GitHub issues.

This ticket involves updating our users about the change and archiving our old repositories. To do this we need to:

 - Put a note on each README.md for our old [`kedro-telemetry`](https://github.com/quantumblacklabs/kedro-telemetry) repository that they have been moved to  [`kedro-plugins`](https://github.com/kedro-org/kedro-plugins) (it would be great if you could point users to the exact directory that `kedro-telemetry` exists in) 
 - Once this is complete then create a ticket with our IT team to archive [Kedro-Telemetry](https://github.com/quantumblacklabs/kedro-telemetry)

**Comment by AhdraMeraliQB** [comment]
README updated and repository archived ✅

**Comment by noklam** [comment]
Related: https://github.com/kedro-org/kedro-plugins/pull/24
