### ISSUE TITLE
Wrong ConfigLoader parameter name in 0.18.0 docs

### ISSUE THREAD

**Issue by patrikhardin** [kedro-org/kedro#1404]
## Description
For the `ConfigLoader` [class](https://kedro.readthedocs.io/en/0.18.0/_modules/kedro/config/config.html#ConfigLoader.__init__), the parameter `conf_source` is referred to as `conf_root` in the 0.18.0 [Local and base configuration environments](https://kedro.readthedocs.io/en/0.18.0/kedro_project_setup/configuration.html#local-and-base-configuration-environments) docs.

The code example:
```
from kedro.config import ConfigLoader

conf_loader = ConfigLoader(conf_root="conf", env="local")
conf_catalog = conf_loader.get("catalog*", "catalog*/**")
```

raises
```
*** TypeError: __init__() got an unexpected keyword argument 'conf_root'
```

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): `0.18.0`
* Python version used (`python -V`): `3.7.10`

**Comment by MerelTheisenQB** [comment]
Hi @patrikhardin! Great catch 🦅 We'd very much appreciate a contribution if you have time! 🙂

**Comment by patrikhardin** [comment]
@MerelTheisenQB I have opened a [PR](https://github.com/kedro-org/kedro/pull/1405) with an update to the docs.

**Comment by AntonyMilneQB** [comment]
Fixed in https://github.com/kedro-org/kedro/pull/1405, thank you!
