### ISSUE TITLE
Fix failing unit tests

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro#1412]
The `tests/io/test_partitioned_dataset.py` and `tests/io/test_incremental_dataset.py` have started failing intermittently on `unit_tests` and `windows_unit_tests` builds. It's not clear if any of the changes in `0.18.0` has caused this, but the failures started happening around the release.

**Comment by MerelTheisenQB** [comment]
This issue is caused by updating `moto` which I'd experienced earlier on when adding support for Python 3.10 ([see point 1 in the development notes](https://github.com/kedro-org/kedro/pull/1275)).

`moto` was bumped in the release process: https://github.com/kedro-org/kedro/pull/1398/files, but not necessarily because it was a change required for any functionality.

Things that fix this issue:
1. Revert the bumping of `moto`
2. Run all tests sequentially  ⚠️ This will add significant build time to all builds
3. Run most tests in parallel and only the `test_partitioned_dataset.py` and `test_incremental_dataset.py` sequentially. ⚠️ If we do this we won't be able to run the code coverage check as part of the build. 

I will do further investigation to see why running in parallel causes these issues with `moto` and if we could use an alternative to `moto`.

**Comment by SajidAlamQB** [comment]
I agree to option 1, pinning `moto` to an older version. I'd rather avoid slowing down build times.

**Comment by noklam** [comment]
That's weird! Let's revert it for now.
