### ISSUE TITLE
which version of kedro????

### ISSUE THREAD

**Issue by tell-me-with-data** [kedro-org/kedro#1417]
which kedro version allows me to complete "Kedro spaceflights tutorial"????

**Comment by noklam** [comment]
https://github.com/kedro-org/kedro-starters/pull/81

For the time being, please see this PR and copy the new catalog.yml. It should work with the latest 0.18.0.

**Comment by tell-me-with-data** [comment]
@noklam ok i try it

**Comment by noklam** [comment]
@tell-me-with-data 

Do you have any problem following the Spaceflights tutorial?
https://kedro.readthedocs.io/en/latest/tutorial/spaceflights_tutorial.html

**Comment by noklam** [comment]
Closing it now, feel free to open a new issue/jump to the Discord channel if you found the tutorial doesn't work.
