### ISSUE TITLE
Updating Kedro spaceflights documentation to match with starter

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#1418]
## Description
Currently, the documentation does not match with the [spaceflights starters](https://github.com/kedro-org/kedro-starters/tree/main/spaceflights).

We have a namespace pipeline while using `parameters.yml`, but in the doc, it mentions `conf/base/parameters/data_science.yml` instead.

https://kedro.readthedocs.io/en/latest/tutorial/namespace_pipelines.html

## Context
* The catalog configuration does not match.

I think the starters are supposed to match with the  “final stage” of the spaceflight tutorial. It started from the basic pipeline to the more advance namespace modular pipeline. The current template we have in starters is a mix of them.

**Comment by noklam** [comment]
Agree, I don't mean to change the tutorial starting from the modular pipeline. I think there are 2 discrepancies right now.

1. The documentation itself doesn't modify the catalog entries correctly after adding namespace
2. The `spaceflights` starter template does not convert `parameters.yml` -> `conf/base/parameters/data_science.yml`. The current starter roughly matches the tutorial at https://kedro.readthedocs.io/en/stable/tutorial/create_pipelines.html, should we update the starter to include this bit?

**Comment by AntonyMilneQB** [comment]
Hmm, not sure I see what the second discrepancy is? In the spaceflights starter we have `conf/base/parameters/data_science.yml`, which is what the tutorial also tells you to edit? We have an empty `conf/base/parameters.yml` file which is a bit silly but seems ok.

**Comment by noklam** [comment]
Another outdated doc for kedro-viz, we should get this documentation fixed first.

https://kedro.readthedocs.io/en/stable/tutorial/set_up_experiment_tracking.html

**Comment by noklam** [comment]
Part of the issues are addressed by #1421, but we still need to fix the viz part.
