### ISSUE TITLE
CustomContext example for PySpark is incompatible with Kedro 0.18.0

### ISSUE THREAD

**Issue by jstammers** [kedro-org/kedro#1425]
## Description
I've been following the documentation which describes how to build a Kedro pipeline using PySpark as described [here](https://kedro.readthedocs.io/en/stable/tools_integration/pyspark.html).

When executing the pipeline via the CLI
```bash
kedro run --env=spark
```
I don't encounter any obvious errors. However, I have written a script that I intend to use as the entrypoint on my databricks cluster

```python
from kedro.framework.session import KedroSession
from kedro.framework.project import configure_project


configure_project("<my_package>")

env  = "spark"
pipeline = "__default__"
with KedroSession.create(env=env) as session:
  session.run(pipeline)
```

That results in the following error

```python
/anaconda/envs/azureml_py38/lib/python3.8/site-packages/kedro/framework/session/session.py in run(self, pipeline_name, tags, runner, node_names, from_nodes, to_nodes, from_inputs, to_outputs, load_versions)
    352         save_version = session_id
    353         extra_params = self.store.get("extra_params") or {}
--> 354         context = self.load_context()
    355 
    356         name = pipeline_name or "__default__"

/anaconda/envs/azureml_py38/lib/python3.8/site-packages/kedro/framework/session/session.py in load_context(self)
    249 
    250         context_class = settings.CONTEXT_CLASS
--> 251         context = context_class(
    252             package_name=self._package_name,
    253             project_path=self._project_path,

TypeError: __init__() got an unexpected keyword argument 'hook_manager'
```

Digging a little deeper, I can see this is because the constructor for `CustomContext` doesn't include the `hook_manager` keyword argument. 

Based on the release notes for version 0.18.0, I think this is just a case of updating the corresponding documentation. I've modified the `CustomContext` class to 
```python
class CustomContext(KedroContext):
    def __init__(
        self,
        package_name: str,
        project_path: Union[Path, str],
        config_loader: ConfigLoader,
        hook_manager: PluginManager,
        env: str = None,
        extra_params: Dict[str, Any] = None,
    ):
        super().__init__(package_name, project_path, config_loader, hook_manager, env, extra_params)
        self.init_spark_session()

    def init_spark_session(self) -> None:
        """Initialises a SparkSession using the config defined in project's conf folder."""

        # Load the spark configuration in spark.yaml using the config loader
        parameters = self._config_loader.get("spark*", "spark*/**")
        spark_conf = SparkConf().setAll(parameters.items())

        # Initialise the spark session
        spark_session_conf = (
            SparkSession.builder.appName(self._package_name)
                .enableHiveSupport()
                .config(conf=spark_conf)
        )
        _spark_session = spark_session_conf.getOrCreate()
        _spark_session.sparkContext.setLogLevel("WARN")
```

and the pipeline launches correctly.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.0
* Python version used (`python -V`): 3.8
* Operating system and version: ubuntu 18.04

**Comment by datajoely** [comment]
Hi @jstammers it's likely related to this, a fix will be out quickly! https://github.com/kedro-org/kedro/issues/1409

**Comment by AntonyMilneQB** [comment]
Hi @jstammers, thanks very much for this. As you say, this is an issue with documentation not being up to date. Your `CustomContext` looks absolutely right, great job figuring it out! The changes required are the same as those [shown here](https://github.com/kedro-org/kedro-starters/compare/0.17.7...0.18.0#diff-6233736be193bbb76518027d9260153aa1a528017b9be2f62d393072223f8f21) on our pyspark-iris starter, which is up to date with 0.18.

We should update our migration guide to include this since I think it might catch a few people out.

**Comment by AntonyMilneQB** [comment]
Update: actually this is problem also in our starter. @SajidAlamQB will include the fix in his update to the iris example https://github.com/kedro-org/kedro-starters/pull/82.
