### ISSUE TITLE
"Hellow World" tutorial doesn't work

### ISSUE THREAD

**Issue by pjamargh** [kedro-org/kedro#1428]
## Description
"Hellow World" tutorial doesn't work

## Context
I going through the "Getting started" documentation.

## Steps to Reproduce
1. Copy the example at https://kedro.readthedocs.io/en/stable/get_started/hello_kedro.html
2. Run it

## Expected Result
The example works and prints on the screen:
```
{'my_message': 'Hello Kedro!'}
```

## Actual Result
The example fails and prints on the screen:
```
Traceback (most recent call last):
  File "/home/xxxxxxx/prj/gactitivy/gactivity/test.py", line 36, in <module>
    print(runner.run(greeting_pipeline, data_catalog))
TypeError: run() missing 1 required positional argument: 'hook_manager'
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro 0.18
* Python 3.9
* Linux Mint 20.3, Linux 5.4.0-105-generic #119-Ubuntu SMP Mon Mar 7 18:49:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by MerelTheisenQB** [comment]
Hi @pjamargh, thanks for flagging! We're already aware of this issue and working on a fix. If you don't mind, I'll close this in favour of the previously reported issue: https://github.com/kedro-org/kedro/issues/1409
