### ISSUE TITLE
Access catalog in node

### ISSUE THREAD

**Issue by drtorchwood** [kedro-org/kedro#1433]
Hi, 

I'm trying to build a node that compares the list of files defined in the catalog with the existing files on disk. 
In a jupyter notebook started with kedro the code works but in a kedro node it fails with the error message` name 'context' is not defined`. 

This is the pipeline entry:
```
from kedro.pipeline import Pipeline, node
import sys
from project.catalog_check.nodes import check_data_catalog


def create_pipeline(**kwargs):
    return Pipeline(
        [
            node(
                func=check_data_catalog,
                inputs=None,
                outputs="information_about_datasets",
                name="check_data_catalog",
            ),
        ]
    )
```

And this is the _beginning_ of the node:
```
import pathlib

def check_data_catalog():
    # get path of project
    proj_path = context._project_path

    files_in_catalog = context.catalog._data_sets.copy()
    datasets = files_in_catalog.keys()
    datasets = [i for i in datasets if not i.startswith("param")]

```

As said, it's working with `kedro jupyter notebook`. 
I haven't migrated to kedro 18.0 and the problem exists in kedro 16.6. and 17.4.

I guess I have to import the context properly. Any advice on this?

**Comment by datajoely** [comment]
By design we don't want users to do this within the node, the node should have no knowledge of IO and should just call a pure python function.

You can however do this with a Kedro hooks:
https://kedro.readthedocs.io/en/0.17.7/07_extend_kedro/02_hooks.html

You could use a `before_pipeline_run` or `after_pipeline_run` hook since the `catalog` object is available in both situations.

**Comment by drtorchwood** [comment]
Thanks for this very fast reply. I was always scared of these hooks. But perhaps it's time to understand them now.

**Comment by ElCuboNegro** [comment]
I need to do something near this, in my case I want to procedurally create new entries to the DataCatalog as they are created in the database (I hope this would be really interesting for almost everyone here)

**Comment by ElCuboNegro** [comment]
yep, actually is what I did.

Thankyou for the advice, and btw, hooks change your life for good.
