### ISSUE TITLE
Quantumblacklabs Github page is not found

### ISSUE THREAD

**Issue by praveenkumarvps** [kedro-org/kedro#1435]
I am a new user exploring Kedro by following the documentation. I was trying to get Reviews, Companies, Shuttles Dataset by doing a **CURL** command however it didn't work because the github pages are not found. ?

curl -o data\01_raw\reviews.csv https://quantumblacklabs.github.io/kedro/reviews.csv
curl -o data\01_raw\companies.csv https://quantumblacklabs.github.io/kedro/companies.csv
curl -o data\01_raw\shuttles.xlsx https://quantumblacklabs.github.io/kedro/shuttles.xlsx

**Error:**
curl : 404There isn't a GitHub Pages site here.

**Comment by datajoely** [comment]
I think you're looking at an older version of the docs if you look at the `stable`, `latest` or `0.17.7` version of the docs the links are now updated to `kedro-org/kedro`:

https://kedro.readthedocs.io/en/stable/tutorial/set_up_data.html

**Comment by praveenkumarvps** [comment]
My bad! Thanks @datajoely for the quick response and fix.
