### ISSUE TITLE
Update docs about deployment with Kubeflow Pipelines V2

### ISSUE THREAD

**Issue by rafaelgildin** [kedro-org/kedro#1440]
## Description
Based on this documentation: https://kedro.readthedocs.io/en/stable/deployment/kubeflow.html#upload-workflow-spec-and-execute-runs, I'm trying to run kedro in Vertex AI pipelines. I need to refactor the code to work with kfp v2, since it's necessary to generate a json file instead of yaml by running build_kubeflow_pipeline.py.

## Context
I'm currently working in a MLE solution to change a server application to serverless. 
This solution will help me to approach this solution.
By solving this problem, kedro will facilitate many cloud companies to changes their applications to serverless. This way you can reduce the costs and expand kedro usage for more applications.

**Comment by datajoely** [comment]
I think our docs may be a little old here - recently Google Cloud put out this article which may be helpful

https://medium.com/google-cloud/migrate-kedro-pipeline-on-vertex-ai-fa3f2c6f7aad

**Comment by rafaelgildin** [comment]
Thanks @datajoely, I'll follow that approach and come back if i find some block.

**Comment by rafaelgildin** [comment]
Is there someway to have input variables in **kubeflow.yaml** like kp2 v2 offers [here](https://www.kubeflow.org/docs/components/pipelines/sdk-v2/component-development/#using-your-component-in-a-pipeline)

**Comment by datajoely** [comment]
So since that's a 3rd party plugin I think this may be best answered here https://github.com/getindata/kedro-kubeflow

That being said, the answer is likely a custom CLI argument or hook. Note in 0.18.x `run_id` is now called a `session_id`

**Comment by merelcht** [comment]
I'm closing this issue since there hasn't been any recent activity. Feel free to re-open this if you're still facing problems!
