### ISSUE TITLE
Clean up the Global `_active_session` and provide a better alternative (Parent)

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#1441]
Notes:

1. The scope of this PR will be limited to an ad-hoc fix so it doesn't block new session in Jupyter/Databricks environment when an active session is not closed.
2. The discussion of removing global `_active_session` will be deferred. Particularly, we will need more information about how the plugins developers are using it and do we need to expose more. Potentially adding new hooks/changing hookspec or some more thinking about the responsibility of KedroSession & KedroContext.

_Originally posted by @noklam in https://github.com/kedro-org/kedro/issues/1434#issuecomment-1099299826_

Follow up issues/PRs:
- [x] #1458
- [x] #1459
- [ ] #1460

**Comment by AntonyMilneQB** [comment]
See #506 for some discussion of adding new arguments to the hook spec or creating a whole new hook.

**Comment by noklam** [comment]
Conclusion from today's discussion:
* Turn KedroContext into a dataclass
* Add the `config_loader` property so people don’t need to use `context._getconfig_loader`
* Add `after_context_created` hook and include KedroContext in the signature.
For 0.19 - deprecating catalog and param hot reload. Not sure if there is a better place to write this down somewhere so we don’t forget about it when we have the 0.19 release

**Comment by astrojuanlu** [comment]
I think most of the tasks here were done? And if there's only one task left, can we close this parent issue and leave the other one open?
