### ISSUE TITLE
Kedro run blocks creation of new multiprocessing context

### ISSUE THREAD

**Issue by avan-sh** [kedro-org/kedro#1442]
## Description

An import of ShelveStore(which happens automatically during `kedro run`) automatically creates a multiprocessing context blocking users or packages that create a new multiprocessing context of a different start method.
**Note: Documenting an error raised by discord user.**

## Context
A user on discord raised the following error that occurs when adding `from pycbc.waveform import get_fd_waveform` import statement in `nodes.py`. Reference to the [thread](https://discord.com/channels/778216384475693066/963181015822651443)

## Steps to Reproduce
1. Have a running kedro project (eg: spaceflights)
2. Add  `from pycbc.waveform import get_fd_waveform` import statement to your project (any module that is imported at runtime eg: `nodes.py` or `settings.py`).
3. Run `kedro run` 

### Alternative option 1
Execute the following script.
```
from kedro.framework.session.store import ShelveStore
from pycbc.waveform import get_fd_waveform
```

Execute the following script.
```
from kedro.framework.cli import main
import multiprocessing

multiprocessing.set_start_method("fork")
```

## Expected Result

Pipeline should run without any error

## Actual Result
`kedro run` 

```
 from pycbc.waveform import get_fd_waveform
  File "/lib/python3.8/site-packages/pycbc/__init__.py", line 150, in <module>
    multiprocessing.set_start_method('fork')
  File "/lib/python3.8/multiprocessing/context.py", line 243, in set_start_method
    raise RuntimeError('context has already been set')
RuntimeError: context has already been set
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): kedro, version 0.18.0
* Python version used (`python -V`): python 3.8.13
* Operating system and version: MacOS

## Analysis
An import of `kedro.framework.session.store.ShelveStore` occurs during a run which creates a context of multiprocessing. This raises error when pycbc tries to create a new context during its import (which it does as it uses fork while the default is spawn in MacOS).

## Temporary Solutions
**Option 1:** Comment ShelveStore class in `kedro.framework.session.store` module.

**Option 2:** Adding import to kedro executable. Updated kedro executable would be:
```
#!/opt/anaconda3/envs/k18/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from pycbc.waveform import get_fd_waveform
from kedro.framework.cli import main

if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
    sys.exit(main())
```

**Comment by MerelTheisenQB** [comment]
We'll resolve this in several steps:
1. Clarify in docs + tutorials that the `ShelveStore` is not the default. Explain what it does, so hopefully users will only use it if really needed.
2. Look into making the `SQLiteStore` the default.

**Comment by avan-sh** [comment]
@MerelTheisenQB I'm afraid I wasn't clear enough with the description. If I remember right, the error is raised even if the project doesn't use `ShelveStore`. It is automatically imported implicitly during start even if it is not being explicitly used. I'll update this again after I verify (I'm 90% sure, usage of `ShelveStore` is not required).

Rethinking now, a possible solution will be that a `kedro` import needs to somehow skip the import of `ShelveStore`. Possibly, making `ShelveStore` it's own module might work. This can ensure the error is occured only when `ShelveStore` is explicitly being imported, at which point the alternative of using `SQLiteStore` would work.

**Comment by avan-sh** [comment]
An alternate way to trigger the error is to run the following lines in your console.
```
from kedro.framework.cli import main
import multiprocessing

multiprocessing.set_start_method("fork")
```

**Comment by MerelTheisenQB** [comment]
Thanks for explaining some more @avan-sh ! I will amend the first ticket to be more than just a docs change!

**Comment by noklam** [comment]
I think we need to fix this earlier - this blocks any deployment that requires multiprocessing, and there are no good workarounds.
