### ISSUE TITLE
pyspark-iris starter fails in kedro 0.18.0

### ISSUE THREAD

**Issue by bgereke** [kedro-org/kedro#1444]
## Description
0.18.0 kedro run fails with the pyspark-iris starter. I was able to resolve the error by changing line 35 of context.py from:

```
parameters = self.config_loader.get("spark*", "spark*/**")
```
to
```
parameters = self._config_loader.get("spark*", "spark*/**")
```

and line 40 from:

```
SparkSession.builder.appName(self.package_name)
```
to 
```
SparkSession.builder.appName(self._package_name)
```

Unsure of potential side-effects of those changes though.

## Context
I was working on creating my own custom starter based on pyspark-iris and discovered the error during initial testing. 

## Steps to Reproduce

1. pip install kedro
2. kedro new --starter=pyspark-iris #then answer questions
3. pip install -r src/requirements.txt
4. kedro run

## Expected Result
Expected the pipeline to run.

## Actual Result
Pipeline failed to complete with the following error(s):

```
AttributeError: 'ProjectContext' object has no attribute 'config_loader'
```

```
AttributeError: 'ProjectContext' object has no attribute 'package_name'
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.0
* Python version used (`python -V`): 3.7.13
* Operating system and version: mac

**Comment by SajidAlamQB** [comment]
Hi, @bgereke we are aware of this issue and are currently working on it. Your solution is absolutely correct.

**Comment by datajoely** [comment]
Thanks for raising this @bgereke !

**Comment by SajidAlamQB** [comment]
This issue is now resolved try pulling the latest `pyspark-iris`.

**Comment by cpdatabricks** [comment]
This issue has not been resolved for me.
