### ISSUE TITLE
Rewrite `_describe_git` in `KedroSession` to use python based implementation of the git commands

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#1451]
> https://github.com/FriendCode/gittle seems to be the easiest option, although it hasn't been maintained for years and it's probably not a good idea to rely on a seemingly abandoned project. Another option is to implement the two functions we need ourselves as per this example here: https://wyag.thb.lt/#orgd8ab0ff (which is more fun, but probably harder, especially for the `git status` check).

# Background
Traditionally we have been using `git` within kedro run to track metadata about the working directory. The current way we do is using `subprocess` which calls the git executable directly. However, it causes some issues when we are in some read-only / Databricks's dbfs / spark-submit job. 

The idea is to use native python calls to eliminate the need for an external process.

Todo:
- [ ] Find alternatives (open-source library or re-implement the 2 functions we need)
Possible solutions
* https://github.com/jelmer/dulwich (A low-level library that is still actively maintained)
* https://github.com/FriendCode/gittle  (A high-level library, but is no longer maintained)
* Implement ourselves (reference: https://wyag.thb.lt/#orgd8ab0ff)

# Use Case
* `_describe_git` https://github.com/kedro-org/kedro/blob/b3c78e57eab5865ffdc32a5813cb839811705d68/kedro/framework/session/session.py#L50-L71
  * ["git", "rev-parse", "--short", "HEAD"]
  * ["git", "status", "--short"],

**Comment by idanov** [comment]
Unfortunately `gitpython` will not fit the bill as it [needs the `git` executable](https://github.com/gitpython-developers/GitPython#requirements), which is exactly what we want to avoid depending on.

**Comment by avan-sh** [comment]
I'm not sure if this error would still pop up after [this change](https://github.com/kedro-org/kedro/pull/1422) to the function. The fatal error was also in directories without `.git` as fixed by that change.

**Comment by AntonyMilneQB** [comment]
As per @avan-sh, now we catch this error I think changing this is not as high priority as it was before. I guess we still want to do it, just it's not essential to get things working on databricks any more.

**Comment by avan-sh** [comment]
@AntonyMilneQB while I understand this is not a priority anymore, I don't get why this is still needed. It might be that using subprocesses is not be ideal.

**Comment by merelcht** [comment]
Closing in favour of https://github.com/kedro-org/kedro/issues/2051
