### ISSUE TITLE
Explain how Pipeline works

### ISSUE THREAD

**Issue by praveenkumarvps** [kedro-org/kedro#1455]
https://kedro.readthedocs.io/en/stable/tutorial/create_pipelines.html

Upon calling _kedro run_, could you please share light on how the code first executes 'preprocess shuttles' than 'preprocess companies'? I don't see an order of preference mentioned anywhere. 

Thanks in advance.

Regards,
Praveen

**Comment by datajoely** [comment]
So Kedro applies a data-centric view of the node inputs/outputs within a pipeline and applies something called a [topological sort](https://en.wikipedia.org/wiki/Topological_sorting).  We talk about it in the docs in a few places such as [this introduction](https://kedro.readthedocs.io/en/stable/nodes_and_pipelines/pipeline_introduction.html).
