### ISSUE TITLE
Provide better documentation on how the config glob pattern works

### ISSUE THREAD

**Issue by idanov** [kedro-org/kedro#1462]
Whilst issue #1363 raises more fundamental issues about the glob paths used by the configuration loader classes being tightly coupled with the low level `context`  object, as an interim solution we should better document what actually happens because it's currently not very clear in the docs.

https://github.com/kedro-org/kedro/blob/e78990c6b606a27830f0d502afa0f639c0830950/kedro/framework/context/context.py#L356

Looking for this information in the docs I checked the following places:

1. **configuration.md**
It is sort of present [here](https://kedro.readthedocs.io/en/stable/kedro_project_setup/configuration.html), but not really comprehensive. We could also do a better job describing the thinking and relationship of `AbstractConfigLoader`

2. **`kedro.config.ConfigLoader`**
It's sort of in the docstring here, but not really comprehensive. We could make it very clear for readers.

We should also make sure we use word 'glob' in the header it's easily retrievable / search indexed / linkable

**Comment by noklam** [comment]
The `ConfigLoader` docstring maybe a good place for mentioning the default.
