### ISSUE TITLE
Checkout parameter with spaceflights starter does not work

### ISSUE THREAD

**Issue by michalrudko** [kedro-org/kedro#1468]
## Description
It seems like checkout parameter with `spaceflights` starter does not work. For compatibility reasons, I wanted to use the tag `0.17.7` which corresponds to the kedro version I am using. According to the documentation (`kedro new -h`) this statement should be correct: `kedro new --starter=spaceflights —-checkout=0.17.7`

## Context
Failure to create kedro project with certain tag (version) of `spaceflights` starter.

## Steps to Reproduce
1. `pip install virtualenv`
2. `virtualenv workshop-env --python=python3.8`
3. `source workshop-env/bin/activate`
4. `pip install 'kedro==0.17.7'`
5.  `kedro new --starter=spaceflights —-checkout=0.17.7`

## Expected Result
This should create kedro project from the starter.

## Actual Result
```
(workshop-env) mr@mr-MacBook-Pro workshop % kedro new --starter=spaceflights —-checkout=0.17.7  
Usage: kedro new [OPTIONS]
Try 'kedro new -h' for help.

Error: Got unexpected extra argument (—-checkout=0.17.7)
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.7 (however same problem exists on 0.18.0)
* Python version used (`python -V`): 3.8.12
* Operating system and version: macOS 10.15.7

**Comment by datajoely** [comment]
Okay so this took me a while to work out, you've got a bad character in your checkout argument:

```diff
+kedro new --starter=spaceflights --checkout=0.17.7
-kedro new --starter=spaceflights —-checkout=0.17.7  
```
