### ISSUE TITLE
Ensure `logging.yml` is optional and tidy logging config

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro#1469]
**Must be completed after #1470.**

### Step 1
Delete (a) the file logging.yml and (b) the logs folder from all the following places:
* kedro project template
* kedro e2e test
* all kedro starters

**No longer doing the above; see https://github.com/kedro-org/kedro/issues/1461#issuecomment-1127770992.**

I think you'll get an exception like this:
```
kedro.config.abstract_config.MissingConfigException: No files found in ['/Users/antony_milne/kedro_stuff/projects/spaceflights/conf/base', '/Users/antony_milne/kedro_stuff/projects/spaceflights/conf/local'] matching the glob pattern(s): ['logging*', 'logging*/**', '**/logging*']
```
Catch this and emit as a debug level message instead. Write new tests/modify existing ones as needed.

**kedro/config/logging.yml should remain! Don't delete that.**

### Step 2 - No longer doing this; see https://github.com/kedro-org/kedro/issues/1461#issuecomment-1127770992.
Add the following to `configure_logging` after the `logging.config` line:
```
logging.getLogger(PACKAGE_NAME).setLevel(logging.INFO)
```

Add the following logger to `kedro/config/logging.yml`:
```
    # A logger for package_name is set at runtime in kedro.framework.project.__init__.
    # This is equivalent to the following entry.
    # package_name:
    #   level: INFO
```
Test to make sure this works as planned. Ask me to explain what this is all about.

### Step 3
Tidy up tests. Look for all places we write a logging.yml in tests and remove them. `local_logging_config` appears to be the way we do this, but check any other references to logs to make sure they should still be there. `local_local_config` in `tests/session/confest.py` is a special case that should remain.

### Step 4
Manual testing: check that everything works the same in terms of console and file logging when you do a `kedro run`. Make sure you test log messages coming from different places, e.g. something emitted from within the project.

**Comment by AntonyMilneQB** [comment]
Maybe! See https://github.com/kedro-org/kedro/issues/1472.

**Comment by MerelTheisenQB** [comment]
Speak to @AntonyMilneQB for details on approaches.

**Comment by AntonyMilneQB** [comment]
This issue has changed a bit: see https://github.com/kedro-org/kedro/issues/1461#issuecomment-1127770992 for explanation.
