### ISSUE TITLE
Add version compatibility to Kedro to KFP deployment.

### ISSUE THREAD

**Issue by ozora-ogino** [kedro-org/kedro#1475]
This example is not compatible with under v0.17.0.
Specifying the compatible version (v0.18.0) is helpful for the readers.

https://kedro.readthedocs.io/en/stable/deployment/kubeflow.html

Thank you.

**Comment by noklam** [comment]
Thank you for the report, you can choose which version of documentation you need using the menu on the left.

![Screenshot_20220423-105053.png](https://user-images.githubusercontent.com/18221871/164889558-bf22bd85-d6d5-42bc-8249-3843d3db1ef9.png)

**Comment by ozora-ogino** [comment]
I didn’t know that.
Thank you for kind replying.

**Comment by noklam** [comment]
Glad it helps🙂 Closing the issue now. Consider joining Kedro Discord channel via https://discord.gg/akJDeVaxnB.
