### ISSUE TITLE
Migrate from recommonmark to MyST

### ISSUE THREAD

**Issue by avan-sh** [kedro-org/kedro#1479]
## Description
We use recommonmark plugin to write docs in markdown format, but this package has been deprecated and archived. The recommendation is to use [MyST](https://github.com/executablebooks/MyST-Parser) instead.

See https://github.com/readthedocs/recommonmark/issues/221 for more info.

## Context
Using mermaid in our docs as proposed by #1392 and any other future changes might require a switch to `MyST` as recommended by [sphinxcontrib-mermaid](https://github.com/mgaitan/sphinxcontrib-mermaid#markdown-support). 

Trying an older suggestion `sphinxcontrib-mermaid` (version 0.7) doesn't work, so it might still require the migration to MyST.

**Comment by datajoely** [comment]
Love this

**Comment by deepyaman** [comment]
@avan-sh I accidentally got here while trying to update #1392! I will try and close this out in the same issue, then (or I can separate it out, never say no to a commit).
