### ISSUE TITLE
Unable to set TemplatedConfigLoader as CONFIG_LOADER_CLASS

### ISSUE THREAD

**Issue by Mercurrent** [kedro-org/kedro#1490]
## Description
When setting TemplatedConfigLoader in setting.py for CONFIG_LOADER_CLASS I get error:

dynaconf.validator.ValidationError: Invalid value `kedro.config.templated_config.TemplatedConfigLoader` received for setting `CONFIG_LOADER_CLASS`. It must be a subclass of `kedro.config.config.ConfigLoader`.

## Context
How has this bug affected you? What were you trying to accomplish?
Transition into Kedro 0.18.0, getting rid of register_catalog hooks.

**Comment by noklam** [comment]
A temporary hacky fix would be https://github.com/kedro-org/kedro/issues/1402.

**Comment by noklam** [comment]
Closing this as this is repeated issue in #1402
