### ISSUE TITLE
Create a new package `kedro-datasets` as part of `kedro-plugins`

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro#1492]
- [ ] Create the new package in `kedro-plugins`
- [ ] Copy all datasets to the new `kedro-datasets` package including the relevant `extras_require=`
https://github.com/kedro-org/kedro/blob/1b1558952c059eea5636d9ccf9a883f9cf4ef643/setup.py#L107-L148
- [ ] Move all dataset tests to `kedro-datasets`

**Comment by noklam** [comment]
PR is merged https://github.com/kedro-org/kedro-plugins/pull/38
