### ISSUE TITLE
Add redirect from `pip install kedro[xxxx]` to `pip install kedro-datasets[xxxx]`

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro#1496]
Now that `kedro-datasets` is namespaced, It might be confusing for users that they can import kedro-datasets through `import ... from kedro`, but need to install a dataset with `pip install kedro-datasets[xxx]` and not` pip install kedro[xxx]`.

We should add a redirect to make this possible, by making all datasets-related `extras_require=` on `kedro` install the relevant `kedro-datasets[xxxx]`. We need to make sure that we bound the specification on the `kedro` side to a suitable version of `kedro-datasets` like `kedro-datasets~=1.0`. 

Investigation needs to be done into whether we need to explicitly do a mapping from `kedro[pandas.CSVDataSet]` to `kedro-datasets[pandas.CSVDataSet]`, `kedro[pandas.ParquetDataSet]` to `kedro-datasets[pandas.ParquetDataSet]`, etc. or whether there's a way of automating in general `kedro[X]` to `kedro-datasets[X]`.

**Comment by AntonyMilneQB** [comment]
We are no longer doing this - see https://github.com/kedro-org/kedro/issues/1758#issuecomment-1234505832. You will only be able to `pip install kedro` and `pip install kedro-datasets[xxx]`.
