### ISSUE TITLE
Check if improvements are needed for `test_requirements.txt` setup

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#1498]
Check if any of the below is still needed now we've implemented the `pyproject.toml` setup + datasets are removed:

- [x] Try and figure out a nicer way of installing all the dependencies listed in the `setup.py` file rather than needing to maintain a separate `test_requirements.txt` file there -> `test_requirements.txt` doesn't exist anymore. Instead of this do:
   - [x] Remove `setup.py`.
 - [x] Clean up kedro's test requirements to remove requirements for datasets that aren't needed any more

**Comment by sbrugman** [comment]
`test` could be another `extras_require`. The `tests_require` now used in `setup.py` seem not to be part of the `pyproject.toml` metadata ([ref]), so this move would be a step in that direction (https://github.com/kedro-org/kedro/issues/1724).

**Comment by deepyaman** [comment]
> `test` could be another `extras_require`. The `tests_require` now used in `setup.py` seem not to be part of the `pyproject.toml` metadata ([ref]), so this move would be a step in that direction (#1724).

+1 on this approach; some packaging frameworks (like `flit`) have this special `test` extra (which I guess lends credibility to the approach?), and I've also used it on some other projects personally.

**Comment by astrojuanlu** [comment]
Note that in #2475 `tests_requires` was removed, there's only `test_requirements.txt`. #2152 was partially addressed, so at least now even if there's a `setup.py` for some dynamic stuff, most of the metadata is in `pyproject.toml`. We could definitely add another `optional-dependencies` group (former "extras").

**Comment by astrojuanlu** [comment]
Reopening, still some work to be done

**Comment by merelcht** [comment]
Completed in https://github.com/kedro-org/kedro/pull/3144 and https://github.com/kedro-org/kedro/pull/3143
