### ISSUE TITLE
How to Join 2 Data Catalogs

### ISSUE THREAD

**Issue by praveenkumarvps** [kedro-org/kedro#1509]
Hello Team,

I am a beginner exploring Kedro Framework and I have a question on joining 2 data catalogs.

Assume I have 2 data catalogs in my intermediate data path - 'catalog1' and 'catalog2' and both have same column called 'column'. I need to join these 2 data catalogs with the common column. 

Can you please explain how to do the same?

Thanks,
Praveen

**Comment by MerelTheisenQB** [comment]
Hi @praveenkumarvps, do you still need help with this?

**Comment by noklam** [comment]
@praveenkumarvps  Closing the issue for now. If you still have question feel free to reopen the issue or join our [Discord Channel](https://discord.com/invite/akJDeVaxnB) and ask questions there.
