### ISSUE TITLE
Change default logging.yml to use RichHandler 2: fancy tracebacks

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro#1513]
**🥳  FUN TICKET 🥳 Prerequisites: #1512. Based off point 4 of https://github.com/kedro-org/kedro/issues/1464**

* Understand what exactly is the difference between setting [`rich_tracebacks: True`](https://rich.readthedocs.io/en/stable/logging.html#handle-exceptions) on our `rich` logging handler vs. [`rich.traceback.install`](https://rich.readthedocs.io/en/stable/traceback.html#traceback-handler) - it would probably be neatest if we can achieve everything we want to just by altering the log handler and not running `rich.traceback.install`
* Play around with the [options available for logging handler](https://rich.readthedocs.io/en/stable/reference/logging.html) or [options for `rich.traceback.install`](https://rich.readthedocs.io/en/stable/reference/traceback.html#rich.traceback.install) depending on which we are using
  - probably the defaults are good for our use, but feel free to change any if there are better values for our use
  - in particular, `suppress` for `click` and/or `kedro` looks like the most powerful option to add
  - overall we want exceptions to be clear to the user exactly what the problem is so that they can debug things easily without having to wade through long tracebacks of unrelated framework errors
* Assuming we're going for the log handler route, add the right options to all the places where `rich` logging handler is defined (framework logging.yml + project-side logging.yml + starters + e2e test)
* Test thoroughly to check that `kedro run` works nicely when there are exceptions coming from different places (e.g. in a node function, in some external libary, in the kedro framework, a `KedroCLIError`)
* Test similarly to see what happens if you do `session.run` in ipython and jupyter

**Comment by MerelTheisenQB** [comment]
Look at how this works in `PyCharm` and other IDEs. @noklam mentioned this might potentially break links in `PyCharm`.

**Comment by AntonyMilneQB** [comment]
@noklam I think this might actually be a more general problem with PyCharm rendering Rich output, not just the traceback feature. 

From a quick read, it seems that enabling "emulate terminal" in PyCharm should make this work, but that setting does not work with PyCharm debug mode.

We should check this and add to our docs since doing a kedro run using Run Configurations in PyCharm is a common workflow and we already discuss it: https://kedro.readthedocs.io/en/stable/development/set_up_pycharm.html#set-up-run-configurations

References:
https://github.com/Textualize/rich/issues/206
https://youtrack.jetbrains.com/issue/PY-43860/Python-package-rich-print-text-in-color-bold-etc-does-not-print-
Advice from [Rich's docs](https://rich.readthedocs.io/en/stable/introduction.html#requirements):
> PyCharm users will need to enable “emulate terminal” in output console option in run/debug configuration to see styled output.
