### ISSUE TITLE
Document what the `ShelveStore` is for

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#1537]
## Description
Users are running into issues when using the `ShelveStore` and other tools that use multiprocessing, e.g. Prefect. See: https://github.com/kedro-org/kedro/issues/1442

This has been reported by several users.

## Implementation

- [X] It seems that even if a user isn't using the `ShelveStore`, kedro imports it and this interferes with multiprocessing used by other tools. Verify this is the case, and if so make sure Kedro _only_ imports `ShelveStore` when it's explicitly set as the session store. This has been solved in : https://github.com/kedro-org/kedro/pull/1614
- [ ] Clarify in docs + tutorials that the `ShelveStore` is not the default. Explain what it does, so hopefully users will only use it if really needed.

**Comment by avan-sh** [comment]
I think I might have found a solution for this, happy to make other necessary changes on this. 
Also please highlight if there are any other instances of conflicts from other libraries other than 1442.

**Comment by astrojuanlu** [comment]
Was the docs/tutorials part done? Sorry, I'm missing some context here

**Comment by noklam** [comment]
@astrojuanlu No, but I guess the priority for that will be really low. We use to put ShelveStore as a commented line in `settings.py`. Recently I update that with #2587, in practice I don't think anyone use it at all.
