### ISSUE TITLE
Update default suggestions in `settings.py` to ones that work

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#1538]
## Description
Update docs and default suggestions in `settings.py`, because currently some of those suggestions don't actually work. 

Currently, the `BaseSessionStore` is the default session store. The other possible stores a user can use are the `ShelveStore` and the `SQLiteStore` (currently part of viz).

The `ShelveStore` is the default suggestion to override the default in `settings.py`, but when users are using some sort of multiprocessing this store type will not work. See: https://github.com/kedro-org/kedro/issues/1442

Also look at the other default suggestions and verify that they make sense. 

(Later consideration, but not part of this work)
If we move the `SQLiteStore` from viz to kedro core, we could add that as the default suggestion instead.

**Comment by noklam** [comment]
I suggest remove the `ProjectHooks` default too since it's not available anymore. But we should leave the `HOOKS` variable there or provide an example so people understand that they need to pass in a hook **instance** into a tuple.

**Comment by astrojuanlu** [comment]
@noklam you refer to this right?

https://github.com/kedro-org/kedro/blob/main/kedro/templates/project/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/%7B%7B%20cookiecutter.python_package%20%7D%7D/settings.py#L5-L7

What would be a better suggestion nowadays?

**Comment by astrojuanlu** [comment]
For reference, `hooks.py` was removed from the project template in https://github.com/kedro-org/kedro/pull/1074
