### ISSUE TITLE
Get parallel runner to recognise framework-side logging config

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro#1558]
The parallel runner does not seem to use the framework-side logging config. By default, if you do a `kedro run --runner=ParallelRunner` then the project-side logging config is picked up correctly and you will see the logs correctly in the console and in the logs/info.log file. However, if you delete conf/base/logging.yml then most messages will no longer be logged:
![image](https://user-images.githubusercontent.com/49395058/169293527-71261b43-ffea-4347-bcac-22fe3666c8ff.png)

See [this explanation](https://github.com/kedro-org/kedro/issues/1461#issuecomment-1116955368) for how logging config is setup for `kedro run`. However, with the parallel runner there's something else that happens too. Assuming that conf/base/logging.yml does exist:
1. https://github.com/kedro-org/kedro/blob/676600c4b63eec53c13fc4e2536d0a990dac77ce/kedro/framework/session/session.py#L190
calls this function:
https://github.com/kedro-org/kedro/blob/62cc27a1441ad49761d38c44e425a77871b6ba74/kedro/framework/project/__init__.py#L208
This sets the global `LOGGING` to be the project-side logging config.
2. `LOGGING` is used in https://github.com/kedro-org/kedro/blob/main/kedro/runner/parallel_runner.py to `_bootstrap_subprocess` which means that all subprocesses have the project-side logging config.

This seems to work (although it's not very nice to have the global variable). However, when there's no conf/base/logging.yml, `configure_logging` isn't called, so `LOGGING` will be left as `None`, so `_bootstrap_subprocess` won't set the logging configuration. This is fine because there's no project-side logging.yml to use _BUT_ the problem is that the framework-side logging doesn't make it into the subprocesses, so no log messages get shown at all.

What we need to do is:
* make sure that the framework-side logging config makes it to the subprocesses. e.g. maybe the default `LOGGING` should not be `None` but instead what comes out of `kedro.config.default_logger`
* ideally figure out a way to do all this without needing the global `LOGGING` so we can remove that

**Comment by noklam** [comment]
Interesting, the behaviour is not the same in `Windows` and `Linux`.

If I do `kedro run --runner ParallelRunner`, the console logs are actually there even if I delete the `logging.yml`.

**Comment by AntonyMilneQB** [comment]
The above problem should exists for cases where the subprocesses are spawned rather than forked.
* spawn, as done on Windows (all Python versions) and macOS (Python 3.8+) ➡️ subprocesses need to get `LOGGING`, hence above bug exists (initial `INFO     Kedro project spaceflights` gets shown in rich, then there's no output)
* fork, as done on Unix (all Python versions) and macOS (Python 3.7) ➡️ subprocesses don't need to get `LOGGING` and will keep the framework-side one, hence above bug doesn't exist (and all messages get rendered in rich as expected)
BUT actually now I can't reproduce the bug at all on my mac?? i.e. it seems to show all logs for both Python 3.7 and Python 3.9?

There does not seem to be a good way to get rid of `LOGGING` global variable. This was actually added relatively recently (https://github.com/kedro-org/kedro/pull/1103 and https://github.com/kedro-org/kedro/pull/1114) and is a lighter coupling than we used to have (which was to the kedro session). The ultimate problem boils down to how Python spawns processes (different behaviour from forking). See https://github.com/quantumblacklabs/private-kedro/pull/850.

**Comment by noklam** [comment]
See the results in PDF [ParallelRunnerLogging.pdf](https://github.com/kedro-org/kedro/files/8947548/ParallelRunnerLogging.pdf)

Few things that I found inconsistent.

## 1st round of experiment - All without `logging.yml`

1. I expect Mac Py3.7 should has the same behavior as Unix, but here I see the full log printed out. (with/without plugin)
2. With plugin installed, all logs are printed for Mac Py3.8 (Spawn process)

Seeing the log is not clear enough, so I do another set of testing with `logging.yml` but with `console` log, so it's clearly if there are logs that didn't apply the config correctly.

## 2nd round - with `logging.yml` + `console` handler
1. This time, `Mac Py3.8 + without plugin` logs are completely normal and format correctly.
2. Mac 3.7 logs are corrected - which is expected because we have provide `logging.yml`
3. `Mac Py3.8 + plugin`, you can clearly there a few lines of log didn't format properly.

**Comment by AntonyMilneQB** [comment]
Thanks very much @noklam for all this testing, it's very helpful!!

## 1st round of experiment - All without `logging.yml`

> 1. I expect Mac Py3.7 should has the same behavior as Unix, but here I see the full log printed out. (with/without plugin)

This is what I would expect: python 3.7 on mac should indeed be the same as Unix, which means processes are forked, and so the bug where logs don't get shown with ParallelRunner doesn't exist.

> 2. With plugin installed, all logs are printed for Mac Py3.8 (Spawn process)

This is definitely weird.

## 2nd round - with `logging.yml` + `console` handler
> 1. This time, `Mac Py3.8 + without plugin` logs are completely normal and format correctly.
> 2. Mac 3.7 logs are corrected - which is expected because we have provide `logging.yml`

These are both what I would expect. 

> 3. `Mac Py3.8 + plugin`, you can clearly there a few lines of log didn't format properly.

This is definitely weird. Just to check: these are exactly the same lines you see missing from the Windows e2e test log file, right?

I will investigate further but overall the issue definitely seems to be plugin + logging + spawned process (i.e. mac + Python 3.8 or Windows e2e tests). Hopefully we can kill both this issue and your windows e2e test issue at the same time.

**Comment by AntonyMilneQB** [comment]
P.S. do you know why all those geopandas warnings are being thrown for Python 3.8?
