### ISSUE TITLE
Clean up setuptools and wheel requirements to align with PEP-518

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#1559]
We've got `"setuptools>=38.0"` and `wheel` requirements in various other places in the repo (just do a Ctrl+F to see them). Does this mean we can remove them from there?

If yes then that would be nice but a bit of a bigger change, so probably worth doing in a separate PR.

_Originally posted by @AntonyMilneQB in https://github.com/kedro-org/kedro/pull/1542#discussion_r877557600_

**Comment by astrojuanlu** [comment]
When #2152 is addressed, I guess the build requirements would only be specified in the PEP 518 `[build-system]` table of `pyproject.toml`.

**Comment by merelcht** [comment]
@astrojuanlu Is there any more work that needs to be done here, or is it completed with #2152 as you commented above?

**Comment by astrojuanlu** [comment]
I _think_ we should be able to safely remove them from scripts and files used for development, namely:

https://github.com/kedro-org/kedro/blob/7dcb60c7309739dc41731b5d84daeb23ab50c956/Makefile#L10-L11

https://github.com/kedro-org/kedro/blob/7dcb60c7309739dc41731b5d84daeb23ab50c956/features/environment.py#L108-L109

https://github.com/kedro-org/kedro/blob/7dcb60c7309739dc41731b5d84daeb23ab50c956/dependency/requirements.txt#L21

https://github.com/kedro-org/kedro/blob/7dcb60c7309739dc41731b5d84daeb23ab50c956/tools/circleci/requirements.txt#L2

However, there are other mentions related to `kedro package`, (which will require addressing https://github.com/kedro-org/kedro/issues/2413 first), and maybe the starters (https://github.com/kedro-org/kedro/issues/2280).

**Comment by merelcht** [comment]
Okay cool, thanks for the clarification! In that case let's get #2413 in the next sprint and complete that first.

**Comment by astrojuanlu** [comment]
Closed in #2927
