### ISSUE TITLE
blacken-docs missing python failure

### ISSUE THREAD

**Issue by AtmosOne** [kedro-org/kedro#1565]
## Description
`blacken-docs` refers to cached pre-commit environment that does't exists

## Context
I wanted to create pull request with feature for further discussion, but failing at pre-commit check

## Steps to Reproduce
1. created environment: `conda create -n kedro python=3.10 -y`
2. installed requirements: `make install-test-requirements`
3. installed pre-commit hooks: `make install-pre-commit`
4. executed pre-commit hook: `make lint`

## Expected Result
Successful pass or `blacken-docs` internal exception

## Actual Result

```
blacken-docs.............................................................Failed
- hook id: blacken-docs
- exit code: 1

Executable `/home/atmosphere/.cache/pre-commit/repoiq31kknf/py_env-python3/bin/python` not found
```

```zsh
(kedro) ➜  kedro git:(parametrized-session-id) ✗ blacken-docs --skip-errors
Traceback (most recent call last):
  File "/home/atmosphere/miniconda3/envs/kedro/bin/blacken-docs", line 8, in <module>
    sys.exit(main())
  File "/home/atmosphere/miniconda3/envs/kedro/lib/python3.10/site-packages/blacken_docs.py", line 203, in main
    black_mode = black.FileMode(
  File "<string>", line 3, in __init__
TypeError: set object expected; got list
```
## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): under `main` branch by 23.05.2022
* Python version used (`python -V`): `Python 3.10.4`
* Operating system and version: `Ubuntu 20.04.3 LTS`

**Comment by noklam** [comment]
Seems to relate to `black` itself. See GH issue here: https://github.com/asottile/blacken-docs/issues/141

**Comment by AtmosOne** [comment]
@AntonyMilneQB Thank you, proposed version `v1.12.1` works for me
