### ISSUE TITLE
Rearrange pipeline creation documentation page

### ISSUE THREAD

**Issue by chsafouane** [kedro-org/kedro#1570]
In the documentation page on [creating pipelines](https://kedro.readthedocs.io/en/stable/tutorial/create_pipelines.html), two pipelines are created:
- **data_processing**
- **data_science** 

In the first part concerning the **data_processing pipeline**, the pipeline is [created](https://kedro.readthedocs.io/en/stable/tutorial/create_pipelines.html#assemble-nodes-into-the-data-processing-pipeline) and then comes the part where the output data is [added to catalog.yml](https://kedro.readthedocs.io/en/stable/tutorial/create_pipelines.html#persist-pre-processed-data).

This way of doing things makes sense as the name of the output is specified in the corresponding node and then it's added to the config.yml.

The problem is that the part concerning the [data_science pipeline](https://kedro.readthedocs.io/en/stable/tutorial/create_pipelines.html#data-science-pipeline) does things in reverse order. It starts by adding outputs to [config.yml](https://kedro.readthedocs.io/en/stable/tutorial/create_pipelines.html#register-the-dataset) and then [specifies them in the corresponding pipeline](https://kedro.readthedocs.io/en/stable/tutorial/create_pipelines.html#assemble-the-data-science-pipeline). 

While this might seem not that much important, for first-time readers of the documentation, it might be helpful to have things in the same order.

**Comment by MerelTheisenQB** [comment]
Thanks for the feedback @chsafouane ! That makes a lot of sense 🙂  I'll add it to our backlog, but if you have time to open a PR yourself, that would be very much appreciated!

**Comment by schergui-thefork** [comment]
@MerelTheisenQB Thanks, I'll make a PR regarding this tomorrow then👍

**Comment by chsafouane** [comment]
@MerelTheisenQB Thanks, I'll make a PR tomorrow then👍

**Comment by noklam** [comment]
Thank you @chsafouane! Let us know if you need any help with the PR.
