### ISSUE TITLE
Use pre-commit.ci to enforce and fix linting

### ISSUE THREAD

**Issue by deepyaman** [kedro-org/kedro#1598]
## Description
I'm always frustrated when waiting for pre-commit hooks to install on the CircleCI worker. It's also annoying when a PR fails due to a linter issue, especially when making changes from the GitHub UI (and then the hooks need to get reinstalled, yada yada yada...).

## Context
pre-commit.ci enforces and fixes issues enforced through pre-commit, and also helps keep hooks up to date. It's also more efficient. Best of all, it's free for open-source projects!

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by jmholzer** [comment]
Discussed in backlog grooming 30/01/23: 

1. Potentially move these hooks to push.

**Comment by deepyaman** [comment]
Not 100% sure this requires technical design? It's pretty straightforward to set up pre-commit.ci, if going that route (and it should just take a day or two to prove out pre-commit.ci, for somebody who has no familiarity with it/hasn't used it before).

**Comment by merelcht** [comment]
@deepyaman I guess it probably makes more sense for someone to come with a proposal before potentially discussing it in tech design. Would you mind adding some of your suggestions to the possible implementation description above?

**Comment by merelcht** [comment]
Closing as this hasn't had any recent activity and it doesn't seem to be something many team members need/want.
