### ISSUE TITLE
Standardize use of project name and python package in documentation

### ISSUE THREAD

**Issue by deepyaman** [kedro-org/kedro#1608]
I somehow got into the business of standardizing `<project-name>` and `<python_package>`, since I missed the `--skip-errors` flag in the `blacken-docs` entrypoint (I forgot that there were two things that needed to be blackened that were actually failing the build).

On that note:

* It's a bit inconsistent to have `<project-name>` and `<python_package>` (dash and underscore, respectively), but I guess that's fair enough, since the actual package name really can't have a dash.
* You have a couple instances in https://github.com/kedro-org/kedro/blob/0.18.1/kedro/framework/session/session.py#L76-L87 with inexplicably roundabout terms for `<python_package>`, but I left them as is.
* A number of files use `<project-root>` or `<project_root>` instead of `<project-name>` and, while I think this could be standardized, there are instances like `<path-to-your-project-root>` in https://github.com/kedro-org/kedro/blob/0.18.1/docs/source/development/commands_reference.md that don't make sense as `<path-to-your-project-name>`. Maybe something to update in the lexicon?

_Originally posted by @deepyaman in https://github.com/kedro-org/kedro/issues/1602#issuecomment-1151740011_

**Comment by AntonyMilneQB** [comment]
Very relevant: https://github.com/kedro-org/kedro/issues/1361. Interested in hearing your thoughts on that @deepyaman. When we make that change then maybe we should try and standardise this too I think.

**Comment by AntonyMilneQB** [comment]
P.S. this is just a docs issue, right?

**Comment by deepyaman** [comment]
> P.S. this is just a docs issue, right?

Yep! I can't add labels, either. 😢
