### ISSUE TITLE
Additional user requirements for parametrized `session_id`

### ISSUE THREAD

**Issue by AtmosOne** [kedro-org/kedro#1609]
## Description

Hello! I know, that you have In a backlog discussion related to parametrized `session_id` and as a user I would like to add mine extra requirements.

1. As a user I want to specify *(entire or prefix or suffix)* of `session_id` as parameter in Kedro CLI
2. As a user I want to log all data I/O operations within scope of particular `session_id`

*(entire or prefix or suffix)* - This part depends on your decision about how you will manage it

## Why as user I would like to have this feature

1. This feature would help to link node & pipeline logs with logs produced from other components in my system when I execute pipelines using `kedro run` command
2. Awareness about `session_id` inside of functions of `DatasetSpecs` class would help to distinguish to which kedro session I/O operation does belong inside of logs. But I don't about degree of coupling kedro striving between `KedroSession` and `DataCatalog` classes, so I think safest is to make `session_id` optional to keep lowest

## Importance

1. Not critical, nice-to-have: I consider feature as nice-to-have because, I can store extra details of KedroSession as environment variable, and refer to them when I log something.
2. Not critical, nice to have: I consider feature as nice-to-have because, I the same as above I can refer to env variable

Thanks for your support

**Comment by noklam** [comment]
@AtmosOne Thanks for creating the issue, what's the motivation for this request? Does this related to #1551 ?

**Comment by AtmosOne** [comment]
@noklam Yes, you are correct it is related to #1551. Sorry, now understand that I should attach this content to issue created earlier

**Comment by noklam** [comment]
I am trying to summarize the information around this `session_id` and different use cases for our internal technical discussion. It would be great to understand the use cases. Is it the same use case that you mentioned #1571 here? or you need it for another reason?

**Comment by AtmosOne** [comment]
Given issue is extension to #1571 which focussed on use case of how I would like to specify `session_id` and how I would like to use it in kedro hooks, particularly `DatasetSpecs` hooks.

**Comment by noklam** [comment]
Closed as duplicate as #1551
