### ISSUE TITLE
Document how users can use `pytest` instead of `kedro test`

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro#1619]
In https://github.com/kedro-org/kedro/issues/1293 we decided to remove the `kedro test` command, which was really only a small wrapper around `pytest`. 

We need to update our documentation to remove any suggestions of `kedro test` and instead write instructions for our users on how to use `pytest`.

**Comment by yetudada** [comment]
This ticket will have implications on #1271
