### ISSUE TITLE
[Needs User Input!] Is there demand for a `kedro-tools` plugin?

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#1622]
[One of the suggestions made after researching the use of kedro CLI commands ](https://github.com/kedro-org/kedro/issues/1293) that can be considered as tools (e.g. `kedro lint`, `kedro jupyter convert`..) was to move these CLI commands to a separate plugin: `kedro-tools`/`kedro-with-tools` (name is tbd)

**We'd like to get users' opinions on the following proposal**. Keep in mind that as was decided in the original research, all the following CLI commands will be removed: `kedro lint`, `kedro test`, `kedro build-docs`, `kedro build-reqs`, `kedro jupyter convert`, `kedro activate nbstripout`

(Below was originally written by @AntonyMilneQB on the research issue)

# Proposal

We strip out all these commands from core kedro, all our current starters, remove packages from requirements.txt, etc.

We (_or someone else_) make a new plugin `kedro-with-tools` (name completely made up for now) that includes:
* `kedro tools` group of commands (like the `kedro dev` group I said above) including `lint`, `test`, `build-docs`, whatever
* dependencies to make all these work
* a starter template (call it `kedro with-tools-starter`) that is heavier than the core one and includes any required configuration (e.g. pyproject.toml, .pre-commit-config.yaml). Along these lines: https://github.com/kedro-org/kedro-starters/pull/40

**Important note:** I say "we or someone else" because I think could be a very good candidate for an unofficial community-maintained plugin. Or we could get it started and then hand over, or we could maintain it but be much more relaxed in accepting updates than we are with the core kedro template.

# User journey

Note that `pip install` immediately makes the new `kedro-with-tools-starter` alias available thanks to #1592.

**Starting a new project:**
```
pip install kedro-with-tools 
kedro new -s kedro-with-tools-starter  # Makes new project template with pre-commit etc. config
kedro tools lint etc. commands are now available
```

**In existing project:**
```
pip install kedro-with-tools 
kedro tools init  # Not sure if we'll actually need this command at all. But it would copy pre-commit etc. config to already existing project
kedro tools lint etc. commands are now available
```

# Pros

* The kedro CLI becomes very clean. We no longer have any little-used commands cluttering it up. The top-level groups like `kedro pipeline`, `kedro catalog` become much more discoverable because they're not hidden among lower-level commands all sitting at the same level
* The core kedro template and starters become very clean and lighter weight
* No need for any dev_requirements.txt. A project requirements.txt would include the bare minimum of what's actually needed. No need to ever touch these dependencies again (as with kedro-datasets, these project dev dependencies tend to move faster than than our core ones and cause a disproportionate number of conflicts and irritations, e.g. piptools has broken through conflicts with pip 3 times this year already)
* We no longer need to worry so much about maintaining the `kedro lint` etc. commands. These are hard to keep up to date since best practice Python tooling changes (e.g. sphinx; [this article](https://python.plainenglish.io/2022-update-understanding-best-practice-python-tooling-by-comparing-popular-project-templates-5872602fe617). The current "recommendations" we make through the project template are kind of arbitrary (e.g. why do we do `isort` but not `mypy` in lint? Just because we haven't updated it for ages I think). We're not really best placed to judge what are the best tools, and it's always changing. If this is community maintained then we don't need to worry about staying on top of it at all! 
* It's consistent with the move to `kedro-datasets`, i.e. a lean core which is extendible
* Very non-disruptive. Everyone who doesn't use these commands immediately benefits from a cleaner kedro; those who do want to use them can still do just by doing a single `pip install`. None of the current functionality is actually lost - it's just moved. In fact, user will have access to better, more up to date versions of these commands
* Nicely showcases the power of plugins for providing custom CLI commands and starters

References that inspired this idea: https://github.com/kedro-org/kedro/issues/826; https://github.com/kedro-org/kedro/discussions/844#discussioncomment-1034549; https://github.com/kedro-org/kedro-starters/pull/40

# Cons
* Discoverability of these commands is harder than it currently is since wouldn't appear by default when you do `kedro`. On the other hand, discoverability of the "core" kedro commands is enhanced
* We need to update our docs and messaging a bit. kedro is all about promoting good software engineer practice, and at the moment a (small) part of that is in our "recommendation" of the tools that we have in our project template and associated `lint` etc. commands. @yetudada above didn't see this is a problem. Given how few people use the commands, I don't think they can be a major part of the kedro value proposition

**Comment by WaylonWalker** [comment]
This sounds very similar to how our template looks, we ripped out the entire cli from the default template, put it in a library, and replaced it with `from <internal-lib> import cli`.  Pipeline Authors can still make custom cli functions, and we have only one place to change all of the built-in cli functions, and our own custom ones to get them in every project.  If you do this the commands are just as discoverable and easy for those who don't want to rip it out.

I'm personally all in on this.

**Comment by deepyaman** [comment]
For my full, initial response to the above proposal, please see https://github.com/kedro-org/kedro/issues/1293#issuecomment-1156339787.

If the above were to be implemented, what users would do `kedro new` but not `kedro new -s kedro-with-tools-starter`? If everybody does indeed prefer `kedro new -s kedro-with-tools-starter`, you've essentially made the `--starter` option unavailable for anything else. Would you also now create `kedro-spaceflights-with-tools-starter`, `kedro-pyspark-iris-with-tools-starter`, etc.?

**Comment by deepyaman** [comment]
On a slightly different note, I do think a `kedro-tools` plugin that offered a lot more would be good. For example, I think the Kedro end-to-end testing framework is something that could be exposed, to allow users to more easily write BDD tests. This is a pretty heavy lift right now, that involves understanding and copying code from the `features/` dir of the Kedro repo.

**Comment by WaylonWalker** [comment]
> If the above were to be implemented, what users would do kedro new but not kedro new -s kedro-with-tools-starter? If everybody does indeed prefer kedro new -s kedro-with-tools-starter, you've essentially made the --starter option unavailable for anything else. Would you also now create kedro-spaceflights-with-tools-starter, kedro-pyspark-iris-with-tools-starter, etc.?

How different would these starters be in practice?  Is it just a different `cli.py`?  If it's just a different cli.py then you can do that with jinja and a cookiecutter question.

**Comment by MerelTheisenQB** [comment]
@deepyaman The research outcome shows that hardly any of our users really actively use the tool commands like `kedro lint`, so my guess is that a lot less people would end up using `kedro new -s kedro-with-tools-starter`. Of course this assumption could be wrong, so that's why in this issue we would like to know how much appetite there would be for a plugin that keeps all those CLI commands.

**Comment by deepyaman** [comment]
> @deepyaman The research outcome shows that hardly any of our users really actively use the tool commands like `kedro lint`, so my guess is that a lot less people would end up using `kedro new -s kedro-with-tools-starter`. Of course this assumption could be wrong, so that's why in this issue we would like to know how much appetite there would be for a plugin that keeps all those CLI commands.

@MerelTheisenQB But, from the way I read the research, you don't know why users aren't using commands like `kedro lint`, right? Are they running the underlying commands themsleves--`pytest`, `black`, `isort`, `flake8`, etc.--or are they not following these best practices at all? If they're just using the underlying commands, what I'm trying to say is that you don't want to make it harder to do the same by providing a template that doesn't satisfy those checks off the bat.

**Comment by AhdraMeraliQB** [comment]
https://github.com/kedro-org/kedro/issues/2075 is also in favour of an external plugin (specifically for build-docs in this case)

**Comment by astrojuanlu** [comment]
Yes, I think the point is: if we are to effectively move forward with the deprecation decision and remove these commands, it would be nice if we offered a migration path for folks that still want to use them.

**Comment by merelcht** [comment]
This ticket hasn't attracted a lot of input from the community. It also overlaps a lot with the utilities workflow: https://github.com/kedro-org/kedro/issues/2388 

I am closing this issue as something we're not building right now. Let's see what the feedback is on the revamped `kedro new` flow and if any tools like the ones described here are still needed then.
