### ISSUE TITLE
Simplify overriding parameters when accesing explicit parameter values in a modular pipeline

### ISSUE THREAD

**Issue by ianwhale** [kedro-org/kedro#1623]
## Description

I'm always frustrated when I define a function that accepts specific values (as in not an entire `parameters` dictionary) and have to override each individual parameter in a modular pipeline. See example:

```python
# pipeline_registry.py

from typing import Dict

from kedro.pipeline import Pipeline, pipeline, node


def register_pipelines() -> Dict[str, Pipeline]:
    pipe = pipeline([
        node(print, "params:pipeline.param_1", None),
        node(print, "params:pipeline.param_2", None),
    ])

    pipe_2 = pipeline(
        pipe,
        parameters={
            "params:pipeline.param_1": "params:pipeline_2.param_1",
            "params:pipeline.param_2": "params:pipeline_2.param_2",
        }
    )

    return {"__default__": pipe + pipe_2}
```

Just to be explicit, our parameters file would look like:

```yaml
# parameters.yml

pipeline:
    param_1: "value_1"
    param_2: "value_2"

pipeline_2:
    param_1: "new_value_1"
    param_2: "new_value_2"

```

Ideally, I could define `pipe_2` like this:

```python
    pipe_2 = pipeline(
        pipe,
        parameters={
            "params:pipeline": "params:pipeline_2",
        }
    )
```

and all the top level keys will be overridden. However, defining `pipe_2` like this raises an error:

```
ValueError: Pipeline input(s) {'params:pipeline_2:param_2', 'params:pipeline_2:param_1'} not found in the DataCatalog
```

Which is operating as expected. 

## Context
The root of the issue is how I want to define my functions. I think this:

```python
def fancy_operation(data: pd.DataFrame, param_1: Any, param_2: Any) -> pd.DataFrame:
    """Apply a fancy operation to ``data`` that requires lots of parameters.

    Args:
        data: some dataset.
        param_1: used for this fancy operation. 
        param_2: also used for this fancy operation. 

    Returns:
        DataFrame with a fancy operation applied.
    """
```

is preferable to this:

```python
def fancy_operation(data: pd.DataFrame, params: Dict[str, Any]) -> pd.DataFrame:
    """Apply a fancy operation to ``data`` that requires lots of parameters.

    Args:
        data: some dataset.
        params: dictionary of parameters.

    Returns:
        DataFrame with a fancy operation applied.
    """
```

This would make modular pipelines much easier to use in the preferred case above. You can imagine how this problem scales if you have many nodes and many parameters, overriding all of them individually in the `parameters` argument of `pipeline` is cumbersome.

## Possible Implementation
This is likely a much more difficult problem than at face value. In the [rename local function](https://github.com/kedro-org/kedro/blob/main/kedro/pipeline/modular_pipeline.py#L238-L257) in `pipeline`, you couldn't exactly infer the intention of the `parameters` override. Those rules wouldn't be able to distinguish between a parameter being a whole dictionary vs. a single value.

One potential implementation is to do some substring replace operation. So we could add a rule to check if a parameter starts with a desired override, only override that part of the parameter. Of course, this would have unintended consequences. 

Any implementation I can think of seems to require knowledge of the actual values in the data catalog.

## Possible Alternatives
One potential alternative would be to use environments. However, this doesn't exactly solve the problem when I'm defining pipelines programmatically like in the example. It would solve it for running pipelines in a project context.

Another would be to implement an explicit keyword argument we want to have the substring behavior described above.

Not sure how else this could be handled. Would love to hear what the team thinks.

**Comment by deepyaman** [comment]
@ianwhale Sorry for the late reply on this!

Would something like this work?

```python
>>> base_pipe = pipeline([
...     node(print, "params:param_1", None),
...     node(print, "params:param_2", None),
... ])
>>> pipe = pipeline(base_pipe, namespace="pipeline")
>>> pipe.inputs()
{'params:pipeline.param_2', 'params:pipeline.param_1'}
>>> pipe_2 = pipeline(base_pipe, namespace="pipeline_2")
>>> pipe_2.inputs()
{'params:pipeline_2.param_2', 'params:pipeline_2.param_1'}
```

Parameter namespacing is available as of Kedro 0.18. It does add namespaces instead of replacing them, hence the `base_pipe` abstraction.

**Comment by AntonyMilneQB** [comment]
Also my apologies - I had shared the same solution as @deepyaman did above with @ianwhale in a slack conversation but forgot to write it up here also.

Note that the spaceflights tutorial actually has an example that does exactly this: [pipeline.py](https://github.com/kedro-org/kedro-starters/blob/main/spaceflights/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/%7B%7B%20cookiecutter.python_package%20%7D%7D/pipelines/data_science/pipeline.py); [parameters file](https://github.com/kedro-org/kedro-starters/blob/main/spaceflights/%7B%7B%20cookiecutter.repo_name%20%7D%7D/conf/base/parameters/data_science.yml).

**Comment by ianwhale** [comment]
Hey again! Namespacing was what I actually needed. I was over complicating. 

@AntonyMilneQB and I had some follow up discussion on this pointing out that namespacing isn't _exactly_ solving the problem as it was stated. However, it's likely what people want in 95% of the cases. 

I'm happy to close this issue if you are.
