### ISSUE TITLE
Evaluating the Kedro and Databricks workflow

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#1653]
## Introduction

We've entered the battleground of ML development workflows, a notebook-driven approach vs one primarily written using an IDE like VS Code, PyCharm and others. ⚔️

### Why should ML developers use an IDE instead of a notebook to develop their data and ML pipelines? 

The [notebook-driven](https://www.youtube.com/watch?v=7jiPeIFXb6U) approach is challenged when producing a code base that needs to be maintained. In addition, it is challenging to write tests and documentation, leverage version control systems, sort out a pipeline's running order and collaborate with others when working with notebooks. 

You don't need to take our word for this but rather reflect on [the perspective of the Databricks Labs team](https://databricks.com/blog/2020/06/05/automate-continuous-integration-and-continuous-delivery-on-databricks-using-databricks-labs-ci-cd-templates.html) that are aware of this problem: 

> "As projects on Databricks grow larger, Databricks users may struggle to keep up with the numerous notebooks containing ETL, data science experimentation, dashboards etc. While there are various short-term workarounds, such as using the `%run` command to call other notebooks from within your current notebook, it's useful to follow traditional software engineering best practices of separating reusable code from pipelines calling that code. Additionally, building tests around your pipelines to verify that the pipelines are also working is another important step toward production-grade development processes."

The Databricks Labs team have piloted multiple projects to allow users to leverage an IDE-based workflow, including [CI/CD templates](https://databricks.com/blog/2020/06/05/automate-continuous-integration-and-continuous-delivery-on-databricks-using-databricks-labs-ci-cd-templates.html), [Databricks Connect](https://docs.databricks.com/dev-tools/databricks-connect.html), [`dbx`](https://dbx.readthedocs.io/en/latest/README.html), [Databricks Repos](https://databricks.com/product/repos) and the [Databricks CLI](https://docs.databricks.com/dev-tools/cli/index.html). 

### Why does this affect Kedro?

[Kedro suggests an IDE-based workflow and proposes that notebooks are suitable for prototyping](https://kedro.readthedocs.io/en/stable/tools_integration/ipython.html#why-use-a-notebook), not the final code base. This tension often reveals itself when [non-Kedro users primarily rely on Jupyter notebooks](https://github.com/kedro-org/kedro/issues/1075) and when Kedro users interact with notebook-driven platforms like Databricks. 

### Why should we care?

We have a growing category of Kedro users that rely on Databricks to scale their data and machine-learning pipelines. We have also seen 341 queries related to Databricks on our Q&A forums; comparatively, there are 37 queries about AWS Sagemaker. This data results from a term search from our internal Slack channel and [open Discord forum](https://discord.gg/2QvVEdVEea).

Our [Databricks deployment documentation](https://kedro.readthedocs.io/en/stable/deployment/databricks.html) is also the most viewed in the deployment series. We also have some qualitative evidence to suggest that the current development and deployment experience is a barrier to adopting Kedro in organisations that rely on Databricks. 

## What is the scope of our work?

This exercise aims to define a seamless development and deployment experience for Kedro users on Databricks. We will target ML developers that prefer an IDE-based workflow, use Databricks to support their PySpark workflows and leverage Kedro to author their data and ML software; out of scope are users that solely rely on a notebook-based approach. We are exploring ways to help this second group in our [improvements to the iPython and Jupyter Notebooks workflows](https://github.com/kedro-org/kedro/issues/1075). 

The first part of our work will focus on a research assignment to understand the landscape of our users' problems related to the IDE workflow on Databricks and leveraging Kedro on Databricks. We'll use interviews to get an initial lay-of-the-land, a survey to source quantitative data and observation (screen recordings) or role-play studies to reproduce workflow errors. 

### What are we hoping to understand? 

At the end of this research study:

- We should have a prioritised list of pain points according to the following categories:
  - The IDE workflow in Databricks, 
  - Kedro on Databricks,
  - And potentially even just Kedro issues;
- We also should understand our users' key workflows,
  - Workarounds they may have created,
  - And be able to communicate the value of using the Kedro and Databricks together.

This work will feed into the Kedro backlog and a hackathon that we will be planned with the Databricks team.

### Who will we be speaking to? 

 - Maria Olivia Lihn
 - Debanjan Banerjee 
 - Diana Montanes 
 - Roman Drapeko
 - Nishant Kumar-NKC
 - Saravanakumar Subramaniam
 - Benjamin Levy
 - Eduardo Coronado
 - Ingo Walz
 - Danny Farah
 - Poornima Ponthagani 
 - Avaneesh Yembadi
 - Anil Chouldary
 - Logan Rupert
 - @marioFeynman
 - @Malaguth
 - @WolVez

**Comment by yetudada** [comment]
## Recruiting email

### Introduction
We're moving into a new phase evaluating how to support platform-based Kedro workflows better. The [highest priority platform to investigate based on usage is Databricks](https://github.com/kedro-org/kedro/issues/1653). Our goal is to determine what an optimal development and deployment experience would look like using the different parts of Databricks. 

### How can you help?
We're conducting interviews to understand pain points, and we will also ask for your participation in a later survey. We'll run a hackathon with Databricks to address some of the findings from this research.

We will ask a series of questions in the interview section and will need help understanding: 

- The reasons why you chose to use Kedro and Databricks together;
- Your Kedro/Databricks workflow in the last project that you used the two tools together;
- Pain points, errors or workarounds you ran into - it is helpful if you can provide stack traces, screenshots or even recordings; 
- Potential improvements for Kedro and even Databricks.

### Why did you get this invite?
You are receiving this invite because you either indicated you were interested in helping us with this study, or we observed questions or comments about Databricks on our support channel.

**Comment by yetudada** [comment]
## Interview questions

### Introduction

1. Have you used Databricks in your previous three projects?
2. Can you describe the last project that you used Kedro on Databricks? 
3. What was your role on this project?
4. What version of Kedro did you use? 
5. _[Bonus]_ Would you be in a position to show us this project so that we can walk through it together?

> I might verify if Q5 is possible before the interview.

### Workflow on the last project that you used Kedro and Databricks together

1. Why did you use Kedro and Databricks together on this project?
2. Can you describe what steps you took to set up your Kedro project on Databricks for this project?
3. Did you use Databricks with any other cloud platform tooling, e.g. Azure or AWS, on this project?
4. What is your overall experience of using Kedro on Databricks on this project?
   - Did you run into any errors or challenges using Kedro on Databricks for this project? 
   - How did you solve these problems? 
5. Which functionalities in Databricks did you use on this project, and why? 

### Conclusion

1. What other challenges have you encountered because of the Kedro and Databricks workflow? 
2. Is there anything else you want to mention?

**Comment by NeroOkwa** [comment]
@yetudada additional interview questions may be:

1. What should we do to improve the Kedro/Databricks workflow ?
2. If we improve this Kedro/Databricks workflow based on your recommendation would you use Kedro on Databricks in the future?

**Comment by Baukebrenninkmeijer** [comment]
@yetudada is this issue mainly intended as administration or would you also like user responses here?

**Comment by yetudada** [comment]
> @yetudada is this issue mainly intended as administration or would you also like user responses here?

The GitHub issue is meant to capture and summarise the research. However, would you be up for an interview with the team? We'd love to hear what you want to say! And thank you so much for reaching out!

**Comment by Baukebrenninkmeijer** [comment]
@yetudada Sure! Let me know when and where!

**Comment by yetudada** [comment]
> @yetudada Sure! Let me know when and where!

Hit me with your email address? I'll get things organised 🥳

**Comment by Baukebrenninkmeijer** [comment]
@yetudada bauke.brenninkmeijer@gmail.com

**Comment by vitoravancini** [comment]
Hello Kedro People, was this evolved somewhere/somehow?
I'm  very interested in this topic, at the company I work at we've been using kedro-connect with fair success, but it seems databricks wont continue it, has anyone tried with dbx?

**Comment by roumail** [comment]
Hi everyone, I'm also just coming across this issue and being a fan of using kedro, I'm now looking into how I can use it in an azure databricks environment. I could be wrong but since I'm not able to develop locally, dbx won't work for my use case. Eager to see conclusions of this workstream!

@yetudada or the kedro team - I'm already on the kedro discord channel. Could you please let me know if there's someplace I can pick up the discussion? Thanks!

**Comment by carlaprv** [comment]
Hi everyone! I've just came across this issue. I've used kedro and databricks in my last QB project and would be happy to help with the interviews.
