### ISSUE TITLE
Documentation review to improve styling 

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#1655]
## Description
This task summarises an exercise to review the documentation for stying improvements. Some of this work will also aim to de-gerund the documentation. 

## Possible Implementation
[Use the style guide to help inform the changes](https://kedro.readthedocs.io/en/stable/contribution/documentation_contributor_guidelines.html).

**Comment by CarolineMLynch** [comment]
Will add comments as I see issues arise.

**Comment by stichbury** [comment]
This is a somewhat nebulous issue! Can I suggest that we close it an instead create a set of issues (or one big one) as I audit the docs, rather than this one, which is serving more as the audit task itself. (cc @NeroOkwa @yetudada)
