### ISSUE TITLE
Investigate removal of prompts.yml

### ISSUE THREAD

**Issue by antonymilne** [kedro-org/kedro#1692]
Every starter template has two files, cookiecutter.json and prompts.yml. This has always been kind of confusing: they contain kind of similar information, so do you need to edit just one file or both files?. Following https://github.com/kedro-org/kedro/pull/1643, there's not much left in prompts.yml.

cookiecutter.json is the system used by cookiecutter; prompts.yml is a custom system we added on top of it. As far as I know there's two things that prompts.yml gives us over the cookiecutter.json file:
1. regex validation of variables with friendly error message
2. ability to prompt user for only a subset of the variables in cookiecutter.json (as we now do)

I believe we could handle both of these using native cookiecutter features:
1. [cookiecutter hooks to provide validation](https://cookiecutter.readthedocs.io/en/2.1.1/advanced/hooks.html#example-validating-template-variables)
2. [private variables](https://cookiecutter.readthedocs.io/en/2.1.1/advanced/private_variables.html)

The advantages would be:
* no longer any need for us to maintain a custom prompts system
* less confusion about what goes in cookiecutter.json vs. prompts.yml
* hopefully simpler for a user to customise the prompts (or at least we can just direct them to cookiecutter docs)

The task here is to work out:
1. are there any other reasons we should keep prompts.yml? What do people use it for?
2. would the native cookiecutter features be able to handle our needs in a reasonably straightforward way? Note cookiecutter 2 was released relatively recently so might contain new features that are useful.

**Comment by AntonyMilneQB** [comment]
@MerelTheisenQB might have more context here on why we originally added prompts.yml and which users we should talk to if we changed this.

**Comment by merelcht** [comment]
Following the new utilities workflow https://github.com/kedro-org/kedro/issues/2388 we'll be expanding prompts with more options, so I'm closing this ticket.
