### ISSUE TITLE
Namespace `kedro-datasets` 

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro#1693]
## Description
As discussed in [Technical Design](https://github.com/kedro-org/kedro/issues/1652#issuecomment-1176338132) the `kedro-datasets` package should be namespaced to `kedro.datasets`

## Implementation
> To enable namespacing edit setup.py: https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages
* When we do the namespace package for kedro-datasets, we also need to rename the current namespace from kedro_datasets.datasets -> kedro.datasets.

These 2 links will be useful for this ticket
* [Mixing of namespace package and non-namespace package](https://discuss.python.org/t/mixing-namespace-and-non-namespace-packages-bad-practice/7536)
  * Mixing namespace/non-namespace packaging is not advised, but possible. Should we also make `kedro` a namespace package in this case?
  * The key different is you [omit the `__init__.py`](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#:~:text=python%203.3%20added%20implicit%20namespace%20packages%20from%20pep%20420.%20all%20that%20is%20required%20to%20create%20a%20native%20namespace%20package%20is%20that%20you%20just%20omit%20__init__.py%20from%20the%20namespace%20package%20directory.%20an%20example%20file%20structure%3A) and let `setuptools` to do the works to figure out where is the package
* [Python Standard Doc for namespace package](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/)

While doing this, we should make sure these still works
```python
import kedro
from kedro.datasets import *  # From kedro-dataset
from kedro.io import *  # From kedro
```

**Comment by AhdraMeraliQB** [comment]
After a discussion during technical design, we have concluded that namespacing is not the correct approach for the `kedro-datasets` split. Further details and discussion can be seen under #1758.
