### ISSUE TITLE
Document how to read and write a multi-sheet excel

### ISSUE THREAD

**Issue by datajoely** [kedro-org/kedro#1700]
## Introduction

>A high-level, short overview of the problem(s) you are designing a solution for.

We have the implementation, but it is not easy to point to a documented example:

![image](https://user-images.githubusercontent.com/35801847/178237457-9152ffa0-fbb1-48ca-bf70-d5e2c89323ed.png)

## Background

> Provide the reader with the context surrounding the problem(s) you are trying to solve.

This is a common feature and something Kedro can already do.

**Comment by MerelTheisenQB** [comment]
Add the example here: https://kedro.readthedocs.io/en/stable/data/data_catalog.html#use-the-data-catalog-with-the-yaml-api
