### ISSUE TITLE
[User Research] Do users use config of file formats other than `yml`? 

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro#1703]
## Description
In order to decide on whether we can switch completely to `OmegaConf` in a non-breaking way (https://github.com/kedro-org/kedro/issues/1657) we need to find out if users are using any other config file formats e.g. `json`, `toml` or only `yml`. 

## Research method
Survey on Slack & Discord

**Comment by MerelTheisenQB** [comment]
A large majority of users who responded use `yaml/yml` file format for their Kedro configuration, with a couple of people using `json` or `py` files. 

The responses on our Slack user channel:
![Screenshot 2022-07-14 at 17 26 52](https://user-images.githubusercontent.com/49397448/179031158-98786492-6345-4a43-b2e3-c2f0832284aa.png)

The responses on our Discord user research channel:
![Screenshot 2022-07-14 at 15 27 27](https://user-images.githubusercontent.com/49397448/179006583-89841d0b-d018-4c08-b7f6-5a5a63537e51.png)

**Comment by MerelTheisenQB** [comment]
I checked with the users who indicated they use another file format from `yaml`/`yml` what their reasons are for using those other formats. The responses were as follows:

**Usage of json:** 
"I meant that I also use json file for configurations / params that are not part of the Kedro process. For Kedro, I mostly used the catalog and in-built param files."

**Usage of .py files:** 
"I’ll generally put constants and things like that in python files. e.g., in my current project there’s a `constants.py` file with various constants. These would normally be things that “should” go in a config file, however, see point 2 below for why I don’t put them into a config file.
I prefer [using python files] for two reasons:
1. Autocomplete works properly in my IDE
2. I’m generally not a fan of configuration in general. My rule of thumb is that if I wouldn’t feel comfortable with an IT person (i.e., non programmer) changing the config, it shouldn’t be in a config file. So a db connection string would be fine, but most of the config in a kedro project doesn’t meet this test, so I think it should go into code where people will take it seriously."

**Comment by MerelTheisenQB** [comment]
### Conclusion
The large majority of Kedro users who responded to the survey about the type of file formats they use for configuration in Kedro, said they use `yml`. This means that introducing `OmegaConf` would not be a breaking change for this majority.

For the two users who indicated they use different file formats, one expressed they actually mostly use `yml` for Kedro related config and `json` for other config and so for this user the `OmegaConf` change wouldn't be breaking either, but for the user who's keen on using `py` files for some Kedro config this would be a breaking change. However, considering this is a fairly unique and opinionated way of using config, which isn't exactly in line with the Kedro way of doing config, I'd suggest to not let this stop us from using `OmegaConf` because the pros definitely outweigh the con of not supporting any other file formats anymore.

**Comment by AntonyMilneQB** [comment]
@MerelTheisenQB also worth noting that hydra/omegaconf seem to work predominantly (only?) with the `.yaml` extension while we usually (always?) use `.yml`. Shouldn't be a big problem, but depending on how deep our reliance on OmegaConf gets, possibly with 0.19 we should change to `.yaml` everywhere to match them. For now we should allow both `.yml` and `.yaml` to be non-breaking.
