### ISSUE TITLE
Release version `1.0.0` for `kedro-datasets` and test it's fully working

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#1711]
1. Make sure the new package has correct naming: `kedro-datasets`
2. Copy any recent updates to datasets to `kedro-datasets`
3. Release new version and make sure the datasets can be used from the package

kedro-datasets: https://github.com/kedro-org/kedro-plugins/tree/main/kedro-datasets

Pre-requisite:
- [x] https://github.com/kedro-org/kedro-plugins/issues/64
- [x] https://github.com/kedro-org/kedro/pull/1734

**Comment by noklam** [comment]
@merelcht I would add that we should add some docs & some notes on the breaking changes.

I think the examples we had in the showcase are enough. i.e. `from kedro.extras.datasets.xxxx -> kedro_datasets.datasets.xxx`
