### ISSUE TITLE
Document the `kedro run` lifecycle and hooks execution order

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#1718]
## Description
Document the `kedro run` lifecycle with hooks execution order

This is the latest chart we have (~2 months ago, omitted the `after_context_created` and `after_command_run` hooks but we should have that in place too)
![image](https://user-images.githubusercontent.com/18221871/180174648-4230c7c0-8f20-411d-924b-27df9bef71fb.png)

I think this should be included in the [hooks documentation page](https://kedro.readthedocs.io/en/stable/extend_kedro/hooks.html)

Bonus:
Add more examples in the `Common Use Cases` section. 
i.e. If you need to use the context, `after_context_created` is probably the way to go.

Double bonus:
embed links in the diagram to link to the relevant API docs for the hooks. [Maybe like this](https://stackoverflow.com/questions/41960529/how-to-add-a-link-in-a-mermaid-node-description)

## Context
[This PR enables using Mermaid](https://github.com/kedro-org/kedro/pull/1392) to draw flow charts in our doc, so we can finally have something that is easier to version control and update.

This is an Mermaid example for our deployment charts

```bash

flowchart TD
    A{Can your Kedro pipeline run on a single machine?} -- YES --> B[Consult the single-machine deployment guide];
    B --> C{Do you have Docker on your machine?};
    C -- YES --> D[Use a container-based approach];
    C -- NO --> E[Use the CLI or package mode];
    A -- NO --> F[Consult the distributed deployment guide];
    F --> G[What distributed platform are you using?\n\nCheck out the guides for:\n<li>Argo</li><li>Prefect</li><li>Kubeflow Pipelines</li><li>AWS Batch</li><li>Databricks</li><li>Dask</li></ul>]; 
    style G text-align:left
    H["Does (part of) your pipeline integrate with Amazon SageMaker?<br/><br/>Read the SageMaker integration guide"];

```

```mermaid

flowchart TD
    A{Can your Kedro pipeline run on a single machine?} -- YES --> B[Consult the single-machine deployment guide];
    B --> C{Do you have Docker on your machine?};
    C -- YES --> D[Use a container-based approach];
    C -- NO --> E[Use the CLI or package mode];
    A -- NO --> F[Consult the distributed deployment guide];
    F --> G[What distributed platform are you using?\n\nCheck out the guides for:\n<li>Argo</li><li>Prefect</li><li>Kubeflow Pipelines</li><li>AWS Batch</li><li>Databricks</li><li>Dask</li></ul>]; 
    style G text-align:left
    H["Does (part of) your pipeline integrate with Amazon SageMaker?<br/><br/>Read the SageMaker integration guide"];

```

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

**Comment by AntonyMilneQB** [comment]
This would be great to have. Just to say that it might be better to do this as two diagrams:
* one that shows the order of hook execution (useful for anyone wanting to use hooks)
* one that shows the mapping between hooks and entry points (useful for plugin developers)

Or maybe it's better to colour code (if possible in mermaid) or label somehow each hook with its plugin entry point.

Basically don't feel like you just need to reproduce the diagram exactly as it is in the Miro board. Change things to whatever is clearest and most useful in the docs.

**Comment by astrojuanlu** [comment]
Potentially useful: how Hooks themselves are run.

> Gave it a quick go, just to see if it has potential:
> 
> ```mermaid
> flowchart LR
>   PluginManager -.- pm.hook --> HookRelay
>   HookRelay -- foo_hook --> HookCaller --> HookSpec
>   HookRelay -- foo_hook2 --> HookCaller -- plugin1 --> HookImpl1
>   HookCaller -- plugin2 --> HookImpl2
> ```

_Originally posted in https://github.com/pytest-dev/pluggy/issues/341#issuecomment-1063980216_

**Comment by stichbury** [comment]
It's almost a happy 1 year birthday for this ticket 🍰 

Here is a ticket that I think forms the parent of this one: https://github.com/kedro-org/kedro/issues/1940

**Comment by noklam** [comment]
Let's ship #1940 to get this going since this has a "low" priority and that smaller ticket has a "high" one. This one would be an useful document even it's just for ourselves internally.

**Comment by noklam** [comment]
Updating this to a parent ticket for all hooks related doc since it's hard to trace.
