### ISSUE TITLE
Evaluating AWS workflows with Kedro

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#1730]
## Introduction

This research aims to unpack what our users are doing when using different AWS services. We have heard references to AWS EC2, EMR, EKS, Batch, Lambda and SageMaker in user conversations. We want to understand and prioritise specific user journeys and see if we can improve the user flow in tandem with a team at AWS. 

## Research questions

We would like to understand:
 - How many AWS users are in our community?
 - What AWS products and services are being used?
 - What workflows are used with these AWS products and services?
 - What challenges exist with the workflows, and why?
 
## Supporting data

An initial search for AWS reveals just over 400 queries across AWS SageMaker, EMR, Glue, EC2, Batch, S3 usage and more, suggesting a larger user group to support.

## Outcome

We will use this work to inform the co-development of Kedro Framework and different AWS services in tandem with the AWS team.

**Comment by merelcht** [comment]
I vote for closing this and instead focussing on what comes out of the Deployment research. @astrojuanlu ?

**Comment by astrojuanlu** [comment]
Agreed, closing. Whenever we want to look at Kedro + AWS we can reopen this issue or just open a new one.
