### ISSUE TITLE
Rationalise data catalog examples in documentation

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#1742]
### Description
In the section on using the `DataCatalog` with the yaml api, we've listed a lot of examples: https://kedro.readthedocs.io/en/stable/data/data_catalog.html#use-the-data-catalog-with-the-yaml-api. However, there are no anchors to any of these examples, so it's very hard to link users to a specific solution.

### Implementation

- [x] https://github.com/kedro-org/kedro/pull/1770
- [ ] Create a separate page for these examples altogether or alternatively, only keep some of the example in Data Catalog to showcase what Kedro can do, but move the advanced examples to the corresponding API Docs.

**Comment by noklam** [comment]
I think "Data Catalog" should show case what Kedro can do, showing examples for saving things in remote storage, but we don't need all the combination of DataSet + Remote Storage type.

This should make the page itself shorter, the more repeated example can be moved to the specific DataSet API docs instead.

**Comment by stichbury** [comment]
This issue, plus #1743 and #1762 all seem to point to improving the API docs and streamlining the DataCatalog docs. I agree with @noklam that it would make sense to extract some of the examples to put them in API docs (or elsewhere).

**Comment by stichbury** [comment]
Also to add that the page needs a significant rework to simplify it and attempt to make it more discoverable through search as per this discussion https://kedro-org.slack.com/archives/C03RKP2LW64/p1673459017999699
