### ISSUE TITLE
Mermaid Diagram disappeared in Doc when search with keywords

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#1772]
## Description
Short description of the problem here.

When searching keywords in Kedro's ReadTheDoc, It will highlight the keywords and generated URL like this:
https://kedro.readthedocs.io/en/stable/deployment/deployment_guide.html?highlight=deployment

The Mermaid Diagram is not rendered properly, sometimes it is rendered as plain text or an empty diagram.
https://kedro.readthedocs.io/en/stable/deployment/deployment_guide.html

Removing the `highlight` will make it work again.

CC @deepyaman 

# Diagnosis
Initial investigation suggests that this is due to an additional `<span class='highlighted'> </span> HTML tag and probably causing it fail to render.

![image](https://user-images.githubusercontent.com/18221871/183655192-07741d09-3426-4c2b-95a8-558d7109c3d9.png)

## Context
How has this bug affected you? What were you trying to accomplish?

## Steps to Reproduce
1. [First Step]
2. [Second Step]
3. [And so on...]

## Expected Result
Tell us what should happen.

## Actual Result
Tell us what happens instead.

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`):
* Python version used (`python -V`):
* Operating system and version:

**Comment by AntonyMilneQB** [comment]
Just to be clear, I believe this is a problem only when the term to be highlighted is in the diagram. 

e.g. https://kedro.readthedocs.io/en/stable/deployment/deployment_guide.html?highlight=asdfsadf works fine 
https://kedro.readthedocs.io/en/stable/deployment/deployment_guide.html?highlight=container does not

Unfortunately I think it might not be easy to fix...

**Comment by MerelTheisenQB** [comment]
Timebox this to max 2 days, if not fixable, report to read the docs.

**Comment by astrojuanlu** [comment]
Don't think this is an issue anymore?

![image](https://user-images.githubusercontent.com/316517/221842333-0486cc83-10fe-4a41-ab05-23380f70540c.png)

(https://kedro.readthedocs.io/en/latest/deployment/deployment_guide.html?highlight=container)

**Comment by merelcht** [comment]
I'm seeing this.. 

![Screenshot 2023-02-28 at 11 55 35](https://user-images.githubusercontent.com/49397448/221847973-7044f58f-d8aa-4542-918f-dfe224312a13.png)

**Comment by AntonyMilneQB** [comment]
I get the same as Merel in Chrome and Safari.

**Comment by astrojuanlu** [comment]
Yeah, I confirm this is browser dependent. And in fact, @noklam left a comment here https://github.com/mgaitan/sphinxcontrib-mermaid/issues/22

Don't think an upstream fix is going to happen, so what we can do is to render statically, rather than dynamically with JS. That way, this issue would disappear, at the cost of losing `Ctrl+F` on diagrams themselves.

**Comment by AntonyMilneQB** [comment]
I'm curious what browser you were using where this wasn't a problem?

**Comment by astrojuanlu** [comment]
Sorry didn't say it - Firefox
