### ISSUE TITLE
Don't work joblib.Parallel in node normaly

### ISSUE THREAD

**Issue by 0shimax** [kedro-org/kedro#1796]
## Description
Only one core is used when trying to parallelize processing in node with joblib.Parallel or multiprocessing. Is there a configuration method to solve this problem?

## Context
Parallel processing within a node is not possible. If it is executed in ipython, etc. without kedro, it will be parallelized using multiple cores.

## Steps to Reproduce
```
import numpy as np
import multiprocessing
from joblib import Parallel, delayed
from skimage.feature import peak_local_max


def _process_on_multi_core(x: np.ndarray) -> np.ndarray:
    n_core = multiprocessing.cpu_count()
    n_sub_block_y = x.shape[0]//n_core
    n_sub_block_x = x.shape[1]//n_core

    result = Parallel(n_jobs=n_core)(
        delayed(peak_local_max)(
            x[i*n_sub_block_y:(i+1)*n_sub_block_y, i*n_sub_block_x:(i+1)*n_sub_block_x], 
            2,
            2,
        )
        for i in range(n_core)
    )

    return result


_process_on_multi_core((np.random.rand(10000, 10000)*100).astype(np.int64).reshape(10000, 10000))
```

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): version 0.18.2
* Python version used (`python -V`): Python 3.10.4
* Operating system and version: joblib 1.1.0

**Comment by datajoely** [comment]
How are you running your example?

**Comment by 0shimax** [comment]
This way.

```
import multiprocessing
from joblib import Parallel, delayed
from skimage.feature import peak_local_max


def _process_on_multi_core(x: np.ndarray) -> np.ndarray:
    n_core = multiprocessing.cpu_count()
    n_sub_block_y = x.shape[0]//n_core
    n_sub_block_x = x.shape[1]//n_core

    result = Parallel(n_jobs=n_core)(
        delayed(peak_local_max)(
            x[i*n_sub_block_y:(i+1)*n_sub_block_y, i*n_sub_block_x:(i+1)*n_sub_block_x], 
            2,
            2,
        )
        for i in range(n_core)
    )

    return result


_process_on_multi_core(np.random.rand(1000,1000))
```

**Comment by datajoely** [comment]
Hi @0shimax , but how do you run your Kedro pipeline?

**Comment by 0shimax** [comment]
@datajoely 
Can't you reproduce it by creating a node that just uses this function? What information do I need to provide to get started?

**Comment by datajoely** [comment]
Hi @0shimax it's a bit difficult to work out from your example which is really only showing Joblib not Kedro. If you're using `ParallelRunner` in combination with `joblib` this will fail due to limitations with Python process isolation - but it should be possible to get this working with `SequentialRunner`.

**Comment by 0shimax** [comment]
@datajoely 
When you say work with `SequentialRunner`, do you mean that parallel operations will be done using joblib? I am simply running it with `kedro run`, so I am running it with `SequentialRunner`.

**Comment by datajoely** [comment]
Yes, but then are you calling `_process_on_multi_core` as a node function?

**Comment by 0shimax** [comment]
@datajoely 
No. I call `add-pipeline-for-comp-dtm-and-chm` from node function as  sub function.

**Comment by datajoely** [comment]
Can you post the stacktrace?

**Comment by 0shimax** [comment]
No errors occur. There is no stacktrace because the calculation is not performed on multiple cores, but only on one core.

**Comment by merelcht** [comment]
I'm closing this issue since there hasn't been any recent activity. Feel free to re-open this if you're still facing problems!
