### ISSUE TITLE
Review fsspec upper boundary to allow use of >=2022.5.0

### ISSUE THREAD

**Issue by jenikovsky** [kedro-org/kedro#1804]
## Description
Version 0.18.2 has dependency fsspec limited to `<=2022.1`. We would appreciate if that could be lifted to `2022.5.0`.

## Context
Our other dependencies require `fsspec >=2022.5.0`, namely because of `s3fs>=2022.5.0`. It is very complicated for us to change that. Other teams might have similar issue when introducing Kedro due to established codebase.

**Comment by AntonyMilneQB** [comment]
Thanks for raising the issue @jenikovsky! I've opened a PR for it; if unit tests pass then we're good to go and the requirement would be bumped in the kedro 0.18.3 release.
