### ISSUE TITLE
Refactor fixtures in test_pipeline.py

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#1808]
See: https://github.com/kedro-org/kedro/pull/1773#discussion_r945609815.

As discovered in #1773  - some of the fixtures are not very self-descriptive, and this impacts the tests' readability. It would be good to go in and refresh the fixtures to reflect how the tests have evolved.

**Comment by adamkells** [comment]
@merelcht Would be keen to do this if the issue is still relevant.

**Comment by merelcht** [comment]
Hi @adamkells, this is indeed something that still needs to be done. Let me know if you need some more explanation! 
Otherwise, if you'd like a more well defined task to do you can have a look at our [Hacktoberfest tickets](https://github.com/kedro-org/kedro/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest) 😄

**Comment by adamkells** [comment]
No problem, some more explanation would be great! My understanding from the linked issue was that it referred mostly to the comments on the fixtures not being very readable and so the scope is to:

- Add comments to existing tests with unclear functions.
- Rename tests to be more clear.
- Edit existing comments to be more human-readable.

Is this correct?

**Comment by merelcht** [comment]
The task is to refactor the test fixtures in [`pipeline/test_pipeline.py`](https://github.com/kedro-org/kedro/blob/main/tests/pipeline/test_pipeline.py). Ideally that would mean renaming the fixtures and/or tests to be more clear. Some tests might actually be more readable if they don't use the fixtures, so they could be changed in that way. Or as you said, add comments to existing tests to make them easier to follow.

**Comment by merelcht** [comment]
This was completed in https://github.com/kedro-org/kedro/pull/3203
