### ISSUE TITLE
kedro-dbt plugin

### ISSUE THREAD

**Issue by Kurdzik** [kedro-org/kedro#1813]
## Description
Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

I was thinking, if there is a way to integrate [dbt]('https://github.com/dbt-labs/dbt-core') project into kedro starter?

Right now, i can't do it because both kedro and dbt make use of Jinja functions and at the moment of running 'kedro new --starter ....' cookiecutter does not generate a project. 

And all solutions i've found on the internet about putting directory path to cookiecutter.json so that it will not take some folders into consideration, have failed

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

We are working of set of different starters to automate some repetitive tasks, given data in the same format. 

Since making transformations directly on a database is much quicker than downloading data, transforming it and then uploading it again, we thought about using dbt for that purpose. 

And then running kedro on newly created tables

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

Right now what we have is kedro starter on one repo and dbt project on another

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

Right now we have shell script in one of the folders of a kedro starter, which clones dbt project into created kedro project

**Comment by foxale** [comment]
I did some tests and it looks like it's possible thanks to [this neat trick](https://cookiecutter.readthedocs.io/en/1.7.2/advanced/copy_without_render.html). I tested few unix-style wildcard variations but could find the one that would exclude the whole folder though.

**Comment by Kurdzik** [comment]
_copy_without_render function inside a cookiecutter.json works :)
