### ISSUE TITLE
Cookiecutter~=1.7.0 a dependency of Kedro ==0.18.2 has a vulnerability 

### ISSUE THREAD

**Issue by ogamaxwell** [kedro-org/kedro#1815]
## Description
After recieving a vulnerability report on kedro, Package cookiecutter version 1.7.3 has a vulnerability that has been patched in version 2.1.1. Please update Kedro to this version of cookiecutter

## Context
To ensure security of my data and code bases, I would like to ensure my data pipeline tool is as secure as possible. Ive run into an issue of not being able to update cookiecutter because Kedro==0.18.2 is dependent on cookiecutter==1.7.3 which contains a vulnerability that has been patched in 2.1.1

## Steps to Reproduce
1. Updated src/requiements.txt. Add cookiecutter and set the version == to 2.1.1
2. run pip install -r src/requriements.txt

## Expected Result
I expect the command to run successful

## Actual Result
<img width="1010" alt="Screen Shot 2022-08-26 at 2 11 14 PM" src="https://user-images.githubusercontent.com/16263554/186966298-cd2dc5b6-5f34-411b-be3d-14f88345be64.png">

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`):
* Name: kedro
Version: 0.17.4
* Python version used (`python -V`):
* Python 3.8.10
* Operating system and version:

**Comment by AntonyMilneQB** [comment]
Hi @ogamaxwell, we bumped our requirement of cookiecutter for exactly this reason in kedro 0.18.2: https://github.com/kedro-org/kedro/pull/1601. The title of your PR says 0.18.2, the environment says 0.17.4 and the screenshot says 0.18.0 so I think there's some confusion over versions here. Note that 0.18.x are non-breaking releases, so if you're running 0.18.0 you can upgrade to kedro 0.18.2 without any problems.

Just to reassure you, this security vulnerability is very unlikely to actually cause any problems: https://github.com/kedro-org/kedro/issues/1600.
