### ISSUE TITLE
find_pipelines should take some Kwargs

### ISSUE THREAD

**Issue by Harsh-Maheshwari** [kedro-org/kedro#1817]
## Description
With 0.18.3 version a new feature is introduced : 
kedro.framework.project.find_pipelines

This automatically runs create_pipelines without any arguments to the function. This is not a very generic behaviour for users.

Suppose we create a project using kedro run and name it "main_project"
now create 2 pipelines :
   1. kedro pipeline create problem_statement_1
   2. kedro pipeline create problem_statement_2

for problem_statement_1 we have 3 kinds of pipeline defined in our create_pipeline method using a pipeline_type parameter which goes into the create_piepline method:

```
def create_pipeline(pipeline_type, **kwargs) -> Pipeline:
     if pipeline_type == 'training':
          return pipeline([
               node(func=training,
                    inputs=["params:A", ],
                    outputs=["training_outputs"],
                    name="training")
        ])
     elif pipeline_type == 'runtime':
          return pipeline([
               node(func=runtime,
                    inputs=["params:A", ],
                    outputs=["runtime_outputs"],
                    name="runtime")
        ])
     else :
          return pipeline([
               node(func=default,
                    inputs=["params:A", ],
                    outputs=["default_outputs"],
                    name="default")
        ])
```

With 0.18.3 is there a way to separate these sub-pipelines for problem_statement_1?

**Comment by datajoely** [comment]
Interesting so if I'm reading this right, you would like to have user defined pipeline templates? 

I think this is something we'd be interested in building but will take a while to be designed and tested. In the short term maybe using cookiecutter directly may be the best solution.

**Comment by Harsh-Maheshwari** [comment]
right now I have all my nodes defined in `nodes.py` file and then I am using different combinations of the functions defined in the `nodes.py` file to generate 3 different pipeline structures

With this new change introduced in 0.18.3 
I am thinking to add a parameter in conf/base/parameters.yml :

```yaml
pipeline_type: training / runtime / default
```

And then before the create_pipeline function I can create a global variable and get the return accordingly from the  create_pipeline function.  

from kedro.config import ConfigLoader
from kedro.framework.project import settings

conf_path = str(project_path / settings.CONF_SOURCE)
conf_loader = ConfigLoader(conf_source=conf_path, env="base")
parameters = conf_loader.get("parameters*", "parameters*/**")
pipeline_type = parameters['pipeline_type']


def create_pipeline(**kwargs) -> Pipeline:
     if pipeline_type == 'training':
          return pipeline([
               node(func=training,
                    inputs=["params:A", ],
                    outputs=["training_outputs"],
                    name="training")
        ])
     elif pipeline_type == 'runtime':
          return pipeline([
               node(func=runtime,
                    inputs=["params:A", ],
                    outputs=["runtime_outputs"],
                    name="runtime")
        ])
     else :
          return pipeline([
               node(func=default,
                    inputs=["params:A", ],
                    outputs=["default_outputs"],
                    name="default")
        ])

Do you have a better solution in mind than this approach?

**Comment by Harsh-Maheshwari** [comment]
@datajoely I am not sure if you are aware of this but ml-flow is experimenting with pipelines themselves and with such a cool integration with mlflow  kedro can also use [mlflow template pipeline](https://www.mlflow.org/docs/latest/pipelines.html) features

**Comment by AntonyMilneQB** [comment]
Hi @Harsh-Maheshwari, thanks for raising the issue! I'm impressed you're aware of `find_pipelines` when it hasn't even been recently yet!

Outside of the new `find_pipeline` functionality, this is a very good question and something we don't currently have a good solution for. Your solution with config loading parameters is basically the right way to do it. It's worth looking at [modular pipelines](https://kedro.readthedocs.io/en/stable/nodes_and_pipelines/modular_pipelines.html) though. Depending on exactly what you're trying to do, it can be very well suited for the sort of thing you give here. You can then call the different pipelines using `kedro run -p` flag.

Now, regarding `find_pipelines` passing `kwargs` through to `create_pipeline`. This is a very interesting idea. On the one hand it seems like an easy addition to make, and what are those `kwargs` in `create_pipeline` for after all? On the other hand, `find_pipelines` is just meant to automatically solve the simple default case where `create_pipeline` is called without any arguments, and it's arguably beyond the scope of the feature to try and cater for this more complex case with `kwargs`. Maybe in the future we'll want to give `find_pipelines` proper arguments that control its behaviour also, in which case we'd need to pass through only `kwargs` that are leftover to `create_pipeline`. Hmm...

Overall I'd be interested in hearing whether other people would find this useful. I think we should wait a while to see how `find_pipelines` gets used and not add this straight away anyway.

**Comment by merelcht** [comment]
This issue hasn't had any recent activity, so I'm closing it.
