### ISSUE TITLE
tracking.JSONDataSet documentation and docstring are not accurate

### ISSUE THREAD

**Issue by clotildeguinard** [kedro-org/kedro#1823]
Here is the source code for `tracking.JSONDataSet`: https://kedro.readthedocs.io/en/latest/_modules/kedro/extras/datasets/tracking/json_dataset.html#JSONDataSet

The `_load` method has been overriden to raise a `DataSetError` when called.

The documentation does not reflect that well. What has to be fixed:

- The `tracking.JSONDataSet` documentation and API ref should mention that this dataset cannot be loaded (see https://kedro.readthedocs.io/en/latest/kedro.extras.datasets.tracking.JSONDataSet.html)
- The `tracking.JSONDataSet` class docstring should not call `data_set.load()` (this code snippet that was probably copied from the `json.JSONDataSet`)

**Comment by MerelTheisenQB** [comment]
Thanks for flagging this @clotildeguinard ! We'd be happy accept a PR for this if you have time 🙂, but will add it to our backlog as well.

**Comment by clotildeguinard** [comment]
Ok @MerelTheisenQB I just submitted a PR. I don't know what to do about the load method docstring in the API reference, because as we are only overriding the _load method, we cannot really modify the load method docstring...

**Comment by MerelTheisenQB** [comment]
> Ok @MerelTheisenQB I just submitted a PR. I don't know what to do about the load method docstring in the API reference, because as we are only overriding the _load method, we cannot really modify the load method docstring...

Yeah sadly those docstrings are created automatically so I don't think there's anything we can change there.
