### ISSUE TITLE
 Can not instamtiate abstract class generator with abstract methods send,throw

### ISSUE THREAD

**Issue by johnson112233** [kedro-org/kedro#1824]

**Comment by noklam** [comment]
@johnson112233  Would you mind fill in more details with the issue template?

**Comment by johnson112233** [comment]
thank you very much

________________________________

**Comment by johnson112233** [comment]
> 
![C04E1FCB-E6AD-467B-A26C-8DB2A8BE0C95](https://user-images.githubusercontent.com/95671163/188117622-b8e6e6af-852f-4fa9-9027-5561b9c58624.jpeg)

**Comment by johnson112233** [comment]
how can i do it

**Comment by noklam** [comment]
This doesn't seem to be a problem related to kedro, closing it now.
