### ISSUE TITLE
Destroy the default_project_path variable in IPython extension

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro#1840]
> **Note**. Related: #1839. Some of the tests that currently exist might not be necessary or would at least be much simpler following this work. 

[From the docs](https://kedro.readthedocs.io/en/stable/tools_integration/ipython.html#managed-jupyter-instances):
<img width="999" alt="image" src="https://user-images.githubusercontent.com/49395058/188971468-e56da5ea-df4a-48ea-a721-db31f9dc6abc.png">

The current implementation uses a global variable `default_project_path` to remember the Kedro project path. This is annoying:
* it's confusing to follow, especially since I want to split the file into multiple modules, which would mean sharing the variable between modules
* it makes unit tests tricky
* plus all the usual reasons people tend to dislike global variables

So let's do it a different way instead. Possible methods include:
1. Turn `%reload_kedro` into a [line magic with state](https://ipython.readthedocs.io/en/stable/config/custommagics.html)
2. Define `reload_kedro` function as a closure inside `magic_reload_kedro` and use `nonlocal`
3. Use `context.project_path` to get the project path once it's been set. This is what we now do in `%run_viz` (`context` is available in `local_ns` there)

> **Note**. Even though we're changing a "public" variable (no `_`) this is definitely a non-breaking change. This variable is not meant to be used externally anywhere and I'm sure it's not (including kedro-viz). The name of it was changed in the past in 0.17.x as a non-breaking change and no one complained, so we can be confident removing it in a non-breaking release.

---

The above all assumes that we want to keep this "memory" behaviour. It is possible that the extra code required to do this doesn't seem to merit this small convenience feature. If this seems to be the case then _in principle_ I'm happy to drop it as a feature, i.e. `%reload_kedro` would need to repeat the project path (but still only when it's needed i.e. kedro project path can't be found automatically from your cwd). This would need a quick bit of user research to check that no one is very attached to the feature. My instinct is that it's a very minor convenience that is rarely used.

**Comment by MerelTheisenQB** [comment]
Do quick user research into whether people are using `%reload_kedro`, e.g. a poll.

**Comment by noklam** [comment]
A side note, some people did use the function `reload_kedro` directly instead of the libe magic `%reload_kedro`, partly because this is the only workaround and `%reload_kedro` arguments only work since `0.18.3`. I think it's nice to keep it working but not a must.
