### ISSUE TITLE
How to store the intermediate results of the pipeline

### ISSUE THREAD

**Issue by niartnelis** [kedro-org/kedro#1860]
## Description
How to store the intermediate results of the associated nodes of the pipeline. For example, node a outputs output1, and output1 is used as the input of node b. How to store output1

**Comment by noklam** [comment]
@niartnelis You may want to check out the tutorials. I think these 2 links are relevant. In short, everything not defined in the catalog will be a `MemoryDataSet`, if you wish to persist these data, you simply make an entry in your `catalog.yml`.

https://kedro.readthedocs.io/en/latest/get_started/hello_kedro.html#datacatalog
https://kedro.readthedocs.io/en/latest/data/data_catalog.html

**Comment by niartnelis** [comment]
> @niartnelis You may want to check out the tutorials. I think these 2 links are relevant. In short, everything not defined in the catalog will be a `MemoryDataSet`, if you wish to persist these data, you simply make an entry in your `catalog.yml`.
> 
> https://kedro.readthedocs.io/en/latest/get_started/hello_kedro.html#datacatalog https://kedro.readthedocs.io/en/latest/data/data_catalog.html
Thank you very much for your reply. It is feasible to save the intermediate result in code. As follows, you can store the intermediate result variable in a DataSet in a specific format.
<img width="900" alt="image" src="https://user-images.githubusercontent.com/37354416/191395443-f91ee9de-696d-4409-9fc9-69f5ca553ce0.png">

**Comment by noklam** [comment]
@niartnelis I just want to make sure you are aware of the Kedro Project, the easiest way to start is via CLI `kedro new` and create a project. In a Kedro project, these `DataCatalog`, `DataSet`, `Runner` objects are managed for you. 

Unless there is a good reason, I will strongly advise sticking with a Kedro Project instead of using these classes directly.

**Comment by MerelTheisenQB** [comment]
Hi @niartnelis, do you still need help with this or is it okay if we close the issue?

**Comment by MerelTheisenQB** [comment]
I'll close this issue due to inactivity. Feel free to re-open it if more support is needed!
