### ISSUE TITLE
Optional steps (nodes) during pipeline run

### ISSUE THREAD

**Issue by foxale** [kedro-org/kedro#1867]
## Context & Description
When I'm building a modelling pipeline, I tend to create a lot of features and feature groups, which I want to turn off and on depending on the experiment. Those features and usually independent from each other, so I can calculate them in parallel. For now, the best way I came up with to implement this is to create one node per each feature, and then a kwargs node that combines them together. 

However, I don't really want to spend resources for calculating features that I know I won't be using. What would be the kedro way to achieve this?

## Possible Implementation
I guess there could be a parameter for `kedro run` command to skip specific nodes

**Comment by datajoely** [comment]
The short answer here is that we've avoided officially supporting this sort of thing since we believe the combinatorial complexity introduced goes against the philosophy of clarity and reproducibility at the core of Kedro's design.

You can achieve this using kwargs and hooks if you really want.

**Comment by foxale** [comment]
Thanks for the answer. I'll close as it looks like the topic has been exhausted.
