### ISSUE TITLE
KedroSession not working on packaged kedro project

### ISSUE THREAD

**Issue by ajinkyachandulwar** [kedro-org/kedro#1869]
## Description
KedroSession giving error `ModuleNotFoundError: No module named 'None'` on kedro version 0.18.2
And after using bootstrap_project() not able to find pipelines defined in another project.

Steps followed to use Kedrosession
https://kedro.readthedocs.io/en/0.18.2/kedro_project_setup/session.html

## Context
I am trying to use the kedro pipelines defined in 1 of my kedro project (ProjectX). I am packaging ProjectX using kedro package and then install it using pip install. 

## Steps to Reproduce
1. Create a new kedro project (ProjectX) using `kedro new`
2. Add 1 pipeline (pipeline1) in it and make entry in pipeline_registry.py
3. package this project using `kedro package`
4. now install the generated wheel file
5. create another kedro project (Project Y) and try to invoke pipeline defined in ProjectX using Kedrosession
 

```
from kedro.framework.session import KedroSession
from kedro.framework.startup import bootstrap_project
from pathlib import Path

metadata = bootstrap_project(Path.cwd())

extra_params = dict(
      param1="value1",
      param2="value2",
  )

with KedroSession.create("projectx", extra_params=extra_params) as s:
        return s.run(pipeline_name="pipeline1")

```

## Expected Result
Should execute pipeline1 and return the output dataframes.

## Actual Result
Getting below error

   354 │   │   try:                                                                               │
│   355 │   │   │   pipeline = pipelines[name]                                                     │
│   356 │   │   except KeyError as exc:                                                            │
│ ❱ 357 │   │   │   raise ValueError(                                                              │
│   358 │   │   │   │   f"Failed to find the pipeline named '{name}'. "                            │
│   359 │   │   │   │   f"It needs to be generated and returned "                                  │
│   360 │   │   │   │   f"by the 'register_pipelines' function."                                   │
│                                                                                                  │
│ ╭──────────────────────────────────────── locals ─────────────────────────────────────────╮      │
│ │       context = <kedro.framework.context.context.KedroContext object at 0x7f8f6b1d5d90> │      │
│ │  extra_params = {'param1': 'value1', 'param2': 'value2'}                                │      │
│ │   from_inputs = None                                                                    │      │
│ │    from_nodes = None                                                                    │      │
│ │ load_versions = None                                                                    │      │
│ │          name = 'pipeline1'                                                             │      │
│ │    node_names = None                                                                    │      │
│ │ pipeline_name = 'pipeline1'                                                             │      │
│ │        runner = None                                                                    │      │
│ │  save_version = '2022-09-23T12.19.58.331Z'                                              │      │
│ │          self = <kedro.framework.session.session.KedroSession object at 0x7f8f6b114b50> │      │
│ │    session_id = '2022-09-23T12.19.58.331Z'                                              │      │
│ │          tags = None                                                                    │      │
│ │      to_nodes = None                                                                    │      │
│ │    to_outputs = None                                                                    │      │
│ ╰─────────────────────────────────────────────────────────────────────────────────────────╯      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Failed to find the pipeline named 'pipeline1'. It needs to be generated and returned by 
the 'register_pipelines' function.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`):
Name: kedro
Version: 0.18.2
* Python version used (`python -V`): Python 3.8.13
* Operating system and version: MacOS Monterey (12.0.1)

**Comment by ajinkyachandulwar** [comment]
also followed the steps mentioned at https://github.com/kedro-org/kedro/issues/1583

**Comment by noklam** [comment]
> also followed the steps mentioned at https://github.com/kedro-org/kedro/issues/1583
> Still the issue is same

@ajinkyachandulwar https://github.com/kedro-org/kedro/issues/1583#issuecomment-1254913429

Have you tried this already? If so what error did u get?

**Comment by ajinkyachandulwar** [comment]
@noklam i followed the same steps mentioned in 
https://kedro.readthedocs.io/en/stable/tutorial/package_a_project.html#package-your-project
for packaging my kedro project, but While using kedrosession i am getting the above mentioned error.
Please note this was working fine on kedro v0.17.7

**Comment by noklam** [comment]
@ajinkyachandulwar

For packaged mode you will simply call the package. 

```
from kedro_spaceflights.__main__ import main

main(
    ["--pipeline", "__default__"]
)  # or simply main() if you don't want to provide any arguments

```

**Comment by ajinkyachandulwar** [comment]
But with this option i will not be getting the output of my pipeline as dataframe (as i am not using any catalog.yml).

Also in kedro 0.17.7 kedrosession was working fine for me so why its not working in 0.18.2 ?
Is kedrosession not meant to use outside kedro project ?

**Comment by noklam** [comment]
- [ ] https://github.com/kedro-org/kedro/issues/1583
- [ ] https://github.com/kedro-org/kedro/pull/1423

**The workaround to use `KedroSession` with package mode can be found here. https://github.com/kedro-org/kedro/issues/1807#issuecomment-1228342162**

In short, there is "package mode" and "project mode". `KedroSession` is not meant to be used outside of Kedro Project as of this moment. See https://github.com/kedro-org/kedro/issues/1583#issuecomment-1191215006 for more information.

However, I like the idea that `KedroSession` can be used for package mode, this is **exactly** what I proposed[here](https://github.com/kedro-org/kedro/pull/1423#issuecomment-1240768160). However, we haven't discussed this within the team, so it's just my opinion. Thanks for raising this, I think this supports my idea.

I have made this issue and "Technical Design" ticket and hopefully we have some time to discuss this next week.

**Comment by noklam** [comment]
Background for discussion
1. Do we intend to support running the package with `KedroSession` prior 0.18.x? Is this a regression? This behavior change is briefly explained in #1583.
2. `KedroSession` currently do nothing about the `package_name` other than saving it. Why do we even need it if it's not doing anything? In my view it's should be used, but maybe there is historical reason that I don't fully understand yet. The full details are in #1423 where @AntonyMilneQB also have some opinion about this.
* One thing that I like about `KedroSession` is we can immediately do `kedro run --package_name=xxx`

**Comment by ajinkyachandulwar** [comment]
Thanks @noklam for creating bug for the requirement. As i mentioned my project pipelined produce outputs as dataframes which are required for further processing. For this change i can see https://github.com/kedro-org/kedro/pull/1423 this pull request is in review. Any idea when this feature it will be available for use to end users ?

**Comment by noklam** [comment]
@ajinkyachandulwar Would this work for you for now? I think it will still take some time before #1423 is merged.
> The workaround to use KedroSession with package mode can be found here. https://github.com/kedro-org/kedro/issues/1807#issuecomment-1228342162
