### ISSUE TITLE
Add `_SINGLE_PROCESS` property to `CachedDataSet`

### ISSUE THREAD

**Issue by MerelTheisenQB** [kedro-org/kedro#1888]
## Description
The `CachedDataSet` cannot be used with the `ParellelRunner` so we should add the `_SINGLE_PROCESS` property just like [DeltaTableDataSet](https://github.com/kedro-org/kedro/blob/main/kedro/extras/datasets/spark/deltatable_dataset.py#L60-L64)

## Context
https://github.com/kedro-org/kedro/issues/673#issuecomment-1026902070

**Comment by carlaprv** [comment]
Hi @MerelTheisenQB I'd like to contribute with this issue for hacktoberfest. How can I be assigned to it?

**Comment by MerelTheisenQB** [comment]
> Hi @MerelTheisenQB I'd like to contribute with this issue for hacktoberfest. How can I be assigned to it?

Fantastic! I'll assign you @carlaprv 😄 If this is your first time contributing to Kedro, you might want to check out our [contribution guide](https://kedro.readthedocs.io/en/stable/contribution/contribute_to_kedro.html) for guidance.

**Comment by carlaprv** [comment]
Thanks @MerelTheisenQB I've read it and forked the repository to start working :D

**Comment by MerelTheisenQB** [comment]
Completed in https://github.com/kedro-org/kedro/pull/1905
