### ISSUE TITLE
Capitalise Kedro-Viz in documentation

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#1896]
## Description
This is hopefully a quick win exercise. We want you to fix a typo in our documentation where we should have capitalised Kedro-Viz but forgot to. 

To find and fix the error: 
1. Head to the [Visualise Pipelines section in our documentation](https://github.com/kedro-org/kedro/blob/main/docs/source/tutorial/visualise_pipeline.md#visualise-layers)
2. Search for "kedro-viz", the affected area is circled in blue
3. Replace with "Kedro-Viz"

<img width="753" alt="Screenshot 2022-10-04 at 15 43 28" src="https://user-images.githubusercontent.com/43755008/193850513-54265ea9-f497-46db-a073-d804f900745b.png">

## Context
You're helping us keep our style guidelines in tact.

## Instructions on how to contribute

Checkout our [guidelines by @stichbury](https://kedro.readthedocs.io/en/stable/contribution/documentation_contributor_guidelines.html) and [head to Slack](https://join.slack.com/t/kedro-org/shared_invite/zt-1eicp0iw6-nkBvDlfAYb1AUJV7DgBIvw) if you have any questions.

**Comment by bilal-aamer** [comment]
Hello! @yetudada , Could I too address the same issue! Thanks
