### ISSUE TITLE
Namespacing does not work with multiple yaml files in modular pipelines

### ISSUE THREAD

**Issue by yurigba** [kedro-org/kedro#1914]
## Description
I normally use namespaces for separating train, test and validation environments. These environments span multiple pipelines, but when I set a specific `train` namespace and it is present in my `feature_engineering` and `model_fit` pipelines at the same time it yields a `ValueError: Duplicate keys found in conf/base/parameters/feature_engineering.yml and conf/base/parameters/model_fit.yml`.

## Context
This bug affects my use of namespacing for pipelines. I have to write extra namespaces for each modular pipeline. I think that this breaks the purpose of namespacing.

## Steps to Reproduce
1. build and register two modular pipelines
2. use same namespace on both yaml files
3. `kedro run'

## Expected Result
Kedro pipeline understands that the same namespace in yaml files can be concatenated and the duplicate keys should not be an issue

## Actual Result
Kedro complains about duplicate keys and raises `ValueError: Duplicate keys found in conf/base/parameters/feature_engineering.yml and conf/base/parameters/model_fit.yml`.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.3
* Python version used (`python -V`): 3.9.13
* Operating system and version: Fedora 36 on toolbox `Linux toolbox 5.18.16-200.fc36.x86_64`

**Comment by yurigba** [comment]
This may solve the problem for me. Thank you.

**Comment by merelcht** [comment]
I'll close this issue for now. Feel free to re-open this if you need more help with it! 🙂
