### ISSUE TITLE
Enable/Disable hook with runtime config

### ISSUE THREAD

**Issue by foxale** [kedro-org/kedro#1935]
## Description
It may be useful to turn off certain hooks for specific kedro runs.

## Context
Let's say I have a hook, that when `kedro run` is invoked, automatically profiles all outputs for me and stores HTML reports somewhere in the project dir. Of course, this is time consuming and I don't want to do have this feature enabled on each run but on demand. What's the best way to turn in on and off? 

## Possible Implementation / Alternatives
Should I use `--params` and implement some switch on the hook side? Or maybe we should have a way to just decide which hooks to activate per run? 

Inspired by #435

**Comment by noklam** [comment]
You can disable installed hooks via `settings.py` via
```python
# settings.py
# DISABLE_HOOKS_FOR_PLUGINS = ("kedro-viz",)`
```

Or are you specifically requesting this for the Kedro CLI?

**Comment by foxale** [comment]
I would want to adjust project source code only if that's a change that should be version controlled down the line (on project level), and leave all single-run-related config to Kedro CLI and yaml run configs.

**Comment by noklam** [comment]
I assume this is identical as [[Allow extra hooks to be passed via the Kedro CLI](https://github.com/kedro-org/kedro/issues/435#top)
#435

**Comment by foxale** [comment]
Correct. The best combo though, would be a CLI parameter + env variable. In the ideal world that would work like so: 
```bash
kedro run --with-profiling
```
where `--with-profiling` would be passed to my custom ProfilingHook() class indicating user preference.

**Comment by noklam** [comment]
Just add more notes from a Discord User

> ToniMaroni — 10/10/2022
Hi Kedro team, do you have some guidelines as per when is it better to split one node into multiple nodes, and conversely when is it better to merge multiple nodes into one? For example, i am working on a feature engineering pipeline that operates on pandas dataframes, and it's not exactly clear for me when i should stack a whole bunch of transformations/augmentations in one single node, or instead split that code into multiple nodes. Would you have some feedback on this? Thanks!

**Comment by noklam** [comment]
> Correct. The best combo though, would be a CLI parameter + env variable. In the ideal world that would work like so:
> 
> ```shell
> kedro run --with-profiling
> ```
> 
> where `--with-profiling` would be passed to my custom ProfilingHook() class indicating user preference.


@foxale I think supporting arbitrary CLI arguments in the official Kedro CLI is unlikely.

To achieve that, you can actually override Kedro CLI in your project easily. The `cli.py` is actually part of Kedro Project Template in the older version - but we remove it since most people don't need to customize it.

I think you can achieve this by doing the following
1. Override the CLI with `cli.py` , add your new CLI arguments
2. Inject the argument as an environment variable
3. In your hooks/plugin - it should read this environment variable and behave accordingly.


See an example here:
https://github.com/noklam/kedro_gallery/blob/master/kedro_cli_extension/src/kedro_cli_extension/cli.py

**Comment by merelcht** [comment]
@foxale You could also point `DISABLE_HOOKS_FOR_PLUGINS` in `settings.py` to read from an environment variable.

**Comment by merelcht** [comment]
I'm closing this issue since there hasn't been any recent activity. Feel free to re-open this if you're still facing problems!
