### ISSUE TITLE
Document the LIFO order in which hooks are executed in `settings.py`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#1940]
### Description

We mention that hook implementations registered in `settings.py` run in LIFO order and that auto discovered hooks run before hooks in `settings.py`. 

- [ ] We need to also document what the order is in which auto-discovered hooks run. Add this to: https://kedro.readthedocs.io/en/stable/hooks/introduction.html To verify the run order, create a project and install several plugins with hooks to test.
- [ ] Add a comment in the `settings.py` template file to explain the run order of hooks

**Comment by deepyaman** [comment]
For reference: https://github.com/pytest-dev/pytest/blob/196f01965ed264e1fd917db236c872f85403753d/doc/en/how-to/writing_plugins.rst#plugin-discovery-order-at-tool-startup

**Comment by stichbury** [comment]
Also, while we are modifying hooks documentation, we need to take another look at the work involved with #978

**Comment by astrojuanlu** [comment]
Potentially overlapping with https://github.com/kedro-org/kedro/issues/1718, or that one should be a parent issue of this one.

**Comment by stichbury** [comment]
OK, let's do this. @noklam do you want to pick up the first draft of this in the upcoming sprint w/c 4th September? If so, please let @merelcht know to assign it to you within the sprint. Otherwise will keep an eye out for this to come next sprint if you are already maxed out with upcoming hack days & values day.

**Comment by noklam** [comment]
That should be fine! I am fairly familiar with the hooks stuff so it shouldn't be too much work.

**Comment by noklam** [comment]
I've bumped the estimate from 3 -> 5. See https://github.com/kedro-org/kedro/pull/3013 for more details. There will be follow up PR but basically I found that there are extra documentation and development work that we should do.
