### ISSUE TITLE
Add debug level logging for hook execution order

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#1942]
### Description
Add logs at debug level that make it clear to users what order their (auto) registered hooks run in.

### Context
https://github.com/kedro-org/kedro/issues/1939

**Comment by astrojuanlu** [comment]
Would be nice to have in the face of https://github.com/kedro-org/kedro/issues/2492 and https://github.com/kedro-org/kedro/issues/2493, and would probably help with https://github.com/kedro-org/kedro/issues/1940 and https://github.com/kedro-org/kedro/issues/1718.

**Comment by astrojuanlu** [comment]
Maybe using the built-in tracing? https://pluggy.readthedocs.io/en/latest/#call-tracing

```python
pm = PluginManager("myproject")
# magic line to set a writer function
pm.trace.root.setwriter(print)
undo = pm.enable_tracing()
```
