### ISSUE TITLE
Remove linting and test files + setup from the project template

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#1947]
## Description
Remove all linting dependencies and configuration:
- `setup.cfg` completely
- linting config from `pyproject.toml`
- linting dependencies from `requirements.txt`: flake8, black, isort

Remove test setup:
- `src/test` directory completely
- `pytest` dependencies from `requirements.txt`

## Context
Follow up on: https://github.com/kedro-org/kedro/issues/1849

**Comment by SajidAlamQB** [comment]
In https://github.com/kedro-org/kedro/pull/1938 we added `jupyterlab_server` pin that can be removed once this is completed.

**Comment by astrojuanlu** [comment]
Following the new utilities workflow https://github.com/kedro-org/kedro/issues/2388 we'll keep these files.
