### ISSUE TITLE
Create new advanced Kedro starter

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#1948]
## Introduction

This is the placeholder ticket to add ideas about what a more advanced Kedro starter should contain.

## Background

Our users have flagged a need for a more advanced tutorial that shows them how Kedro is used for more complex use cases. This will also help in keeping spaceflights (the most complex example to date) simpler and onboard users gradually.

## What should this starter contain?

- Linting and testing setup
- Test examples for testing nodes and pipelines

**Comment by stichbury** [comment]
@merelcht would you mind if I close this in favour of a set of tickets for small examples that extend Spaceflights (but don't necessarily become new starters). I think that would be more useful from the user research results returned recently.
