### ISSUE TITLE
Rename the documentation pages to replace underscores with hyphens

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#1960]
## Description
This isn't a massively high priority but is something we should deal with (and it could be a task we do relatively quickly) but it'll require touching every page of the docs 🙀

## Context
So I've recently learned that google doesn't recognise underscores as word separators when it indexes pages. So if we have a page called `create_a_modular_pipeline` then Google will report that as `createamodularpipeline` to its algorithm. (If we had `create-a-modular-pipeline` then it would go into the mix as `create a modular pipeline` which earns more google juice for the keywords "modular pipeline" or "create a modular pipeline"). [More explanation here](https://www.woorank.com/en/blog/underscores-in-urls-why-are-they-not-recommended)

Now for Kedro docs, we probably don't care too much about SEO so the priority is low, but if we are looking to build an exception documentation offering, it follows that we should follow best practice.

## Solution
We can set up redirects in readthedocs to redirect all the existing links through to newly hyphenated pages, so it's not a big piece of work to rename the files. BUT we would also have to change all existing links within the docs themselves, since Sphinx will barf otherwise.

**Comment by astrojuanlu** [comment]
At least, going forward we should make sure new files have hyphens rather than underscores. I don't know if there's some linting we could put in place?

**Comment by stichbury** [comment]
> At least, going forward we should make sure new files have hyphens rather than underscores. I don't know if there's some linting we could put in place?

I have steered clear of mixing two paradigms but kept the underscores in each new page I create since I feel like the inconsistency is worse than the issue reported. Let's keep them consistent and accept that we take an (minor) SEO hit with the naming, which we can make up for with well-chosen titles/subheads and linking.
