### ISSUE TITLE
SVMLight DataSet

### ISSUE THREAD

**Issue by vilozio** [kedro-org/kedro#1972]
## Description
Add a DataSet for LibSVM format (or sometimes called SVMLight format)
https://catboost.ai/en/docs/concepts/input-data_libsvm
https://www.cs.cornell.edu/people/tj/svm_light/

Implementation in sklearn
https://scikit-learn.org/stable/modules/generated/sklearn.datasets.dump_svmlight_file.html
https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_svmlight_file.html

## Context
This format is used to store sparse data with a lot of zeros.

## Possible Implementation
The functions from sklearn can be reused for a DataSet.

**Comment by merelcht** [comment]
Hi @vilozio, thanks for the suggestion! We would very much welcome a contribution for this 😄 We've got docs explaining how to create a new dataset: https://kedro.readthedocs.io/en/stable/extend_kedro/custom_datasets.html#how-to-contribute-a-custom-dataset-implementation

**Comment by vilozio** [comment]
Hi @merelcht. Nice, I am going to create a pull request.
