### ISSUE TITLE
pytest doesn't debug, only run tests until failure or success

### ISSUE THREAD

**Issue by KikiCS** [kedro-org/kedro#1982]
## Description
When I try running tests in debug mode, they don't stop at any breakpoint and run all the way to the end.

## Context
I wrote some tests for my nodes inside a kedro project.

## Steps to Reproduce
1. Set up a virtual environment with kedro and a kedro project.
2. Pipeline code can be debugged normally.
3. Tests code can be run using "kedro test" or "pytest" in terminal, as well as from the debugging tools in VSCode and PyCharm, but doesn't stop at breakpoints.

## Expected Result
I expect tests to stop at any breakpoint I manually set.
Other unittests written for other libraries (in different virtual environments that don't use kedro) are stopping fine at their breakpoint.

## Actual Result
The breakpoints are ignored. Also setting "User Uncaught Exceptions" in VS Code doesn't solve.

## Your Environment
I tried both on VS Code running on my WSL (Ubuntu 20.04 with virtualenv) and on PyCharm running on my Windows 11 OS (anaconda with a custom virtual env). 

In VS Code I tried both adding test configuration to `launch.json` as well as deleting `launch.json` from `.vscode` folder.

* Kedro version used: 0.18.3
* Python version used: 3.8.10

**Comment by daniel-ressi** [comment]
Hi, I ran across the same issue a while ago. The fix is to run pytest or kedro test with --no-cov. Otherwise you can also disable the coverage in the pyproject.toml `[tool.pytest.ini_options]`

**Comment by noklam** [comment]
Thank you for flagging this. This is a known issue with `coverage`. Maybe we should flag it in our docs.

`pytest --no-cov` is the correct solution. Thanks. @daniel-ressi
