### ISSUE TITLE
Update docs to remove any mention of Discord and replace with Kedro's Slack org details

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#1983]
## Description
As we migrate away from Discord to use our own Slack org, we need to update the docs to remove all mention of Discord and point users to Slack instead. We should also consider adding a section to explain why the Slack org exists (for support) and compare with how to use Github discussions/Github issues for Kedro-project specific discussions.

**Comment by BSGalvan** [comment]
Hello! I'd like to take up this issue.

Just to make sure I understand the scope of this correctly, a PR in this direction would involve:
- Swapping out the Discord links in the _docs_ with links to the Slack org. I see that there are mentions to the Discord in [README.md](https://github.com/kedro-org/kedro/blob/main/README.md?plain=1#L6), [CONTRIBUTING.md](https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md?plain=1#L18) and elsewhere (eg: the website). Do we swap those out as well, or reserve those for another PR?
- Add section(s) (where ever applicable) to explain why the Slack org exists, and how it compares with the use case for Github discussions/issues (as you mentioned).

**Comment by stichbury** [comment]
Hi @BSGalvan and thank you, thank you, for offering to pick up this issue! 🙏 

I think we should leave the README and CONTRIBUTING docs for now, although it's a good spot. The reason being that we should separate built docs from others just for PR "hygiene". I will make a second issue for those two files but I will probably make a few other other changes in them as I go through, so I'll do a general "Review and update..." kind of ticket. The Website will need separate update and we have some other thoughts on that, so again, let's keep that separate and -- for now -- limit work to the docs markdown files only, if you are OK to take those on.

* I agree with your analysis to just swap out the links (I think most of the mentions of discord should be just be passing ones rather than particularly detailed). 

* I can't quite yet decide where to put the section on why we have moved to use the Slack org (rather than discord) and to compare use cases for Slack questions with the Github issues/discussions options. I think it should probably be an initial github discussion (to confirm the best approach) and then dropped into the docs in the "Get Started" section to explain how best/most efficiently get the kind of help you need.

Howsabout I write up the github discussion today and post it, then leave the community to discuss it, and revisit when the rest of this issue is in a PR? Then we can work together to drop the section into place. Does that sound OK?

🌟 Again, thanks for offering to take this one. Much appreciated!! 🌟 

cc @yetudada @merelcht @datajoely @noklam

**Comment by BSGalvan** [comment]
> ... let's keep that separate and -- for now -- limit work to the docs markdown files only, if you are OK to take those on.

Sounds awesome to me! I'm delighted to be of help 😄 

I do have a slight clarification regarding this.

So in [`docs/source/index.rst`](https://github.com/kedro-org/kedro/blob/main/docs/source/index.rst#L42), there is a Discord badge for which I couldn't find a readymade alternative on shields.io.
[Here is one](https://img.shields.io/badge/slack-chat-blueviolet.svg?label=Kedro%20Slack&logo=slack&style=flat-square) I conjured up by tweaking certain parameters from the Discord badge itself. Any thoughts on which direction this could be further modified? Maybe there's a Slack `shields.io` badge I missed?

With that decided, I'll be ready to make a PR soon. Then we can wait for the community to deliberate, and see where we go from there 🎊

**Comment by stichbury** [comment]
That's a neat shield, thanks! I don't know if there are other options available, but possibly someone in our team does (paging @tynandebold as a possible candidate).

Looking forward to seeing your PR. Thank you again! 🙌

**Comment by tynandebold** [comment]
Hey @BSGalvan that shield you created looks great! I haven't seen many of them, and when I do they aren't anything special (e.g. [this one](https://github.com/apollographql/graphql-tag/blob/main/README.md)). I think we should go with yours 😄
