### ISSUE TITLE
Bump s3fs version number

### ISSUE THREAD

**Issue by datajoely** [kedro-org/kedro#1995]
## Description
> Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

Our current setup.py has the following restriction `S3FS = "s3fs>=0.3.0, <0.5"`

[s3fs has been on calendar versioning](https://s3fs.readthedocs.io/en/latest/changelog.html#version-2021-04-0) since April 2021 so we're quite out of date.

## Implementation
- Move to the same calendar versioning scheme we apply to related fsspec project.
- Fix tests using `moto` or `aiobotocore`

**Comment by noklam** [comment]
See #2017 for more details. This may not be trivial as bumping `s3fs` immediately cause a lot of tests fails. I suspect this is a pure test issue (Kedro will still work, but the tests are not working because of `moto` or `aiobotocore`).

Estimate: 5/8

**Comment by astrojuanlu** [comment]
xref https://github.com/kedro-org/kedro-plugins/issues/337, which has an open PR https://github.com/kedro-org/kedro-plugins/pull/348
