### ISSUE TITLE
Dry run option that checks DAG and existence of pipeline inputs

### ISSUE THREAD

**Issue by jwaton** [kedro-org/kedro#1997]
## Description
Hello, I would like to use something like this dry runner https://kedro.readthedocs.io/en/stable/nodes_and_pipelines/run_a_pipeline.html#custom-runners but in a slightly different context - I would like to also check whether the data exists.
I am using multiple kedro environments https://kedro.readthedocs.io/en/stable/kedro_project_setup/configuration.html for different model experiments
When I do a partial run with `--from-nodes` and `--to-nodes` (to save time over a full pipeline run), I often discover that some data does not exist in my environment - but it takes a while to discover this, as the code needs to run first
Then "checking whether the data exists" is a bit complex:
- Either check whether it is an intermediate output of the provided pipeline
- Or check whether it can be read from the catalog using the _exists method of the abstract dataset class

## Context
This would save considerable time in debugging pipeline runs.

## Possible Implementation
I shared a rough, unpolished implementation in this slack thread: https://kedro-org.slack.com/archives/C03RKP2LW64/p1667314369586859
Improvements:
- Using public `exists` method
- Raising the appropriate data not existing error

**Comment by datajoely** [comment]
We have this in the docs but I feel there is a lot of value building it in natively.

**Comment by jwaton** [comment]
A very basic version is in the docs. I suggest also extending it to check existence of inputs (existence being not just that a `catalog` entry exists but also that some data can be found in its `filepath`)

**Comment by merelcht** [comment]
Hi @jwaton ! We really like this suggestion. Could you make a contribution and add your `DryRunner` implementation? 🙂

**Comment by noklam** [comment]
I have pasted the code here before it gets lost in Slack. I can take over this if @jwaton doesn't have the time.

```
from kedro.io import AbstractDataSet, DataCatalog, MemoryDataSet
from kedro.pipeline import Pipeline
from kedro.runner.runner import AbstractRunner


class DryRunner(AbstractRunner):
    """``DryRunner`` is an ``AbstractRunner`` implementation. It can be used to list which
    nodes would be run without actually executing anything.
    """

    def create_default_data_set(self, ds_name: str) -> AbstractDataSet:
        """Factory method for creating the default data set for the runner.

        Args:
            ds_name: Name of the missing data set
        Returns:
            An instance of an implementation of AbstractDataSet to be used
            for all unregistered data sets.

        """
        return MemoryDataSet()

    def _run(
        self, pipeline: Pipeline, catalog: DataCatalog, session_id: str = None
    ) -> None:
        """The method implementing dry pipeline running.
        Example logs output using this implementation:

            kedro.runner.dry_runner - INFO - Actual run would execute 3 nodes:
            node3: identity([A]) -> [B]
            node2: identity([C]) -> [D]
            node1: identity([D]) -> [E]

        Args:
            pipeline: The ``Pipeline`` to run.
            catalog: The ``DataCatalog`` from which to fetch data.
            session_id: The id of the session.

        """
        nodes = pipeline.nodes
        self._logger.info(
            "Actual run would execute %d nodes:\n%s",
            len(nodes),
            "\n",
            pipeline.describe(),
        )
        self._logger.info("Checking inputs...")
        input_names = pipeline.inputs()
        missing_inputs = [
            input_name
            for input_name in input_names
            if not catalog._get_dataset(input_name).exists()
        ]
        if missing_inputs:
            raise KeyError(f"Datasets {missing_inputs} not found.")
```
