### ISSUE TITLE
Hook: `before_node_run` is not working as expected when only dataset filepath is needed to be passed

### ISSUE THREAD

**Issue by RakibulHoque** [kedro-org/kedro#2001]
## Context
I was working with a `kedro.extras.datasets.text.TextDataSet` dataset where I saved a `.pbf` file in a node. I needed the `filepath` in the next node to operate on the `pbf` . So, I wrote a hook for that node to convert the input dataset to give only the filepath to the node, not the data (as it is not what I want). Current process seems to load the dataset before updating the the node input datasets data via `before_node_run` hook. Though it is not a major problem in most of the cases, but if the file is too big or cannot be parsed (such as .exe) by the described loader, it can be a problem (which was in my case).

## Hack
Currently I have made a hack on the library function debugging via the error and found that if the function `_run_node_sequential` is slightly changed, then this issue can be handled for current case.
### Unchanged Function:
```
#kedro/runner/runner.py
def _run_node_sequential(
    node: Node,
    catalog: DataCatalog,
    hook_manager: PluginManager,
    session_id: str = None,
) -> Node:
    inputs = {}

    for name in node.inputs:
        hook_manager.hook.before_dataset_loaded(dataset_name=name)
        inputs[name] = catalog.load(name)
        hook_manager.hook.after_dataset_loaded(dataset_name=name, data=inputs[name])

    is_async = False

    additional_inputs = _collect_inputs_from_hook(
        node, catalog, inputs, is_async, hook_manager, session_id=session_id
    )
    inputs.update(additional_inputs)

    outputs = _call_node_run(
        node, catalog, inputs, is_async, hook_manager, session_id=session_id
    )

    for name, data in outputs.items():
        hook_manager.hook.before_dataset_saved(dataset_name=name, data=data)
        catalog.save(name, data)
        hook_manager.hook.after_dataset_saved(dataset_name=name, data=data)
    return node
```

### Changed Function:
```
#kedro/runner/runner.py
def _run_node_sequential(
    node: Node,
    catalog: DataCatalog,
    hook_manager: PluginManager,
    session_id: str = None,
) -> Node:
    inputs = {}

    is_async = False

    additional_inputs = _collect_inputs_from_hook(
        node, catalog, inputs, is_async, hook_manager, session_id=session_id
    )
    inputs.update(additional_inputs)

    for name in node.inputs:
        hook_manager.hook.before_dataset_loaded(dataset_name=name)
        if name not in inputs.keys():
            inputs[name] = catalog.load(name)
        hook_manager.hook.after_dataset_loaded(dataset_name=name, data=inputs[name])


    outputs = _call_node_run(
        node, catalog, inputs, is_async, hook_manager, session_id=session_id
    )

    for name, data in outputs.items():
        hook_manager.hook.before_dataset_saved(dataset_name=name, data=data)
        catalog.save(name, data)
        hook_manager.hook.after_dataset_saved(dataset_name=name, data=data)
    return node
```

After this hack on the library function, my pipelines seems to work fine. Thought this is something to be reported. Please give your valuable suggestions for achieving the same result without this hack. Thanks in advance.

**Comment by allenhaozi** [comment]
1. write your own custom dataset
2. use `kedro.extras.datasets.text.TextDataSet`to record the address of the pdf file, not the pdf itself,
The next node dataset gets the address, following your logic

I didn't practice it. I just suggested it

**Comment by RakibulHoque** [comment]
@allenhaozi , Thanks for the suggestion. 
1. I was initially thinking about writing a dataset, however, later found this might be a far fetched effort for a simple task of getting the filepath. Also, kedro already has an example for getting the filepath via [hooks](https://kedro.readthedocs.io/en/stable/hooks/examples.html#modify-node-inputs-using-before-node-run-hook). So, I have decided to go with it and found this bug.
2. But the second suggestion is good idea, but I also need to save the actual `.osm.pbf` file. not only the name. Alternatively, I might save the filename in a separate dataset, but would it be a good solution if I needed the filename in many datasets?

**Comment by RakibulHoque** [comment]
@allenhaozi , decided to go with your first suggestion. wrote a custom dataset and it worked. Thanks a lot. 👍  Here's the custom dataset:
```
from kedro.extras.datasets.text import TextDataSet
from kedro.io.core import (
    get_filepath_str
)

class FOPathTextDataSet(TextDataSet):
    def _load(self) -> str:
        load_path = get_filepath_str(self._get_load_path(), self._protocol)
        return load_path
```

**Comment by datajoely** [comment]
Closing this since it looks like we've come up with a good solution!
