### ISSUE TITLE
Tutorial data: Sanitise the spaceflights data to remove real countries and replace with fictional locations

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2008]
It would make sense to change the spaceflights data slightly to keep the example completely fictional. Let's revise the locations and any other information that looks to be "genuine" since it isn't (it's completely fabricated) and shouldn't appear to be realistic in any way.

**Comment by merelcht** [comment]
> We could also reduce the size of the data perhaps. As @noklam mentions
> 
> > As a starter that it get used in demo and testing, it takes a considerate of time to run the pipeline. For example in the Kedro bootcamp I see demoing catalog.load("shuttles") takes like 15-20 seconds and is a bit awkward for demo purpose.

I've created a separate ticket for this: https://github.com/kedro-org/kedro/issues/3109

**Comment by ggermade** [comment]
Working on this :) !

**Comment by Gundalai-Batkhuu** [comment]
Hi. Can I get assigned for this please? I'm a CS student and this is my first open-source contribution.

**Comment by ggermade** [comment]
hello! I'm actually with this already, I have a branch with changes but have not opened a PR yet as I'm missing a crucial step: finding out if there's missing documentation referencing the country name changes, so I can address them too

**Comment by Gundalai-Batkhuu** [comment]
No worries. I'll have a look at another issue.

**Comment by stichbury** [comment]
Hi @ggermade just wanted to check how this is going for you? Anything we can help with?

**Comment by stichbury** [comment]
Hi @ggermade This is the final call for contributions for October 2023. Please let us have any PRs you have in flight for Hacktoberfest before the end of the day!

**Comment by astrojuanlu** [comment]
This is an old issue and, apart from some interest during Hacktoberfest, not much has happened. I'm closing for now.
