### ISSUE TITLE
Fix comma splitting for node re-run suggestion

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2012]
## Description
Running kedro with the command `kedro run --from-nodes "two_inputs([A0,B0]) -> [C1]"` will cause an error: `Pipeline does not contain nodes named ['B0]) -> [C1]', 'two_inputs([A0'].`

Kedro has incorrectly split the name of the intended Node into the names of two Nodes that do not exist.

This bug prevents the user from re-running kedro from any Node with a comma in its name. This is the case for any Node that is not explicitly given a name and has more than one input or output.

### Steps to Reproduce
1. Create a kedro project
2. Attempt to run the pipeline from a node with a comma in its name (`kedro run --from-nodes 'My node, a good node'`)
3. Receive the error `Pipeline does not contain nodes named ['a good node', 'My node']`.

## Context
https://github.com/kedro-org/kedro/issues/1828

## Implementation
@jmholzer idea of a fine-state machine csv-parsing type solution to do the string splitting rather than just blindly splitting on `,`. This would basically mean that `,` inside `()` would not split the string.

**Comment by jmholzer** [comment]
I have an implementation of this ready to go. Now that I have started manually testing my changes, I'm starting to think that once https://github.com/kedro-org/kedro/issues/2013 is merged, we'll never see `Node`s with names that contain commas. If you try to instantiate one using `node` (or `Node`), you'll see the following error:


![Image](https://user-images.githubusercontent.com/37243923/204901729-419ed2e3-3c45-42a0-9ad6-786dbb92eca7.png)


Is there a way to instantiate a node with such a name that I am not thinking of?

**Comment by merelcht** [comment]
> I have an implementation of this ready to go. Now that I have started manually testing my changes, I'm starting to think that once #2013 is merged, we'll never see `Node`s with names that contain commas. If you try to instantiate one using `node` (or `Node`), you'll see the following error:
> 
> ![Image](https://user-images.githubusercontent.com/37243923/204901729-419ed2e3-3c45-42a0-9ad6-786dbb92eca7.png)
> 
> Is there a way to instantiate a node with such a name that I am not thinking of?

This will still need to be done for the Kedro `0.18.x` series. But you're right that from `0.19.0` onwards we shouldn't be seeing `Node` names with commas anymore.
