### ISSUE TITLE
Avro support for dask.ParquetDataSet 

### ISSUE THREAD

**Issue by filpano** [kedro-org/kedro#2016]
Disclaimer: This is not a feature request per se, but intended to gauge interest after I noted the discussion in https://github.com/kedro-org/kedro/pull/1746 with regard to schema declarations.

## Description
I noted via the above linked discussion that support for complex nested typed and the like are not supported (i.e. `list<struct<fieldA: valueA, fieldB: list<int>>>` and so on).

I had a use case where I needed to write a Dask Dataset which contains some rudimentary support for parsing an `Avro` Schema (passed via a Confluent Schema Registry - optionally as a string) into a `pyarrow` schema. I believe with some work, it could be generified for other use cases as well.

## Context
We are using Kedro for, among other things, transformation of data types into ones more suited for our workloads. As part of this, the `dask.ParquetDataSet` has some issues with saving data that is not in the expected, inferred schema. To circumvent this issue, since our expected schema is defined in an Avro format, and to prevent schema drift by defining it in multiple locations, I wished to parse my existing Avro schema into pyarrow.

## Possible Implementation
Without going too much into implementation details, at this time I am parsing a self-contained Avro schema into a pyarrow schema, taking into account some logical types (e.g. `decimal`) and backreferencing of custom `record` types. The parsing itself is relatively lightweight but should probably to be extended to support things like custom mapping based on user-defined Avro fields or custom `logicalType`s.

## Possible Alternatives
None that I am aware of for the use case of using an existing schema in Avro format.

---
## Question
Would this be something that the Kedro community has interest in? If so, I can likely get a prototype out relatively quickly.

**Comment by AhdraMeraliQB** [comment]
Hi @filpano, thank you for this issue! Just closing this as our datasets have now moved to [the kedro-plugins repository](https://github.com/kedro-org/kedro-plugins/tree/main/kedro-datasets). Feel free to migrate this issue there, and/or open a PR, we'd love to see what this could look like!
