### ISSUE TITLE
Enable Codespace/GitPod on Kedro docs for smoother onboarding experience

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2028]
## Description
Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

One of the key obstacles to trying out kedro is the setup. You need to install the dependencies, clone a certain repository and run a couple of commands. We can make it easier by pre-configuring the environment so that it has the correct dependencies and kedro would just work.

## What problem does it solves?
* Smoother onboarding experience - automated the installation and users can start playing with kedro immediately
* Good for running workshops/training- since everyone can work on a Linux environment and we will have fewer problems dealing with Windows or specific permission issues.

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

* Use Codespace/GitPod (User need to have an account first, both offer some free compute hours monthly)
* A button shows up at the tutorial - A click of it will direct you to a web-IDE. User can then interact with the repository.

**Comment by astrojuanlu** [comment]
This ticket is almost 2 years old, offers a solution to a problem that has evolved a lot in that time, and hasn't had much activity ever since it was opened. I'm closing for now but feel free to reopen if you disagree.
