### ISSUE TITLE
Running specific pipeline with a string input

### ISSUE THREAD

**Issue by ytan101** [kedro-org/kedro#2035]
## Description
When I have 2 pipelines, I am able to pass a string output from the first pipeline into the second one. However, I am unable to run the second pipeline independently as the DataCatalog doesn't support single string data.

My first pipeline trains a model and produces the path (a string) to that checkpoint. Then the second pipeline is able to consume this string to run evaluation. However, I am unable to run the second pipeline directly as I cannot define the string itself in the data catalog.

## Context
I am trying to run a pipeline independently that takes in a string as part of its inputs

```
DataSetError: An exception occurred when parsing config for DataSet 'ckpt':
Class 'string' not found or one of its dependencies has not been installed.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.2
* Python version used (`python -V`): 3.10.
* Operating system and version: Ubuntu 20.04

**Comment by jmholzer** [comment]
Hi @ytan101, thanks for opening this issue.

Could you elaborate on why you need to store a path to the result of the first pipeline? If we don't offer a DataSet that can load these results, the right move could be writing a custom one for your use case.

**Comment by merelcht** [comment]
Hi @ytan101, do you still need help solving this issue?

**Comment by ytan101** [comment]
Apologies for the rather delayed response. My pipeline was a training node then inference an inference node.

When using Kedro in conjunction with PyTorch Lightning, I wanted to use multi-gpu training (on training node) then single gpu inference (on inference node).

What I expected was the training node to run once, as I instantiated the model in the training node rather than having the model code within the training node. However it ended up calling the training node 4 times (and so the inference node was also called 4 times).

What I wanted to do was only store the string (containing the model ckpt path) of the first run and pass that string to the validation node (this is because MLFlow is only creating ckpts and logs using GPU 0, the other GPUs produced NoneType instead of the ckpt path)

In the end, I just treated the validation node separately from the training node (since the model class itself is already doing validation every few training epochs). So I did not have to resolve the issue.

I'm more interested in why instantiating the model class on Kedro caused the node to run four times, but that would be a separate issue altogether (unfortunately I also did not have time to check it out.)

However, thank you very much for checking in with me on this issue again, and the suggestion of custom datasets.

**Comment by merelcht** [comment]
Hi @ytan101, thanks for explaining your use case in more detail! And I'm glad to hear you managed to find a way around the issue 🙂 

In order for Kedro to correctly deal with PyTorch checkpoints you would indeed have to write a custom dataset for it. I personally don't have any experience with PyTorch, so there might be other ways to make it work better with Kedro, but this is probably how I would approach it.

> I'm more interested in why instantiating the model class on Kedro caused the node to run four times, but that would be a separate issue altogether (unfortunately I also did not have time to check it out.)

This I find interesting as well! It's definitely a separate issue and we'd have to probably dive deep into your project. If you do ever want to talk about it in more detail, feel free to join [our slack](https://slack.kedro.org/) and continue the conversation there 🙂
