### ISSUE TITLE
More consistent kedro version information in pyproject.toml

### ISSUE THREAD

**Issue by sinha1** [kedro-org/kedro#2038]
## Introduction

[tool.kedro] in pyproject.toml mandates putting kedro version in project_version, which is inconsistent with remaining config defined in pyproject.toml

## Problem
In pyproject.toml mandatory attributes for [tool.kedro] are `package name`, `project_name` and `project_version`. At the moment version in project_version does not represent version of project defined in `project_name` but represents version on kedro used to create the project. This creates conflicting information presented in final pyproject.toml. Example below.

![image](https://user-images.githubusercontent.com/35728909/202738189-28468c97-09bd-4204-97db-585c7b026662.png)

The check is implemented [here](https://github.com/kedro-org/kedro/blob/82d69f43b3d8ce93605c272557e22547bca5bf11/kedro/framework/startup.py#L95) 

As a side effect, current nature of check also allows user to enter patch version in their pyproject.toml which does not exist. For example if you are running kedro 0.17.7 `project_version = "0.17.99"` will be a valid configuration for pyproject.toml even though the kedro version don't exist. 

### Alternatives considered

It will create a consistent interface if we call `project_version` as  `max_kedro_version` or a similar name, due to following reasons:
1. It will represent actual information defined in this attribute i.e. max compatible kedro version for this project.
2. In the context of a kedro project, `project_version` signifies version of the project, rather than version of kedro, so it will make interface more intuitive.
3. It would remove conflicting information from pyproject.toml illustrated in screenshot above.

## Rollout strategy

It will be great to have this resolved for kedro 0.17.

**Comment by merelcht** [comment]
Hi @sinha1, we will be renaming the `project_version` in https://github.com/kedro-org/kedro/issues/2118. However, we won't be able to change this for older versions of Kedro.
