### ISSUE TITLE
Write a "Yay, new release" blog post for 18.4

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2050]
As the title. We need to work out what the key points of 18.4 are and craft something for the QB blog as I don't think we'll be ready to go with the Kedro one yet. We can decide details of where to put it later though, first thing is to get it done.

I'm happy to draft a first version but will need some support to get a list of what's changed. This is probably something for this sprint but could come shortly after as long as we don't leave it too long. I'm thinking a similar post to this [one](https://medium.com/quantumblack/unboxing-kedro-0-17-0-and-kedro-viz-3-8-0-dfdbdb024289) for Christmas :)

**Comment by stichbury** [comment]
@merelcht @idanov How straightforward would it be to gather data on the 18.4 release in terms of the number of community contributions we received? Can we easily get numbers of PRs (or commits) that come from OS community members (either the number of the percentage)? It would be fantastic to be able to quote some data about 18.4 so if not the OS contributions, is there another metric we could use (number of issues resolved perhaps?).

**Comment by merelcht** [comment]
Contributions from the community for `0.18.4`:
1. [Fix issue with specifying format for SparkHiveDataSet ](https://github.com/kedro-org/kedro/commit/13ba2e35edcbc1e32b91170291f26a8b3a03ffea)
2. [Fix micro package pull from PyPI ](https://github.com/kedro-org/kedro/commit/e2cf9808b62a3ab452f1e4dde204321c78cb9ced)
3. [Capitalise Kedro-Viz in the "Visualize layers" section](https://github.com/kedro-org/kedro/commit/ff8e2a1dd22422655344216b54d225ec869ac4c7)
4. [Add _SINGLE_PROCESS property to CachedDataSet](https://github.com/kedro-org/kedro/commit/e1da30f2e4da85bfe20730eb5335e194f3ac3e19)
5. [Update the tutorial of "Visualise pipelines"](https://github.com/kedro-org/kedro/commit/34b2d337c9626a7109c6903ff3c2713c396b1f70)
6. [Enable TensorFlowModelDataset to overwrite existing model, and add …](https://github.com/kedro-org/kedro/commit/cbe0522c184bb808b1a49648b502e11b2215c3f5)
7. [Refactor ShelveStore into a separate module](https://github.com/kedro-org/kedro/pull/1614)
8. [Fix Docstring example for PickleDataSet](https://github.com/kedro-org/kedro/commit/ed3204931fe15d2c75b03deabd1abadce69ae326)
9. [Improve MatplotlibWriter documentation with examples](https://github.com/kedro-org/kedro/commit/fa5b87fb22da2142f5840cd2fc696f711f26ea11)
10. [Replace Discord links in docs with links to Slack](https://github.com/kedro-org/kedro/commit/4f42708c28e1c84c0ef7bc14c5a6ab2f6fa7278b)
11. [Improve DataSet API documentation with YAML examples](https://github.com/kedro-org/kedro/commit/bc6f3fe1af666ee77b52dd68a9623eaea40b6b1d)
12. [Add a video dataset (](https://github.com/kedro-org/kedro/commit/13089ea31a27f2c83d1ad7f479f36494519ac612)
13. [Add execution_options to SQLQueryDataSet (](https://github.com/kedro-org/kedro/commit/665b46de7b5bb61066d38956f2a34da4f23d2fa3)
14. [Add SVMLight DataSet (](https://github.com/kedro-org/kedro/commit/82d69f43b3d8ce93605c272557e22547bca5bf11)


It could be that some are from QB/McK people but made from a personal account.

**Comment by stichbury** [comment]
Wow, thanks @merelcht that's great. I'll take those and also add the review that Sean gave to my docs changes. Nice!

**Comment by stichbury** [comment]
There's a draft in review now. I haven't published a link here but it's on the Kedro team slack FWIW.

**Comment by stichbury** [comment]
Sent to Eloise to pass onwards to Antidote. 

Possible images. Any preferences? @yetudada ?

1. I've gone with the theme of architecture/framework/regular design: 
* https://unsplash.com/photos/jz137K3sees
* https://unsplash.com/photos/C_cQW1JS99w
* https://unsplash.com/photos/ZmN1uXn7_7g
* https://unsplash.com/photos/4Pc-IqA_6Ro

2. Data-ish theme:
* https://flic.kr/p/SDpjbS
* https://wordpress.org/openverse/image/9cdc3f8d-d77f-4359-b3b6-056e6146e907

3. Boring gift box
* https://wordpress.org/openverse/image/9727cfde-cd7a-4f61-9fd4-f7e3f475cfe5

![33241097510_431b096d6c_q](https://user-images.githubusercontent.com/5180475/204265351-6cecc19f-1935-4d5d-ab80-d784acad5e2f.jpg)

![5097547405_6701529706_b](https://user-images.githubusercontent.com/5180475/204265354-e567ccd2-751a-4f87-9ea6-4130d15515bf.jpg)

![8085629858_be68d12232](https://user-images.githubusercontent.com/5180475/204265355-ec70bb43-e1fb-4183-a195-78ef290e525e.jpg)

![jimmy-nilsson-masth-4Pc-IqA_6Ro-unsplash](https://user-images.githubusercontent.com/5180475/204265318-5483ba3b-a1ca-4b30-b99b-0ded4a7d18aa.jpg)

![andrea-de-santis-jz137K3sees-unsplash](https://user-images.githubusercontent.com/5180475/204265228-244079ff-2e29-4fa6-9fd4-7e653b45daaa.jpg)

![ussama-azam-C_cQW1JS99w-unsplash](https://user-images.githubusercontent.com/5180475/204265272-08f67db1-c9c1-493c-a0a9-4486ba367f47.jpg)

![sergey-kvint-ZmN1uXn7_7g-unsplash](https://user-images.githubusercontent.com/5180475/204265293-28af5c63-3544-4df8-8c75-d1667943f368.jpg)
