### ISSUE TITLE
Two way communication between Kedro-Viz & Framework

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2055]
## Description
- Make Kedro more interactive then just CLI maybe somehow incorporate with Viz.
- New CLI/UI for interactivity with pipeline for "low tech" users
- Full control over Pipeline build (code authoring) in Viz

## Questions

**Comment by yetudada** [comment]
Closed in favour of [#1201](https://github.com/kedro-org/kedro-viz/issues/1201)
