### ISSUE TITLE
load_ipython_extension does not register_magic_function "reload_kedro"

### ISSUE THREAD

**Issue by sfc-gh-mgorkow** [kedro-org/kedro#2060]
## Description
https://github.com/kedro-org/kedro/blob/main/kedro/ipython/__init__.py

If there is no project found, the function does not execute the following line:
`ipython.register_magic_function(magic_reload_kedro, magic_name="reload_kedro")`

This prevents a user from reloading the project.

## Context
How has this bug affected you? What were you trying to accomplish?
I wanted to run kedro_viz in my notebook but were unable to reload the project.

## Steps to Reproduce
1. Start a notebook from outside project folder
2. Run: %reload_ext kedro.ipython 
3. Try running: %reload_kedro testproject/

## Expected Result
Project should be reloaded.

## Actual Result
```
UsageError: Line magic function `%reload_kedro` not found.
```

## Solution:
Move the register_magic_function before the return statement of the function.

**Comment by jmholzer** [comment]
Hey @sfc-gh-mgorkow, thanks for the report.

I've looked into this, it was introduced in #1955, it looks like we didn't catch this case.

I'll prioritise a fix for this.
