### ISSUE TITLE
Upgrade vulnerable wheel and setuptools

### ISSUE THREAD

**Issue by Galileo-Galilei** [kedro-org/kedro#2067]
## Description

Snyk is complaining about ``wheel`` and ``setuptools`` versions pinned by kedro.

![image](https://user-images.githubusercontent.com/29451317/204100081-7a83cf67-ce54-49e2-9fa7-d840d0028901.png)

## Context

My CI fails because Snyk warns about 2 vulnerabilities.

## Steps to Reproduce

Log to snyk and analyse kedro requirements.

## Expected Result

Kedro should not pin vulnerable packages. 

## Solution
1. Upgrade ``wheel>=0.38`` and ``setuptools>=65.5.1``
2. Update the CI to check automatically for vulenrabilities in kedro codebase

**Comment by noklam** [comment]
Hi @Galileo-Galilei, thank you for reporting this. To understand this better, is this issue new or it's just caught by Snyk recently?

I don't think we have Synk enable, may require sometime to get the infrastructure setup and verify ourselves. 

I checked our requirements, currently we have
```pip
wheel
setuptools>=38.0
```

Based on your screenshot, does that mean Synk is suggesting this?
```pip
wheel>=38.0
setuptools>=65.5.1
```
