### ISSUE TITLE
Make return value of session run until dataset consistent

### ISSUE THREAD

**Issue by vivecalindahl-northvolt** [kedro-org/kedro#2106]
## Description
When a dataset is not declared in the data catalog it implicitly is defined as a MemoryDataSet. When I explicitly define the same dataset as a MemoryDataSet in the catalog I expect the same behavior in general. However, when I for instance in a Jupyter notebook run a Kedro sesssion until this dataset as output it gives different behavior: it only returns the dataset when it is implicitly defined. If the dataset is listed in the catalog I get an empty dict as a return value. 

## Possible Implementation
 My preferred behavior is that the session run always returns the MemoryDataSet dataset it runs until, whether it's listed explicitly or not.

**Comment by vivecalindahl-northvolt** [comment]
... Or is this a bug? :)

**Comment by merelcht** [comment]
Closing in favour of https://github.com/kedro-org/kedro/issues/1900
