### ISSUE TITLE
Add /kedro/datasets/* to .gitignore?

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2111]
## Description
I've noticed that `make build-docs` is pulling in all the kedro/datasets now. It means we end up with loads of `__init.py__` files added to the `kedro/datasets` directory, and `git` tries to add these as new files.

## Context
It's a bit annoying but not exactly terminal. Still would be good to fix though...I think?

**Comment by SajidAlamQB** [comment]
This makes sense, will add it in. Also, note `make clean` will remove the `kedro/datasets` directory.

**Comment by SajidAlamQB** [comment]
Fixed in https://github.com/kedro-org/kedro/pull/2112.
