### ISSUE TITLE
Investigate creation of Versioned PartitionedDataSet 

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2115]
## Description
Different users have requested a versioned PartitionedDataSet. We need to investigate how such an implementation works and what's required. 

## Investigation
- Collect all issues/PRs/questions about this 
- Investigate possible next steps and implementation

## Issues opened by users requesting this dataset feature

- [x] https://github.com/kedro-org/kedro/issues/2043

**Comment by astrojuanlu** [comment]
Is this addressed by #521? cc @deepyaman

**Comment by merelcht** [comment]
Yes this will be solved in https://github.com/kedro-org/kedro-plugins/pull/447
