### ISSUE TITLE
Setup Snyk on Kedro

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2121]
## Description
We need to set-up Snyk across the Kedro project. Previously, we used the QuantumBlack Snyk account, but now we'll have to set it up on the LF account. If we can't set it up with LF, we'll have to talk to QB Infosec.

**Comment by stichbury** [comment]
Would it make sense to draft a short blog post about this when we've done it, to go through the advantages of an open source package that uses it and explain why it's a benefit to anyone coming to Kedro to know that we have Snyk deployed. We can then put this out somewhere like internal McK confluence blog or something, if we don't go with making it a full blog post.

**Comment by merelcht** [comment]
I'm not so sure it would. It turned out Snyk and other security scans were already setup by the Linux Foundation, so there wasn't anything left to do from our side. We could link people to this page in the docs if we want: https://lfx.linuxfoundation.org/tools/security/ But I don't think there's enough to say about this to write a blog post.

**Comment by merelcht** [comment]
The security dashboard of LF can be found here: https://security.lfx.linuxfoundation.org/#/
