### ISSUE TITLE
Add `kedro-datasets` in `kedro[all]`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2128]
### Description
Add `kedro-datasets` in `kedro[all]` to make sure datasets are installed when doing `pip install kedro[all]`

### Implementation
- Check if it's possible not to pin `kedro-datasets` 
- Check if implementing this doesn't cause a circular dependency issue.

**Comment by idanov** [comment]
Wouldn't that cause a cyclic dependency? This will also create a pin of `kedro` versions to specific `kedro-datasets` version.

**Comment by astrojuanlu** [comment]
Good point @idanov 👍🏽 better not to do that

**Comment by astrojuanlu** [comment]
Wait, are you referring to my proposal of making `kedro[all]` depend on `kedro-datasets[all]`, or the original intent of making `kedro[all]` depend on `kedro-datasets`?

**Comment by noklam** [comment]
Should we still do this? Though I am not particular clear about the concern.

Is there benefit of `pip install kedro[all]` over `pip install kedro-dataset` which includes kedro already?

`kedro[all]` will also included `docs` which I find weird as we deprecated kedro lint. Effectively `pip install kedro[all` = `pip install kedro kedro-datasets`.

**Comment by astrojuanlu** [comment]
And one more drawback: we have to add kedro[all] to our installation instructions, explain users when to pick each... Don't think it's worth it at this point

**Comment by merelcht** [comment]
Briefly discussed this in sprint planning and since no users have asked for this, we've decided to not do it.
