### ISSUE TITLE
Rename all mentions of `DataSet` to `Dataset`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2129]
### Description
Rename `DataSet` to `Dataset` in `kedro`:
- [x] Remove aliases from `core.io` datasets: https://github.com/kedro-org/kedro/pull/3147
- [x] Replace any mentions of `DataSet` in `.py` files: https://github.com/kedro-org/kedro/pull/3147
- [x] Replace any mentions of `DataSet` in `.md` (docs) files: https://github.com/kedro-org/kedro/pull/3148
- [x] Replace any other mentions of `DataSet` in the project: https://github.com/kedro-org/kedro/pull/3147

Rename `DataSet` to `Dataset` in `kedro-datasets` -> This is for `kedro-datasets` `2.0.0` so moving it in a separate issue: https://github.com/kedro-org/kedro/issues/3159

Other:
- [x] Replace any mentions of `DataSet` in docs in all repos: `kedro-starters`: https://github.com/kedro-org/kedro-starters/pull/155, `kedro-plugins`: https://github.com/kedro-org/kedro-plugins/pull/384
- [x] Replace any mentions of `DataSet` in tests in all repos: `kedro-starters`: https://github.com/kedro-org/kedro-starters/pull/155, `kedro-plugins`: https://github.com/kedro-org/kedro-plugins/pull/384
- [x] [Graphic in the Data Catalog section on the website](https://kedro.org/#features): https://github.com/kedro-org/kedro-website/pull/167
- [x] On `main`: add messaging about move of datasets + rename: https://github.com/kedro-org/kedro/pull/3155
- [x] Any mentions in `kedro-viz`: https://github.com/kedro-org/kedro-viz/pull/1572

**Comment by astrojuanlu** [comment]
I'm so happy this is within scope 😬 should we transfer this to kedro-plugins? How do we want to handle the breaking change?

**Comment by merelcht** [comment]
@astrojuanlu I'd prefer to keep it here so it can be part of the milestone. Milestones unfortunately can't be shared between repos. This change will be part of the `0.19.0` release.
