### ISSUE TITLE
Unpickling issues when following "How to integrate Amazon SageMaker into your Kedro pipeline" from Kedro Docs

### ISSUE THREAD

**Issue by GuidoHeijden** [kedro-org/kedro#2131]
## Description
I have attempted to run the default pipeline from the spaceflight kedro starter with SageMaker integration exactly as described in https://kedro.readthedocs.io/en/stable/deployment/aws_sagemaker.html . The pipeline starts out fine, but fails on the node that runs the SageMaker training job. The SageMaker training job fails due to an error when unpickling the training data located in S3. The training data was pickled as a `pandas.DataFrame`. 

I believe the error is caused by mismatched `pandas` versions when saving the training data on my local machine and when reading the data in AWS SageMaker training. This reason was also mentioned as a cause for unpickling errors in a different case on StackOverflow: https://stackoverflow.com/questions/68625748/attributeerror-cant-get-attribute-new-block-on-module-pandas-core-internal .

Suggested solution: update the Kedro Docs page on SageMaker integration to not use pickle for storing the training data in AWS. Rather than pickling, store the training data as parquet. This prevents having to match the local python environment with that in AWS SageMaker in order to pickle and unpickle without issues.

## Context
The bug caused made the Kedro Docs instructions for SageMaker integration incompatible with the current version of Kedro. This prevented me from quickly seeing how to integrate SageMaker in my Kedro pipeline.

## Steps to Reproduce
1. Create a new conda environment for python 3.7 with Kedro 0.18.3 installed via pip
2. Follow the instructions in Kedro Docs up to and including running the pipeline: https://kedro.readthedocs.io/en/stable/deployment/aws_sagemaker.html#run-the-project
3. An error message is returned during the run of node 4 (called "sagemaker_train_node"). The error is also shown in the AWS SageMaker training job logs (located in CloudWatch).

## Expected Result
The pipeline should run a SageMaker training job that trains a SKlearn LinearRegression model in AWS.

## Actual Result
The SageMaker training job fails when trying to unpickle the training data set (`X_train.pickle`).

> Note: the roughly one hour difference in the error logs are likely the result of different timezone configurations in AWS and on my local machine.

Local Kedro error log message:
``` 
2022-12-15 12:34:27,023 - kedro.pipeline.node - ERROR - Node 'sagemaker_train_node: train_model_sagemaker([X_train@path,params:sklearn_estimator_kwargs]) -> [model_path]' failed with error: 
Error for Training job sagemaker-scikit-learn-2022-12-15-11-31-41-560: Failed. Reason: AlgorithmError: framework error: 
Traceback (most recent call last):
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_trainer.py", line 84, in train
    entrypoint()
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/training.py", line 39, in main
    train(environment.Environment())
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/training.py", line 35, in train
    runner_type=runner.ProcessRunnerType)
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_training/entry_point.py", line 100, in run
    wait, capture_error
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_training/process.py", line 291, in run
    cwd=environment.code_dir,
  File "/miniconda3/lib/python3.7/site-packages/sagemaker_training/process.py", line 208, in check_error
    info=extra_info,
sagemaker_training.errors.ExecuteUserScriptError: ExecuteUserScriptError:
ExitCode 1
ErrorMessage ""
Command "/miniconda3/bin/python sagemaker_entry_point.py"
```

AWS SageMaker training job error log message:
```
Invoking script with the following command:
/miniconda3/bin/python sagemaker_entry_point.py

"Traceback (most recent call last):
  File ""sagemaker_entry_point.py"", line 56, in <module>
    main()
  File ""sagemaker_entry_point.py"", line 44, in main
    X_train = _unpickle(data_path / ""X_train.pickle"")
  File ""sagemaker_entry_point.py"", line 19, in _unpickle
    return pickle.load(f)"

AttributeError: Can't get attribute 'new_block' on <module 'pandas.core.internals.blocks' from '/miniconda3/lib/python3.7/site-packages/pandas/core/internals/blocks.py'>

"2022-12-15 11:33:51,524 sagemaker-containers ERROR    Reporting training FAILURE"

"2022-12-15 11:33:51,524 sagemaker-containers ERROR    framework error: "

"Traceback (most recent call last):
  File ""/miniconda3/lib/python3.7/site-packages/sagemaker_containers/_trainer.py"", line 84, in train
    entrypoint()
  File ""/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/training.py"", line 39, in main
    train(environment.Environment())
  File ""/miniconda3/lib/python3.7/site-packages/sagemaker_sklearn_container/training.py"", line 35, in train
    runner_type=runner.ProcessRunnerType)
  File ""/miniconda3/lib/python3.7/site-packages/sagemaker_training/entry_point.py"", line 100, in run
    wait, capture_error
  File ""/miniconda3/lib/python3.7/site-packages/sagemaker_training/process.py"", line 291, in run
    cwd=environment.code_dir,
  File ""/miniconda3/lib/python3.7/site-packages/sagemaker_training/process.py"", line 208, in check_error
    info=extra_info,"

sagemaker_training.errors.ExecuteUserScriptError: ExecuteUserScriptError:

ExitCode 1

"ErrorMessage """""

"Command ""/miniconda3/bin/python sagemaker_entry_point.py"""

ExecuteUserScriptError:

ExitCode 1

"ErrorMessage """""

"Command ""/miniconda3/bin/python sagemaker_entry_point.py"""
```

## Your Environment
Local environment:
* Kedro version used (`pip show kedro` or `kedro -V`): 1.18.3
* Python version used (`python -V`): 3.7
* Operating system and version: Windows 10 Pro - 21H2 - ‎26/‎09/‎2022 - 19044.2251 - Windows Feature Experience Pack 120.2212.4180.0
* Terminal: bash

SageMaker SKlearn estimator environment (derived from AWS logs and specified in Kedro docs):
* Python version used (displayed in AWS error log message): 3.7
* SKlearn framework version: 0.23-1

**Comment by GuidoHeijden** [comment]
I fixed the issues using the following changes

Change `./conf/sagemaker/catalog` to:
```
X_train@parquet:
  type: pandas.ParquetDataSet
  filepath: ${s3.train_path}/X_train.pq

X_train@path:
  type: MemoryDataSet
  data: ${s3.train_path}/X_train.pickle

y_train:
  type: pandas.ParquetDataSet
  filepath: ${s3.train_path}/y_train.pq
```

Change the `split_data` function in `./src/kedro_tutorial/pipelines/data_science/nodes.py` as shown below. The change entails returning `y_train` as a `pandas.DataFrame` rather than a `pandas.Series`, such that it can be saved as parquet.
```
def split_data(data: pd.DataFrame, parameters: Dict) -> Tuple:
    """Splits data into features and targets training and test sets.

    Args:
        data: Data containing features and target.
        parameters: Parameters defined in parameters/data_science.yml.
    Returns:
        Split data.
    """
    X = data[parameters["features"]]
    y = data["price"]
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=parameters["test_size"], random_state=parameters["random_state"]
    )
    return X_train, X_test, pd.DataFrame(y_train), y_test
```

Change the `create_pipeline` function in `./src/kedro_tutorial/pipelines/data_science/nodes.py` to:
```
def create_pipeline(**kwargs) -> Pipeline:
    return pipeline(
        [
            node(
                func=split_data,
                inputs=["model_input_table", "params:model_options"],
                outputs=["X_train@parquet", "X_test", "y_train", "y_test"],
            ),
            node(
                func=train_model_sagemaker,
                inputs=["X_train@path", "params:sklearn_estimator_kwargs"],
                outputs="model_path",
                name="sagemaker_train_node",
            ),
            node(untar_model, inputs="model_path", outputs="regressor"),
            node(
                func=evaluate_model,
                inputs=["regressor", "X_test", "y_test"],
                outputs=None,
            ),
        ]
    )
```

Lastly, change the `main` function in `./src/kedro_tutorial/sagemaker_entry_point.py` to:
```
def main():
    """The main script entry point which will be called by SageMaker
    when running the training job
    """
    parser = _get_arg_parser()
    args = parser.parse_args()

    data_path = Path(args.train)
    # X_train = _unpickle(data_path / "X_train.pickle")
    # y_train = _unpickle(data_path / "y_train.pickle")
    X_train = pd.read_parquet(data_path / "X_train.pq")
    y_train = pd.read_parquet(data_path / "y_train.pq")

    regressor = LinearRegression()
    regressor.fit(X_train, y_train)

    model_dir = Path(args.model_dir)
    _pickle(model_dir / "regressor.pickle", regressor)
```

This solution allows me to run all 7 nodes in the pipeline succesfully using `kedro run --env sagemaker`. Note that the SKlearn LinearRegression model is still stored as a pickled object in S3, but seems to work fine when loaded again on my local system. It could be that this unpickling fails to work sometime in the future as well. You could perhaps store the model as ONNX, but I did not look into this myself.

**Comment by GuidoHeijden** [comment]
Oops I accidently closed the bug by misclicking the comment button... I reopened it to fix my mistake

**Comment by astrojuanlu** [comment]
The code alluded in this page was removed and now we're linking to https://github.com/getindata/kedro-sagemaker, so this issue is no longer relevant. Closing.
