### ISSUE TITLE
Support for multiple conf_sources

### ISSUE THREAD

**Issue by jptissot** [kedro-org/kedro#2136]
## Description
I am writing multiple Kedro projects for a data processing engine that share some configuration. I currently have to maintain a custom config loader that look in a "common" folder in addition to the conf folder provided by kedro.

## Context
This change is important because it would allow someone to easily have shared configuration between kedro projects.

**Comment by merelcht** [comment]
Hi @jptissot thanks for creating this issue! Could you provide some more information? Could you share your custom config loader? And do you perhaps have suggestions on how you would like this feature to work?

**Comment by jptissot** [comment]
Thanks for the reply @merelcht this is still on my radar, been off of work the past few weeks but will try to circle back next week. I think I have an interesting use case for Kedro and have some questions / ideas on how to achieve them.

**Comment by merelcht** [comment]
I'm closing this issue for now. Feel free to re-open if there's more context that helps us understand the request better @jptissot
