### ISSUE TITLE
Improve Kedro-Viz documentation for Experiment Tracking

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2144]
This issue is to track the work on the third and final page of the Kedro-Viz section of docs which discusses Experiment Tracking.: https://kedro.readthedocs.io/en/stable/visualisation/experiment_tracking.html

There are a raft of changes/improvements coming and this ticket should cover any rework of the docs to include those.

I suggest that we revise the page to make it more of a tutorial in experiment tracking (maybe taking the Spaceflights starter and extending, but it could be a separate example). We could potentially create a separate page for information about using the experiment tracking feature, and keep the tutorial about it separate. Let's see how much copy there is as the page is currently too long.

**Comment by stichbury** [comment]
Tagging @NeroOkwa for visibility and extra information/feedback

**Comment by stichbury** [comment]
Also to do:

* Remove the [page about experiment tracking from the logging section ](https://kedro.readthedocs.io/en/stable/logging/experiment_tracking.html) and consolidate into one page
* Better introduction to tracking as part of the example, as per this comment https://github.com/kedro-org/kedro/pull/2061#discussion_r1061386622

**Comment by tynandebold** [comment]
Highest priority items:

- Ensure that the spaceflights tutorial works without issue. There was a problem with Plotly where the charts weren't rendering (relates to https://github.com/kedro-org/kedro-viz/issues/1205).
- There are actually two pages for exp. tracking documentation. We should only have one.
    - Copy the contents of the second, smaller page into the first and then delete that content from the second page.
- Mention parallel coordinate and time-series plots.

**Comment by tynandebold** [comment]
@stichbury the related PR (https://github.com/kedro-org/kedro/pull/2193) is now closed. What do you want to do with this issue? Is there more to do or shall we close it?

**Comment by stichbury** [comment]
We can close it. Thanks @tynandebold!
