### ISSUE TITLE
Unable to use Kedro with great-expectations

### ISSUE THREAD

**Issue by DhavalThkkar** [kedro-org/kedro#2151]
## Description
I am using Kedro to create a pipeline for ETL purposes and column specific validations are being done using Great-Expectations. There is a hooks.py file listed in Kedro documentation [here](https://kedro.readthedocs.io/en/stable/hooks/examples.html#add-data-validation). This hook is registered as per the instructions mentioned on Kedro-docs.

Unable to use Kedro with Great-Expectations

## Context
How has this bug affected you? What were you trying to accomplish?

I am trying to create expectations for any data that is going to be loaded into the kedro pipelines for a project which I want to orchestrate using Prefect/Airflow

## Steps to Reproduce

1. Created a kedro project using `kedro new`, project name `ecom_analytics`
2. Stored the datasets in `data/01_raw` folder called `dataset_raw.csv` & `dataset_validate.csv`
3. Initialize great_expectations project using `great_expectations init`
4. Create a new datasource using `great_expectations datasource new`. The name I added was `main_datasource`
5. Create a new expectation using `great_expectations suite new`. This expectation is called `data.raw` using data assistant
6. Edited the great_expectations suite using `great_expectations suite edit data.raw`
7. Created the catalog entries for the datasets in `conf/catalog.yml`
8. Added the Great expectations `hooks.py` given in the kedro documentation and registered the hook on `settings.py` file
9. Tried `kedro viz --autoreload`. This works to view the visualisation

## Expected Result
All the datasets with their required expectations should be validated using the suite given for the pipeline

## Actual Result
```
│ /opt/conda/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_dat │
│ a_context.py:758 in get_batch                                                                    │
│                                                                                                  │
│    755 │   │   else:                                                                             │
│    756 │   │   │   data_asset_type = arg3                                                        │
│    757 │   │   batch_parameters = kwargs.get("batch_parameters")                                 │
│ ❱  758 │   │   return self._get_batch_v2(                                                        │
│    759 │   │   │   batch_kwargs=batch_kwargs,                                                    │
│    760 │   │   │   expectation_suite_name=expectation_suite_name,                                │
│    761 │   │   │   data_asset_type=data_asset_type,                                              │
│                                                                                                  │
│ /opt/conda/lib/python3.9/site-packages/great_expectations/data_context/data_context/abstract_dat │
│ a_context.py:867 in _get_batch_v2                                                                │
│                                                                                                  │
│    864 │   │   │   expectation_suite = self.get_expectation_suite(expectation_suite_name)        │
│    865 │   │                                                                                     │
│    866 │   │   datasource = self.get_datasource(batch_kwargs.get("datasource"))  # type: ignore  │
│ ❱  867 │   │   batch = datasource.get_batch(  # type: ignore[union-attr]                         │
│    868 │   │   │   batch_kwargs=batch_kwargs, batch_parameters=batch_parameters                  │
│    869 │   │   )                                                                                 │
│    870 │   │   if data_asset_type is None:                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Datasource' object has no attribute 'get_batch'
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.4
* Python version used (`python -V`): 3.9.12
* Operating system and version: alpine docker container

**Comment by ankatiyar** [comment]
Hey @DhavalThkkar, check out the **latest** version of the [Hooks examples documentation](https://kedro.readthedocs.io/en/latest/hooks/examples.html) which now has the [`great-expectations` example using v3 API](https://kedro.readthedocs.io/en/latest/hooks/examples.html#v3-api) (added in PR #2172) which should work if you're using `great-expectations v0.13.x`.
