### ISSUE TITLE
Drop support for Python 3.7 end of year 2023

### ISSUE THREAD

**Issue by idanov** [kedro-org/kedro#2158]
## Description

Python's end of life for version 3.7 ends in June 2023 so we should be prepared, since a lot of packages might stop supporting 3.7, which will make our support for 3.7 more difficult. Therefore I would suggest we drop official support for 3.7 before June, and possibly with the release of 0.19. As a benefit, we can start using some nice features, as listed [here](https://realpython.com/python38-new-features/). I am especially interested in the walrus operator, the improved support for typing, performance optimisations and last, but not least, `importlib.metadata` which can be super helpful for checking for installed versions of other Python packages (think of `kedro-viz`, `kedro-datasets` and other plugin compatibilities with `kedro`).

## Context

To make sure we move along in pace with the rest of the ecosystem in Python.

## Possible Implementation

Removing Python 3.7 support with Kedro 0.19.0.

## Possible Alternatives

Waiting for Kedro 0.20.0 to drop Python 3.7 support.

**Comment by astrojuanlu** [comment]
+1 to removing Python 3.7 support with Kedro 0.19.0. But I think we should communicate this in the 0.18.x releases.

**Comment by astrojuanlu** [comment]
> it looks like 3.7 is reaching end-of-life. Unless another security release happens in June, 3.7.17 will be the final release of Python 3.7.

https://mail.python.org/archives/list/python-announce-list@python.org/message/XEQ7I3YDDXJJA3JSARTHFDCBVXD6CPHT/

**Comment by merelcht** [comment]
Done in https://github.com/kedro-org/kedro/pull/3060

**Comment by merelcht** [comment]
This isn't done for `kedro-dataset` yet right?

**Comment by astrojuanlu** [comment]
As far as I understand 3.7 was dropped already https://github.com/kedro-org/kedro-plugins/pull/392 what we have to do now for kedro-datasets is drop 3.8 https://github.com/kedro-org/kedro-plugins/issues/404

**Comment by lrcouto** [comment]
> As far as I understand 3.7 was dropped already [kedro-org/kedro-plugins#392](https://github.com/kedro-org/kedro-plugins/pull/392) what we have to do now for kedro-datasets is drop 3.8 [kedro-org/kedro-plugins#404](https://github.com/kedro-org/kedro-plugins/issues/404)

We left kedro-datasets to be done on a separate PR, since it depended on the release.

**Comment by astrojuanlu** [comment]
I stand corrected, thanks @lrcouto 👍🏽

**Comment by merelcht** [comment]
This is completed now https://github.com/kedro-org/kedro-plugins/pull/419 has been merged 🎉
