### ISSUE TITLE
Define user journeys for manual testing

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#2160]
## Description

Each Kedro component should have documented user jouneys, broken down into individual steps, for the purposes of manual testing.

## Context

This follows from the team discussion on 16/12/22. 

The bug reported in #2060  was introduced by the changes made in #1955 - highlighting an oversight in our automated testing. However, for certain components (like the interactive workflow) it can be difficult to set up automated e2e tests. As a result, we should be testing these components manually when making changes to ensure that the code still behaves as expected. 

Defining these user journeys will:
- Define the expected behaviour, ensuring we catch bugs like that in the example above
- Allow for consistency and completeness when manually testing (for both code authors and reviewers)
- Provide the foundation for outlining e2e tests, should we decide to automate some/all of the use cases

## Next steps

Due to the scope spanning most (if not all) of the codebase, the next steps would be to identify and prioritise the relevant components, and building the user journeys section by section under individual issues/tickets.

**Comment by astrojuanlu** [comment]
Useful resources

Developer Journey Maps https://devrelbook.substack.com/p/the-developer-journey-map, https://www.devrel.agency/developerjourney

![image](https://github.com/kedro-org/kedro/assets/316517/d0ef9a4f-5364-4c52-a020-9a9dbcc4514e)

DX Audits https://dev.to/theworstdev/the-developer-advocates-guide-to-addressing-product-friction-1p4j

![image](https://github.com/kedro-org/kedro/assets/316517/99ce8003-fb52-40fe-86f8-02f82f1dab5c)

**Comment by merelcht** [comment]
We haven't really run into similar problems throughout the 18 series so I'd suggest closing this as not planned.

**Comment by astrojuanlu** [comment]
Agreed
