### ISSUE TITLE
Evaluate Bowler as an alternative to Rope

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#2173]
## Description
I came across [Bowler](https://github.com/facebookincubator/Bowler), safe code refactoring for modern Python, and I wondered if it would be a suitable alternative to Rope which is used in our micro-packaging workflow? While Rope is fantastic on all fronts, its GNU Lesser General Public v3.0 License shows up in Kedro's license dependency scan and has to be explained. 

This task would be to evaluate if _at all_ Bowler could replace Rope and you would have to make a recommendation that included the pros and cons of the changes. 

Here is the [documentation for Bowler](https://pybowler.io/).

**Comment by merelcht** [comment]
Bowler hasn't been updated since September 2020, so it doesn't look like a good alternative.
