### ISSUE TITLE
Add documentation explaining how to load credentials from environment variables using OmegaConfLoader

### ISSUE THREAD

**Issue by jmholzer** [kedro-org/kedro#2188]
## Description
In #2178 we are adding the ability to load credentials from environment variables via `OmegaConfLoader`. We should add documentation that helps our users find this feature and use it.

## Context
This is a much-requested and very useful feature, so we should help users discover it as easily as possible.

**Comment by merelcht** [comment]
Resolved in https://github.com/kedro-org/kedro/pull/2256
