### ISSUE TITLE
The DryRunner example in the document does not work

### ISSUE THREAD

**Issue by everdark** [kedro-org/kedro#2201]
## Description

https://kedro.readthedocs.io/en/0.18.4/nodes_and_pipelines/run_a_pipeline.html#custom-runners

The example implementation of a `DryRunner` is not working, when run with:

```bash
kedro run --runner=<pkg-name>.runner.DryRunner
```

the following error occurs:

```
TypeError: _run() takes from 3 to 4 positional arguments but 5 were given
```

## Context

I would like to have a working example of a dry-runner implementation in the documentation.

## Steps to Reproduce

Simply follow the document: 
https://kedro.readthedocs.io/en/0.18.4/nodes_and_pipelines/run_a_pipeline.html#custom-runners

## Expected Result

The runner should work as documented.

## Actual Result

```
TypeError: _run() takes from 3 to 4 positional arguments but 5 were given
```

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.4
* Python version used (`python -V`): 3.9.15
* Operating system and version: macOS 13.1

**Comment by merelcht** [comment]
Thanks for flagging this @everdark. We'll put this on our backlog, but would also very much welcome a PR with a fix!

**Comment by merelcht** [comment]
Actually, this turned out to be a very easy fix so I've already opened a PR for it: https://github.com/kedro-org/kedro/pull/2222 🙂

**Comment by everdark** [comment]
The fix works for me. :)
