### ISSUE TITLE
Update the 'Deployment to Databricks cluster' documentation

### ISSUE THREAD

**Issue by jmholzer** [kedro-org/kedro#2203]
## Description
The [section](https://kedro.readthedocs.io/en/stable/deployment/databricks.html) of our documentation dealing with deployment to Databricks needs some updating to reflect a few changes on Databricks' side:
1. A different UI
2. Runtime version 7.1 is no longer available
3.  Worker type is no longer available

## Context
Deployment on Databricks is important to our users, we should have an accurate guide for it.

**Comment by yetudada** [comment]
I'll link this ticket to #2185. Thanks for spotting this @jmholzer
