### ISSUE TITLE
Tweak logging to improve UX

### ISSUE THREAD

**Issue by antonymilne** [kedro-org/kedro#2205]
The milestone [Improve the setup of logging](https://github.com/kedro-org/kedro/milestone/5) is complete! However, there are still a couple of minor issues we should try to resolve before 0.19.

- [x] #2206
- [x] #2277
- [x] #2429
- [x] #2207
- [x] #2281
- [x] #2208
- [x] #2383
- [x] #2426
- [x] #2520 
- [x] #2428

Reminder about how logging works:
1. `LOGGING = _ProjectLogging()` is called to set up the framework-side logging configuration given in `default_logging.yml`
2. `configure_project` called by `bootstrap_project` imports settings.py (so users can currently "unofficially" insert code there e.g. to disable rich tracebacks)
3. session is created, and project-side logging.yml loads (if it exists) by `session._setup_logging`
4. if operating parallel runner with spawned subprocess, `configure_logging` is called in each subprocess by `_bootstrap_subprocess`

**Comment by merelcht** [comment]
All tasks have now been completed.
