### ISSUE TITLE
Consider using rich-click or typer

### ISSUE THREAD

**Issue by antonymilne** [kedro-org/kedro#2210]
**Alternative mentioned below: https://github.com/tiangolo/typer, which is based on click and uses rich if installed. Would be good to understand better what are the pros/cons of migrating and whether it would be worth the effort.**

---

Originally written by @datajoely in #1464.

> **Warning**. We need to consider whether this is actually a good change before implementing it. It would solve #1752 but should be discussed with @deepyaman and carefully tested to see if it's an improvement overall.

We could leverage the 3rd party [rich-click](url) package:
  - The [rich-click](https://github.com/ewels/rich-click) package is a small but actively maintained library which has reached v1.3.x at the time of writing.
  - It is a drop-in replacement for click, all you have to do in theory is `import rich_click as click`
  - If you want to use it piecemeal you can just provide the classes as arguments to the command/group decorators [like I do here](https://github.com/datajoely/kedro-rich/blob/bc0313f0bd909a52abbcd730a4995d211082dded/kedro_rich/rich_cli.py#L84).
  - The main benefit of this library is the fact we get much more readable help messages, like so:
  ![image](https://user-images.githubusercontent.com/35801847/164470373-aefc10ea-b7ff-481a-abe6-753e4c85dbfe.png)

**Comment by MatthiasRoels** [comment]
Why not use Typer instead? https://github.com/tiangolo/typer

**Comment by datajoely** [comment]
Good push - I was thinking the same this week!

**Comment by datajoely** [comment]
Here's how we'd migrate 
https://typer.tiangolo.com/tutorial/using-click/

**Comment by astrojuanlu** [comment]
I think rather than pursuing Typer to solve #1752, we should make rich optional #2928 and keep Kedro as lean as possible (hence avoid adding yet another dependency).

**Comment by astrojuanlu** [comment]
We're proceeding with https://github.com/kedro-org/kedro/issues/2928
