### ISSUE TITLE
Package config as a `tar.gz`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2212]
## Description
Related to https://github.com/kedro-org/kedro/issues/2146. Ideally https://github.com/kedro-org/kedro/issues/2146 is completed first.

## Context
When packaging the kedro project, currently config isn't included. In this task, add functionality to package the config in a separate `tar.gz` file, inside the same `dist/` directory.

**Comment by datajoely** [comment]
Can I pitch we do `.zip` so that it's more accessible to novice and Windows users?

**Comment by merelcht** [comment]
In what way would `.zip` be more accessible? Users don't have to zip or unzip the config manually, so does it matter if it's zip or tar? It also seems that tar support is now better on windows: https://learn.microsoft.com/en-us/virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows

**Comment by datajoely** [comment]
From the linked article that's still only possible via Powershell - enterprise machines are locked down and it may be disabled. in all sorts of ways and Zips are by far the path of least resistance for both novice users and corporate environments.

**Comment by merelcht** [comment]
But my point is that Kedro will be handling the zipping and unzipping so why would it matter for the user what type we're working with?

**Comment by datajoely** [comment]
ah gotcha - I thought this is related to the deployment model we've discussed several times, something like:

`kedro run --config conf.zip`

**Comment by merelcht** [comment]
> ah gotcha - I thought this is related to the deployment model we've discussed several times, something like:
> 
> `kedro run --config conf.zip`

So that would be: https://github.com/kedro-org/kedro/issues/2146

**Comment by noklam** [comment]
> But my point is that Kedro will be handling the zipping and unzipping so why would it matter to the user what type we're working with?

Just thinking more about this after today's presentation. How would the user inspect the config file? I imagine the way of distribution is giving a 1. kedro package + 2. config. It would still work with `kedro run --config` but I think it's also common to inspect the config, particularly if something isn't running correctly.

**Comment by merelcht** [comment]
Closed by https://github.com/kedro-org/kedro/pull/2395
