### ISSUE TITLE
Slack link not working

### ISSUE THREAD

**Issue by gaetansnl** [kedro-org/kedro#2215]
Hello,
The Slack link isn't working
![image](https://user-images.githubusercontent.com/8348807/212841028-c43bbcba-0f95-4133-a284-8f0138cb17c6.png)

**Comment by yetudada** [comment]
Thank you so much for flagging this @gaetansnl! 

I need to double-check, where did you find this link so we can update it? 

Please use this link in the meanwhile: https://join.slack.com/t/kedro-org/shared_invite/zt-1eicp0iw6-nkBvDlfAYb1AUJV7DgBIvw

**Comment by stichbury** [comment]
Hi @gaetansnl and thanks for your report. @yetudada and I were replying at the same time. The issue is that the link to slack.kedro.org has expired. @tynandebold is looking into it.

**Comment by tynandebold** [comment]
This has been fixed.

**Comment by astrojuanlu** [comment]
Weird, this happened again with another user half an hour ago. I unfortunately don't have the full context, they just sent an screenshot with a "this link is no longer active" link without showing the full URL. In the end, I shared the updated invite and they were able to join.

**Comment by stichbury** [comment]
That's really odd -- I wonder if they loaded the page with the link to Slack a while ago and it hadn't refreshed before they followed the link, so they went to the old one. Certainly we seem to be OK in incognito now, but one to keep an eye upon.

@astrojuanlu has suggested we look into https://communityinviter.com/ as well (just fyi @tynandebold)
