### ISSUE TITLE
use custom dataset from external repository

### ISSUE THREAD

**Issue by asafalina** [kedro-org/kedro#2221]
## Description
I have an existing kedro project, and I have a separate repository (python package) with several private custom kedro datasets.
Is it possible to incorporate those custom kedro datasets in the existing project? and if so, how?
It would be ideal if I could simply install the external python package, package which contains the custom kedro datasets, and that immediately I would be able to use them from within my kedro project (use them in the `catalog.yaml` file for example).
I need these custom datasets to be available for multiple kedro projects. Therefore I'm looking for such solution (otherwise, I would simply put these custom kedro datasets in my single kedro project, and maintain them inside that project).

I know that kedro is planning on putting the supported datasets in a [different project](https://github.com/kedro-org/kedro-plugins) than kedro, however I wonder if its possible to support another project, private one, and if so, then how.

## Context
I'm planning on having several unrelated kedro projects, and that those projects will import the custom kedro datasets from an external package/repository.
Therefore it would be best if I could maintain those custom kedro datasets under a single repo, instead of maintaining them under different kedro projects.

**Comment by deepyaman** [comment]
> It would be ideal if I could simply install the external python package, package which contains the custom kedro datasets, and that immediately I would be able to use them from within my kedro project (use them in the catalog.yaml file for example).

You can do exactly this! For example, if you can install `pip install asafalinas-package` and then `from asafalinas_package.datasets import AsafalinasDataset`, you can also create a catalog entry:

```yaml
asafalinas_dataset:
  type: asafalinas_package.datasets.AsafalinasDataset
  filepath: whatever
```

Try it out, and let us know if you run into any issues!

**Comment by asafalina** [comment]
@deepyaman Thanks! simple and clean, works perfectly.
