### ISSUE TITLE
Docs builds are failing on RTD

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2226]
It was good while it lasted, but the docs builds are failing again.

[This build, 3 days ago on 16th Jan](https://readthedocs.org/projects/kedro/builds/19180216/) seems to be the first failing build but I can't find any reason for that in terms of the change itself, which was probably [this merged PR](https://github.com/kedro-org/kedro/commit/ed44722571dfac85a9c7b37f2502554e64378340).

Please could someone with more experience than me in understanding the runes take a look? I'm happy to help resolve!

**Comment by merelcht** [comment]
It looks like these three things are making it fail:
```
/home/docs/checkouts/readthedocs.org/user_builds/kedro/envs/latest/lib/python3.7/site-packages/kedro/extras/datasets/json/json_dataset.py:docstring of kedro.extras.datasets.json.json_dataset.JSONDataSet:12: WARNING: Unexpected indentation.
/home/docs/checkouts/readthedocs.org/user_builds/kedro/envs/latest/lib/python3.7/site-packages/kedro/extras/datasets/json/json_dataset.py:docstring of kedro.extras.datasets.json.json_dataset.JSONDataSet:13: WARNING: Block quote ends without a blank line; unexpected unindent.
/home/docs/checkouts/readthedocs.org/user_builds/kedro/envs/latest/lib/python3.7/site-packages/kedro/extras/datasets/spark/spark_hive_dataset.py:docstring of kedro.extras.datasets.spark.spark_hive_dataset.SparkHiveDataSet:9: WARNING: Bullet list ends without a blank line; unexpected unindent.
```

**Comment by astrojuanlu** [comment]
See https://github.com/kedro-org/kedro/pull/2228

**Comment by astrojuanlu** [comment]
Builds back to green 🟢 https://readthedocs.org/projects/kedro/builds/19228189/
