### ISSUE TITLE
Add validation to node tags

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#2241]
## Description
Currently we do not validate or restrict the format of tags that can be added to nodes. This is inconsistent with other user-defined values. As part of #2014 it was agreed that tags should be subject to the same constraints as node names (see: https://github.com/kedro-org/kedro/blob/main/kedro/pipeline/node.py#L102)

**Comment by merelcht** [comment]
Completed in https://github.com/kedro-org/kedro/pull/3314
