### ISSUE TITLE
Add node to the dataset hooks

### ISSUE THREAD

**Issue by AntonyMilneQB** [kedro-org/kedro#2258]
## Description

Here's the current behaviour of hooks when a node is run:
1. For each input dataset:
    1.  run `before_dataset_loaded` hook
    2. load dataset
    3. run `after_dataset_loaded` hook
4. Run `before_node_run` hook
5. Run node
6. Run `after_node_run` hook
7.  For each output dataset:
    1.  run `before_dataset_saved` hook
    2. load dataset
    3. run `after_dataset_saved` hook

The dataset hooks are quite sparse in terms of arguments: they only have `dataset_name` and `data` (apart from `before_dataset_loaded`, which obviously doesn't have `data` available yet). We should add `node` to these hook specifications.

This change has been discussed before in the context of W&B. It's a trivial change in terms of code, but does increase the API surface so should be given due consideration.

> **Note**. Both `_run_node_sequential` and `_run_node_async` need to be modified similarly here.

## Context
I've now seen about five independent cases in which dataset hooks require the context of the `node`, most recently @DavidRoschewitzQB. The current workaround is something like this:
```
class Hooks:
    @hook_impl
    def after_node_run(self, node: Node) -> None:
        self.node = node

    @hook_impl
    def before_dataset_saved(self, dataset_name: str) -> None:
        # use self.node
```

It would be much cleaner to just make `node` an argument to the dataset hooks instead.

Here's some rough pseudocode of where it would be useful for W&B. Other examples I've seen are along similar lines (mlflow artifactory, profiling hooks, rich dataset loading/saving hooks).
```
class WandBHooks:
    def __init__(self):
        self.wandb_nodes = {} # dict mapping node name to set of node outputs

    @hook_spec
    def before_dataset_loaded(node):
        if node.name not in wandb_nodes:
            wandb.init(name=node.name)
            self.wandb_nodes[node.name] = set(node.outputs)

    def after_dataset_saved(dataset_name, data, node):
        self.wandb_nodes[node.name].remove(dataset_name)
        wandb.log_artififact(data)
        if not self.wandb_nodes[node.name]: # all outputs have been written
            wandb.finish(name=node.name)
```

## Possible Alternatives
New `before_any_dataset_loaded`, `after_all_datasets_loaded` and similarly for saved. But that would require another 4 hooks to be provided which seems like a lot given they probably wouldn't be very well used in general. It feels much tidier and more powerful to make `node` generally available. This way you can basically simulate the behaviour of "am I the first or last dataset being loaded/saved" by keeping track of the datasets compared to `node.inputs` or `node.outputs` as above.

**Comment by DavidRoschewitzQB** [comment]
Thanks for opening this issue @AntonyMilneQB ! 

Indeed adding `node` information would help with how we are using the hooks. Let me provide some more detail on our usecase and outline our motivation.

We're using `mlflow` throughout our pipelines (on databricks) and have a very non-intrusive implementation of logging various metrics. Namely, we use tags on a node to specify whether we want any elements of this node to be logged to `mlflow`, and then create a run based on the node name. For this, having knowledge of the `node` (and by extension name and tags) would be very helpful.

Furthermore, we also want to support automatic logging of node outputs (as artifacts). However, `mlflow.log_artifact(path)` requires knowledge of the `path` (on disk) of a particular output to log. To support this without the workaround mentioned above, having information not just of the `data` but ideally the `DataSet` (providing information such as `version` and `path`) would be needed. 

I hope this helps in understanding the potential benefits of making such changes. If you have some thoughts or ideas, always happy to discuss :)

**Comment by sbrugman** [comment]
One alternative to consider for `mlflow`, `wandb` & co (that I've had good experiences with in the past) is to use the python `logging` module from the standard library. Kedro offers excellent support for configuration of loggers out-of-the-box.

The way you would go about this is to define a logging handler (see [docs](https://docs.python.org/3/howto/logging-cookbook.html)) and log the artifacts etc there.

**Comment by AntonyMilneQB** [comment]
Thanks for the extra comments @DavidRoschewitzQB. And thanks for the suggestion @sbrugman - I agree that's a good approach.

This was discussed in technical design on 25 January 2023, and we will be adding `node` to all the dataset hooks.
* @idanov was initially hesitant about the idea of adding `node` to dataset hooks, since it introduces coupling between them: ideally, dataset hooks would only take as arguments things which are related to datasets, and likewise for node hooks
* @idanov also pointed out that many hooks (not the dataset ones) seem to have become cluttered with unsuitable arguments. We don't want to go down the route of adding lots of new things to all the hooks
* we considered whether it would be sufficient to add just `node_name` to the hooks but given that `tags` are required as well, we decided it would just be easiest to add the whole `node` object
* adding `dataset` itself to hooks is more controversial and should be discussed separately
* in general, it's been a while since hooks were introduced and we should probably take stock of what they've done and see if there's any further rejigging we should do (new hooks? new arguments? remove old arguments?)
