### ISSUE TITLE
Tracebacks not working properly within notebooks when using kedro ipython extension

### ISSUE THREAD

**Issue by MatthiasRoels** [kedro-org/kedro#2260]
## Description

After upgrading kedro to v0.18.4 along with other packages (such as ipython and jupyterlab), we noticed as issue with tracebacks no longer showing up properly in notebooks. This issue was already reported here: https://github.com/Textualize/rich/issues/2271 and was fixed in a newer version of rich. The issue should this be resolved by bumping the version of rich in kedro's requirements. 

## Context

Because of this issue, only the exception is printed without a traceback. So it is really hard to pinpoint exactly where the error comes from. Instead of a proper traceback, this is the type of error you would see:

``` 
tmp/ipykernel_1565558/3782956317.py:1 in <cell line: 1>                                                                                          
 [Errno 2] No such file or directory: '/tmp/ipykernel_1565558/3782956317.py'
``` 

## Steps to Reproduce
1. Open jupyter notebooks/lab or you could even open a notebook with your IDE (if supported, e.g. VSCode).
2. Then create a cell with the following snippet: 
``` 
import kedro 

%load_ext kedro.extras.extensions.ipython
%reload_kedro $PROJECT_ROOT

params = context.params
params['and_what_about_a_key_that_does_no_exist']
``` 
3. You would see something like:
``` 
/tmp/ipykernel_29366/1308041660.py:1 in <cell line: 1>
[Errno 2] No such file or directory: '/tmp/ipykernel_29366/1308041660.py'
``` 

## Your Environment

We run everything in a Docker container (`python:3.10-slim`)

* Kedro version used (`pip show kedro` or `kedro -V`): `v0.18.4` 
* Other packages (only relevant ones are shown):
  - rich==12.6.0
  - ipython==8.8.0
  - ipykernel==6.20.2
  - jupyter-client==7.4.9
  - jupyter-core==5.1.5
  - jupyter-server==2.1.0
  - jupyterlab==3.5.3
  - jupyterlab-server==2.19.0
  - nbclassic==0.4.8
  - notebook==6.5.2

**Comment by AntonyMilneQB** [comment]
Hi @MatthiasRoels, thanks very much for raising the issue. Our rich requirement has already been bumped to `~=13.2` and so this should be reflected when Kedro 0.18.5 is released (within the next couple of weeks I believe): https://github.com/kedro-org/kedro/blob/main/dependency/requirements.txt#L18.

Until then, you should still be able to do `pip install -U rich` to bump your version of rich locally. Hopefully that fixes it.

P.S. soon we will have a better way for users to disable rich tracebacks in Jupyter notebooks in case there's any further issues with them.

P.P.S. you don't need to `import kedro` before loading the IPython extension. There's also a shorter alias for it now: just `%load_ext kedro.ipython` will work.

**Comment by MatthiasRoels** [comment]
Thanks for the reply! Will update as soon as 0.18.5 comes out then.
