### ISSUE TITLE
Adding filename_prefix in PartitonedDataset

### ISSUE THREAD

**Issue by simonrevel** [kedro-org/kedro#2266]
## Description
It would greatly help to add `filename_prefix` propriety to the io.PartionedDataset so that we can properly filter mask and images.

## Context
Computer Vision dataset for segmentation often separate images and masks using filenames and/or paths. We could use the path inside the catalog dictionary or add a bash script to reorganize the project data but both options would be less pythonic.

## Possible Implementation
Adding the `filename_prefix` propriety to the io.PartionedDataset

**Comment by noklam** [comment]
Hi @simonrevel, really sorry for the late response. This is a nice idea, but it wouldn't be maintainable to add too many parameters to `filename_prefix`. In fact, we want to have more generic solution for arbitary structure.

It's not documented very cleary - but PartitionedDataSet using `fsspec`'s `find` method, which you can support additional arguments like `max_depth` and `with_dirs`. You can find inspiration in this [thread](https://kedro-org.slack.com/archives/C03RKP2LW64/p1677525924480159)

Can you provide an example of your folder structures?

**Comment by merelcht** [comment]
I'm closing this issue now due to the long inactivity. Feel free to re-open if you still need help with this @simonrevel 🙂
