### ISSUE TITLE
Modify pyspark-iris starter so that it can be deployed to Databricks

### ISSUE THREAD

**Issue by jmholzer** [kedro-org/kedro#2272]
## Description
Currently, our [documentation](https://kedro.readthedocs.io/en/stable/deployment/databricks.html) for deployment of a Kedro project to Databricks uses the [pyspark-iris](https://github.com/kedro-org/kedro-starters/tree/main/pyspark-iris) starter. However, this starter will not run successfully when deployed to Databricks.

The problem in pyspark-iris is with the catalog:
- Spark datasets are saved, DataBricks will resolve any filepaths passed to PySpark in DBFS
- Pandas is used to load these datasets, though DataBricks will resolve any filepaths passed to normal python code in the block storage volume attached to the driver node
This causes a DataSetError, as the code will try to load files from a location in which they have not been saved.

The additions to the catalog that would cause the Databricks deployment to stop working were added in [this](https://github.com/kedro-org/kedro-starters/pull/82/files) PR.

## Context
This issue is causing the documentation for deployment to Databricks to be inaccurate. Any users will encounter an opaque error when following the documentation correctly.

**Comment by AntonyMilneQB** [comment]
This is a great catch and something we should have thought of before 👍

A few questions just to understand:
* would this have been an issue on the old pyspark starter before https://github.com/kedro-org/kedro-starters/pull/82?
* is there any way of changing this catalog so that it will work straightaway on both databricks and not on databricks? (I'm guessing not because you have to add `dbfs` to filepaths or something?)
* is there anything else in the `iris-pyspark` starter that's not compatible with databricks? I hope not but this should be easy to check just by deleting the catalog entries.

**Comment by jmholzer** [comment]
> * would this have been an issue on the old pyspark starter before [Simplify pyspark-iris starter kedro-starters#82](https://github.com/kedro-org/kedro-starters/pull/82)?

I haven't tested it manually, but from looking at the catalog before this change I don't think so.

> * is there any way of changing this catalog so that it will work straightaway on both databricks and not on databricks? (I'm guessing not because you have to add `dbfs` to filepaths or something?)

I'm thinking about this, but for the moment I fear you're right, I don't think there's a clean way to make this work. It needs some more investigation.

> * is there anything else in the `iris-pyspark` starter that's not compatible with databricks? I hope not but this should be easy to check just by deleting the catalog entries in your databricks project.

Replacing the local filepaths supplied to `pandas.ParquetDataSet` with filepaths that point explicitly to `/dbfs/...` fixes things, and the pipeline runs succesfully, so it appears this is the only problem.

**Comment by AntonyMilneQB** [comment]
That's good to know, thanks. In that case I think the best fix here would be to create a new `databricks` environment with a catalog.yml file that works there. This way you could just do `kedro run --env=databricks` (or `%reload_kedro` with env specified or `session.create` or whatever) and it should work there also while we can leave the `base` environment as it is now.
