### ISSUE TITLE
Stop producing `.egg` files from `kedro package`

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#2273]
While going over the spaceflights tutorial (#2261) I saw Eggs mentioned. For the uninitiated, Eggs are an ancient distribution format that predate Wheels. They were linked to `easy_install`, a predecessor of `pip` that has been officially deprecated since november 2019 (that's almost 3.5 years ago), and that stopped being relevant (in favor of pip) much earlier. `pip install --egg` is deprecated as well. As such, there is no widespread official tool supporting `.egg`s nowadays, and I don't think it makes sense to keep producing `.egg` files as part of the `kedro package` command.

The spaceflight tutorial references the Python Packaging User Guide, which unfortunately is not very well maintained. The setuptools documentation is [much more explicit](https://setuptools.pypa.io/en/latest/deprecated/easy_install.html):

> Easy Install is deprecated. Do not use it. Instead use pip. If you think you need Easy Install, please reach out to the PyPA team (a ticket to pip or setuptools is fine), describing your use-case.

Any objections?

**Comment by AntonyMilneQB** [comment]
100% agree with this.

The `micropkg` workflow seems to use egg-info files. At a glance it looks like it's not a core feature but just used to find the right directory and unpackage stuff correctly. I don't know whether this should be updated also. It was fixed quite recently it seems: https://github.com/kedro-org/kedro/pull/1848.

**Comment by stichbury** [comment]
I will remove the "Documentation" label from this ticket and leave the issue here to be an action to remove anything from Kedro that relates to egg creation (🦆 🐔 🦅 ). I'll separately note that we need to remove mention of egg packages in #2261 and make the documentation fix there.

**Comment by merelcht** [comment]
This is technically a breaking change, but it has been deprecated from setuptools for a long time and it's probably not used by many users. So, let's do this in a non-breaking release. The person picking this up, could do a quick user poll if that would make them feel better about breaking this.

**Comment by astrojuanlu** [comment]
This blocks https://github.com/kedro-org/kedro/issues/2280, because such starters wouldn't have `setup.py`, hence producing this message:

```
> kedro package
/Users/juan_cano/.micromamba/envs/workshop310/bin/python3.10 setup.py clean --all bdist_egg --dist-dir ../dist
/Users/juan_cano/.micromamba/envs/workshop310/bin/python3.10: can't open file '/Users/juan_cano/Projects/QuantumBlack Labs/workshop-kedro-polars/src/setup.py': [Errno 2] No such file or directory
```

**Comment by astrojuanlu** [comment]
Just in time 😬 https://blog.pypi.org/posts/2023-06-26-deprecate-egg-uploads/
