### ISSUE TITLE
Possible improvement to hooks?

### ISSUE THREAD

**Issue by antonymilne** [kedro-org/kedro#2274]
# Context

There's some user research that needs to be done here. I don't think it's urgent but wanted to write about it while I remembered and provide an issue to collect any other thoughts on the topic.

Hooks have been around for a while now and are generally great, but they haven't changed much since they were introduced. Maybe it's time to take stock of where we are and think about if it's correct. Here's how we got to where we are now:
* 0.16.0 (May 2020): first hooks released: `after_catalog_created`, `before_node_run`, `after_node_run`, `on_node_error`, `before_pipeline_run`, `after_pipeline_run`, `on_pipeline_error` (see [blog post](https://medium.com/quantumblack/introducing-kedro-hooks-fd5bc4c03ff5))
* 0.16.5 (Sep 2020): added registration hooks (`register_pipelines`, `register_config_loader`, `register_catalog`).
* 0.17.0 (Dec 2020): registration hooks made mandatory. Added hooks `after_dataset_loaded`, `after_dataset_saved`, `before_dataset_loaded`, `before_dataset_saved`
* 0.18.0 (Mar 2022): registration hooks removed in favour of settings.py
* 0.18.1 (May 2022): added hook `after_context_created`

I'm ignoring CLI hooks here, since they're a bit different. Personally I don't think there's a lot that we need to fix here, but would be interested in what others think and if there's any pain points we could easily solve. We're already adding `node` to the dataset hooks (see https://github.com/kedro-org/kedro/issues/2258). Is there anything else we should do?
* hooks: do we need any new ones? Should we get rid of any existing ones? e.g. what is the role of `after_catalog_created` now we have `after_context_created`? (I think it's probably still legit, but would like to understand better what people use it for)
* arguments: do we need any new ones? Should we get rid of any existing ones? e.g. do the node hooks need all those arguments?

---
# Hook specifications as of 0.18.4

### DataCatalogSpecs
```
after_catalog_created(catalog, conf_catalog, conf_creds, feed_dict, save_version, load_versions)
```
### DatasetSpecs
```
after_dataset_loaded(dataset_name, data)
after_dataset_saved(dataset_name, data)
before_dataset_loaded(dataset_name)
before_dataset_saved(dataset_name, data)
```
### KedroContextSpecs
```
after_context_created(context)
```
### NodeSpecs
```
after_node_run(node, catalog, inputs, outputs, is_async, session_id)
before_node_run(node, catalog, inputs, is_async, session_id)
on_node_error(error, node, catalog, inputs, is_async, session_id)
```
### PipelineSpecs
```
after_pipeline_run(run_params, run_result, pipeline, catalog)
before_pipeline_run(run_params, pipeline, catalog)
on_pipeline_error(error, run_params, pipeline, catalog)
```

---
Bonus: here's the script used to generate the above because why spend a few minutes copying and pasting it manually when you  could spend much longer writing a script to do it for you...
```
import inspect
import sys

for hook_class_name, hook_class in inspect.getmembers(sys.modules[__name__], inspect.isclass):
    if hook_class_name.endswith("Specs"):
        print(f"### {hook_class_name}")
        print("```")
        for hook_spec_name, hook_spec in inspect.getmembers(hook_class):
            if not hook_spec_name.startswith("__"):
                params = ", ".join(list(inspect.signature(hook_spec).parameters)[1:])
                print(f"{hook_spec_name}({params})")
        print("```")
```

> **Note**. `inspect.signature()` by itself gives a nice string representation of the function signature with type hints and return type, but it seemed too long to include all that here.

**Comment by astrojuanlu** [comment]
This ticket doesn't have any concrete actions and hasn't had any activity in 1.5 years. Closing for now.
