### ISSUE TITLE
Define a model workflow for deploying Kedro on Databricks

### ISSUE THREAD

**Issue by jmholzer** [kedro-org/kedro#2282]
## Description
Databricks has features that would significantly benefit a user deploying Kedro. Currently, our [documentation](https://kedro.readthedocs.io/en/stable/deployment/databricks.html) does not guide users in using these features.

As a prerequisite to documenting a better way of working with Kedro on Databricks, we need a clear definition of what an improved workflow looks like. The outcome of this ticket is a concrete definition of a workflow for:

1. Syncing local code with a Databricks workspace, using [Databricks Repos](https://www.databricks.com/product/repos) and [dbx sync](https://dbx.readthedocs.io/en/latest/reference/cli/?h=cli#dbx-sync-repo).
2. Running Kedro pipelines on Databricks, using the Kedro iPython extension or use of [dbx deploy](https://dbx.readthedocs.io/en/latest/reference/cli/?h=cli#dbx-deploy)

## Context
This issue is a child of https://github.com/kedro-org/kedro/issues/2185.

**Comment by jmholzer** [comment]
## Two-workflow approach

The original brief in this investigation ticket and https://github.com/kedro-org/kedro/issues/2185 was to define separate workflows, one for synchronising local code with Databricks and one for running Kedro pipelines without using the Workspace UI. After researching possible implementations, I found that the latter workflow has no dependency on the former. Therefore, I think that we should document two separate end-to-end workflows for working with Kedro on Databricks. The workflows are mutually exclusive and provide a different set of benefits to users with different levels of Databricks competency:

1.  *Hybrid Workflow*. Databricks Repos is used to synchronise local code with a Databricks workspace. This is a 'light' option which improves the development experience while remaining accessible for users without advanced knowledge of Databricks. The use of `dbx` is optional in this workflow.

2. *IDE-only workflow*. `dbx` is used to deploy and run a Kedro project on Databricks without any need for code synchronisation. All development work is performed in the user's local environment. This highly-automated solution lends itself well to developers with enough knowledge of Databricks and its API to work completely outside of the Workspace UI.

Documentation for both of these workflows should be added, along with a comparison of their relative benefits to help Kedro users choose which is right for their project.

### 1. Hybrid Workflow (local development with code synchronisation)

In this hybrid workflow, development takes place in the user's local environment and deployment takes place using notebooks and the Databricks Workspace UI. Databricks Repos is synchronise local code with Databricks via a source control provider (e.g. GitHub or Azure DevOps). This allows users to use their preferred IDE to develop a Kedro project in their local development environment and then run it on a Databricks cluster using notebooks.

The main advantages of the hybrid workflow for are:

1. Efficiency: Users can use an IDE to develop Kedro projects in their local development environment.
2. Flexibility: It allows for a more flexible workflow. Users can switch between local development and the Databricks Workspace UI, depending on their needs.

The main disadvantages of the hybrid workflow for are:

1. Additional code: A shim script is still required to install dependencies and run the user's project on a Databricks cluster. However, not as much boilerplate code is required as for the IDE-only development workflow.
2. Environment switching: Switching between local development and the Databricks Workspace UI is necessary, which is less efficient than the IDE-only approach.

To implement this workflow, users can use Repos to synchronise their local code with Databricks. They can either commit and push local changes using their source control solution or use `dbx sync` to unidirectionally synchronise any local changes as soon as they are made. The advantage of using `dbx sync` is that changes do not have to be manually committed and pushed, but the disadvantage is that this is unidirectional and changes made in Databricks will not be reflected locally unless committed to source control and pushed.

We should document both synchronisation approaches and allow our users to choose which one to use. Additionally, we will provide a shim script that users can use to install dependencies and run their project on a Databricks cluster as we do in our current documentation.

### 2. IDE-only workflow (local development with automated deployment)

This proposal is for an IDE-only workflow for Kedro on Databricks, in which a user develops their Kedro project entirely in their local development environment and uses the `dbx launch` and `dbx deploy` commands to deploy and run a Kedro project on a Databricks cluster. The main advantage of this approach is that the user does not have to interact with the Databricks workspace UI at all, and can develop and deploy their entire project using their local IDE and shell.

The main advantages of the IDE-only workflow are:

1. Improved productivity: With an IDE-only workflow, users can develop and deploy their Kedro projects faster and more efficiently. The entire workflow can be performed from their local IDE and terminal, eliminating the need to switch between the IDE and the Databricks workspace UI.
2. Automated deployment: Running a project on Databricks only requires two terminal commands with this approach.

The main disadvantages of the IDE-only workflow are:

1. Maintenance of deployment files: The user will have to add and maintain a 'deployment file' (`conf/deployment.yml`). This is a potential drawback, as knowledge of the [deployment file syntax](https://dbx.readthedocs.io/en/latest/reference/deployment/) as well as yaml syntax is necessary. This can be mitigated to a degree by covering the most common cases in our documentation, with template deployment files. In addition, we could add a Databricks starter including a template deployment file.
2. Additional code: A boilerplate shim script is necessary to allow the Kedro project to run. This disadvantage can be mitigated by adding this script to our documentation as well as potential inclusion in a starter. Nevertheless, this is another file the user will have to keep in their project.

This approach is compatible with the deployment of [package-based projects](https://dbx.readthedocs.io/en/latest/guides/python/devloop/package/).

### Conclusion

We should document two separate workflows for working with Kedro on Databricks: the Hybrid Workflow and the IDE-only Workflow. The Hybrid Workflow uses Databricks Repos to synchronize local code with the Databricks. The documentation for both workflows will include a comparison of their relative benefits to help users choose the best approach for their project.

**Comment by jmholzer** [comment]
@yetudada @merelcht @SajidAlamQB what are your thoughts on the above approach?

**Comment by SajidAlamQB** [comment]
Awesome write-up @jmholzer! I like the idea of having two separate workflows depending on user experience. I have some thoughts:

- Maybe we should add to the IDE-only workflow for specific IDEs like VS Code because IIRC they have an extension which does all the dbx stuff already. 
- Do we consider both workflows "best practice" or do we favour an approach? How do we reconcile this with beginner users?
- If I understand correctly the main difference between both workflows is the deployment, dbx vs notebooks, maybe the Hybrid workflow should be the baseline setup for all users with the IDE-only workflow being an extension to it?

**Comment by yetudada** [comment]
I have enjoyed the write-up for this @jmholzer! It's very impressive and a lot of this content can already be used with our users! Please proceed with these two journeys! 

Here are my high-level thoughts: 

 - It would be great it to have an introduction to this piece that includes a flowchart for which option to pick.
 - I like the thinking around a hybrid option, it solves for some users that do not want to use an IDE at all when they are collaborating with people that want to use the IDE
 
And then I have two questions:

- In the IDE-only workflow, what is used to keep the code synced to the Databricks workspace? Is it `dbx sync`? 
-  I would be happy for a databricks starter to exist, would this replace our need for the `kedro-databricks` plugin?

**Comment by noklam** [comment]
I have experimented with the [Databricks VSCode Extension](https://docs.databricks.com/dev-tools/vscode-ext.html) @jmholzer @SajidAlamQB 

# Summary
I find this approach much smoother than the IDE-only workflow since it's **optional** to use Databricks UI or not, you can just stay within IDE, and go to Databricks if you need interactiveness (Which you always need at some point).

* It syncs files unidirectionally (from local -> databricks Repo) automatically - no need to run any command, it could be using `dbx sync` in the background but I did not do any `dbx` specific configuration. All I have is the name of instance and a token to access Databricks
* User can execute a python file as if they are running on Databricks - no need to leave the IDE
* User can execute python file/notebook as a Databricks Job

![image](https://user-images.githubusercontent.com/18221871/225606977-c8bf1863-9526-4a0c-95ea-72071dc53487.png)
![image](https://user-images.githubusercontent.com/18221871/225607803-649c7e61-8288-4aab-847c-f323c1fcaef8.png)


The workflow that I used
Visually, I have both VSCode (Left) and Databricks UI (Right).
* All files change are made on VSCode (update config, pipelines, node) - sync automatically to Repo
* On the Databricks notebook, I always use `%reload_kedro` and session.run, any debugging development process will happen on the right

## Is it better than `dbx`?
I think `dbx` would make sense if you need to properly package the project, but it is not efficient to re-package the whole project when you are doing development.


![image](https://user-images.githubusercontent.com/18221871/225606319-dc755d1c-d411-4291-9b43-122f5db1a158.png)

**Comment by jmholzer** [comment]
Thanks for all the feedback so far! It's appreciated 🙂

@merelcht 

> * Is it possible to have a workflow where users don't use an IDE at all (e.g. only notebooks)? It might not be realistic, but we've heard in the past that some users even struggle using an IDE.

I think this actually describes the default workflow offered in Databricks workspace. Users interact with and run code on their cluster using embedded Notebooks. This is a good question and we should consider keeping our current documentation (based on this workflow) in some form for these users.

> * Would you recommend a different flow depending on whether people need to share code or not? I guess you could still have a regular git flow, but I'm wondering if with Databricks Repos it would be simpler to run someone else's code?

This is also a good question, I think both workflows work equally well in this regard. Both allow users to use versioned code written by their colleagues and I wouldn't lean towards either one in particular.

> * How do you check your databricks deployment in the IDE-only workflow? Wouldn't you still have to go to the UI to see the status of whatever you've deployed?

`dbx` allows routing the output of the deployed code to the terminal, we can set this up for our users in the documentation.

@SajidAlamQB

> * Maybe we should add to the IDE-only workflow for specific IDEs like VS Code because IIRC they have an extension which does all the dbx stuff already.

This is a good idea and I am in favour of looking into, though I would rather look do this outside of the scope of this milestone, as there is no guarantee that our users will use VS Code. [Databricks](https://docs.databricks.com/dev-tools/vscode-ext.html#how-does-dbx-by-databricks-labs-relate-to-the-databricks-extension-for-visual-studio-code) also suggest it offers a subset of the features of `dbx`, some of which we may want to expand the scope of our workflow to include (CI / CD).

> * Do we consider both workflows "best practice" or do we favour an approach? How do we reconcile this with beginner users?

I think it's more a case of documenting both and helping our users choose the right one for them. You make a great point concerning beginner users. As I mention in my answer above, I think we could reuse much of our existing documentation to help beginners use the the default Databricks workspace workflow. This be the 'zeroth' option.

> * If I understand correctly the main difference between both workflows is the deployment, dbx vs notebooks, maybe the Hybrid workflow should be the baseline setup for all users with the IDE-only workflow being an extension to it?

With the IDE-only workflow, there is actually no need connect a Git service provider to Databricks Repos. Instead, the code is versioned and stored with a service provider as usual. When it comes to running the code, `dbx` uploads and runs the code without relying on Databricks Repos.

@yetudada

> * It would be great it to have an introduction to this piece that includes a flowchart for which option to pick.

Agreed, this would be great ⭐️.

> * In the IDE-only workflow, what is used to keep the code synced to the Databricks workspace? Is it dbx sync?

The IDE-only workflow actually avoids the need for syncing code with Databricks workspace. Code is versioned normally, using the user's preferred Git provider and is uploaded once when it is run on Databricks. This avoids the overhead of integrating Databricks Repos, though there is some cost to uploading code each time. I am currently de-risking this workflow and I'll be able to comment more on the disadvantages once this is a bit more advanced.

> * I would be happy for a databricks starter to exist, would this replace our need for the kedro-databricks plugin?

This is a good question. I think this is a possibility though it will be possible to tell after the de-risking for these workflows is closer to being finished, I'll be able to comment on this more definitely at the halfway point of the next sprint.

@noklam 

Thanks for writing this summary of the Databricks VS Code extension. I agree it is promising and it can do some things well, though I don't feel that we should consider it in the scope of this ticket at the moment for the reasons I outlined in my response to @SajidAlamQB above. I think if implementing workflow two does not go according to plan, we could consider documenting this in place of `dbx`.

> I find this approach much smoother than the IDE-only workflow since it's optional to use Databricks UI or not, you can just stay within IDE, and go to Databricks if you need interactiveness (Which you always need at some point).

I'm not sure I follow, in the IDE-only workflow as defined above, this would also be the case.

> I think dbx would make sense if you need to properly package the project, but it is not efficient to re-package the whole project when you are doing development.

It is not necessarily the case that you need to repackage the project every time when using `dbx`, no-package execution is an option and I am trying to make it work with Kedro as part of the de-risking of workflow two.

> I find it almost impossible, as you will need to edit the source code and the file editing function on Databricks is weak (Think of editing files on the Github browser directly, or worse)

I agree with this. Just for clarity, this is the workflow we currently recommend to our users and are seeking to replace with the two workflows defined above. Neither of the proposed new workflows advocate editing code exclusively in notebooks.

**Comment by merelcht** [comment]
Thanks for all the clarifications and answers @jmholzer ! 
- Noted on the "notebook" workflow. We could keep a mention of that workflow in the docs, but at the same time I guess that workflow just isn't really ideal for Databricks + Kedro. The most important thing is that our docs describe a good workflow even if it's slightly more difficult from the "plain notebook" one.
- The VS Code extension does indeed look great, but I also feel like we should describe the more generic IDE flow and then mention the VS Code as an FYI. I personally wouldn't change IDEs just for working with a new platform.

> dbx allows routing the output of the deployed code to the terminal, we can help set this up for our users in our documentation.

- That would be great 👍 

In any case, I think the two workflows you've described are really good options and I'd be happy to go ahead with having these as our recommended flows in the docs.

**Comment by yetudada** [comment]
Fantastic write-up! Proceed on this. I'm also happy for VSCode to be mentioned (and perhaps this GitHub issue can be referenced) but we definitely need a more general IDE-approach because we have a lot of PyCharm users.

**Comment by jmholzer** [comment]
@merelcht 

> Noted on the "notebook" workflow. We could keep a mention of that workflow in the docs, but at the same time I guess that workflow just isn't really ideal for Databricks + Kedro. The most important thing is that our docs describe a good workflow even if it's slightly more difficult from the "plain notebook" one.

I agree. My current thinking is to retool and reuse it, removing much of the outdated and difficult-to-follow advice (https://github.com/kedro-org/kedro/issues/2443) and document it as a possible workflow for beginners, but nudge users to working with the more advanced ones. This nudge will also be in the guide informing users which workflow is most suitable for them (https://github.com/kedro-org/kedro/issues/2444).

> The VS Code extension does indeed look great, but I also feel like we should describe the more generic IDE flow and then mention the VS Code as an FYI. I personally wouldn't change IDEs just for working with a new platform.

Agreed, we'll definitely note a possible workflow with VS Code.


@yetudada 

> I'm also happy for VSCode to be mentioned (and perhaps this GitHub issue can be referenced) but we definitely need a more general IDE-approach because we have a lot of PyCharm users.

Definitely, I will think about which form this VS Code extension guide should take and open an issue.

**Comment by jmholzer** [comment]
Since we have converged on a definition for what our recommended workflows will be, I will close this ticket.

In summary, the action items to come out of this investigation are:

1. Both newly-defined workflows will be implemented tested by the framework team.
2. After testing, we'll assess whether a Databricks plugin is still necessary.
3. Documentation for the new workflows will be created.
4. The existing deployment documentation will be retooled as a 'Workspace / Notebooks' workflow.
5. A short guide for developing Kedro with the Databricks VS Code extension will be documented.
