### ISSUE TITLE
Add Sonatype scanning to Kedro

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2289]
### Description 

Check if this should be setup through the Linux Foundation. Otherwise QB infosec should be able to help.

**Comment by merelcht** [comment]
Sonatype or SonarQube? Or both? 😄

**Comment by merelcht** [comment]
I vote for closing this issue now we're in the process of getting our own managed Snyk setup. At this point in time, the Linux Foundation is not prioritising security scans, so it's up to us what we setup.

**Comment by astrojuanlu** [comment]
Agreed. Closing.
