### ISSUE TITLE
Curate plugins by maintenance activity in Kedro's documentation

### ISSUE THREAD

**Issue by idanov** [kedro-org/kedro#2291]
## Description

Currently Kedro lists a number of community plugins in its documentation (https://kedro.readthedocs.io/en/stable/extend_kedro/plugins.html) , but it's hard to assess how actively maintained those plugins are currently. It would be really useful for the users to have a badge against each plugin on that list with the activity of that plugin, e.g. either commits per month or last commit activity badges.

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
We can use any of these badges: https://shields.io/category/activity

|Last commit |Plugin |
-------------|-------|
|![GitHub last commit](https://img.shields.io/github/last-commit/brickfrog/kedro-pandas-profiling?style=flat-square) | [kedro-pandas-profiling](https://github.com/brickfrog/kedro-pandas-profiling)|
|![GitHub last commit](https://img.shields.io/github/last-commit/Galileo-Galilei/kedro-mlflow?style=flat-square) | [kedro-mlflow](https://github.com/Galileo-Galilei/kedro-mlflow)|
|![GitHub last commit](https://img.shields.io/github/last-commit/WaylonWalker/find-kedro?style=flat-square) | [find-kedro](https://github.com/WaylonWalker/find-kedro)|
|![GitHub last commit](https://img.shields.io/github/last-commit/getindata/kedro-kubeflow?style=flat-square) | [kedro-kubeflow](https://github.com/getindata/kedro-kubeflow)|
|![GitHub last commit](https://img.shields.io/github/last-commit/getindata/kedro-airflow-k8s?style=flat-square) | [kedro-airflow-k8s](https://github.com/getindata/kedro-airflow-k8s)|
|![GitHub last commit](https://img.shields.io/github/last-commit/getindata/kedro-vertexai?style=flat-square) | [kedro-vertexai](https://github.com/getindata/kedro-vertexai)|
|![GitHub last commit](https://img.shields.io/github/last-commit/getindata/kedro-azureml?style=flat-square) | [kedro-azureml](https://github.com/getindata/kedro-azureml)|
---

And so on...

Additionally, we could ensure the links open in a new tab, since currently they open in the same tab of the documentation.

**Comment by merelcht** [comment]
The idea of badges is nice, but it's not clear how this would actually work inside the Sphinx docs. As a alternative solutions we'll go through all the plugins and divide them into "actively maintained" and "unknown state". Presumably users would create a PR if their plugin is in the wrong category. 

It's not ideal that this division needs to be maintained manually, but at least it's better than not having the categories at all.

**Comment by astrojuanlu** [comment]
Prior art: https://myst-parser.readthedocs.io/en/latest/intro.html (link to https://sphinx-extensions.readthedocs.io/en/latest/)

![image](https://user-images.githubusercontent.com/316517/224733765-50b66d3c-26fd-4b6d-aa2c-c89ba3296aef.png)

Related: https://github.com/kedro-org/kedro-devrel/issues/40

**Comment by astrojuanlu** [comment]
cc @inigohidalgo

**Comment by astrojuanlu** [comment]
Other prior art: Astropy affiliated packages https://github.com/astropy/astropy-project/blob/main/affiliated/affiliated_package_review_guidelines.md (see an old example https://github.com/poliastro/poliastro/issues/279).

![image](https://user-images.githubusercontent.com/316517/235316146-6d4b782d-8469-4969-a81f-f0e4e979f2d0.png)

**Comment by astrojuanlu** [comment]
In summary: I think it's not enough that we put a colored badge depending on activity. Users have showed concerns about whether plugins not under `kedro-org` are worth adopting (see [example](https://www.linen.dev/s/kedro/t/10470016/hey-all-dotyou-think-a-aset-for-onnx-models-woris-th-contrib#4ffa4dc1-854e-4eea-a98b-d1ab827070d2)), and we should draft a strategy to address those concerns.

This is a huge topic that would deserve some discussion, but off the top of my head and just to start scratching the surface, one thing that could be more valuable than "days since last commit" would be: "does this plugin actually work with the latest versions of Kedro"? Hence providing a compatibility matrix. Something similar to what the Numba folks started here https://github.com/numba/numba-integration-testing

**Comment by astrojuanlu** [comment]
Prior art: https://intake.readthedocs.io/en/latest/plugin-directory.html

![image](https://github.com/kedro-org/kedro/assets/316517/0b40b632-cd90-42ee-a497-cb6d59df86be)

**Comment by noklam** [comment]
Tangentially related #2719

**Comment by merelcht** [comment]
I looked at this issue again today and indeed implementing a readable table with badges in sphinx is not trivial at all. I also agree that latest commit is not informative enough. I vote for closing this specific issue and instead, as part of the ongoing deployment work, discuss our support & promotion model for third-party plugins.

**Comment by astrojuanlu** [comment]
I know this is closed but just wanted to leave this here! https://github.com/mkdocs/catalog
