### ISSUE TITLE
Pipeline to_outputs doesn't accept list as mentioned in the documentations.

### ISSUE THREAD

**Issue by zeinabJS** [kedro-org/kedro#2293]
I'm trying to run a pipeline using SequentialRunner and extract the output of the pipeline and an output of a node that was run as part of the pipeline. 
The purpose is to run some end-to-end testing and I need an interim result for a check. 

## Steps to Reproduce
```
pipeline = Pipeline([Node(inputs1,outputs1),Node(inputs2,outputs2),Node(inputs3,outputs3)]).create_pipeline()
pipeline = pipeline.to_outputs([outputs1, outputs3])
catalog = DataCatalog()
runner = SequentialRunner()
output = runner.run(pipeline, catalog)
```

## Actual Result

```
--     def to_outputs(self, *outputs: str) -> "Pipeline":
        """Create a new ``Pipeline`` object with the nodes which are directly
        or transitively required to produce the provided outputs.
        If provided a name, but no format, for a transcoded dataset, it
        includes all the nodes that output to that name, otherwise it matches
        to the fully-qualified name only (i.e. name@format).
    
        Args:
            outputs: A list of outputs which should be the final outputs of
                the new ``Pipeline``.
    
        Raises:
            ValueError: Raised when any of the given outputs do not exist in the
                ``Pipeline`` object.
    
    
        Returns:
            A new ``Pipeline`` object, containing a subset of the nodes of the
            current one such that only nodes which are directly or transitively
            required to produce the provided outputs are being copied.
    
        """
>       starting = set(outputs)
E       TypeError: unhashable type: 'list'
```

If I use pass the outputs without the list I don't get the error. But the output still doesn't include the `output1`:

```
pipeline = pipeline.to_outputs(outputs1, outputs3)
runner = SequentialRunner()
output = runner.run(pipeline, catalog)

output['outputs1']
```
Raises KeyError: 
```
E           KeyError: "outputs1"
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): `Version: 0.17.2`
* Python version used (`python -V`): `Python 3.7.5`
* Operating system and version: Ubuntu 18.04.3 Bionic

**Comment by AntonyMilneQB** [comment]
The second example you give is the right way to call it (`to_outputs(output1, output2)`). What you're probably missing is that `runner.run` only returns the _free_ outputs of your pipeline, i.e. those which are not given in the catalog.  So if you remove the catalog entry for `outputs1` you should find it's then present in the `output` dictionary. You can do `print(output.keys())` to see all the free outputs if you like.

**Comment by zeinabJS** [comment]
@AntonyMilneQB Thank you. 
I didn't define those entries in the catalog. It's an empty DataCatalog. I basically just add the `inputs1` to it. 
I can see that `output` contains the outputs that were not reused in the pipeline, but I didn't find a way to read the ones that were used in another node. 

A better example might be this 
```
pipeline = Pipeline([Node(inputs1,outputs1),Node(output1,outputs2),Node(output2,outputs3)]).create_pipeline()
pipeline = pipeline.to_outputs([outputs1, outputs3])
catalog = DataCatalog()
runner = SequentialRunner()
output = runner.run(pipeline, catalog)

```
Here `output1` is passed over to the next node as input. This is what I'm interested in extracting.

**Comment by noklam** [comment]
https://github.com/kedro-org/kedro/issues/1802#issuecomment-1270096651

Noted that this behavior is designed for saving memory footprint. For development/debugging purpose, sometimes you may wish it just return everything for inspect.

I have put together an implementation that can return all output here https://github.com/kedro-org/kedro/issues/1802#issuecomment-1270096651
