### ISSUE TITLE
Rename ``OmegaConfLoader`` as ``OmegaConfigLoader``

### ISSUE THREAD

**Issue by Galileo-Galilei** [kedro-org/kedro#2294]
## Description

A new ``OmegaConfLoader`` has been introduced in the master branch, but has not been released yet. I was looking for the class and I was confused by the name because it is not consistent with all other kedro names. This class should likely be renamed ``OmegaConfigLoader`` for consistency with all other configuration-related object names: ``AbstractConfigLoader``,``TemplatedConfigLoader``, ``MissingConfigException``...

The rationale in the current name is that it is relies on the ``omegaconf`` library whose name is not consistent with kedro. The correct name should even be ``OmegaconfConfigLoader`` but it seems a bit complicated. This is a bit of splitting hair, but naming is something that will stay for a long time so I think it should be carfully though at the very beginning. 

 It is likely better to choose the name well before making it too official. I guess ultimately it may be renamed ``ConfigLoader`` in the 0.19 series, and kedro will get rid of ``TemplatedConfigLoader`` at this point?

**Comment by merelcht** [comment]
Hi @Galileo-Galilei , this was exactly my consideration when adding the `OmegaConfLoader`: `OmegaConfigLoader` would be more consistent, but then you're not loading "omega", while with the `TemplatedConfigLoader` you are loading templated config.. 

I asked whether this was the right name in the original PR https://github.com/kedro-org/kedro/pull/2085, but didn't get many responses to it.

**Comment by datajoely** [comment]
Another vote for `OmegaConfigLoader` from me :)
