### ISSUE TITLE
Explore adding the `DryRunner` into the Kedro package

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2310]
### Description

Users ask about the `DryRunner` functionality frequently, so it might be a good idea to move it from the docs and add it as a real class into the Kedro Framework.

### Approach

Search slack for questions/mentions about the `DryRunner` + talk to users directly to ask how they use it.

**Comment by astrojuanlu** [comment]
Last mention of `DryRunner` in Slack according to Linen was in November 2022 https://linen-slack.kedro.org/t/9703736/hello-i-would-like-to-use-something-like-this-dry-runner-htt#14e2145f-ceaa-4f94-9e96-546a21a25158

I'm voting to put it in a separate repo, like @noklam did with https://github.com/noklam/kedro-softfail-runner, and close this issue.

**Comment by merelcht** [comment]
Since there hasn't been a lot of ask recently, I'll close this issue now. We can always add the runner to a repo when demand spikes again.
