### ISSUE TITLE
Enable Read the Docs Pull Request Builder

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2324]
## Description
[From this comment](https://github.com/kedro-org/kedro/pull/2304#issuecomment-1429585369).

We can enable the Pull Request Builder on RTD to build HTML from our PRs so that it's easy to see them in HTML format. Currently, I do this separately using GitHub pages and provide a link to my own repo.

Someone with proper permissions on the kedro-org/kedro repository needs to add a GitHub connection from https://readthedocs.org/dashboard/kedro/integrations/create/ as per @astrojuanlu's recommendation.

**Comment by astrojuanlu** [comment]
cc @kedro-org/kedro-admin

**Comment by tynandebold** [comment]
I can do it. Can someone please add me to the Read the Docs project though? You can use my QB email address.

**Comment by astrojuanlu** [comment]
@tynandebold invite sent ✔️

**Comment by tynandebold** [comment]
I've successfully added the webhook.

![image](https://user-images.githubusercontent.com/16869061/219345186-010408fc-ec7c-4259-b44d-9a8fb23c8a6c.png)

Let's test it?

**Comment by astrojuanlu** [comment]
Opened gh-2328, it's working! 🥳 
![image](https://user-images.githubusercontent.com/316517/219348721-28632335-7fad-4499-b972-f8fb4cfbe8ab.png)
