### ISSUE TITLE
Plan to improve ci/cd + automated release setup of `kedro-plugins`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2333]
### Description

Following up on https://github.com/kedro-org/kedro-plugins/pull/4

Currently `kedro-plugins` has one top level `Makefile`, each plugin has it's own `.pre-commit-config.yaml` and `pyproject.toml`. Look at whether it would be better for these configuration files to be unified or for each plugin to have it's own files. 

@AntonyMilneQB Raised a good question about whether the pre-commit hooks actually still work without the file being at the root of the repo. 

For this issue come up with a plan to improve the setup:
- Decide what parts exactly need to be improved
- Come up with a proposal of breaking this down and how to implement
- Discuss in Technical Design when needed

**Comment by merelcht** [comment]
As discussed in **technical design** on 15/2:

1. This issue becomes a milestone:
2. All P0 points are converted into issues
3. When all P0 issues have been completed, we'll revisited what more needs to be done. Most likely in technical design sessions.

**Comment by deepyaman** [comment]
One additional note to keep in mind that I just remembered; we need to address the behavior when multiple plugins are modified (or just make sure this doesn't happen in the future approach):

<img width="857" alt="image" src="https://user-images.githubusercontent.com/14007150/219698607-a13f2061-9f55-4abb-a060-a7af6a27505d.png">

**Comment by astrojuanlu** [comment]
Potentially relevant for the automated release https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/

**Comment by astrojuanlu** [comment]
I think most of https://github.com/kedro-org/kedro/issues/2333#issuecomment-1434492921 has already been done, except for https://github.com/kedro-org/kedro/issues/2336

**Comment by merelcht** [comment]
Closing this because the CI/CD of `kedro-plugins` has been hugely improved already. I created a new milestone for testing the plugins individually: https://github.com/kedro-org/kedro/milestone/60
