### ISSUE TITLE
Add nightly build or trigger on Kedro core change

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2335]
## Description
The CI on `kedro-plugins` is not run regularly - for the core Kedro repo we have frequent changes so any dependency changes will be found out pretty quickly. For plugins, there could be a dependency change but we only have new commits after a few months. In this case, it is unclear whether the new changes break the CI or something in between happened, often it takes a long time to isolate the error.

## Possible Implementation
- Add a nightly build trigger
- Trigger the build every time a change is merged to Kedro `main`

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro-plugins/pull/283
