### ISSUE TITLE
Move `pre-commit` config to the top level of `kedro-plugins`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2337]
## Description
Move `pre-commit` config to the top level and use path filters if/when necessary.

## Context

- `pre-commit` configuration is maintained per-plugin
- Not ideal because part of the idea of a monorepo is that configuration for consistent styling, etc. can be shared.
- pre-commit doesn't have first-class monorepo support (e.g. support hierarchical config); see the https://github.com/pre-commit/pre-commit/issues/466#issuecomment-274282684 on monorepo support
- Having .pre-commit-config.yaml at the root of the repo is also recognizable by other tools, such as pre-commit.ci https://github.com/kedro-org/kedro/issues/1598.

**Comment by SajidAlamQB** [comment]
Steps to complete:

- Move the existing `.pre-commit-config.yaml` files to the root of the repository and merge all the `.pre-commit-config.yaml` files into a single file at the root level. Ensure that all hooks and configurations are included in the merged file.

- Update the merged `.pre-commit-config.yaml` to use path filters. For each hook, add the files and/or exclude keys with appropriate regex patterns to specify which plugin the hook should run on.

- Test the updated pre-commit configuration to ensure that the hooks are running as expected and only on the specified files.

**Comment by merelcht** [comment]
I also noticed that we don't have `mypy` as part of the pre-commit setup of `kedro-plugins`. It would be good to add that as part of this ticket.

**Comment by AhdraMeraliQB** [comment]
As the mypy setup is a bit more substantial, I have moved it out of the scope for this ticket and described it separately in #2697; ideally #2156 would be completed first and that updated setup can thenn be applied to `kedro-plugins`.

**Comment by merelcht** [comment]
Completed in https://github.com/kedro-org/kedro-plugins/pull/259
