### ISSUE TITLE
Maximise our community standards rating by setting up a security policy

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#2338]
GitHub outlines a set of steps to maximise an open source repository's [Community Standards rating](https://github.com/kedro-org/kedro/community). We need to set up a security policy to hit 100%.

**Comment by noklam** [comment]
Maybe useful to look at https://github.com/google/oss-vulnerability-guide to find some inspiration.

**Comment by astrojuanlu** [comment]
Extra context from #3427:

> ## Description
> 
> I think we can improve our security scores and create a `SECURITY.md` document for Kedro, Kedro-Viz, Kedro-Starters and Kedro-Plugins.
> ## Context
> 
> It will improve our scores on [Snyk](https://snyk.io/advisor/python/kedro).
> ## Possible Implementation
> 
> Click on the security tab and set it up.

---

> Link: https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository
