### ISSUE TITLE
Investigate CI setup and identify flaky tests

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#2339]
## Description

Previously we have had some flaky tests on the CI (most recently the Windows e2e jupyter tests) that will occassionally fail not because the code doesn't work, but because the test is not dependable. We should not be having such tests in our CI setup; flaky tests can block releases and general progress from being achieved.

The purpose of this issue to identify these tests so that we can go ahead and rewrite/refactor them to achieve a good CI state.

**Comment by merelcht** [comment]
Could we use CCI features to detect flaky tests? See discussion in https://github.com/kedro-org/kedro/issues/2340#issuecomment-1450590592

**Comment by merelcht** [comment]
Closing this because we've moved to Github Actions which is a lot more stable.
