### ISSUE TITLE
Rewrite e2e jupyter tests

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#2341]
## Description

The jupyter e2e tests are flaky. Recently [the tests started failing on the Windows CI](https://github.com/kedro-org/kedro/issues/2320), despite no changes being made to any of the components tested. Though resolved now, checking the test output shows that even when e2e tests pass, it's often the case that an error was thrown but resolved itself before the test timed out. This has been the case for some time, not just with the new fix.

Suspicions are that the step "Then jupyter <notebook/lab> should run on port 8888" in `jupyter.feature` is implemented poorly/incorrectly in `cli_steps.py`. This check should be rewritten such that the test becomes dependable and is less prone to failing randomly.

**Comment by SajidAlamQB** [comment]
We have temporarily fixed the issue in https://github.com/kedro-org/kedro/pull/2331 but the solution wasn't optimal. In this issue, we should also investigate this fix further.
