### ISSUE TITLE
Symlink resolution during configuration detection might break some CLI commands

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#2346]
## Description
While debugging another issue, I found an interesting behavior that only happens in very specific circumstances. Since [on macOS `/tmp` is a symlink to `/private/tmp`](https://apple.stackexchange.com/questions/1043/why-is-tmp-a-symlink-to-private-tmp), while trying to instantiate a `KedroCLI` object I was getting a long error:

```
In [2]: from kedro.framework.cli.cli import KedroCLI

In [3]: cli = KedroCLI("/tmp/test-kedro-ipython-regular/")
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
...
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: Source path '/private/tmp/test-kedro-ipython-regular/src' has to be relative to your project root 
'/tmp/test-kedro-ipython-regular/'.
```

which of course was addressed by using the resolved path instead:

```
In [10]: cli = KedroCLI("/private/tmp/test-kedro-ipython-regular/")

In [11]: cli
Out[11]: <KedroCLI None>
```

## Context
I guess this never happens in real life because of how the codebase calls the initializer, but looks like the brittleness could be averted by replacing `.resolve()` with `.absolute()` here:

https://github.com/kedro-org/kedro/blob/116ddd015e81d2a6930a0dfbe83e630e526634f4/kedro/framework/startup.py#L64

I'm not sure if there are other consequences potentially hidden. This line has been there "forever" (dc39a96fa386).

## Steps to Reproduce
(given above)

## Expected Result
The `KedroCLI` can be instantiated in paths regardless of symlinks.

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.4
* Python version used (`python -V`): 3.10.9
* Operating system and version: macOS Ventura 13.2.1

**Comment by merelcht** [comment]
Test if this also breaks datasets or only the CLI.

**Comment by noklam** [comment]
Opposite idea, what about we make sure both `project_path` and `source_path` are `resolved`?

**Comment by noklam** [comment]
Windows do have something similar to symlink, used to do that with Powershell

**Comment by astrojuanlu** [comment]
Another user affected by this on Windows: https://linen-slack.kedro.org/t/16006555/hello-everyone-anyone-ever-tried-using-prefect-on-their-pipe#2851de33-7433-4492-bd70-c551ad7b2422

```
Finished in state Failed("Flow run encountered an exception. ValueError: Source path 'C:\\Users\\KodeCraft-3\\AppData\\Local\\Temp\\tmpcc05q7ogprefect\\src' has to be relative to your project root 'C:\\Users\\KODECR~1\\AppData\\Local\\Temp\\tmpcc05q7ogprefect'.")
```

**Comment by astrojuanlu** [comment]
I think Prefect specifically might be generating these temporary directories and hitting that error in the codebase.

**Comment by astrojuanlu** [comment]
Possibly related: `kedro package` also affected by this https://linen-slack.kedro.org/t/16156114/hi-kedro-team-i-am-trying-to-run-the-command-kedro-package-f#e74682ca-af3e-4eff-83d7-422ac0a574ab

**Comment by astrojuanlu** [comment]
Another user communicated in private that they're also having this problem:

```
Source path 'C:\Users\USERNAME\OneDrive - McKinsey & Company\Desktop\Code\kedro_test\spaceflight-pandas\src' has to be relative to your project root 'C:\Users\USERNAME\Desktop\Code\kedro_test\spaceflight-pandas'.
```

So this affects Windows too.

**Comment by noklam** [comment]
I didn't get any error by following the description, then I notice I need to create the project first to trigger the error.

```bash
cd /tmp
kedro new -n test-kedro-ipython-regular
```

```ipython
In [2]: from kedro.framework.cli.cli import KedroCLI

In [3]: cli = KedroCLI("/tmp/test-kedro-ipython-regular/")
```
>> ERROR
