### ISSUE TITLE
Discuss what to do with the oldest 6 pull requests

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2348]
## Description
Our `main` has 6 old pull requests that have been open between April and November 2022. Shall we attempt to deal with some of them?

## Context
It will bring our Snyk score up and also look better to the community to see that we move on PRs when they come in.

## Possible Implementation
Close anything outstanding. It's still there, and we can ticket any future work that revives them.

## Possible Alternatives
Pick them up into new tickets and complete them in an upcoming sprint.

**Comment by merelcht** [comment]
There's just one more PR open of these old ones which is https://github.com/kedro-org/kedro/pull/2041 and will be discussed in grooming/tech design!
