### ISSUE TITLE
Mermaid diagram for deployment guide isn't rendering

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2351]
## Description
In 0.18.1 we had a graphic at [the bottom of the deployment guide](https://kedro.readthedocs.io/en/0.18.1/deployment/deployment_guide.html#deployment-choices)

In 0.18.2 it looks like this was replaced by a mermaid graphic ([Rendered the deployment guide flowchart as a Mermaid diagram, and added Dask.](https://github.com/kedro-org/kedro/releases/tag/0.18.2))

I don't know if this has ever worked on RTD though, since the same page for 0.18.2 isn't showing a rendered graphic (to me, at least, on latest Chrome, latest M1 MacOS) https://kedro.readthedocs.io/en/0.18.2/deployment/deployment_guide.html#deployment-choices

@deepyaman I think this was your initiative originally (https://github.com/kedro-org/kedro/pull/1392) but I'm not heaping it on you to solve! I just wanted to get your perspective on what you saw on kedro.readthedocs.io when that release went out (did it work back then?) -- if you can recall :)

**Comment by stichbury** [comment]
Thanks to @ankatiyar for the spot -- it's been out for 6 months without anyone reporting AFAICT, so thanks for bringing it to my attention!

**Comment by deepyaman** [comment]
It definitely was working for the most part; I remember somebody--maybe @merelcht?--pointing out that it didn't render when there was highlight on the page, but it worked if you removed that.

I see an error in the console now saying:

> Refused to execute https://unpkg.com/mermaid/dist/mermaid.min.js as script because "X-Content-Type-Options: nosniff" was given and its Content-Type is not a script MIME type.

I haven't looked into it, but seems like somebody pointed out a similar issue (https://github.com/just-the-docs/just-the-docs/pull/857#issuecomment-1198404402) that should be addressable.

As a side note, may also be worth trying out https://github.com/mgaitan/sphinxcontrib-mermaid/pull/101, as pointed out by @AntonyMilneQB, although I don't expect it'll fix anything.

**Comment by stichbury** [comment]
Thanks @deepyaman that's very helpful. I wonder what changed to break this and whether we want to consider whether to fix it or remove for now, if this is something that changes beyond our control.

**Comment by deepyaman** [comment]
> Thanks @deepyaman that's very helpful. I wonder what changed to break this and whether we want to consider whether to fix it or remove for now, if this is something that changes beyond our control.

I'm biased since I spent a lot of time getting it to work, but I'd be in favor of trying to fix it. :) I assume it's a pretty minor fix.

**Comment by merelcht** [comment]
Yes we have a ticket for the highlighting problem: https://github.com/kedro-org/kedro/issues/1772 
AFAIK the diagram used to render fine without the highlight, so something must have changed..

**Comment by AntonyMilneQB** [comment]
I'm also in favour of trying to fix rather than remove because I think we should have more diagrams in our docs e.g. https://github.com/kedro-org/kedro/issues/1718. Or to find some alternative to mermaid that works better in sphinx, but I suspect mermaid is as good as we can get.

**Comment by stichbury** [comment]
I've noticed that the mermaid markdown isn't rendering even when you [view the markdown on Github](https://github.com/kedro-org/kedro/blob/main/docs/source/deployment/deployment_guide.md). 

I'd expect it to, given [this says it does](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/).
And here's a test to prove it should and does:

```mermaid
  graph TD;
      A-->B;
      A-->C;
      B-->D;
      C-->D;
```

So... maybe it's just the markdown that's now incorrect for some reason. Let me take a look and see if I can spot any glitches.

**Comment by deepyaman** [comment]
The Markdown won't render on GitHub; GitHub's support is something
different from what I remember.

**Comment by stichbury** [comment]
I've spent about 2 hours trying to get a basic Sphinx project (non-Kedro) created with `sphinx-quickstart` to use Mermaid with [the sphinx extension](https://github.com/mgaitan/sphinxcontrib-mermaid). I used Sphinx 5.3.0 and sphinxcontrib-mermaid 0.8. 

I didn't use the flowchart text but took the simple mermaid example above and I still couldn't get it to work. It could be me, but equally it could be just broken (or it could be both). I set a timebox and have run out of time now. The example is [on my repo](https://github.com/stichbury/kedro-projects/tree/main/mermaid-test) and I will return to this issue at some point, but not in this sprint.

**Comment by astrojuanlu** [comment]
As with all things Sphinx, the answer is buried in a pile of logs...

@stichbury I tried rendering your example on my machine, and it works after installing all the dependencies: 
![image](https://user-images.githubusercontent.com/316517/221158906-d12fc8e4-711d-4a24-9094-1fab9b7d862f.png)

And in fact, the result of not having mermaid-cli installed is this:
![image](https://user-images.githubusercontent.com/316517/221159374-13b746a0-e918-48d8-a6f2-849595f83d4a.png)

What's happening is that mermaid is not installed. See for example buried in the logs of https://readthedocs.org/projects/kedro/builds/19549544/:

```
writing... WARNING: command 'mmdc' cannot be run (needed for mermaid output), check the mermaid_cmd setting
```

So, I guess that installing mermaid-cli should do the trick.

**Comment by astrojuanlu** [comment]
Now I understand a bit better the differences between @stichbury test repo and ours. It turns out that you had `mermaid_output_format = 'png'`, which requires the mermaid-cli. However, Kedro uses the defaults, except for the fact that we inject the JS ourselves:

https://github.com/kedro-org/kedro/blob/9b65e480fd0b989626ea5c1af324022d2fb9559f/docs/conf.py#L602

I'm not touching that custom logic, but I'm fixing the URL in gh-2362.

**Comment by astrojuanlu** [comment]
Closed in gh-2362.
