### ISSUE TITLE
RFC: loop pipeline over result other pipeline?

### ISSUE THREAD

**Issue by ruben-s** [kedro-org/kedro#2354]
Hi,

I new to Kedro. I created a few simple pipelines and read the documentation (parameters, modular pipelines, create catalog entries via code, ...)

After reading the documentation I'm still not sure the idea I have is feasible in Kedro.
Can someone experienced please comment? Thx.

The Kedro project I have in mind would need to execute the flow as illustrated in below diagram:
With a first pipeline fetch a list of tables for which data needs to be extracted.
In a second pipeline loop over the list of tables to fetch metadata (i.e. list of columns) for a table.
Filter the set of columns.
Use the remainder of the columns in a select statement to fetch data from said table.
Write the fetched data to a file on Azure.

![loop_over_list](https://user-images.githubusercontent.com/7804142/220624294-f1828368-c1b2-4a97-9b77-2eff1560b1f4.PNG)

As stated it's not clear to me at the moment if such an approach is feasible with Kedro or not.
I think the Table List would be easy to consume in a next pipeline.
In that 2nd pipeline I could write a loop over the list, but unsure if that loop should be inside my code, or Kedro provides an iterator to execute a pipeline multiple times based on a list?
Each time the pipeline runs a new query is run against the database, so the node would need to pass the table name to the catalog entry (which is a generic database table). e.g. 

_The goal of the project is to easily extend the list of tables for which data needs to be fetched without extra code or config to be created._

Example Catalog:
```
df_amcs_sybase:
  type: src.utils.datasets.oracle_connector.OracleDataSet
  collist: [columnlist_string]
  tablename: [tablename]
  schemaname: [schemaname]
```
Example OracleDataSet:
```
class OracleDataSet(AbstractDataSet):
    def __init__(self, schemaname: str, tablename: str, columnlist: str):
        self.sql = f"select {columnlist] from {schemaname}.{tablename} "
        self.oracle = Oracle(project)  # fetched from our own libraries to set-up a db connection
        self.tablename = tablename
        self.schename = schemaname
        self.columnlist = columnlist

    def _load(self):
        with self.oracle as db:
            if db.has_table(table_name=self.tablename, schema=self.schemaname):
                return db.get_dataframe(self.sql)
            else:
                return pd.DataFrame()
```

Also once the data is fetched it should be written to a generic file:

Example Catalog entry:
```
df_generic_table_data:
  type: pandas.ParquetDataSet
  filepath: data/03_primary/df_[table_name].parquet
```
So the node should pass a tablename to the catalog item.

Is this feasible, or should the idea be approached differently?
All input/feed-back welcome.
Thx.

br,
 Ruben

**Comment by ruben-s** [comment]
related tickets:
#1044
#1784
#213
#138

https://waylonwalker.com/bind-dynamic-lambdas/
https://www.youtube.com/watch?v=7eRBNra6TVo
https://stackoverflow.com/questions/74178198/how-to-generate-kedro-pipelines-automatically-like-dataengineerone-does

**Comment by ruben-s** [comment]
Hi,

To whom it might concern, _my_ findings so far:

The original idea I had, to use the output dataset (a list of tables) from a first pipeline to use in a second pipeline to read from does not seem to be within the standard capabilities of Kedro.

My mental model: Kedro has a 2 pass approach: first pass set everything up (datasets in the catalog, nodes, pipelines (i.e. node interdependencies..) in some sort of execution plan,  and then execute on this plan.

As said a table as item in the output of the first pipeline, should be available as a dataset to read from in a second pipeline.
Perhaps this could be done by registering datasets in the catalog in the pipeline.py?
However that does not seem to be the way Kedro intends to be used.

So all set-up to iterate over needs to be present in the set-up phase.

Solution so far:

1.  Put the data to iterate over in parameters (instead of using a pipeline to fetch the data).  
This is possible as it's a limited (<20) list.

 2. With hooks create the necessary datasets based on the parameters.   In this way it is not needed to manually create catalog.yml entries for each table to read (on-prem db) from and write to (parquet file on Azure).  
Cfr. https://stackoverflow.com/questions/74357203/how-can-i-register-kedro-data-catalog-programmatically-in-kedro-0-18

3.  Based on the same set of parameters, iterate over said parameters to create a list of nodes in a pipeline that use the datasets as registered with the hooks.

pipeline.py code looks like:
``` 
nodes_list = []
tables = conf_parameters['tables']

for table in tables.keys():
    partitions = tables[table]['partitions']
    for partition in partitions:
        schema = tables[table]['schema']
        db_table_partition = f"df_dwh-{schema}-{table}_{partition}"
        azure_dataframe_partition = f"kedro-{schema}-{table}_{partition}.parquet"
        nodes_list.append(node(
            inputs=db_table_partition,
            func=pass_dataframe_with_gdpr_safe_columns,
            outputs=azure_dataframe_partition,
            name=f"load_{table}_{partition}"
            )
        )

def create_pipeline(**kwargs) -> Pipeline:
    return pipeline(nodes_list)

``` 

This works for me. YMMV

Note: in kedro viz for the generated pipeline the node is not linked to the output. It is linked to the input but not the output. Not found out why yet.

br,
 R.

**Comment by astrojuanlu** [comment]
Hi @ruben-s, thanks a lot for sharing your thoughts and sorry we didn't respond to the original issue!

I'll let others from the engineering team chime in, but I'd say the Kedro catalog is not really amenable to dynamic datasets. Do you think [modular pipelines](https://docs.kedro.org/en/stable/nodes_and_pipelines/modular_pipelines.html) could fit your use case?

**Comment by astrojuanlu** [comment]
To note, possibly similar to https://github.com/kedro-org/kedro/issues/1993 as well

**Comment by ruben-s** [comment]
Hi @astrojuanlu,

to be honest I do not believe modular pipelines are relevant here. The problem seems to lie in what you also identify as "I'd say the Kedro catalog is not really amenable to dynamic datasets".

I'm thinking to try and register the required datasets in the pipeline itself instead of in the hooks.  
It probably won't win any beauty prizes but perhaps it might work?

br,
 Ruben
