### ISSUE TITLE
[BUG] Passing runtime nested params to `kedro run --params` overwrites params from config files in latest release

### ISSUE THREAD

**Issue by tsanikgr** [kedro-org/kedro#2357]
Hello team - nice to be back in these discussions :)

## Description
There was a regression in the latest release (0.18.5), which introduced `OmegaConf` for parsing parameters provided to the `kedro run --params`.

More specifically, in previous versions

```kedro run --params foo.bar=a```

was properly merged with an existing parameter ```{"foo": {"baz": 1}}```.

Now, `kedro.framework.cli.hooks.utils._split_params` returns an `omegaconf.DictConfig` object (rather than a plain dictionary), and the second part of the if clause [here](https://github.com/kedro-org/kedro/blob/45c345d5a8109938e2735c1056a62182eb85d2f3/kedro/framework/context/context.py#L157) returns false:

```python
if isinstance(old_dict[key], dict) and isinstance(value, dict):
    _update_nested_dict(old_dict[key], value)
```

Which means that after merging we get 
```
{"foo": {"bar": a}}
```

instead of the expected

```
{"foo": {"bar": a, "baz": 1}}
```

I could open a PR to fix but it ll take way longer that letting you fix it :)
In the meantime I 've got a local workaround by subclassing `KedroContext` and casting params to a dict!

**Comment by tejaassolanki** [comment]
This is also a problem at the line [here](https://github.com/kedro-org/kedro/blob/94e87ef6b5a7eee1021a877d90691e070b6d3220/kedro/framework/context/context.py#L326) 
The run time params provided through
`kedro run —params`
are an instance of `omegaconf.dictconfig.DictConfig` even when the configloader is not set to OmegaConf.

Thus, the params are not added to the catalog which fails overriding them from a parameters file and also failure of the pipeline itself.

This is my first ever comment on an open source project. Please feel free to correct me.

**Comment by merelcht** [comment]
Hello @tsanikgr nice to see you on here! Even if it's to report a bug 😂  Thanks for reporting this and also thank you @tejaassolanki to report your findings. We will have a look at this asap!
