### ISSUE TITLE
Can the cancellation out of telemetry not give an exception or a better one?

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2365]
A while ago, @astrojuanlu reported this:

> With a global installation of Kedro (I used `pipx`), `kedro info` behaves differently whether a project `.venv` is activated or not 
> 
> - Without it: just display the Kedro version
> - With it: prompts for telemetry collection
>     - The options are `y` and `N`, but it's not clear if they're definitive for the project or not, so I did `Ctrl+C` and a 
> somewhat ugly error message appeared: `[12/14/22 16:46:13] WARNING  Failed to confirm consent. No data was sent to Heap. 
> Exception:  plugin.py:259`
> 

This may be one for @amandakys to take a look at?

**Comment by astrojuanlu** [comment]
This is a petty problem probably nobody cares about, and 8 months in _I_ don't care about it that much 😄 safe to close
