### ISSUE TITLE
Remove the Kedro architecture page from the documentation

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2368]
## Description
I don't see that the [Kedro architecture page](https://kedro.readthedocs.io/en/latest/faq/architecture_overview.html) has much that is useful to contribute. It has less than 3000 page views in a year and I don't really know what it is documenting. 

It may be that we need a way to illustrate the overall system, and perhaps a mermaid graphic (and then a reorganisation of the docs to reflect that graphic) would be a good way to do it. However, I don't see what we have as valuable and suggest that we remove it. Maybe we could write a blog post about the architecture of Kedro at a later stage.

**Comment by astrojuanlu** [comment]
I think we should put this, and possibly other pages, in a Developers Documentation page, that is more for contributors (even for ourselves). This is what we did at RtD, see https://docs.readthedocs.io/ vs https://dev.readthedocs.io/ (and discussion at https://github.com/readthedocs/readthedocs.org/pull/8751)

**Comment by astrojuanlu** [comment]
(Alternatively we could opt for something completely different for the dev docs, for example using the GitHub wiki)
