### ISSUE TITLE
Separate dev docs from user docs

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#2376]
## Description
Remove development docs (how to contribute, principles, FAQs, etc) from the user docs (currently living under https://kedro.readthedocs.io/).

## Context
Users and contributors are very different user personas and have different needs, and this should be reflected in the documentation. We could be moving the dev docs to a separate Read the Docs site or even GitHub wiki. Benefits:

- Surface area of the user docs is smaller.
- Search results are more meaningful.
- Dev docs don't need to be versioned, since they usually contain policies and procedures that don't change a lot over time _and_ it's not important to see how they looked like in a past version.
- Dev docs could live closer to the source code (for example on GitHub wiki).

## Possible Implementation
Move dev docs to GitHub wiki.

## Possible Alternatives
- Move dev docs to a separate Read the Docs site. There are tricks to have 2 RtD projects under the same repository, but they are quite hacky (see https://github.com/readthedocs/readthedocs.org/pull/8751 for example). Alternatively it could be a separate repository. Sounds too much of a hassle for something like this.
- Don't do anything. This would be very much less than ideal.

**Comment by stichbury** [comment]
I'd definitely be keen to see these on the wiki to remove a barrier to contribution that exists for the community (the PR process).

**Comment by astrojuanlu** [comment]
Only missing bit is https://docs.kedro.org/en/stable/contribution/

**Comment by stichbury** [comment]
@astrojuanlu I'm thinking I may come back to this ticket in an upcoming sprint and move most of the contribution section onto the wiki (except for the maintainer list for the TSC process compliance). If you think it's worth exploring further I'll flesh out a set of changes here before I dive in and do them, and we can review.

**Comment by astrojuanlu** [comment]
Good opportunity to publish our release checklist as well: https://mckinsey.atlassian.net/wiki/spaces/CAI/pages/446826369/Release+step-by-step+checklist+Kedro (internal link)

**Comment by stichbury** [comment]
I'm removing this from the current sprint as it isn't a high priority for docs right now.

**Comment by stichbury** [comment]
This is now done (#2667 and related tickets). The only developer documentation outstanding are the TSC page (which has to sit behind a sign-off system for voting purposes) and a landing page for indexing purposes.
