### ISSUE TITLE
Update docs to remove mentions of `pkg_resources`

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#2391]
## Description
Kedro uses `pkg_resources` to register plugins:

https://github.com/kedro-org/kedro/blob/200ebdb2e80dc9b8ce2d523593815558cae82c69/docs/source/extend_kedro/plugins.md?plain=1#L5-L7

However, setuptools has just officially deprecated `pkg_resources` (see https://github.com/pypa/setuptools/pull/3843):

> Although pkg_resources has been discouraged for use, some projects still consider pkg_resources viable for usage. This change makes it clear that pkg_resources should not be used, emitting a DeprecationWarning when imported.

and:

> Use of `pkg_resources` is deprecated in favor of [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html), and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Users should refrain from new usage of `pkg_resources` and should work to port to importlib-based solutions.

The time has come to drop `pkg_resources`.

Tangentially related: #2152 and #2280.

## Context
With the long support windows of Kedro, relying on deprecated functionality is a liability. The sooner we move away from it, the better.

In addition, importlib is much faster than `pkg_resources` (see discussion from 2017 https://github.com/pypa/setuptools/issues/926).

## Possible Implementation
[Entry points are fully standardized in PEP 621](https://peps.python.org/pep-0621/#entry-points), therefore `setuptools` is not a privileged build backend in this regard anymore (if you're curious, [this is the spec](https://packaging.python.org/en/latest/specifications/entry-points/)).

The way to go is to use `importlib.metadata`: https://docs.python.org/3/library/importlib.metadata.html#entry-points

## Possible Alternatives
- Don't do anything. Bad idea.
- Use a third party library like pluggy. Benefits seem unclear, plus other projects are considering leaving it behind too https://github.com/pypa/hatch/issues/752.

**Comment by AntonyMilneQB** [comment]
I am also not a fan of this at all (or other parts of the micropackaging workflow) and there are definitely cases where it breaks: https://github.com/kedro-org/kedro/issues/1536. Using requirements.txt to provide `install_requires` has always been wrong.

**Comment by noklam** [comment]
The doc should be fixed as we switch to `importlib` for a while. It is worth to mention `pkg_resources` is the major source of slowing down Kedro CLI (for a relatively small project). I remember it's a bit tricky to parse the requirement so I couldn't remove the dependency for `micropkg`. I would love to see `pkg_resources` disappear from the codebase otherwise. :)
* #1476
