### ISSUE TITLE
Consider more modern theme for docs

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#2394]
I find navigating the Kedro docs quite daunting, and I don't think trimming them down (as @stichbury and I are trying to do) will significantly improve the situation. For example, when landing to a random page, it's difficult to locate the subsections on the left menu (I usually `Ctrl/Cmd+F` or just scroll up and down until I find it).

As an idea, we could use the right hand side of the page to place an extra navigation menu, which is what many modern themes are doing. See for example:

### Furo

https://pradyunsg.me/furo/customisation/ (left + right navigation)

![image](https://user-images.githubusercontent.com/316517/223418755-b3ca31e9-dc2c-4053-aee4-81b11e7d48e5.png)

### PyData Sphinx Theme

https://pydata-sphinx-theme.readthedocs.io/en/latest/user_guide/layout.html (left + right + top navigation)

![image](https://user-images.githubusercontent.com/316517/223418698-d92c7a51-cfb3-47be-b22c-39a518d8ee85.png)

### Lutra

https://pradyunsg.me/lutra/porting/organise-configuration/ (left + right + top navigation)

![image](https://user-images.githubusercontent.com/316517/223418810-35b6004a-5b2f-4be8-95cd-ec2e21dac3be.png)

---

All these screenshots were taken from my laptop screen (no external monitor) at the default Zoom level. This is how Kedro landing looks like as a comparison:

![image](https://user-images.githubusercontent.com/316517/223418946-70955261-8dca-4632-b900-60c04a8bdf0d.png)

We are using a highly customized version of html_theme = "sphinx_rtd_theme", which is quite responsive on mobile and was much better than the average Sphinx theme when it was created. However, it is known to waste lots of horizontal space and we kind of inherited that (see this issue from 2016 https://github.com/readthedocs/sphinx_rtd_theme/issues/295, _ahem_ 7 years ago).

(Potentially overlaps or conflicts with #2072)

**Comment by yetudada** [comment]
Ah, this ties in with the branding workstream. We're going to do an overhaul of the docs as one of the outputs from that workstream.

**Comment by stichbury** [comment]
Came here to say this. I agree but (a) we need to decide a docs toolchain & host and (b) do the rebranding. As a more temporary step to help reading, any extensions that help (like a floating table of contents on the RHS) would be worth considering, but otherwise let's prioritise #2072.

**Comment by datajoely** [comment]
I'd also validate how much of a pain migrating to MkDocs would be, here's a lovely example:
https://textual.textualize.io/api/app/

**Comment by stichbury** [comment]
We are going to pick this up in the sprint w/c 17th April

**Comment by astrojuanlu** [comment]
OMG https://sphinxawesome.xyz/

**Comment by datajoely** [comment]
> OMG https://sphinxawesome.xyz/

Wow! They managed to get search to be useful too, that's all I really really like about mkdocs

**Comment by astrojuanlu** [comment]
No wonder - the person who created the theme works at Algolia 😄

**Comment by astrojuanlu** [comment]
@amandakys was already working on a redesign of the docs so this is still pretty much desired. It will not only be a theme change though, but will also touch the information architecture and other things.

Let's continue the discussion in https://github.com/kedro-org/kedro-viz/issues/1474

**Comment by stichbury** [comment]
Shall we close this one then? I'll leave you to decide @astrojuanlu as the creator.

**Comment by astrojuanlu** [comment]
Most of the info is on the other issue anyway, so I'll close this one.
