### ISSUE TITLE
Inform users about not using `--async`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2405]
## Description
As discussed in https://github.com/kedro-org/kedro/issues/2036#issuecomment-1460425776 there's a possibility that users aren't aware of the `--async` feature. Instead of only logging that the async is enabled when it is, change the logging to mention that async isn't being used by default and offer steps on how to use it. 

## Context
https://github.com/kedro-org/kedro/issues/2036

## Possible Implementation
Message could be: "Asynchronous mode is disabled for loading and saving data. Use the `--async` flag for potential performance gains. https://docs.kedro.org/en/stable/nodes_and_pipelines/run_a_pipeline.html#load-and-save-asynchronously"
(Not sure if a link in logs is good practice though.. )

**Comment by AntonyMilneQB** [comment]
A link in logs is fine, and rich should even render it nicely and make it clickable 🙂
