### ISSUE TITLE
Make sure Kedro custom Jupyter Kernel works on platform like SageMaker

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2412]
@AntonyMilneQB 

On SageMaker Studio there is an option to select Kernel as it is build on top of JupyterLab.
![image](https://user-images.githubusercontent.com/18221871/224698048-13dab4c3-a597-42ff-bd47-8d21b1a47983.png)

However, it doesn't work as expected. The kernel is just hanging.

![image](https://user-images.githubusercontent.com/18221871/224698244-15a1b2f4-a678-48d9-be4a-0df44caba54f.png)

It's possible to have a custom Kernel but it uses LifeCycle Configuration Script. I have a quick glance it should work similarly as it used this line to set up the kernel.

`python -m ipykernel install --user --name "$BASENAME" --display-name "Custom ($BASENAME)"`

https://docs.aws.amazon.com/sagemaker/latest/dg/nbi-add-external.html.

I am opening this as a separate issue as I think it would be quite challenging to solve it across different platforms (i.e. Databricks/SageMaker/AzureML). But until then the command may not be too useful.

_Originally posted by @noklam in https://github.com/kedro-org/kedro/issues/2353#issuecomment-1466036805_

## Description
Related #2353
`kedro jupyter setup` `kedro jupyter notbeook` `kedro jupyter lab` both setup a custom Jupyter Kernel. In the background it loads up the `kedro.ipython` module automatically, which is equivalent to run `%load_ext kedro.ipython` in a notebook cell.

This works nicely locally, or even JupyterHub. However, it does not run smoothly on Notebook base platform like SageMakers, Databricks. Particularly, the `kedro jupyter setup` is useful to be used for these notebook platforms, as the Jupyter instance is managed and users should not launch a separate Jupyter server themselves.

## Checklist
- [ ] Figure out how it can work on these platform
- [ ] Update the documentation in [Kedro and Jupyter Notebook](https://docs.kedro.org/en/stable/notebooks_and_ipython/kedro_and_notebooks.html#useful-to-know)

**Comment by astrojuanlu** [comment]
Curious @noklam, does `%load_ext kedro.ipython` work on SageMaker?

**Comment by noklam** [comment]
@astrojuanlu I haven't tested it, but it works on Databricks so it should work on SageMaker too as it's not platform specific.

**Comment by AntonyMilneQB** [comment]
Just to add something about Databricks here. From memory you can execute the Python API `jupyter_client.KernelSpecManager` from a databricks notebook to list available kernels etc., and the kedro one will appear there. So the underlying Python required to handle different kernels is all there on Databricks, and I believe the kernel is created successfully. Hence it's "just" a question of how to activate the kernel on Databricks.

(From memory I also thought you could just select a custom kernel on Databricks though, which is apparently not the case, so I might be wrong here again...)

**Comment by yetudada** [comment]
<img width="423" alt="Screenshot 2023-06-30 at 15 05 11" src="https://github.com/kedro-org/kedro/assets/43755008/7d76edc3-16ce-48ea-b1e4-75848c0a9e5a">

Also in scope, making sure that `%run_viz` works on SageMaker.

**Comment by noklam** [comment]
Potentially useful?
https://medium.com/@haridada07/creating-persistent-python-kernels-for-sagemaker-63993138ae50

**Comment by astrojuanlu** [comment]
Also, a user was confused about this today https://www.linen.dev/s/kedro/t/13539901/hi-team-i-m-working-in-a-sagemaker-notebook-which-is-in-the-#9e4405fc-878e-4d24-a140-7975a651cdcc cc @matescharnitzky

**Comment by astrojuanlu** [comment]
Maybe we should favour `%load_ext kedro.ipython`

**Comment by astrojuanlu** [comment]
In #2777 we already made `%load_ext kedro.ipython` more prominent and we haven't heard complaints about this in a while. Closing this issue for now.
