### ISSUE TITLE
Use `pyproject.toml` instead of `setup.py` for `kedro micropkg`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2414]
## Description
Inline with modernising the packaging/setup in Kedro to use `pyproject.toml`. 

## Context
Move along with the rest of the python community. 

## Possible Implementation
Ideally implement in a backwards compatible way to look for `setup.py` first and if that's not available use `pyproject.toml` in the `0.18.X` series. Then in `0.19.0` remove support for the `setup.py` way. This is not as important as for `kedro package`.

**Comment by astrojuanlu** [comment]
I think we should address gh-2542 and gh-2567 before or at the same time as this issue.
