### ISSUE TITLE
Add support for pandas 2.0

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2416]
It looks like [pandas 2.0.0 is slated to be released in March 2023](https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html)! Given that pandas-oriented workflows are very common with Kedro, including everything from starters like `pandas-iris` and `spaceflights` to the slew of pandas datasets, it makes sense that users should be able to use the latest and greatest pandas has to offer.

It looks like support for pandas 2.0 is not as trivial as bumping the upper bound; for example, [initial exploration](https://github.com/kedro-org/kedro-plugins/pull/123) shows that libraries like PyArrow will need to have their dependencies resolved. It's also possible not all integrations will be able to include pandas 2.0 support from the start, but we should try to relax as much as possible.

**Comment by deepyaman** [comment]
From https://github.com/kedro-org/kedro-plugins/pull/123, for visibility:

> For now, I've pinned test_requirements.txt to `pandas==2.0.0rc0` (to avoid having to `pip install --pre`), and verified that I can make modifications to get tests to pass. I'll put this on hold until pandas 2.0.0 is actually released.
> 
> I assume bandit is failing because it can't find the pandas release candidate?

Actual effort should not be that high once it's released, I hope, now that have worked things out with the release candidate. 🤞
