### ISSUE TITLE
Unable to save versioned dataset in a google cloud bucket 

### ISSUE THREAD

**Issue by fernandoferreira-me** [kedro-org/kedro#2419]
## Description
Unable to save versioned dataset in a google cloud bucket 

## Context
Tried to store a parquet file on google cloud bucket using versioned True.

## Steps to Reproduce
Add versioned: true 
and  save a datafraome

## Expected Result
a file should be created. 

## Actual Result
DataSetError: Cannot save versioned dataset `file.parquet` to `bucked/file.parquet/YYYY-MM-DDThh.mm.ss.sssZ` because a file with the same name already exists in the directory. This is likely because versioning was enabled on a dataset already saved previously. Either remove `file.parquet` from the directory or manually convert it into a versioned dataset by placing it in a versioned directory (e.g. with default versioning format

**Comment by noklam** [comment]
As you have notice if you have a file with the same name, it’s not possible to create a directory. You need to decide removing the dataset or renaming it. If you enabled versioning from the beginning it should work.

**Comment by fernandoferreira-me** [comment]
Sorry if I wasn't clear, but there is no file created before. I mean, there is no `file.parquet` located at the bucket. So, it is the first attempt of creating a file and the error is thrown

**Comment by noklam** [comment]
Are you still unable to create the file? What if you turns off the versioning would it work?

**Comment by RaulAlexandreMatos** [comment]
> Sorry if I wasn't clear, but there is no file created before. I mean, there is no `file.parquet` located at the bucket. So, it is the first attempt of creating a file and the error is thrown

Have the same problem with AWS S3

**Comment by noklam** [comment]
Can you provide more information including example of your catalog.yml.

Also make sure you have the right permission on the bucket. You will need the **ListObjects**  permission otherwise Kedro cannot see what's available in the directory.

**Comment by merelcht** [comment]
I'll close this ticket now due to inactivity. @fernandoferreira-me feel free to re-open if you need further support! 🙂
