### ISSUE TITLE
Garden the Kedro team space on Confluence ready for migration

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2420]
At some point in Q2, Kedro's Confluence space will be migrated. We don't want to take it wholesale as is because some of the content is old and should either be deprecated or updated. There may also be some that should be public for our community rather than behind the iron curtain.

So there are several tasks here:

1. Review existing pages on the Confluence space and decide which are so out of date that we need to remove them
2. Update any pages that are valuable but need modification and ensure all pages left on the site are accurate
3. Transfer anything useful that could be public to Kedro's GitHub organisation (e.g. wiki or discussion pages) or website and delete the page.
4. Reorganise what is left so that migration takes useful content in a sensible IA.

**Comment by astrojuanlu** [comment]
The migration has happened.
