### ISSUE TITLE
Standardise terminology for starters 

### ISSUE THREAD

**Issue by amandakys** [kedro-org/kedro#2422]
## Introduction

We refer to Kedro starters interchangeably as starters, templates or starter templates. 

It would be good to standardise how we refer to them across the CLI and the docs 

## Design

I propose changing `starter` to `template` as it is the more common name for what they are. alternatives could include: 
- quickstart
- samples (used by Azure and Google) 

This would change the CLI command `kedro new --starter=spaceflights` to `kedro new --template=spaceflights`

## Rollout

This change can be made as part of the rollout of the new `kedro new` flow proposed in #2388

**Comment by datajoely** [comment]
Tangentially, I've always disliked that `kedro starter list` and `kedro new --starter` are completely disconnected

**Comment by DimedS** [comment]
Discussed on 18.12.23 during Issue Grooming. We decided not to proceed with that as it appears to be no longer relevant. Additionally, it was not included in the 0.19 release.
