### ISSUE TITLE
Eliminate the need of having all datasets defined in the catalog

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2423]
## Description
Users struggle with ever increasing catalog files:
https://github.com/kedro-org/kedro/issues/891
https://github.com/kedro-org/kedro/issues/1847

Current "solutions":
- Use yaml anchors: https://www.educative.io/blog/advanced-yaml-syntax-cheatsheet#anchors
- The `TemplatedConfigLoader`
- Use the `TemplatedConfigLoader` with Jinja2: https://docs.kedro.org/en/stable/kedro_project_setup/configuration.html#jinja2-support

Instead of allowing anchors or loops in config let's just tackle the need of having so many datasets defined in the catalog in the first place. 

## Context
The new `OmegaConfigLoader` doesn't currently allow the use of yaml anchors (the omegaconf team discourages people to use this with omegaconf: https://github.com/omry/omegaconf/issues/93) or Jinja2. While Jinja2 is very powerful, we've always had the standpoint as a team that it's better to not use it, because it makes files hard to read and reason about. Jinja2 is meant for HTML templating, not for configuration. 

In order to make `OmegaConfigLoader` a suitable replacement for the `ConfigLoader` and `TemplatedConfigLoader` we need to find another solution to reduce the size of catalog files. 

## Possible Implementation
This is an idea from @idanov (written up by me, so I hope I have interpreted it correctly 😅 ) :

In every runner we have a method to create a default dataset for datasets that are used in the pipeline but not defined in the catalog:

https://github.com/kedro-org/kedro/blob/8acfb2a67049cce8f8d9126fc2373cb40e26b0d8/kedro/runner/sequential_runner.py#L32-L43

We can allow users to define what a "default" dataset should be so that in the catalog they only need to specify these default settings and Kedro would then create those without needing them to be defined in the catalog. The default dataset definition could then look like something like this:

```yaml
default_dataset: 
  type: spark.SparkDataSet
  file_format: parquet
  load_args:
    header: true
  save_args:
    mode: overwrite
```

And any dataset used in the pipeline, but not mentioned in the catalog, would get the above specifications. 

### Extra info
I collected several catalog files from internal teams to see what patterns I could find in there. I think these will be useful when designing our solution. https://miro.com/app/board/uXjVMZM7IFY=/?share_link_id=288914952503

**Comment by datajoely** [comment]
Would you only allow a singular `default_dataset`?

**Comment by deepyaman** [comment]
> We can allow users to define what a "default" dataset should be so that in the catalog they only need to specify these default settings and Kedro would then create those without needing them to be defined in the catalog.

Non-memory datasets need more information, like where you're going to store datasets and with what name. For example, Kubeflow Pipelines has the idea of `pipeline_root` ("The root path where this pipeline’s outputs are stored. This can be a MinIO, Google Cloud Storage, or Amazon Web Services S3 URI. You can override the pipeline root when you run the pipeline.") But if users want control over specifically what their file name is, they don't, and instead it becomes something like the catalog entry name.

**Comment by datajoely** [comment]
```yaml
"{root_namespace}.{*}@{spark}":
  type: spark.SparkDataSet
  filepath: data/{chunks[0]}/{chunks[1]}.parquet
  file_format: parquet
```

@idanov  - this is a work of art, I'm sold.

What I would ask is that we consider introducing an [equivalent of](https://docs.getdbt.com/reference/commands/compile) `dbt compile` so the users have a mechanism for reviewing what is rendered at runtime versus what they configure at rest.

**Comment by idanov** [comment]
@AntonyMilneQB shared a nice alternative pattern-matching syntax here, which uses reverse Python f-strings format, which is definitely going to do the job and help us avoid creating a homebrew patter-matching language: https://github.com/r1chardj0n3s/parse

@datajoely we could do something like that, inspired from what @WaylonWalker created sometime ago: https://github.com/WaylonWalker/kedro-auto-catalog

Another option is a CLI command giving you the dataset definition per dataset name, something like `kedro catalog get <dataset-name-of-interest>`.

**Comment by AntonyMilneQB** [comment]
Before we get carried away with using [`parse`](https://github.com/r1chardj0n3s/parse) to do the pattern matching we should definitely do some careful thinking about how this would work in practice. It seems like a great solution in theory (it's very lightweight and simple, gives you named chunks, everyone who knows Python should know the mini-language already), but when I've used it before it was a bit tricky to get right. Here's what the above example would look like:

```
"{root_namespace}.{dataset_name}@spark":
  type: spark.SparkDataSet
  filepath: data/{root_namespace}/{dataset_name}.parquet
  file_format: parquet

# would parse as follows
germany.companies@spark:
  type: spark.SparkDataSet
  filepath: data/germany/companies.parquet
  file_format: parquet
```

All good so far, but what happens in this case?
```
"{dataset_name}_{layer}":
  type: spark.SparkDataSet
  filepath: data/{root_namespace}/{dataset_name}.parquet
  layer: raw

# would parse as follows
big_companies_raw:
  type: spark.SparkDataSet
  filepath: data/companies_raw/big.parquet
  layer: companies_raw
```

...which is probably not what you wanted. The reason for this is that ["`parse()` will always match the shortest text necessary (from left to right)"](https://github.com/r1chardj0n3s/parse#potential-gotchas). This is fine but would need explaining.

We also need to be wary of how to handle multiple patterns that match. e.g. let's say you want to override the default. Then you should be able to do something like this:

```
"{root_namespace}.{dataset_name}@spark":
  type: spark.SparkDataSet
  filepath: data/{root_namespace}/{dataset_name}.parquet
  file_format: parquet

france.companies@spark:
  type: spark.SomethingElse
  filepath: other/data/france/companies.parquet
  file_format: parquet
```

Here `france.companies` should take precedence over the general pattern, so we can have a rule like "if two patterns match and there's no `{}` in one pattern, then that one is more specific and so wins". But how about in cases where multiple `{}` patterns match?

```
"{root_namespace}.{dataset_name}@spark":
  type: spark.SparkDataSet
  filepath: data/{root_namespace}/{dataset_name}.parquet
  file_format: parquet

"{dataset_name}@spark":
  type: spark.SomethingElse
  filepath: data/{dataset_name}.parquet
  file_format: parquet
```

Now `france.companies@spark` matches both entries, and it's not really clear which should win. Do we use the order the patterns are defined in the file to choose which wins? What about if the patterns come from a different file (since we merge multiple catalog.yml files together)?

All this is not to say that this solution is unworkable. I do think `parse` feels like a good fit here (after all, regex will suffer from similar problems), but that we really need to think about how it would work in practice.

**Comment by datajoely** [comment]
@AntonyMilneQB - thank you for this, it's really an excellent write-up. One push I would make is that we could manage this complexity by providing a live editor / prototyping space in Viz. 

I think it would massively improve the learning journey and help us get up and running quickly.

**Comment by datajoely** [comment]
Something like this https://textfsm.nornir.tech/#

**Comment by AntonyMilneQB** [comment]
@merelcht The `.` is not a specific pattern that should be matched - it's just a character in the string like anything else. Think of replacing it with the letter `A`:

```
In [2]: parse("{dataset_name}@spark", "france.companies@spark")
Out[2]: <Result () {'dataset_name': 'france.companies'}>

In [4]: parse("{dataset_name}@spark", "franceAcompanies@spark")
Out[4]: <Result () {'dataset_name': 'franceAcompanies'}>
```

One way around this is to add a [format specification](https://github.com/r1chardj0n3s/parse#format-specification) like this:

```
parse("{dataset_name:w}@spark", "france.companies@spark")
# No matches because . doesn't come under format w, which means Letters, numbers and underscore
```

But, by default, if you don't specify a format then it will just match anything.

This still feels better to me than regex but it is definitely not as simple as it might first appear.

@idanov also asked me to post the `make_like` example here - I'll do it in a second.

**Comment by merelcht** [comment]
@AntonyMilneQB 

I don't think it's possible to pass a value that needs to be interpolated to a resolver. In this prototype example below:

```
# Define the "template" entry - needs to be an actual valid catalog entry I think (?)
germany.companies@spark:
  type: spark.SparkDataSet
  filepath: ${make_filepath:${..dataset_name}}  # this won't work - I don't know what the right syntax is or even if it's possible
  file_format: parquet

# Define other entries that follow the same pattern
france.companies@spark: ${make_like: ${..germany.companies@spark}} 
uk.companies@spark: ${make_like: ${..germany.companies@spark}} 
italy.companies@spark: ${make_like: ${..germany.companies@spark}} 
```

`${make_filepath:${..dataset_name}}` isn't possible as far as I found. Only if you add the `dataset_name` as a key in the file as well, but that would defeat the purpose of generalising the value, because you'd then just have the same file path value for all countries.

**Comment by merelcht** [comment]
Summary of the **technical design** discussions we had on 22/3 and 30/3:

Through the discussions we've identified there are in fact three problems that are all related.

## Problems to address

1. Users don't like working with large + hard to maintain catalog files.
2. Users want to be able to have another default than `MemoryDataSet` for datasets not defined in the catalog.
3. Users need a way to keep constant/global values in one place to minimise mistakes e.g. typos and pass these in configuration files. [Add templating functionality to allow "global" values in the catalog in OmegaConfigLoader](https://github.com/kedro-org/kedro/issues/2175)

## Proposed solutions:

1.[ Dataset factories](https://github.com/kedro-org/kedro/issues/2423#issuecomment-1470784359): addresses problem 1 & 2
2. Omegaconf "make-like" resolver: turns out that this isn't a feasible solution. 

## Problem 1: points discussed
- General agreement that large catalog files is a valid problem and not only for QuantumBlack vertical teams.
- Users are reluctant to make use of modular pipelines because it increases configuration.
- General impression is that when users start working with Kedro they prefer readable (more verbose) catalog files, but the more they get used the Kedro the greater the need for features like templating and other tools that make the catalog more compact. 
- Concern with any solution to make the catalog more compact is **readability**. With existing solutions like Jinja2 and yaml-anchors it's also hard to understand what the "compiled" catalog looks like that's used by Kedro.
   - **Solution:**  add a mechanism to compile the catalog. Could be a CLI command similar to [`dbt compile`](https://docs.getdbt.com/reference/commands/compile)
- Whatever solution we go for, we will always allow the full fledged dataset definitions in the catalog, so users do not have to use the more compact syntax. 


## Problem 2: points discussed
- @WaylonWalker created a tool that allows to change the default: https://github.com/WaylonWalker/kedro-auto-catalog
   - This solution saves the datasets into a separate "default" catalog file, so it addresses problem 2, but not problem 1 because datasets still end up in the catalog.
   - AFAIK you can only add 1 default
- The datasets factories solution would address this problem.   

## Problem 3
Not yet addressed. 

## Other comments
- Omegaconf resolvers do allow for some reduction of the catalog content just like `yaml` anchors. 
- With custom resolvers power users can find ways to reduce their catalogs more by themselves.
- Perhaps it's not worth introducing this extra syntax if the `OmegaConfigLoader` leverages all resolver syntax properly. 

## Next steps

- [ ] Discuss problem 3 in the next technical design session: [Add templating functionality to allow "global" values in the catalog in OmegaConfigLoader](https://github.com/kedro-org/kedro/issues/2175)
- [ ] Through some quick experimenting we found that resolvers can be used in place of yaml anchors. What needs to be done to make this work in `OmegaConfigLoader`? Same solution as for [Add templating functionality to allow "global" values in the catalog in OmegaConfigLoader](https://github.com/kedro-org/kedro/issues/2175)?

> **Note** We need to do user testing to verify any solution we decide on.

**Comment by datajoely** [comment]
I know we don't want to - but I also think we need to ask, does our solution support dynamic pipelines? Our users, particularly those who care about this templating stuff are going to try that sort of thing very quickly.

**Comment by datajoely** [comment]
For a slightly 🌶️ comparison


|     |     |     |     |     |
| --- | --- | --- | --- | --- |
|     | Reduce the number Catalog Entry (How many top-level keys in the file)| Shorten Catalog Entry (How many lines for each Dataset) | Ability to Change Default DataSet | Constant/Global Value for all Configurations |
| Jinja2 (with .j2 template support) | ✅    | ✅   | ❌   |  ✅  |

**Comment by merelcht** [comment]
Feedback on the prototypes (https://github.com/kedro-org/kedro/issues/2423 + https://github.com/kedro-org/kedro/pull/2559) to be taken into account for the proper implementation:

- Do not call `catalog.list()` in the runner checks to determine if there's any missing inputs/datasets that need the default dataset, but instead create a new method to check if a dataset name exists in the catalog that finds any exact matches as well as pattern matches.
- Clarify to users that the default dataset creation will be replaced by any pattern with the following format:
```
{dataset}:
   .....:
  ......:
```
- We should properly design with new catalog CLI commands to add:
   - a command that ranks all patterns so a user can understand the priority matching order
   - a resolve command that shows the fully resolved catalog when all patterns are matched (this excludes the actual patterns for ease of reading)
- We should design a way of testing this functionality before releasing.
