### ISSUE TITLE
`PartitionedDataSet` and `SparkDataSet` interoperability issue

### ISSUE THREAD

**Issue by ianwhalenqb** [kedro-org/kedro#2424]
## Description
I'm trying to use `PartitionedDataSet ` with `PySparkDataSet`. Saving and loading causes `PartitionedDataSet` to read all of the underlying files generated by the pyspark `write` operation, which is not exactly what I'd want.

In general, it seems like `PartitionedDataSet` and `SparkDataSet` are not meant to play nicely together.

## Context
See below. 

### Path already exists issue

My data looks like this:

```
└── data
    ├── account.csv
    ├── transaction.csv
    └── loan.csv
```

I can then define my dataset like this:

```python
dataset = PartitionedDataSet(
    data_path,
    dataset={
        "type": "spark.SparkDataSet",
        "file_format": "csv",
        "load_args": {"header": True},
    },
    filename_suffix=".csv",
)
```

Calling `load` gives what I would expect:

```python
out = {name: loader() for name, loader in dataset.load().items()}
out
```

outputs:

```
{
    'account': DataFrame[...],
    'transaction': DataFrame[...],
    'loan': DataFrame[...],
}
```

Calling `dataset.save(out)` throws an error:

```bash
DataSetError: Failed while saving data to data set SparkDataSet(file_format=csv, 
filepath=...path.../account.csv, load_args={'header': True}, 
save_args={}).
path 
...path.../account.csv 
already exists.
```

### Loading from a previously saved dataset

Let's say we changed our `data_path` to somewhere new and saved things. The new directory would something look like:

```
├── account.csv
│   ├── _SUCCESS
│   ├── part-00000-a46eea9a-8d07-4bae-a02a-f2ba652dae8c-c000.csv
│   └── part-00001-a46eea9a-8d07-4bae-a02a-f2ba652dae8c-c000.csv
├── transaction.csv
│   ├── _SUCCESS
│   └── part-00000-fdf92d71-4634-4649-a752-441e76b9ce23-c000.csv
├── loan.csv
│   ├── _SUCCESS
│   └── part-00000-dc8e3779-57bc-4430-b400-059328de6dde-c000.csv
```

Calling `load` one more time gives:

```
{
    'account.csv/part-00000-a46eea9a-8d07-4bae-a02a-f2ba652dae8c-c000': DataFrame[...],
    'account.csv/part-00001-a46eea9a-8d07-4bae-a02a-f2ba652dae8c-c000': DataFrame[...],
    'transaction.csv/part-00000-fdf92d71-4634-4649-a752-441e76b9ce23-c000': DataFrame[...],
    'loan.csv/part-00000-dc8e3779-57bc-4430-b400-059328de6dde-c000': DataFrame[...],
}
```

Of course, these are the partitions from spark.

## Expected Result

From the second load, I would expect:

```
{
    'account': DataFrame[...],
    'transaction': DataFrame[...],
    'loan': DataFrame[...],
}
```

Just as I got in the first load.

## Actual Result

See above.

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): `0.18.4`
* Python version used (`python -V`): `3.8.16`
* Operating system and version: `macOS Ventura 13.2.1`

**Comment by noklam** [comment]
Will have a closer look, but there are good chance it doesn't play nice with Spark partition since the input/output structure is different here.

I suppose changing `spark.SparkDataSet` ->`pandas.CSVDataSet` would work fine in this case.

**Comment by ianwhalenqb** [comment]
@noklam absolutely, using `CSVDataSet` works as expected. Just wanted to report the weird interactions. Probably not the most common use case :)

**Comment by noklam** [comment]
As it expects homogenous data, but in this case the saving/writing isn't consistent.

To properly read output from Spark you will need extra argument to read from the folder level instead of per file.

**Comment by ianwhalenqb** [comment]
Makes sense! Happy to have this closed if the above is expected behavior.

**Comment by deepyaman** [comment]
Related:

* https://kedro-org.slack.com/archives/C03RKP2LW64/p1677525924480159
* https://kedro-org.slack.com/archives/C03RKP2LW64/p1673276124256309
* Probably many more :)

I actually didn't realize you could use `maxdepth` and `withdirs` in `load_args`, but that seems like a really clean solution @noklam. Do you think that would work for you @ianwhalenqb (assuming all the folders are at the same depth)?

**Comment by ianwhalenqb** [comment]
Yeah that makes total sense! I'll close this.
