### ISSUE TITLE
Divorce config loader from logging.yml

### ISSUE THREAD

**Issue by antonymilne** [kedro-org/kedro#2426]
> **Note**. Breaking, goes in 0.19.0.

Following https://github.com/kedro-org/kedro/issues/2281 we have decided that users will no longer be able to change logging configuration dependent on kedro run environment. This is a huge simplification and means that logging only gets configured _once_ in the kedro process with `LOGGING = _ProjectLogging()`.

There's a few things to be done here, but they all need to be done at the same time or it will be very confusing.

- [ ] Remove `KedroSession._setup_logging` and `KedroSession._get_logging_config` 🥳 
- [ ] Remove everything to do with logging from all config loaders (e.g. in `config_patterns` and docstring examples)
- [ ] Double check you've removed everything that needs removing by searching `logging` throughout the whole codebase. Note that `configure_logging` must _stay_ since it's needed by the parallel runner
- [ ] #2644
- [ ] Make sure you explain in the release notes migration guide that a custom logging file is now independent of kedro run environment and only used if `KEDRO_LOGGING_CONFIG` is set to point to it

**Comment by datajoely** [comment]
fantastic use of the verb
