### ISSUE TITLE
Improve documentation of PartitionedDataSet to include advance example of partitioning

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2430]
## Description
Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

Details: https://kedro-org.slack.com/archives/C03RKP2LW64/p1677525924480159

It's not very clear that users actually use `load_args` to support a different way of partitioning.

## Context
Why is this change important to you? How would you use it? How can it benefit other users?
* Improve Usage of `PartitionedDataSet` 
* Iterating through a directory is quite common for deep learning pipeline as u need to loop process data iteratively
* Many datasets come with a format of folders of folders of files (e.g. Image data)

**Comment by stichbury** [comment]
Probably a duplicate or superset of #1567

**Comment by astrojuanlu** [comment]
Agree, let's continue the conversation there.
