### ISSUE TITLE
Review community databricks contributions

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2449]
We have a few incoming contributions that impact our databricks solution:

* [Updated docs related to Databricks](https://github.com/kedro-org/kedro/pull/2448)
* [Databricks starter](https://github.com/kedro-org/kedro-starters/pull/120)
* [Databricks dataset -- merged](https://github.com/dannyrfar/kedro-plugins/tree/main/kedro-datasets/kedro_datasets/databricks)

We need to block out some time to determine how to merge/manage these contributions alongside our existing and ongoing work. This issue is for that, and will (hopefully) be picked up in the next sprint w/c 3rd April 2023)

**Comment by astrojuanlu** [comment]
This is done.
