### ISSUE TITLE
Revamp and simplify Sphinx documentation process

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#2454]
Lately we've been having some hiccups with the docs (https://github.com/kedro-org/kedro-plugins/issues/134, #2451, #2453) which are difficult to fix because building the full documentation locally without warnings is nearly impossible. In gh-2452 I ended up disabling the strict mode on Read the Docs to try to come back to these with more calm.

The amount of non-standard customization we're doing on our `docs/conf.py` is quite large. Parts of that are necessary (like installing `kedro-datasets` to a custom location until 0.19 is released, see gh-2006, gh-1651) but we should try to keep it to the minimum.

And finally, we are using a really old version of Sphinx, which prevents us from profiting from recent quality of life improvements, like https://github.com/sphinx-doc/sphinx/issues/9481 and https://github.com/sphinx-doc/sphinx/issues/7989.

Without the need of boiling the ocean, and in the broader context of gh-2025, I think we should:

- Remove unused extensions and configuration (low hanging fruit - this includes things like LaTeX conf, man pages conf, and so on)
- Upgrade to Sphinx 6 and docutils >= 0.18 (which requires updates to the CSS, otherwise the styles are not properly applied)
- Stop editing docstrins on the fly (make those changes to the docs directly) or replace that functionality with a third party extension, like https://sphinx-codeautolink.readthedocs.io/en/latest/:

https://github.com/kedro-org/kedro/blob/c144b8768a9a52275a93f8ba051c5b21bd8b4531/docs/conf.py#L354-L359

- Try to remove the need to move files around and remove directories before and after documentation builds:

https://github.com/kedro-org/kedro/blob/c144b8768a9a52275a93f8ba051c5b21bd8b4531/docs/conf.py#L496-L507

One more thing that could greatly improve the process, but that need some investigation, is moving away from `sphinx.ext.autosummary` and use either `sphinx-autoapi` or `sphinx-autodoc2` instead (probably the latter, since it can generate Markdown). The reason is that `autosummary` needs to _import_ the code, and therefore _all_ the dependencies of _all_ `kedro-datasets` need to be installed. On the other hand, `autoapi` and `autodoc2` use static analysis, and therefore don't need any of the dependencies installed.

**Comment by astrojuanlu** [comment]
First revamp happened in gh-2459. Pending:

- Attempt to move to `sphinx-autoapi` or `sphinx-autodoc2` to avoid having to install _all_ the datasets dependencies to build the docs (high priority)
- gh-2483 (high priority)

Then some low priority stuff:

- Update CSS to be compatible with Sphinx 6 and docutils >= 0.18 (low priority, could be overridden by #2394)
- Consider stop editing docstrings on the fly (low priority)

**Comment by stichbury** [comment]
Marking this a parent ticket for #2459

**Comment by astrojuanlu** [comment]
Maybe you meant some other issue? (That one is the PR we merged last week)

**Comment by astrojuanlu** [comment]
Another note to self: `sphinx-autoapi` cannot generate one page per class, as `sphinx.ext.autosummary` does, therefore even if it's technically feasible to migrate to it (did some successful local experiments), it would completely break the current URL structure https://github.com/readthedocs/sphinx-autoapi/issues/226

**Comment by stichbury** [comment]
Agreed, let's close this and keep those issues separate, not children of this one.
