### ISSUE TITLE
OmegaConfigLoader parameters does not propogate properly

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2458]
## Description
An user report this in Slack https://kedro-org.slack.com/archives/C03RKP2LW64/p1679502160140669

To summarise this, there are two potential issues here
1. Only top-level parameters are interpolated - any nested parameters will be an `OmegaConf` object instead - Functionally it will still works when accessing a group of parameters
2. CLI override `global` but the `global` isn't  propagate to the references

## Context
How has this bug affected you? What were you trying to accomplish?
1. is potentially a bug
2. Definitely a bug

## Steps to Reproduce
I created an example so you can clone and run with this command:
`git clone git@github.com:noklam/omega-nest-params-bug-demo.git`

```yaml
# parameters.yml
demo: ${global}

demo_nested:
  param: ${global}
```

```yaml
# parameters_global.yml
global: test_1
```

The function will simply print out the `parameters`.
```python
def demo_node(parameters, nested_parameters):
    pprint(parameters)
    print(parameters["demo_nested"]["param"])
    pprint(nested_parameters)
```

### Problem 1 - Only top-level parameters are interpolated
`kedro run`

#### Expected Result
```python
{'demo': 'test_1', 'demo_nested': {'param': 'test_1'}, 'global': 'test_1'}
test_1
{'param': 'test_1'}
```
#### Actual Result
```python
{'demo': 'test_1', 'demo_nested': {'param': '${global}'}, 'global': 'test_1'}
test_1
{'param': '${global}'}
```

This may not be a real problem, since when access `parameters["demo_nested"]["param"] it will still interpolate correctly. 
Two minor issues here:
1. This looks a bit weird when inspected since the printed object looks like `Dict[str]`, and force users to know more about `OmegaConf` since this parameters is returning some Omega's object instead of a real dictionary 
2. Technically if the function is expecting a dict `def some_fun(arg1: dict)`, is it the right thing to do to pass a `Omega` object? It may confuse static code analyzers like `mypy`, but I doubt it works with `kedro` anyway. 
The more problematic case will be when the function is doing some kind of type-checking `isinstance(arg1, dict)`, it will get it wrong. Arguably it makes the code more coupled with Kedro.

```python
    print(type(parameters))
    print(type(parameters["demo_nested"]))
    print(type(parameters["demo_nested"]["param"]))

<class 'dict'>
<class 'omegaconf.dictconfig.DictConfig'>
<class 'str'>
```

### Problem 2 - CLI override `global` but the `global` isn't  propagate to the references
`kedro run --params=global:test_2 `

#### Expected Result
```python
{'demo': 'test_2', 'demo_nested': {'param': '${global}'}, 'global': 'test_2'}
test_2
{'param': '${global}'}
```
#### Actual Result
```python
{'demo': 'test_1', 'demo_nested': {'param': '${global}'}, 'global': 'test_2'}
test_1
{'param': '${global}'}
```

Here the issue is `global` is override by CLI, but all the `${global}` reference is not. This probably has to do with the order of execution.

@merelcht

**Comment by MatthiasRoels** [comment]
I believe the reason why you still have 
```
    print(type(parameters))
    print(type(parameters["demo_nested"]))
    print(type(parameters["demo_nested"]["param"]))

<class 'dict'>
<class 'omegaconf.dictconfig.DictConfig'>
<class 'str'>
```
is because of this line: https://github.com/kedro-org/kedro/blob/main/kedro/config/omegaconf_config.py#L278

the proper way to cast an OmegaConf obj to a dict is something like this: https://github.com/MatthiasRoels/kedro-examples/blob/main/custom-configloader/src/prototype/lib/configloader.py#L246

**Comment by MatthiasRoels** [comment]
@noklam that is exactly what I am suggesting. The proper way to cast to a dict is with `to_container`. According to the docs at least. It makes sense that `dict` only casts the top level object to a dict while leaving the rest as an OmegaConf object…

**Comment by noklam** [comment]
@MatthiasRoels Ah awesome I was confused since you highlight something different. Thanks for the tip!

**Comment by MatthiasRoels** [comment]
@merelcht: ok but why would you return a `dict` in `load_and_merge_dir_config` instead of a DictConfig object? I think that if we could keep the config data format internally a `DictConfig` object and only cast it to a dict when returning from `__getitem__` (it does then resolve variable interpolation etc).

**Comment by MatthiasRoels** [comment]
Oh and thinking about the actual issue. This really **is** because we actually never use `OmegaConf.to_container`!

**Comment by noklam** [comment]
I don't think we want to support cross env interpolation, what's the difference of using globals then?

Keeping an internal copy sounds like a viable solution👍 I will need to do some testing.

**Comment by MatthiasRoels** [comment]
Well the difference with globals is that you can use globals with all config patterns whereas in this case, you can only do variable interpolation within the same config pattern.

**Comment by noklam** [comment]
I will break it down to individual issues since there are 3 things mentioned here. I will keep this issue for Problem 2 - since this is mainly what this issue about.

- [ ]  Problem 2 - CLI override `global` but the `global` isn't  propagate to the references (#2458)
- [ ] #2466 
- [ ] #2465
