### ISSUE TITLE
OmegaConfigLoader returns a DictConfig object instead of dictionary

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2466]
## Context
See parent issue #2458 

## Description
Short description of the problem here.

1. This looks a bit weird when inspected since the printed object looks like `Dict[str]`, and force users to know more about `OmegaConf` since this parameters is returning some Omega's object instead of a real dictionary 
2. Technically if the function is expecting a dict `def some_fun(arg1: dict)`, is it the right thing to do to pass a `Omega` object? It may confuse static code analyzers like `mypy`, but I doubt it works with `kedro` anyway. 
The more problematic case will be when the function is doing some kind of type-checking `isinstance(arg1, dict)`, it will get it wrong. Arguably it makes the code more coupled with Kedro.
Few possible outcome:
1. Improve the display of parameters - so it prints out the interpolated value instead of weird string that could confuse user
2. Could we return an interpolated dictionary instead? This needs to work well with resolvers.

## Steps to Reproduce
`git clone git@github.com:noklam/omega-nest-params-bug-demo.git`

```yaml
# parameters.yml
demo: ${global}

demo_nested:
  param: ${global}
```

```yaml
# parameters_global.yml
global: test_1
```

The function will simply print out the `parameters`.
```python
def demo_node(parameters, nested_parameters):
    pprint(parameters)
    print(parameters["demo_nested"]["param"])
    pprint(nested_parameters)
```

### Problem 1 - Only top-level parameters are interpolated
`kedro run`

#### Expected Result
```python
{'demo': 'test_1', 'demo_nested': {'param': 'test_1'}, 'global': 'test_1'}
test_1
{'param': 'test_1'}
```
#### Actual Result
```python
{'demo': 'test_1', 'demo_nested': {'param': '${global}'}, 'global': 'test_1'}
test_1
{'param': '${global}'}
```

```python
    print(type(parameters))
    print(type(parameters["demo_nested"]))
    print(type(parameters["demo_nested"]["param"]))

<class 'dict'>
<class 'omegaconf.dictconfig.DictConfig'>
<class 'str'>
```

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`):
* Python version used (`python -V`):
* Operating system and version:

**Comment by astrojuanlu** [comment]
Was this closed in gh-2467?

**Comment by noklam** [comment]
@astrojuanlu Yes, no idea why Github didn't close it as it's linked properly
