### ISSUE TITLE
Add flake8 configuration to documentation

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#2473]
## Description
When reviewing the [linting documentation](https://docs.kedro.org/en/stable/development/linting.html), I realised that we don't recommend settings specific to `flake8`. We use [these settings](https://github.com/kedro-org/kedro-starters/blob/main/spaceflights/%7B%7B%20cookiecutter.repo_name%20%7D%7D/setup.cfg) and users should be told to create `setup.cfg` and add these settings.

**Comment by stichbury** [comment]
Now ready for review in https://github.com/kedro-org/kedro/pull/2517

**Comment by stichbury** [comment]
Resolved by PR #2517
