### ISSUE TITLE
Information architecture: Build a clear picture of docs usage through data

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2478]
Child of #1866 

As a docs person, I still don't feel I have sufficient grasp of how people use the docs -- I'm finding Heap quite hard to get my head around. I would like for me, and @amandakys (and others that want to join) to sit together and learn how to build a set of dashboards that we can navigate to get referral information, bounce rate, heat maps, organic traffic, all that kind of useful stuff.

**Comment by noklam** [comment]
I don't know much about this but would love to get involve and learn more :)
