### ISSUE TITLE
Bug: Incremental dataset miss some file when using checkpoint

### ISSUE THREAD

**Issue by HOZHENWAI** [kedro-org/kedro#2487]
## Description
When using incremental dataset, you can miss some data due to the way checkpointing was done if the filenames are not incremental.

## Context
I have a folder where I store data with more and more files that are added hence the use of `IncrementalDataSet`. Following the same logic as `PartitionedDataSet`, I use the filename as key to the dictionary that is returned from the node. The issue happen when you confirm the dataset and add another file a name that is above the checkpoint. This new file will not be found by the new call to load because the logic of the checkpoint is to list all files, take the last filename and save it in the checkpoint. Then for next call, we compare by default the filenames to the checkpoint.

Maybe an implementation would be to store a manifest in the checkpoint file or to prepend the filename with a number that can be incremented

## Steps to Reproduce
1. Create a basic IncrementalDataSet `test_dataset` pointing for example to files :
    - `file1`
    - `file2`
    - `file3`
2. create a blank pipeline with node `lambda x : x ` with inputs `test_dataset` and outputs `memory_dataset` and confirms `test_dataset`
3. run the pipeline once
4. check the value in checkpoint and see that it is `file3`
5. add a file in the directory with name that is above the checkpoint using the default comparator i.e. `file0`
6. check the new dataset (for example by launching a jupyter notebook and load the dataset)
7. see that the dataset is empty

## Expected Result
the dataset loads `file0`

## Actual Result
the dataset returns an empty dict

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment
Include as many relevant details about the environment in which you experienced the bug:

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.7
* Python version used (`python -V`): 3.10
* Operating system and version: windows 10

**Comment by astrojuanlu** [comment]
Thanks a lot for reporting @HOZHENWAI and sorry you had a bumpy experience! We will have a look at this soon.

**Comment by HOZHENWAI** [comment]
Not much reason actually, I started with PartitionedDataset and the filenames were not modified to account for new addition, imagine for example uuid as filename. The only issue is the switch from partitioned to incremental which is not as natural as one would like it to be.

**Comment by HOZHENWAI** [comment]
Hi @merelcht , not really, will close this issue.
