### ISSUE TITLE
Missing TSC list

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#2490]
## Description
I was trying to find the list of maintainers for Kedro (i.e. who's on our TSC) and I realised I can't find it. 

## Context
We need to have a visible list of who is on our TSC; this is also the same place that TSC members get added to and removed from the team. There needs to be a PR raised to amend the list. 

## Steps to Reproduce
1. I went to _Technical Steering Committee documentation_ and clicked on a link to [Kedro’s current and past maintainers](https://github.com/kedro-org/kedro/blob/main/README.md#the-humans-behind-kedro)
2. That link took me to the README.md and then I clicked on: https://docs.kedro.org/en/stable/faq/faq.html#who-maintains-kedro
3. And the FAQ is missing

## PR which changed this
I believe the changes were made in this PR: https://github.com/kedro-org/kedro/pull/2373/files

**Comment by astrojuanlu** [comment]
Indeed, after https://github.com/kedro-org/kedro/pull/2373/ the "Who maintains Kedro" section that used to be at https://docs.kedro.org/en/0.18.6/faq/faq.html#who-maintains-kedro is not there anymore, and we didn't update the README accordingly, which still points there:

https://github.com/kedro-org/kedro/blob/0497d45b4ddb8ba53118ced0e855cbb088d7323e/README.md?plain=1#L73-L75

**Comment by astrojuanlu** [comment]
New location https://github.com/kedro-org/kedro/wiki/FAQ#who-maintains-kedro

**Comment by stichbury** [comment]
I think this may be better in the contributor section maybe on the TSC page itself https://docs.kedro.org/en/stable/contribution/technical_steering_committee.html
