### ISSUE TITLE
Casing Consistency: Rename TensorFlowModelDataset to ...DataSet

### ISSUE THREAD

**Issue by BrianCechmanek** [kedro-org/kedro#2494]
## Description

`TensorFlowModelDataset` is the only [included dataset](https://docs.kedro.org/en/stable/kedro.datasets.html) not following the "DataSet" casing consistency. 

## Context

Maintaining consistency assists with mental overhead. 

## Possible Implementation

I believe the fix is just a refactor in the 7 instances across the following two files:

* `./extras/datasets/tensorflow/tensorflow_model_dataset.py`
* `./extras/datasets/tensorflow/__init__.py:__all__`

I am happy to submit a PR of the refactor, if appropriate. 

## Possible Alternatives

It may have been intentional to break convention for this DataSet. Searching open and closed Issues, I found no reference. 

**NB** : I believe I followed the [contributing](https://docs.kedro.org/en/stable/contribution/developer_contributor_guidelines.html#get-started-areas-of-contribution) guide correctly. Please let me know if not - first ever OS Issue submission :)

**Comment by deepyaman** [comment]
@BrianCechmanek Great catch! It's not intentional (AFAIK), just an oversight. :) You're welcome to make a PR, but please do so on https://github.com/kedro-org/kedro-plugins instead (the new home from datasets).

**Comment by deepyaman** [comment]
It would also be nice to make everything `SomethingSomethingDataset` in the future, to be most consistent (see https://github.com/kedro-org/kedro/issues/533), but that would be outside the scope of this PR (and probably should be aligned with the broader team).

**Comment by BrianCechmanek** [comment]
Tubular! 

1. Will get on this (PR to plugins, per your comment)
2. Is there any consideration like a deprecation warning for changing `Dataset` -> `DataSet` ?

**Comment by deepyaman** [comment]
> 2. Is there any consideration like a deprecation warning for changing `Dataset` -> `DataSet` ?

I don't think it's necessary for datasets, but let me confirm...

**Comment by astrojuanlu** [comment]
See https://github.com/kedro-org/kedro/issues/2129

**Comment by BrianCechmanek** [comment]
Thanks @astrojuanlu - sorry I missed that. 

Sounds like that's a much bigger task (and probably above my head). I think this can be safely closed, then.
