### ISSUE TITLE
Project Creation Wizard GUI 

### ISSUE THREAD

**Issue by amandakys** [kedro-org/kedro#2509]
Parent Issue: #2388 

## Description
Investigate a project creation wizard GUI 

As the project creation flow takes on more options and branching steps, it might be valuable to have a UI to hguide users through it. Inspired by [(https://dev.to/napoleon039/how-to-create-new-projects-with-the-vue-cli-3pgo)]

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by yetudada** [comment]
We'll close this for now but can re-open this ticket at a later stage. ❤️
