### ISSUE TITLE
Investigate how to improve documentation readability with a language "linter"

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2518]
Mentioned in retro: [Vale](https://engineering.contentsquare.com/2023/using-vale-to-help-engineers-become-better-writers/) is a tool that we can configure to pick up issues in our markdown docs such as capitalisation, bullet inconsistency and hard-to-read language. I'm skeptical that it will be useful to apply over all our docs, as the work required to trawl through all the issues and fix may be high for the benefits that it gives us.

But, I do think it may be useful to run over docs as they change, to pick up issues in files that we are touching, and tidy them up as we go. I'm going to spend a couple of hours looking at it with the thought that, even if this doesn't work for Kedro, it could be helpful for other teams that don't have such dedication to docs (and/or a technical writer).

**Comment by astrojuanlu** [comment]
Yes! More info: https://passo.uno/posts/first-steps-with-the-vale-prose-linter/

And I agree, let's not run it through _all_ of our docs. But we could set a pre-commit hook so that it only runs on files that are changed: https://github.com/errata-ai/vale/blob/v2/.pre-commit-hooks.yaml

**Comment by astrojuanlu** [comment]
https://github.com/Datadog/datadog-vale

**Comment by ankatiyar** [comment]
Can set this up as a github actions workflow as well - https://github.com/marketplace/actions/vale-linter

**Comment by stichbury** [comment]
This looks great. How much time do you think it would take -- shall we make a ticket for next sprint or is it a short piece of work to move forward as part of this ticket? What is the next step; for me to decide on the rules to apply?

**Comment by ankatiyar** [comment]
@stichbury I think it's not too much effort to set up the GA, I have a PR for this already - https://github.com/kedro-org/kedro/pull/2953. Once this PR is merged (or even as a part of the same PR), you could add the necessary rules.
