### ISSUE TITLE
Make sure project logs of INFO level are shown

### ISSUE THREAD

**Issue by antonymilne** [kedro-org/kedro#2520]
> **Note**. Technically this is non-breaking, but best to do this following https://github.com/kedro-org/kedro/issues/2426, which is a breaking change. Hence this is for 0.19.0.

We are removing logging.yml from the project template (see https://github.com/kedro-org/kedro/issues/2281). However, there's a subtle piece of functionality that exists in project-side logging.yml that's not easily reproduced in the framework-side one: the project-side logging.yml has something like this:
```
loggers:
  kedro:
    level: INFO

  iris:
    level: INFO
```

It's not possible to put this in the framework-side logging.yml because you don't know what the project name is there. We can achieve this by adding it in the Python code in `framework/project/__init__.py` though by using `PACKAGE_NAME` (defined in `configure_project`), something like this:

```
logging_config["loggers"].append(PACKAGE_NAME: {"level": "INFO"})
```

_Originally posted by @AntonyMilneQB in https://github.com/kedro-org/kedro/issues/2281#issuecomment-1419040400_

**Comment by astrojuanlu** [comment]
Closed by gh-2684!
