### ISSUE TITLE
Revise Data Catalog documentation to bring it up-to-date and simplify it

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2521]
## Description
Based on #2488, the goal is to take the pages as discussed and move content into a more intuitive set of pages for introduction/basic usage/advanced usage and examples

There is a definite need to do this as the Data Catalog pages are some of the most visited, and the update will remove some of the incorrect or plain confusing material.

However, since there will be some upcoming discussion on information architecture and docs usability, it may be that this happens in two phases: first improve the docs as discussed in #2488 and then make final tweaks if needed for the output of the IA review.

**Comment by astrojuanlu** [comment]
Inspiration: https://stackoverflow.com/q/76765840/554319

**Comment by stichbury** [comment]
Joel made a good point that the factory documentation isn't easy to spot and should be highlighted: https://docs.kedro.org/en/latest/data/data_catalog.html#example-3-generalise-datasets-using-namespaces-into-one-dataset-factory

**Comment by astrojuanlu** [comment]
Closed in #2888, opened a few follow-up tickets from there.
