### ISSUE TITLE
Documentation for matplotlib artifacts is in page called `visualise_charts_with_plotly.html`

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#2527]
## Description
I was searching for a way to add matplotlib plots to a Kedro Viz node (thanks @rashidakanchwala!) and landed in 
https://docs.kedro.org/en/stable/visualisation/visualise_charts_with_plotly.html?highlight=matplotlib#visualisation-with-matplotlib. I think we should rename that page to `visualise_charts_with_kedro_viz`, `custom_plots` or something like that.

Alternatively, we could split it in two: one for Plotly and one for matplotlib.

**Comment by McDonnellJoseph** [comment]
If needed I can take care of this @astrojuanlu

**Comment by Gundalai-Batkhuu** [comment]
Can I take this one?

**Comment by astrojuanlu** [comment]
Hello @Gundalai-Batkhuu , sure thing! My original message was a bit open ended - can you tell us what do you intend to do?

**Comment by Gundalai-Batkhuu** [comment]
Hello @astrojuanlu. I have noticed that the docs are generated using Sphinx. I'm thinking to separate the markdown file 'visualise_charts_with_plotly' into two: one for Plotly and one for matplotlib as you have suggested. Then I will update the toctree of the parent index.md file.
Please let me know if my approach is correct. I'm a CS student :)

**Comment by astrojuanlu** [comment]
Sounds good! An alternative would be to have 1 page for both, but change the URL. @stichbury what do you think would be best?

**Comment by stichbury** [comment]
This is _so_ weird as I'm literally doing this right now as part of changes I'm making for https://github.com/kedro-org/kedro-viz/issues/1524 where i've created a new docs project just for Kedro-Viz. 

I'm sorry @Gundalai-Batkhuu that I've been (possibly) duplicating your work. You are welcome to submit anyway if you've made changes but if you haven't, then please leave this one for now as it'll be resolved by my broader work.

**Comment by Gundalai-Batkhuu** [comment]
@stichbury Sorry I had already made the changes. I have just submitted a pull request. Please let me know if I did anything incorrectly. This is my first ever open source contribution. I'm happy to work on other issues.

**Comment by astrojuanlu** [comment]
This is not yet reflected on the project documentation but it was addressed by @stichbury in https://github.com/kedro-org/kedro-viz/pull/1586
