### ISSUE TITLE
Change `pandas-gbq` to optional dependency

### ISSUE THREAD

**Issue by matheus-sampaio-mck** [kedro-org/kedro#2528]
## Description
Hi folks!

I noticed `pandas-gbq`  is a requirement for pandas on [kedro](https://github.com/kedro-org/kedro/blob/ebfed0c49a85f7157151d881654fd0378bacfb04/setup.py) and it downloads some google cloud packages as  `google-cloud-bigquery` , `google-cloud-bigquery-storage` , `google-cloud-core`  and others

Would be nice if we could avoid downloading these packages. Most of the time I’m not using Google Cloud and don’t need these packages

## Context
This can save some installing time and memory

## Possible Implementation
create a pandas-gcp extras dependency

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by yetudada** [comment]
Hi @matheus-sampaio-mck! Thanks for raising this query. I'll need to ask a follow-up question, how are you installing Pandas in Kedro? 

Are you using something like: `pip install "kedro-datasets[pandas]"`or do you install each dependency separately with something like `pip install "kedro-datasets[pandas.ExcelDataSet]"`?

**Comment by astrojuanlu** [comment]
Hi @matheus-sampaio-mck! Indeed, datasets in `kedro` are being deprecated, precisely to simplify the framework itself, and the right way now is `pip install kedro` for the framework and `pip install kedro-datasets[spark, pandas, matplotlib, plotly]` for the datasets. Please test it and let us know if it works.

> NOTE: Kedro datasets are moving from kedro.extras.datasets to a separate kedro-datasets package in
> [kedro-plugins repository](https://github.com/kedro-org/kedro-plugins). Any changes to the dataset implementations
> should be done by opening a pull request in that repository.

**Comment by matheus-sampaio-mck** [comment]
I see, thanks @astrojuanlu 

Noticed we can select only some pandas datasets, that works for me. In the end is a design choice if `kedro-datasets[pandas]` should download `pandas-gbq` or just the most commom pandas usages.

Thanks all, I'm closing this issue, as it is possible to select only some pandas datasets and is all good with the packages.

**Comment by astrojuanlu** [comment]
Indeed, one can do `pip install kedro-datasets[pandas.CSVDataSet]` 😊

**Comment by yetudada** [comment]
Yes, @matheus-sampaio-mck. You can see the code that causes this: https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/setup.py#L26 

Some of the `pandas` datasets in the `pandas` group need `pandas-gbq` so that's why we give flexibility to install at a dataset level instead.
