### ISSUE TITLE
Remove the `draft` folder in docs which contains `.puml` files

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2529]
## Introduction

I've only recently noticed (I don't know why!) that there's a `draft` folder in `kedro/docs` and I've no idea what it's for. It was introduced here: https://github.com/kedro-org/kedro/commit/d996ce78a07b2e582343ee00e4763b4e7f6eaec0 but that commit doesn't match up to the PR it is associated with (presume this is something to do with moving the repos). I don't think we still use these diagrams? Can I suggest we remove them? Does anyone know what they're for besides @idanov ?

**Comment by astrojuanlu** [comment]
I noticed that too. They will always live on version control ✨ so +1 to removing those.

**Comment by stichbury** [comment]
Fixed
