### ISSUE TITLE
Make subcommands work in subdirectories, or improve error messages

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#2541]
## Description
Today one user was puzzled because their `kedro micropkg` command was not working:

```
> kedro micropkg -h
Usage: kedro [OPTIONS] COMMAND [ARGS]...
Try 'kedro -h' for help.

Error: No such command 'micropkg'.
```

The most likely explanation (still to be confirmed) is that they are running `kedro micropkg` from a sub-directory, and it doesn't work. It would be nice if it did, or at least if the error message was better, like:

```
> kedro micropkg package
Please run `kedro micropkg package` from the root of the Kedro project.
```

## Context
"No such command" is really unhelpful. Is my Kedro installation broken? Did I make a typo?

This has hit me in the past already https://github.com/kedro-org/kedro-starters/issues/115 I understand that some commands are dynamically generated and therefore it's impossible to completely avoid that error for potentially existing commands, but at least we should minimize the number of times it appears.

## Possible Implementation
Be able to run subcommands (in particular `kedro micropkg` from a subdirectory.

## Possible Alternatives
Improve the error message to clarify that the subcommand exists, but the environment is not correct.

**Comment by noklam** [comment]
I think we can push this a little bit, we already have a semi working solution, it should not be too hard to do it. We can at least merge the one provide better error message.

**Comment by astrojuanlu** [comment]
Good catch @antonymilne! Closing this in favor of gh-1831.
