### ISSUE TITLE
[PARENT] - User research process to improve Kedro documentation

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2545]
# Introduction

This is a parent issue that has a number of individual tasks, described sequentially below.

The goal of this research about Kedro documentation is to:
* understand what users need from the docs to reach their goals
* uncover where the docs are failing to provide what they need
* synthesise a set of insights of how to address the failures and remove any pain points. 
* build a prioritised documentation roadmap for improvements.

## Task 1. Document the research process

This includes documenting the hypotheses we will test and building out data dashboards for quantitative data.

## Task 2. Quantitative analysis
Write up key findings from data gathered from dashboards. 

## Task 3. Initiate user research
Book interviews and execute.

## Task 4. Survey based on interview synthesis
Consider interview output the input to survey questions, and validate hypotheses.

## Task 5. Synthesise survey feedback
Document the findings from data and user-facing research.

## Task 6. Gather internal feedback
Team discussion/exercise to plan docs improvements

We should come out of this research with a roadmap of additions/enhancements for 2023-24.

**Comment by noklam** [comment]
Parent Ticket for 
- #2580 
- #2581
