### ISSUE TITLE
Add an advanced example (how to use hooks to load external credentials) to the configuration documentation

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2547]
[Taken from a discussion thread on Slack](https://kedro-org.slack.com/archives/C054U0LJLAC/p1682674168666069)

https://docs.kedro.org/en/stable/hooks/common_use_cases.html#use-hooks-to-load-external-credentials was added to the documentation but hasn't been clearly indicated. 

It seems to make sense to add it to the configuration documentation as an advanced example.

**Comment by astrojuanlu** [comment]
The link to the conversation is lost forever, and it isn't clear what's missing beyond https://docs.kedro.org/en/stable/hooks/common_use_cases.html#use-hooks-to-load-external-credentials. In the absence of more information I'm closing this.
