### ISSUE TITLE
Update Prefect deployment documentation for new version of Prefect

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2571]
Comes out of the work in #2435 which tidied up the deployment docs following some review from subject experts.

We have Prefect docs that we are relatively confident in, but they aren't for Prefect 2.0, so we should spend some time checking on the new version and making sure they are compliant or updated for it as needed.

**Comment by astrojuanlu** [comment]
Duplicate of https://github.com/kedro-org/kedro/issues/2431?

**Comment by stichbury** [comment]
Yes!
