### ISSUE TITLE
Broken Slack invite link: Link on website and docs are no longer active

### ISSUE THREAD

**Issue by MarkusSagen** [kedro-org/kedro#2574]
The invite link for the Slack channel for kedro seem to not be active anymore for both the original link and the redirect link

- https://slack.kedro.org/
- https://kedro-org.slack.com/join/shared_invite/zt-1n71lwpzb-OqgFymBRZ6PHKwDEswyc~A#/shared-invite/error

<img width="1250" alt="Screenshot 2023-05-10 at 10 17 18" src="https://github.com/kedro-org/kedro/assets/20767068/f66a024f-6e1a-4bb6-8af7-0803810b75a1">

**Comment by astrojuanlu** [comment]
I confirm this is working now:

```
$ curl -I "https://slack.kedro.org"
HTTP/2 301 
content-type: text/html; charset=utf-8
location: https://join.slack.com/t/kedro-org/shared_invite/zt-1eicp0iw6-nkBvDlfAYb1AUJV7DgBIvw
x-redirector-version: 2.18.3-49f64c4
date: Thu, 11 May 2023 16:44:50 GMT
```

Closing!
