### ISSUE TITLE
Optimize our GitPod setup

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2586]
## Description
Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

Our GitPod setup has not been working for a while. #2585 is the quick fix but we can do better. In #2585 @astrojuanlu mentioned he use a custom Docker and we can do something similar for this repostory.

## Context
Why is this change important to you? How would you use it? How can it benefit other users?
GitPod is quite useful for review & testing purposes, the current setup is slow and broken.

## Possible Implementation
We might be able to use a custom Docker setup, but this requires some investigation into how it works and if that's the best approach. 

## Possible Alternatives
-

**Comment by noklam** [comment]
Just to add more, I tried to build docs on GitPod last week and it doesn't seem to work.

**Comment by astrojuanlu** [comment]
I've talked about this with @antonymilne a couple of times but sadly I never got the time to dive deep into why things are the way they are at the moment. I know there are some weirdnessess on how Gitpod pre-caches some things:

https://github.com/kedro-org/kedro/blob/64b7960e346565478fc269f3aeb6162d8143090f/.gitpod.yml#L4-L13

![image](https://github.com/kedro-org/kedro/assets/316517/cc3c6195-d4b1-47ec-a780-b5fa67932ca1)

(More info at https://www.gitpod.io/docs/configure/workspaces/tasks, https://www.gitpod.io/docs/configure/projects/prebuilds)

I'm all for simplifying the setup or having a custom Docker image as I'm doing with my workshops https://github.com/astrojuanlu/workshop-jupyter-kedro/blob/ce202c7d1164d9e5b6aa331320b32a4f1a342407/.gitpod.yml#L1-L2 but we should not do it carelessly.

At the same time, if the current setup doesn't work, it doesn't matter much if it's optimized.

**Comment by astrojuanlu** [comment]
pyenv shims unfortunately make all this even more complicated 😬

**Comment by astrojuanlu** [comment]
@noklam you mentioned #2688 is not a complete fix, what else do you think is needed?

**Comment by noklam** [comment]
It's functional now but not optimised, spinning a  gitpod instance takes 10 minutes.

It would be great if can fix the pre-built so it doesn't fetch the whole docker image every time.

**Comment by astrojuanlu** [comment]
I'm hoping that `uv` makes further optimisations unnecessary for now? Closing, but feel free to reopen if you disagree
