### ISSUE TITLE
Install Kedro, plugin, and test requirements in a single `pip install` command

### ISSUE THREAD

**Issue by deepyaman** [kedro-org/kedro#2588]
I think this is a critical problem that needs resolving.

What this means is that, in reality, we don't have resolvable requirements, and we're only able to get to a resolvable state by overwriting some of the previously-installed requirements. Some of the stuff installed in the `pip install -r test_requirements.txt` are not actually going to be compatible with Kedro on `main`, it seems.

_Originally posted by @deepyaman in https://github.com/kedro-org/kedro-plugins/pull/155#discussion_r1164384301_

**Comment by astrojuanlu** [comment]
I agree this needs fixing.

This can be achieved by moving the contents of `test_requirements.txt` to the `optional-dependencies` subtable of `pyproject.toml`, which requires moving the contents of `dependency/requirements.txt` to the same file. This will require slight adjustments on our CI, but it's for the greater good.

**Comment by deepyaman** [comment]
> I agree this needs fixing.
> 
> This can be achieved by moving the contents of `test_requirements.txt` to the `optional-dependencies` subtable of `pyproject.toml`, which requires moving the contents of `dependency/requirements.txt` to the same file. This will require slight adjustments on our CI, but it's for the greater good.

Yeah, the CI adjustments and shuffling of requirements shouldn't be bad at all (and generally beneficial, as you say); the bigger problem is that our requirements aren't actually compatible if installed together, and this needs to be resolved. 😿

**Comment by astrojuanlu** [comment]
In progress in gh-2597

**Comment by astrojuanlu** [comment]
It will be easier to tackle this after gh-2569 is merged.
