### ISSUE TITLE
Add new catalog CLI commands for dataset factories

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2603]
## Description
Part of https://github.com/kedro-org/kedro/issues/2423

We should decide what new catalog CLI commands to add to support the dataset factories syntax:
- a command that ranks all patterns so a user can understand the priority matching order
- a resolve command that shows the fully resolved catalog when all patterns are matched (this excludes the actual patterns for ease of reading)

## Context
These CLI commands are mainly to make it clear for users how exactly the dataset factories work and match the catalog entries.

**Comment by ankatiyar** [comment]
Adding updating `kedro catalog list` command to be done with this.

**Comment by merelcht** [comment]
This has now been completed with:
- https://github.com/kedro-org/kedro/issues/2789
- https://github.com/kedro-org/kedro/issues/2790
- https://github.com/kedro-org/kedro/issues/2791
- https://github.com/kedro-org/kedro/issues/2849
