### ISSUE TITLE
Document the use of custom resolvers with `OmegaConfigLoader`

### ISSUE THREAD

**Issue by ankatiyar** [kedro-org/kedro#2624]
## Description
To be done after #2622. Add a Kedro specific use case for custom resolvers with `OmegaConfigLoader` in the docs.
This will require some creativity in trying out ways of using custom resolvers in a Kedro project that's useful for our users rather than just addition which they show in the omegaconf docs. 

We also need to clarify what "custom resolvers" are in our own words. 

## Context
Follow up task from the tech design discussion https://github.com/kedro-org/kedro/issues/2407 (24/05)

**Comment by astrojuanlu** [comment]
To note: we have some docs on how to register custom resolvers, but using a custom class, which is probably not necessary

https://github.com/kedro-org/kedro/blob/4a4bd7396668887309dd2352e72ce5b822c24b48/docs/source/configuration/advanced_configuration.md?plain=1#L243-L277

Also, rather than a simple `add` resolver, we could use my Polars use case for instance.

**Comment by ankatiyar** [comment]
Also, mention `replace` is set to `True` in the docs when new resolvers are registered.

**Comment by noklam** [comment]
Cross-post Slack answer

> 
> Ankita Katiyar
>   [25 minutes ago](https://kedro-org.slack.com/archives/C03RKP2LW64/p1691068792855539?thread_ts=1690997737.947639&cid=C03RKP2LW64)
> [@Nok Lam Chan](https://kedro-org.slack.com/team/U03RJ2PH79D)
>  is right - after the next release (or if you use the main branch of the source code), you would be able to set custom resolvers through CONFIG_LOADER_ARGS in your settings.py like this :
> def mydate():
>     return whatever
> 
> CONFIG_LOADER_ARGS = {
>     "custom_resolvers": {
>         "date_resolver": lambda: mydate(),
>     }
> }
> And then in your parameters.yml
> my_date: "${date_resolver:}"
> ---
> Right now you can also do in your settings.py
> def mydate():
>     return whatever
> 
> from omegaconf import OmegaConf
> if not OmegaConf.has_resolver("date_resolver"):
>     OmegaConf.register_new_resolver("date_resolver, lamda: mydate())
