### ISSUE TITLE
Dynamic pipeline from current data

### ISSUE THREAD

**Issue by jccalvojackson** [kedro-org/kedro#2626]
## Description

Is kedro planning to add dynamic pipeline support?

Toy problem:

1- Scan a large image and identify regions of interests
2-For each region of interest do some processing (this processing might be a pipeline)

The above would require to add one modular pipeline in step 2 per number of regions of interest identified on step 1.

I believe something [like this](https://airflow.apache.org/docs/apache-airflow/stable/authoring-and-scheduling/dynamic-task-mapping.html) could be used here.

## Context

I would love to be able to implement something like the above in kedro

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by astrojuanlu** [comment]
Let's continue the discussion in #2627.
