### ISSUE TITLE
TemplatedConfigLoader does not allow a list as conf_paths

### ISSUE THREAD

**Issue by aadi350** [kedro-org/kedro#2639]
## Description
I'm working on upgrading a Kedro 0.17.X project to Kedro 0.18.8. (I've gone through the release notes, breaking changes, etc and found it hadn't been addressed prior). The subclasses of `AbstractConfigLoader` no longer allow a list to be passed in to its primary argument. In `0.17.5`, we were able to create multiple folders for pipelines, where each had its own set of configuration defined in YAML (parameters, etc). However, the new ConfigLoaders do not allow this since it expects a single path as its input for conf_path (even the constructor signature changed with no explanation as far as I could find)

## Context
We are no longer able to dynamically configure pipelines in YAML. Micro-packaging partly solves the issue, however then we're not able to maintain the project structure

## Steps to Reproduce
1.  Define a list of `conf_source` in `settings.py and set `CONFIG_LOADER_CLASS` to `TemplatedConfigLoader`
2. `kedro run`

## Expected Result
Kedro should find the pipelines in the nested folder directories

## Actual Result
```
TypeError: ABCMeta object got multiple values for keyword argument `conf_source`
```

## Your Environment
Python Version: 3.8.0
Kedro Version: 0.18.8
Environment: Ubuntu 20.04 LTS on Windows 10

**Comment by noklam** [comment]
I opened a thread on Slack about this issue as I think we need more context about this.

**Comment by noklam** [comment]
Inactive issues - feel free to ask the question in our Slack channel, this will requires some more context to clarify the problem.
