### ISSUE TITLE
Update `TemplatedConfigLoader` with runtime params

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2640]
### Description
Update `TemplatedConfigLoader` to fix runtime parameters not being passed properly. This can be done in the same way as it's done in `OmegaConfigLoader`

```python
# settings.py
class MyTemplatedConfigLoader(TemplatedConfigLoader):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.runtime_params:
            self._config_mapping.update(self.runtime_params)

CONFIG_LOADER_CLASS = MyTemplatedConfigLoader # TemplatedConfigLoader
# Keyword arguments to pass to the `CONFIG_LOADER_CLASS` constructor.
CONFIG_LOADER_ARGS = {
    "globals_pattern": "*globals.yml",
}
```

With recent changes we already started merging runtime_params in ConfigLoader. This question comes out quite often when people try to migrate from 0.17.x -> 0.18.x, maybe we should just fix it in 0.18.x.

https://www.linen.dev/s/kedro/t/12115548/hi-i-m-trying-to-migrate-from-kedro-0-17-to-kedro-0-18-and-h#5d1d302d-198f-4d13-839d-cdf7bc7892e8

**Comment by astrojuanlu** [comment]
Ahead of the removal of `TemplatedConfigLoader`, do we still want to do this?

**Comment by astrojuanlu** [comment]
I agree. Closing!

**Comment by datajoely** [comment]
Can we now that globals is in that we're at feature parity now? Obv jinja isn't happening but we have pretty much everything now right?

**Comment by merelcht** [comment]
Yes! You can see here that pretty much all features that were in `TemplatedConfigLoader` are in some way supported in `OmegaConfigLoader`: https://docs.kedro.org/en/stable/configuration/config_loader_migration.html

**Comment by datajoely** [comment]
Amazing work everyone - feels like a very long journey getting here
