### ISSUE TITLE
How to run a pipeline which contain parallel and sequential

### ISSUE THREAD

**Issue by RTae** [kedro-org/kedro#2649]
## Introduction

Recently, I create a Kedro pipeline which have multiple pipeline and it have one pipeline that will wait another pipeline to finish to aggregate data into one before do another process

## Problem

Currently, the pipeline has done it job. However, it run very slow, since it have many pipeline which could run in parallel and I don't know how to do it

This is example of my pipeline look like
```
[A] [B] [C]
 |   |   |
 \   |   /
    [D]
```

I want A,B,C to run in parallel and D need to wait for A,B,C  before do it's task. Could some one give a example to impanelment this ? I'm very new with Kedro

**Comment by NeroOkwa** [comment]
Hello @RTae, a good place to understand runners in Kedro is in the [docs](https://docs.kedro.org/en/stable/nodes_and_pipelines/run_a_pipeline.html).

**Comment by astrojuanlu** [comment]
Hi @RTae, did the `ParallelRunner` suit your needs? I think there's nothing for us to do here so I'm closing, but feel free to comment if you think otherwise.
