### ISSUE TITLE
Revisit Debugging documentation in Kedro

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2672]
## Description
Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."
Quoting myself from Slack
> One small thing, when I search debugger kedro, this is what I get from search. This link me to this [fun example](https://docs.kedro.org/en/stable/development/debugging.html) which create PDB hook with Kedro. It’s an interesting example to showcase what you can do with hooks, but I don’t think it should be the way we suggest users to debug.
IMO I expected it to be linking to the setup of using VSCode/PyCharm or in future when we have the jupyter debug magic developed or just using catalog.load to start debugging in a notebook. (edited)

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.
- Update our documentation, possibly remove this example of move it to Advance hooks example instead of "Development"
- I'd love to see https://docs.kedro.org/en/stable/development/set_up_vscode.html#debugging or Pycharm get return as the 1st search result instead of the current page.

![image](https://github.com/kedro-org/kedro/assets/18221871/6ac4c753-beb9-4f90-ba85-7e43a76366a7)
https://docs.kedro.org/en/stable/development/debugging.html

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by noklam** [comment]
Pinging @stichbury for some thought around this

**Comment by stichbury** [comment]
Yes! I'd like to see this chunk of text revised to bring it up to date and focus on answering the intent behind the query as you identify. Let's get this in a sprint soon.

**Comment by AhdraMeraliQB** [comment]
Closed by #3608
