### ISSUE TITLE
Add deprecation warnings to top-level use of layer in catalog definition

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#2677]
## Introduction

Following #2440, it was decided the datasets' layer attribute should be moved to within the new metadata attribute. As such we will stop supporting defining it at the top level in 0.19.0 - we should add deprecation warnings to alert users to this change in advance.

Note: It was decided that these deprecation warnings should only be defined when the user defines the layer at the top-level, but not when this top-level layer is accessed

**Comment by noklam** [comment]
The latest way to do this is https://docs.kedro.org/en/latest/visualisation/kedro-viz_visualisation.html#visualise-layers
