### ISSUE TITLE
Remove support for defining layer attribute at top-level within catalog

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#2678]
> **Note**. Breaking, goes in 0.19.0.

After the implementation of #2440, it was decided that layer would move to within the introduced metadata result. As a result we will drop support for defining it at the top-level. Layer, at the top-level, is currently handled in https://github.com/kedro-org/kedro/blob/main/kedro/io/data_catalog.py#L183.

**Comment by merelcht** [comment]
Completed in #3402
