### ISSUE TITLE
Improve docs around creating plugins

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#2685]
## Description
We have these docs https://docs.kedro.org/en/stable/extend_kedro/plugins.html#example-of-a-simple-plugin

which briefly mentions `setup.py` but assumes that the reader already knows how to create a Python package, which is a huge assumption I'd say.

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
There are several ways to modernize these docs. But even if we don't do anything else, at the very least we should replace `setup.py` with `pyproject.toml`.

Apart from that, we should add all the steps on how to create a distributable Python project, either with

a. something like `flit init` (or its hatch/rye/{whatever} equivalent), or
b. providing a template of our own and then instructing users to do `copier gh:kedro-org/kedro-plugin-template`, or
c. even having a `kedro plugin init` command what does the right thing.

**Comment by noklam** [comment]
Backlog Grooming: We decide to keep this as a documentation effort.

**Comment by noklam** [comment]
Now I review, may be duplicate  #1539, Can we move this to milestone https://github.com/kedro-org/kedro/milestone/50 here?

**Comment by astrojuanlu** [comment]
Indeed, feel free to close this one
