### ISSUE TITLE
Remove `ConfigLoader` and `TemplatedConfigLoader` 

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2692]
## Description
`OmegaConfigLoader` will be the config loader from `0.19.0` onwards.

## Context
https://github.com/kedro-org/kedro/milestone/34

## To do:
- [ ] Remove `ConfigLoader`
- [ ] Remove `TemplatedConfigLoader`
- [ ] Remove all other code related to these config loaders
- [ ] Remove any docs about these loaders and re-order the `OmegaConfigLoader` content where needed.
- [ ] Can we remove the `anyconfig` dependency? Double check if any other parts of our codebase are using it.

**Comment by astrojuanlu** [comment]
A few of places that still use `anyconfig`:

https://github.com/kedro-org/kedro/blob/f89a504b81a96e9aca84e18089f8b93690a2f778/kedro/framework/startup.py#L78-L79

https://github.com/kedro-org/kedro/blob/f89a504b81a96e9aca84e18089f8b93690a2f778/kedro/framework/cli/micropkg.py#L262-L264

https://github.com/kedro-org/kedro/blob/f89a504b81a96e9aca84e18089f8b93690a2f778/kedro/framework/cli/utils.py#L405-L406

**Comment by ankatiyar** [comment]
Closed with #3253 and #3257
