### ISSUE TITLE
Add deprecation warnings to `ConfigLoader` and `TemplatedConfigLoader`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2693]
## Description
We plan to deprecate `ConfigLoader` and `TemplatedConfigLoader` and replace them with the `OmegaConfigLoader` from `0.19.0` onwards. 

## Implementation
Add a deprecation warning in the code and docs. 

## Follow-up
- [ ] #2699

**Comment by astrojuanlu** [comment]
Do you think, rather than deprecating `ConfigLoader`, we could "swap" it and make it an alias to `OmegaConfigLoader` (say, in 0.20.x)?

**Comment by noklam** [comment]
Options
1. Rename `OmegaConfigLoader` -> `ConfigLoader`
2. Remvoe `ConfigLoader` and `TemplatedConfigLoader` , keep only `OmegaConfigLoader`

**Comment by astrojuanlu** [comment]
(Context: We noted that making users that had already adopted `OmegaConfigLoader` change the name back to `ConfigLoader` could frustrate them, and also make issues potentially more difficult to debug)
