### ISSUE TITLE
Migration guide for switching to OmegaConfigLoader

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2699]
# Description
Related  #2693
We should document the migration path from `ConfigLoader` -> `OmegaConfigLoader` and `TemplatedConfigLoader` -> `OmegaConfigLoader`.

i.e.
1. Jinja2 Template loop <-> Dataset Factory + OmegaConf variable interpolation?
2. YAML Anchor
3. Templated variable <-> OmegaConf variable interpolation

![image](https://github.com/kedro-org/kedro/assets/18221871/6a49bc6f-104d-4230-ae14-6339fbec04cb)

It should be similar to the [table](https://github.com/kedro-org/kedro/issues/2423#issuecomment-1490578223) here but we need to have code example to show this.

It will be also a good opportunity to check if we missed any feature before we release 0.19.0

Edited 2023-08-21
- [ ] #2887
- [ ] #2904

**Comment by merelcht** [comment]
Not yet done.
