### ISSUE TITLE
How to leverage versioning features from DeltaTable or equivalent

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2703]
## Description
Is your feature request related to a problem? A clear and concise description of what the problem is: "I'm always frustrated when ..."

Kedro offers it own basic versioning feature. With the emerging ecosystem with `DeltaTable` and more, versioning is a built-in feature. When we force data to inherit from `AbstractVersionedDataSet`, we are missing out these built-in functions.

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

**Comment by astrojuanlu** [comment]
Research on versioning is ongoing and outcomes are better tracked in other tickets. Closing this until we better understand how to move forward.
