### ISSUE TITLE
Replace "DataSet" with "Dataset" in Kedro-Datasets

### ISSUE THREAD

**Issue by deepyaman** [kedro-org/kedro#2751]
### Description
In the spirit of consistency, we should first deprecate, later rename, datasets with the "DataSet" spelling (as already done in Kedro). This should also include docs updates.

This should not replace references to core "DataSet" versions (e.g. `AbstractDataSet`) yet, because that would break compatibility with older Kedro.

### Possible implementation
Naive way:

**Comment by astrojuanlu** [comment]
Should we move this to kedro-plugins ?
