### ISSUE TITLE
Update kedro pipeline create to use new /conf file structure 

### ISSUE THREAD

**Issue by amandakys** [kedro-org/kedro#2752]
## Description
Currently, the `kedro pipeline create` command creates a new /parameters folder and adds a {pipeline-name}.yml inside (or just adds the file to the parameters folder if it aready exists. 

## Context
To make this more consistent and so the global parameters.yml doesn't just randomly sit outside the directories, we want to maintian all the pipeline specific config files directly in the /conf with a specific naming convention. 

Before
```
├── conf
    └── base
        └── parameters         
	    ├── data_science.yml     #blank files
        ├── catalog.yml              #blank files   
	└── parameters.yml           #blank files
```

After
```
├── conf
    └── base
	├── catalog_data_science.yml          #blank files
	└── parameters_data_science.yml       #blank files
        ├── catalog.yml          #blank files   
	└── parameters.yml       #blank files
```

## Possible Implementation

calling the updated `kedro pipeline create` should: 
1. add `parameters_{pipeline_name}.yml` to `/conf`
2. add `catalog_{pipeline_name}.yml` to `/conf`
3. add a pipeline diretory called {pipeline_name} to the `/pipelines` with empty `nodes.py` and `pipeline.py` files 

Currently, it also adds a `/tests` directory, but we want to remove this from the command because of work on #2149

**Comment by amandakys** [comment]
Following discussion with @merelcht @deepyaman @astrojuanlu @DmitriiDeriabinQB  we decided to move forward with this work with the following updates: 

calling `kedro pipeline create` will: 
- add parameters_{pipeline_name}.yml to /conf
- add a pipeline diretory called {pipeline_name} to the /pipelines with empty nodes.py and pipeline.py files

it will no longer add a /tests directory 
it will also no longer add a `catalog_{pipeline_name}.yml` to /conf, this will instead be delegated to the `kedro catalog create` command which will also need updating as a follow up to this. #2844

**Comment by merelcht** [comment]
> Following discussion with @merelcht @deepyaman @astrojuanlu @DmitriiDeriabinQB we decided to move forward with this work with the following updates:

I think you meant to tag @DimedS 😄

**Comment by noklam** [comment]
I update the description to reflect the final decision - I also make it a parent ticket so it's easy to track the rest. This is done already but I think it will be useful to keep the record for future reference.
