### ISSUE TITLE
Update starters to use new /conf structure 

### ISSUE THREAD

**Issue by amandakys** [kedro-org/kedro#2753]
## Description
We want to update the new /conf folder structure to look like 

```
├── conf
    └── base
	├── catalog_{pipeline-name}.yml          #blank files
	└── parameters_{pipeline-name}.yml       #blank files
        ├── catalog.yml          #blank files   
	└── parameters.yml       #blank files
```
with separate catalog and parameters files for each pipeline in the project 

rather than

```
├── conf
    └── base
        └── parameters.yml          
	    ├── {pipeline-name}.yml     #blank files
        ├── catalog.yml              #blank files   
	└── parameters.yml           #blank files
```

This change needs to be made across the starters

This is a follow up on the work to update the `kedro pipeline create` command #2752

**Comment by astrojuanlu** [comment]
The scope of this is replacing

```
├── conf
    └── base
        └── pipeline_name
            └── catalog.yml
```

with

```
├── conf
    └── base
	├── catalog_{pipeline-name}.yml
```

so, no new complexity or indirection is added, we just make the file hierarchy more flat.

You raise a good point but that's not what we are intending to solve here, I'd say. @amandakys correct me if I'm wrong.

**Comment by astrojuanlu** [comment]
Quick comment on one of the points:

> We could also choose to name them `catalog_global.yml` or something similar to better indicate their function.

I'd be -1 on that, since it can create ambiguity with a pipeline called `global`.

**Comment by astrojuanlu** [comment]
I'm going to vote on continuity over consistency here. I agree splitting catalog files puts them at the same level as parameters, which increases consistency and informs users that they can do such a thing. But I also agree with @deepyaman and @yetudada that it might create confusion for arguably the most important file of the whole project. On top of that, we were not creating separate catalog files before, so by continuing to use a "global" one _by default_, we keep the same behavior.

**Comment by DimedS** [comment]
I discovered that currently, we have only one starter (spaceflights) that contains a 'parameters' folder with two pipeline_name.yml files inside. There are no starters with a catalog folder. So, it seems that we only need to move and rename the two spaceflights YAML files.
