### ISSUE TITLE
Update /conf file structure 

### ISSUE THREAD

**Issue by amandakys** [kedro-org/kedro#2755]
We want to update the new /conf folder structure to look like
```
├── conf
    └── base
	├── catalog_{pipeline-name}.yml          #blank files
	└── parameters_{pipeline-name}.yml       #blank files
        ├── catalog.yml          #blank files   
	└── parameters.yml       #blank files
```
with separate catalog and parameters files for each pipeline in the project

rather than
```
├── conf
    └── base
        └── parameters.yml          
	    ├── {pipeline-name}.yml     #blank files
        ├── catalog.yml              #blank files   
	└── parameters.yml           #blank files
```
This change needs to be reflected in the 

- [x] `kedro pipeline create` command #2752 
- [x] the starters #2753 
- [x] the docs #2754

**Comment by yetudada** [comment]
Add the docs ticket to this: https://github.com/kedro-org/kedro/issues/2754

**Comment by merelcht** [comment]
This has been completed in:
- https://github.com/kedro-org/kedro/pull/2856
- https://github.com/kedro-org/kedro-starters/pull/141
- https://github.com/kedro-org/kedro/pull/2913
