### ISSUE TITLE
Strip project template 

### ISSUE THREAD

**Issue by amandakys** [kedro-org/kedro#2756]
## Description

We want to simplify the project template in preparation for future work based on #2388 to allow the linting, testing, docs, and the other removed features to be optionally inserted. 

The simplified project template 

```
└── project-dir          
	├── .gitignore 
	├── conf
		└── base
			├── catalog.yml          #blank files
			└── parameters.yml       #blank files
		└── local
			└── credentials.yml     
	├── notebooks       
	├── pyproject.toml  
	├── README.md              
	└── src 
		├── requirements.txt
		├── setup.py   
		└── project-code 
			├── pipeline_registry.py
			├── settings.py                  
			└── pipelines
				
```

Files & Directories to be removed 
/tests 
/docs
/data
/logs
setup.cfg 
conf/base/logging.yml

Files to. be updated 
requirements.txt should be updated to remove all unnecessary dependencies 

[https://github.com/amandakys/kedro-plugin-validation](https://github.com/amandakys/kedro-plugin-validation) - i made this repo to demo what the base project template would look like - msg me if you'd like access. 

## Possible Alternatives

in #2149 we also discuss the removal of requirements.txt and setup.py and merging them into pyproject.toml. This should not block this ticket and should be discussed as a follow up see #2757 

## Implementation 
This change needs to be reflected in 
- [ ] framework
- [ ] framework blank template 
- [ ] starters 
- [ ] docs

**Comment by merelcht** [comment]
We discussed this ticket in grooming and decided that with the new project creation flow, where we'll be stripping the template with the post project hook, a stripped project template isn't necessary anymore.
