### ISSUE TITLE
Find out why our linen archive of Slack discussions isn't indexed (or isn't ranking) 

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2802]
We put in some time to https://github.com/kedro-org/kedro-devrel/issues/84 and have a fair number of links to the archive now...but we are not seeing it in search results. Is there something up with linen?

**Comment by stichbury** [comment]
True, although that is a big effort and we have a wealth of content on Slack of only people had access to it from Google! Let's see if we get any leads from my efforts today.

**Comment by stichbury** [comment]
So far, nobody has returned to me from Linen with any help or information about why Google isn't indexing our Slack archive correctly.

I'm wondering if we should consider a different approach. I've done quite a bit of hunting around for alternatives to Linen but it's limited. Kartik (who I mentioned above) shared a link to his repo with me. This is code that reads a Slack workspace and builds a set of static HTML. It's here: https://github.com/akkartik/foc-archive

It's not ideal but I'm wondering if there's scope for us to do this and publish on the Kedro website (with no links to it or particular formatting). We don't advertise that it's there, but somewhere on the kedro.org domain we have an equivalent to this (this is the future of coding Slack workspace archive) https://akkartik.name/archives/foc/ 

The reasoning is that we have this online, and indexed so we flood Google with all the Q&A discussions about Kedro so people searching for answers get to see them. (THE WHOLE POINT OF LINEN). We'd add links through to slack.kedro.org onto the archive to push users browsing it to sign up and get the content from Slack, but at least we'd initially get the answers in front of them. If it's hidden in Slack, they can't see it's there at all.

Problem with it being static is that we would need to schedule regular rebuild of the archive and republication. It's non-trivial. But I think it's worth considering from a discoverability point of view.

WDYT @astrojuanlu @tynandebold ?

**Comment by astrojuanlu** [comment]
Linen got back to us. I think the limitations are in two areas:

- Having our own domain. That's easy, can be sorted out either on Linen or the solution you propose @stichbury.
- The thread and content model. I think this might be the difficult part. Since Slack is a stream of text, I think Google might be deciding to rank it low or index it in a suboptimal way. In that sense I'm not sure having the text in our own system would help things.

**Comment by stichbury** [comment]
I don't see how the domain makes much difference to the indexing TBH, particularly since we don't have huge authority or strong backlinks as a project. I'm unconvinced but willing to try that option if it doesn't cost us anything, and I think we did previously discuss having a `questions.kedro.org` or `community.kedro.org` subdomain, so let's see if that happens.

**Comment by tynandebold** [comment]
So which of those two subdomains do we want to point to Linen, `questions.kedro.org` or `community.kedro.org`?

**Comment by astrojuanlu** [comment]
`https://linen-slack.kedro.org/`? (to mirror https://linen-discord.kedro.org/)

**Comment by tynandebold** [comment]
Don't we already have that? I think I set this up a while ago.

Visit this: linen-slack.kedro.org, it actually works.

**Comment by stichbury** [comment]
Great. Now I think of it, there were no redirects between the custom domain but now it's working so I guess we can update the docs/github/blog posts etc to point to the new location, give it a couple of weeks and see if it helps...I'll keep this open in the interim.

**Comment by stichbury** [comment]
https://github.com/kedro-org/kedro/issues/2877 now ticketed for the worked needed

**Comment by SajidAlamQB** [comment]
@stichbury Sorry this might be a stupid question but could the `robots.txt` in our docs be having any effect? https://github.com/kedro-org/kedro/blob/main/docs/source/robots.txt

**Comment by astrojuanlu** [comment]
Our community is now visible in the Linen main page https://www.linen.dev/ and https://www.linen.dev/communities

**Comment by stichbury** [comment]
And the indexing does seem to be working! I tried "Is it possible to define multiple types of base datasets for PartitionedDataSet?" and our linen was the first result. Closing this for now.
