### ISSUE TITLE
Encourage users to give more complete information on issues

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#2831]
## Description
As per title.

## Context
Sometimes we get bug reports or feature requests that lack some information, which requires some extra work on the dev team to do triaging.

## Possible Implementation

For example, we could use issue forms:

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

Example: https://github.com/pypa/pip/issues/new/choose

![image](https://github.com/kedro-org/kedro/assets/316517/f9be6752-b4aa-4b50-af06-e3d35ebd5ef0)

![image](https://github.com/kedro-org/kedro/assets/316517/5de8cb48-bde5-40af-94a3-7d3e51c414ea)

**Comment by stichbury** [comment]
I'd also like to see the conclusion of issues be templated or clearly explained, so later inspection (particularly if coming to them from the result of a google search) makes it clear what happened to resolve the issue (or how, if it's a misunderstanding in terms of usage, to go forwards)

**Comment by merelcht** [comment]
Closing this after discussing it in backlog grooming and getting agreement from the team that the quality of issue content isn't really a problem.
