### ISSUE TITLE
Create new spaceflight starters

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2838]
## Description
Follow up on https://github.com/kedro-org/kedro/issues/2758

## Context
Create a new suite of starters all based on spaceflights and add them to a repo.
We'll need at least:
1. spaceflights based on pandas (the existing spaceflights starter) 
2. spaceflights based on pyspark https://github.com/kedro-org/kedro/issues/2984
3. spaceflights based on pandas with viz features enabled https://github.com/kedro-org/kedro/issues/2985
4. spaceflights based on pyspark with viz features enabled https://github.com/kedro-org/kedro/issues/2986

## Possible Additional examples
(Not to be done now https://github.com/kedro-org/kedro/issues/2838#issuecomment-1685895743)
- spaceflights with Databricks setup
- spaceflights with Airflow setup

> **Note**
> When the full list of examples has been decided on we should break this ticket down so there's one for each example and they can be tackled separately.

**Comment by merelcht** [comment]
As a follow up on this ticket we should look at how do we deal with overlaps in spaceflight projects. Can we somehow combine them to lessen the maintenance burden?

**Comment by amandakys** [comment]
As a follow up to the conversation we had about #2844 and #2752, @DmitriiDeriabinQB @deepyaman would also like further discussion on the /conf set up of our starters. i.e. what catalog and parameters files we supply.

**Comment by merelcht** [comment]
> As a follow up to the conversation we had about #2844 and #2752, @DmitriiDeriabinQB @deepyaman would also like further discussion on the /conf set up of our starters. i.e. what/how many catalog and parameters files we supply.

@amandakys Again I think you meant to tag @DimedS, the other Dmitrii left the team a while ago 😉

**Comment by deepyaman** [comment]
> As a follow up on this ticket we should look at how do we deal with overlaps in spaceflight projects. Can we somehow combine them to lessen the maintenance burden?

💯 I think most repos I've seen that have this level of duplication have automated processes to generate the different versions.

**Comment by yetudada** [comment]
I think we may need to consider an empty starter for PySpark. Alloy uses it to put code for the verticals in it. I'll leave @datajoely to add comment here.

**Comment by datajoely** [comment]
Yes you are! We can manage this otherwise if you're desperate to delete it. But today we require a starter that has the hook + `spark.yml` in it. cc @marc-solomon @imdoroshenko

**Comment by stichbury** [comment]
Also worth noting is that we have a plan to revise the spaceflights data https://github.com/kedro-org/kedro/issues/2008 and have recently considered reducing the size (@noklam commented "Any reason that we can’t trim the dataset? As a starter that it get used in demo and testing, it takes a considerate of time to run the pipeline. For example in the Kedro bootcamp I see demoing catalog.load("shuttles") takes like 15-20 seconds and is a bit awkward for demo purpose.")

**Comment by astrojuanlu** [comment]
> But today we require a starter that has the hook + spark.yml in it.

Wondering if this could be `pip install kedro-spark` 🤔 I see lots of people copy-pasting the Spark hook, but I'm not sure how much flexibility is needed

**Comment by merelcht** [comment]
> > As a follow up on this ticket we should look at how do we deal with overlaps in spaceflight projects. Can we somehow combine them to lessen the maintenance burden?
> 
> 💯 I think most repos I've seen that have this level of duplication have automated processes to generate the different versions.

@deepyaman Do you have any examples of repos like this? I'd be interested to see how they manage the different versions.

**Comment by yetudada** [comment]
The revised plan of action for this is that to ship this feature in 0.19.0, we will create starters for: 
- Spaceflights based on Pandas (the existing Spaceflights starter) - `spaceflights-pandas`
- Spaceflights based on PySpark - `spaceflights-pyspark`
- Spaceflights based on Pandas with Kedro-Viz features enabled - `spaceflights-pandas-viz`
- Spaceflights based on PySpark with viz features enabled - `spaceflights-pyspark-viz`

In the short-term, our support for Airflow and Databricks will be through documentation. We will have to tell users to edit `spaceflights-pyspark`. And then post 0.19.x, we'll look at improving the workflow when using Airflow and Databricks. At a later stage, we'll also look at how to reduce the duplication across these starters #2874. 

To that end: 

- [ ] I want to see a clean-up of the tickets related to this issue, we have a lot of information in many different places
- [ ] I want to see what the final CLI journey for this ticket looks like, acknowledging that certain features are left out
- [ ] I want a ticket on how we track telemetry for what people select

**Comment by merelcht** [comment]
This has been completed in:
- https://github.com/kedro-org/kedro/issues/2984
- https://github.com/kedro-org/kedro/issues/2985
- https://github.com/kedro-org/kedro/issues/2986
