### ISSUE TITLE
Addition `--name` `-n` argument for kedro new in non-interactive mode

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2865]
## Description

When you have created a Kedro project and execute a kedro command on the CLI for the first time it asks a <project_name>. This is annoying when you keep creating new project, or need to create project with non-interactive mode.

Currently the workaround looks like:
`yes project | kedro new -s pandas-iris`

The task is to add an option to kedro new to immediately

## Context

When running `kedro new`, it will prompt you to enter the project name. It takes some time for `cookiecutter` to download the repository and user are stuck until it finished. It would be a nice-to-have if I can give a `name` argument so I can create the project in 1 command instead of 2.

## What this is not
- We should not make this a mandatory argument. We should keep the current behavior when `-n` is not provided, then prompt user to input the name of the project.

> (kedro_core) kedro_gallery master % kedro new -s pandas-iris

> Project Name
> ============
> Please enter a human readable name for your new project.
> Spaces, hyphens, and underscores are allowed.
>  [Iris]: 

## Possible Implementation

`kedro new -s pandas-iris -n my-pandas` - introduce a new argument

This should be very easy to implement.

**Comment by Galileo-Galilei** [comment]
I've been looking for this in a loooong time, i definitely upvote this!

**Comment by astrojuanlu** [comment]
Tangentially related #1692

**Comment by datajoely** [comment]
Can I also ask for telemetry consent at this point as well, for CI/CD workflows this is critical?

**Comment by noklam** [comment]
> Can I also ask for telemetry consent at this point as well? For CI/CD workflows this is critical.
Relate to 
- #1640

**Comment by deepyaman** [comment]
There are a lot of assignees, so I'm a bit confused, but can I take this? I've already implemented this for a private Kedro-ish fork, so I'll just copy it.

**Comment by merelcht** [comment]
> There are a lot of assignees, so I'm a bit confused, but can I take this? I've already implemented this for a private Kedro-ish fork, so I'll just copy it.

AFAIK @lrcouto and @DimedS started working on this, so you might want to check with them 🙂

**Comment by lrcouto** [comment]
I've started working on this yesterday

**Comment by astrojuanlu** [comment]
Closed in #3235 🎉
