### ISSUE TITLE
Add addon flags to `kedro new` command  

### ISSUE THREAD

**Issue by amandakys** [kedro-org/kedro#2873]
## Description
Related to the work on adding the add on menu to the kedro new creation flow #2850, we want to add the corresponding CLI commands that will allow users to bypass the wizard and create a full project in 'one line'. 

## Possible Implementation
`kedro new --addons=lint,test,log,docs,data` or any subset of these options 
`kedro new --addons=all` 
`kedro new --addons=none`

**Comment by datajoely** [comment]
Can I have a workflow if I want to add something later on?

**Comment by merelcht** [comment]
Completed in https://github.com/kedro-org/kedro/pull/3081
