### ISSUE TITLE
Create redirects for contributor documentation moved into the Github wiki

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2911]
## Introduction
We have moved contributor documentation into the GitHub wiki to separate it from developer docs. We need to add a set of redirects so people with bookmarks can still find it.

## Background
Create a set of redirects in RTD for these pages

* https://docs.kedro.org/en/stable/contribution/developer_contributor_guidelines.html
* https://docs.kedro.org/en/stable/contribution/backwards_compatibility.html
* https://docs.kedro.org/en/stable/contribution/documentation_contributor_guidelines.html
* https://docs.kedro.org/en/stable/contribution/development_for_databricks.html

<s>Also add redirects for the architecture overview page to point to https://github.com/kedro-org/kedro/wiki/Architecture#kedro-architecture-overview</s>

**Comment by stichbury** [comment]
* /en/stable/contribution/developer_contributor_guidelines.html https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers
* /en/stable/contribution/backwards_compatibility.html https://github.com/kedro-org/kedro/wiki/Backwards-compatibility-and-breaking-changes
* /en/stable/contribution/documentation_contributor_guidelines.html https://github.com/kedro-org/kedro/wiki/Contribute-to-the-Kedro-documentation
* /en/stable/contribution/development_for_databricks.html https://github.com/kedro-org/kedro/wiki/Contribute-changes-to-Kedro-that-are-tested-on-Databricks

**Comment by stichbury** [comment]
I've added these...but they're not working 😢  so I'll check again to see what is happening (will give it an hour or two to propagate).

**Comment by astrojuanlu** [comment]
If they're in `/en/stable`, a new `stable` build would be needed. Maybe try in `/en/latest` first?

**Comment by stichbury** [comment]
Ah, interesting. I didn't realise that redirects were built into the docs...I thought they were part of the hosting somehow so as soon as they were set the link would change from RTD page -> GitHub wiki.

**Comment by stichbury** [comment]
From the RTD docs 

>By default, redirects only apply on pages that don’t exist. Forced redirects allow you to apply redirects on existing pages, but incur a small performance penalty, so aren’t enabled by default. You can ask for them to be enabled via support.

> Only [Page redirects](https://docs.readthedocs.io/en/stable/user-defined-redirects.html#id2) and [Exact redirects](https://docs.readthedocs.io/en/stable/user-defined-redirects.html#exact-redirects) can redirect to URLs outside Read the Docs, just include the protocol in To URL, e.g https://example.com.
