### ISSUE TITLE
Replace `.absolute()` with `.resolve()`

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#2912]
## Description

Potentially helps
- #2059 
- https://github.com/kedro-org/kedro/issues/2819
## Context

See https://github.com/kedro-org/kedro/issues/2819#issuecomment-1669748465
See docs:
> Path.resolve(strict=False)[¶](https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve)
Make the path absolute, resolving any symlinks. A new path object is returned:
Python Discussion Thread: https://discuss.python.org/t/pathlib-absolute-vs-resolve/2573/11

![image](https://github.com/kedro-org/kedro/assets/18221871/95ff5625-7dd4-4c68-97bc-2014e53fe2f4)

The only way to remove `..` in a path is using `.resolve()`, this is useful when user need to instantiate `DataCatalog` in a notebook, because the project root is in `../` one level up.

**Comment by astrojuanlu** [comment]
About symlinks, notice that in https://github.com/kedro-org/kedro/issues/2346 I was advocating for the opposite: replacing `.resolve()` with `.absolute()`.

> this is useful when user need to instantiate DataCatalog in a notebook, because the project root is in ../ one level up.

If we do away with the magic path conversion as proposed in https://github.com/kedro-org/kedro/issues/2965, is this still needed?

**Comment by noklam** [comment]
Actually I have a second look. This is the only case that in our codebase use `absolute()`
https://github.com/kedro-org/kedro/blob/a91ccdbecb5541490b5146b6179ab4c621b9ea73/kedro/framework/cli/utils.py#L204-L218

This is the only leftover we used `.absolute()` in the codebase.


https://github.com/kedro-org/kedro/issues/2819#issuecomment-1669771871
Additionally, we may always do a `resolve` in ConfigLoader so even if user provide a relative path it would work. I will add this comment to #2971, depends on the implementation we may avoid this completely with the new `root` argument.

This ticket will remains as a clean up ticket.

**Comment by merelcht** [comment]
Do we still need to do this?

**Comment by astrojuanlu** [comment]
I actually think we should close this and do the opposite: https://github.com/kedro-org/kedro/issues/2346

**Comment by noklam** [comment]
@merelcht It didn't change by #3742. 

https://github.com/kedro-org/kedro/blob/a91ccdbecb5541490b5146b6179ab4c621b9ea73/kedro/framework/cli/utils.py#L204-L218

I just check again, this function is not used anywhere in framework, but only tests. (last change is 4 years ago). Maybe at some points it was used for `kedro build-reqs`? I suggest we deprecate this function since it's a public function and move it to test.

**Comment by astrojuanlu** [comment]
+1

**Comment by astrojuanlu** [comment]
@noklam should we rename and re-scope this issue? Alternatively we can close this one as "won't fix" and open a new one about deprecating `get_pkg_version`

**Comment by noklam** [comment]
@astrojuanlu let's close this ticket and open a new one, the context aren't that relevant here.

I will do it shortly.

**Comment by noklam** [comment]
Closed and open #3789
