### ISSUE TITLE
Make starter tests use non-deprecated dataset

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#2933]
## Description
https://github.com/kedro-org/kedro/blob/16dd1df61c48b6820e077db7bf36b83762e430f0/features/steps/test_starter/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/requirements.txt#L9

This should be `kedro-datasets[pandas.CSVDataSet]` instead (even though we might soon deprecate that name, see https://github.com/kedro-org/kedro-plugins/issues/306)

**Comment by merelcht** [comment]
This issue is outdated and has already been done, see: https://github.com/kedro-org/kedro/blob/main/features/steps/test_starter/%7B%7B%20cookiecutter.repo_name%20%7D%7D/requirements.txt
