### ISSUE TITLE
Add a section to data docs about the `metadata` attribute used by plugins

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2940]
In working on #2888 @astrojuanlu made the comment that we needed to add some content about the `metadata` attribute (https://github.com/kedro-org/kedro/pull/2537) that can be used by plugins, such as the preview stuff for viz? We do need this in the `data_catalog.md` file that introduces settings in the catalog YAML. @merelcht says "I don't think there's any existing docs other than the part about "preview" datasets in viz. I'd suggest doing that in a separate task because it requires new content".

This is that ticket 👯‍♀️

**Comment by merelcht** [comment]
I just realised there was already a ticket for this: https://github.com/kedro-org/kedro/issues/2689

**Comment by astrojuanlu** [comment]
Indeed, let's close in favor of that one.
