### ISSUE TITLE
Set up subproject builds for new RTD projects

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2947]
## Description
Parent task #2600 has the context. As @astrojuanlu comments, we need to set up builds for each project. 

We also need a Heap property to track usage, and it seems sensible to keep each separate.

This is relatively high priority since the work has started (@astrojuanlu has created a subproject) and the sooner we untangle these projects the better for them (particularly for Viz, since it enables a different release cadence).

I'm unsure of the exact steps and what's needed to complete ticket so need some guidance on who is best placed to tackle and how to estimate.

**Comment by astrojuanlu** [comment]
Just wanted to clarify that the fact that the work has started doesn't add more pressure for us to finish it, luckily what we have done so far doesn't have any user-facing implications just yet. However, I do agree that decoupling the projects in this way is going to improve the developer experience for all of us.

**Comment by astrojuanlu** [comment]
Additionally, `kedro-datasets` will need re-syncing the webhook https://readthedocs.org/dashboard/kedro-datasets/integrations/247276/ maybe it got disconnected after I asked the support team to rename the repository.

**Comment by astrojuanlu** [comment]
This is done ✔️
