### ISSUE TITLE
Make `OmegaConfigLoader` the default config loader

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#2949]
## Description
The `ConfigLoader` and `TemplatedConfigLoader` will be removed in https://github.com/kedro-org/kedro/issues/2692, so the new default should be `OmegaConfigLoader`. 

## To be decided
We could either do this in the 18 series before the `ConfigLoader` and `TemplatedConfigLoader` are removed or do it as part of `0.19.0`.

**Comment by astrojuanlu** [comment]
I feel like changing the default could be seen as a breaking change? So I'm voting to do it for 0.19.0.

**Comment by ankatiyar** [comment]
closed by #3243
