### ISSUE TITLE
Review and revise PyPI page for Kedro

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#2952]
## Description

https://pypi.org/project/kedro/ is looking a bit dated now we've updated our contribution guide and set up `awesome-kedro`. There's also a missing graphic and the badges don't work :-0

As a matter of priority, let's review the page and revise it to fix any issues with it.

**Comment by astrojuanlu** [comment]
The contents of the page are derived from `README.md`:

https://github.com/kedro-org/kedro/blob/c9fc80a2ba14d24910de904837b802db3f6c1283/pyproject.toml#L73

**Comment by stichbury** [comment]
I vote to remove the pipeline visualisation since that's a Viz feature and we link to viz anyway; the graphic is on that README where it should be. We need to fix that in the https://pypi.org/project/kedro-viz/ page so let's do as you suggest and use the raw URL to see if works. I'm start on a PR for all this.
