### ISSUE TITLE
Remove CircleCI Tests from config

### ISSUE THREAD

**Issue by ankatiyar** [kedro-org/kedro#2972]
## Description

Part of GHA migration 

## Context

* Make sure we're not missing anything
* remove the CircleCI config

**Comment by SajidAlamQB** [comment]
In https://github.com/kedro-org/kedro/pull/3306 we removed all tests from CircleCI including e2e, unit, linting and nightly build tests.

The remaining workflows on CircleCI is the release and sync workflows which will need to be moved to GitHub actions before we can completely remove the CircleCI config.

See:

https://github.com/kedro-org/kedro/issues/2968
https://github.com/kedro-org/kedro/issues/2969

I will close this issue in favour of https://github.com/kedro-org/kedro/issues/3318.
