### ISSUE TITLE
Link section for disabling file based logging to Databricks docs

### ISSUE THREAD

**Issue by ankatiyar** [kedro-org/kedro#2978]
## Description
* The docs on logging are kind of hidden away. [This page](https://docs.kedro.org/en/stable/logging/logging.html) with all the information about the logging setup does not show up on the [landing page for logging](https://docs.kedro.org/en/stable/logging/index.html) but is visible in the side bar. 
* It's also worth linking the [section for disabling file based logging](https://docs.kedro.org/en/stable/logging/logging.html#disable-file-based-logging) to the deployment docs - eg. [The Databricks docs ](https://docs.kedro.org/en/stable/deployment/databricks/databricks_ide_development_workflow.html) and recommending disabling file based logging for read-only Databricks repos. Not everyone starts with the `databricks-iris` starter.
* We had this as a note in the old docs - https://docs.kedro.org/en/0.18.10/deployment/databricks/databricks_workspace.html#databricks-notebooks-workflow

**Comment by noklam** [comment]
quote the comments from the conversation

> hi db-comminity - I am using this article for DBX and running kedro on databricks https://docs.kedro.org/en/stable/deployment/databricks/databricks_ide_development_workflow.html. However one of the problem is - when writing the logs it reports that logs folder /Workspace/Repos/<USER>/<REPO>/logs is read-only. I tried amending permissions, but did not work.

> we have our own project created from our template and so it default handlers. I can see the examples for dbx is correct one. May be on the documentation we can add a line saying this as people might just create project first using default kedro and then just use this documentation

**Comment by Kundai10** [comment]
May you please assign this issue to me. I want to work on it

**Comment by ankatiyar** [comment]
@Kundai10 Done!

**Comment by Kundai10** [comment]
@ankatiyar I need clarity on some issues. From what I can tell, on the 1st issue, everything seems to be working well. But on the second issue, there seems to be an actual issue. Where exactly, which sub section do I link the 'disabling file based logging'?

**Comment by ankatiyar** [comment]
I would add a note under the following sections saying if you're not using the the `databricks-iris` starter and you would want to disable the file based logging on your projects and a link to https://docs.kedro.org/en/stable/logging/logging.html#disable-file-based-logging -
* https://docs.kedro.org/en/stable/deployment/databricks/databricks_notebooks_development_workflow.html#create-a-new-kedro-project
* https://docs.kedro.org/en/stable/deployment/databricks/databricks_ide_development_workflow.html#create-a-new-kedro-project
* https://docs.kedro.org/en/stable/deployment/databricks/databricks_deployment_workflow.html#create-a-new-kedro-project

For inspiration, the previous note was like this - 
https://github.com/kedro-org/kedro/blob/22fc2707a54d9b3138abe7bf58bd713226a004bf/docs/source/deployment/databricks.md?plain=1#L5-L8

**Comment by JayOaks** [comment]
Hi,
I think I understand this and would like e to attempt it.
May I?

**Comment by astrojuanlu** [comment]
Hi @JayOaks , we haven't heard back from Kundai so please go ahead!

**Comment by JayOaks** [comment]
Thank you.

**Comment by stichbury** [comment]
This is all done and waiting to merge. Thanks @JayOaks!
