### ISSUE TITLE
Control excessive Kedro versions in search results

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#2980]
## Description
Sometimes when I search content from the Kedro docs, too many versions appear:

![image](https://github.com/kedro-org/kedro/assets/316517/c87d0e44-c0cb-45e9-ab84-0825653148ed)

## Context

Ideally, only one version (the latest one) should be shown.

## Possible Implementation

Read the Docs allows you to _hide_ a version from search engines https://docs.readthedocs.io/en/stable/guides/deprecating-content.html#deprecating-versions however, doing so _also_ hides the version from the flyout menu.

## Possible Alternatives

Alternatively, we can create our own `robots.txt` file https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html#use-a-robots-txt-file that disallows certain versions from search engines while leaving the flyout menu untouched. This would need a bit of maintenance over time.

cc @stichbury

**Comment by stichbury** [comment]
This has bothered me for a while too, and I did restrict some of the older versions in RTD for that reason, but figured the flyout needed to show most, if not all, recent versions. I like the idea of modifying `robots.txt` and also thinking about how we present versions when we come to customise the docs with our theme for the subprojects. Maybe there's a way to update in RTD to restrict visibility in the flyout, but then add a design element to allow access to all versions that's separate from the flyout for people that really want them?

**Comment by stichbury** [comment]
I'm going to suggest we put this in the coming sprint as a task for engineering (maybe @SajidAlamQB ?) but it's not a high priority if we need to push it over to the next.

**Comment by astrojuanlu** [comment]
Starting point: the automatically generated `robots.txt` https://docs.kedro.org/robots.txt

**Comment by stichbury** [comment]
We will need to guide @tynandebold and @SajidAlamQB on which versions we want to index and which we want to hide. Do we want to be fairly proscriptive and have just these indexed:
* 0.16.0
* 0.17.0
* 0.18.0
* Latest, stable

Or be a bit more generous and index these:

* 0.16.0
* 0.17.0
* 0.18.0, 
* 0.18.5 - 0.18.13
* Latest, stable

**Comment by stichbury** [comment]
I think we may as well be quite strict but it does depend how familiar people are with the flyout at the bottom left, if they want more versions. Can we change the RTD settings so the docs always load with the flyout open?

**Comment by stichbury** [comment]
Sounds reasonable, probably more useful than just going with the initial versions of each major release. Let's do it!

**Comment by stichbury** [comment]
I've changed my mind, and think we should now update robots.txt to just allow these for search:
