### ISSUE TITLE
Fix Configuration Loader to Handle Paths Containing dots

### ISSUE THREAD

**Issue by erwinpaillacan** [kedro-org/kedro#3004]
## Description

When working within Databricks workflows, it's possible to create a job that utilizes a notebook hosted inside a repository. Each time the job is executed, the code is automatically cloned to a path that depends on the commit. In my case, I have hosted a notebook that runs the Kedro project within the `.azuredevops` directory.

To locate the current project root, we can employ a regular expression (regex) pattern:

```python
pattern = r"^/Workspace/Repos/.internal/(?!./.azuredevops)."
```

With this regex, we can effectively identify the project root. For example, one possible path is:

```
/Workspace/Repos/.internal/02476ba86f_commits/20adcb96c8bec99ac2fad8b78b25158e7d968fa4/
```

However, there's an issue that arises when a period (dot) appears within the path. This problem is not limited to Databricks; it can also occur locally. It's important to note that the OmegaConfigLoader did not encounter any issues with this path until Kedro version 0.18.12.

## Context
Just running a normal kedro project. Which was working untill 0.18.12

## Steps to Reproduce
1. modify you project directory adding some `.`, for example if you a have a kedro project in `Users/yourname/kedro_project` you can create a new folder with some point `Users/yourname/.somefolder/kedro_project` 
2. [Second Step] Enable OmageConfigLoader
3. [And so on...]  Kedro run

## Expected Result
kedro should load the session

## Actual Result
The config loader is not be able to find any config file

```
`No files of YAML or JSON format found in /Workspace/Repos/.internal/02476ba86f_commits/20adcb96c8bec99ac2fad8b78b25158e7d968fa4/conf/base or /Workspace/Repos/.internal/02476ba86f_commits/20adcb96c8bec99ac2fad8b78b25158e7d968fa4/conf/databricks_dev matching the glob pattern(s): ['catalog*', 'catalog*/**', '**/catalog*']`
```

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): 0.18.13
* Python version used (`python -V`): 3.10.12
* Operating system and version: mac

**Comment by noklam** [comment]
@erwinpaillacan Potential conflict requirements with https://github.com/kedro-org/kedro/pull/2977

Does it work with other ConfigLoader? And what will be the expected behavior?

**Comment by erwinpaillacan** [comment]
I think we need to ignore internal folders but after project root, not before.
to allow to have project root with dots, which is useful in databricks workflows.

The expected behaviour would be to able to run the kedro project.

Just tested TemplatedConfigLoader and it works fine.

**Comment by noklam** [comment]
@erwinpaillacan I agree that but we need something more generic. Conf is not necessary inside a project. While it may not be common, one may actually have their conf folder inside a hidden folder but outside project root.

I have some idea to fix this but will need further investigation.

**Comment by astrojuanlu** [comment]
Potential root cause (not checked):

https://github.com/kedro-org/kedro/blob/955bc935d709ee85ecbb4c36e987162c2ae4f0ca/kedro/config/omegaconf_config.py#L258-L259

https://github.com/kedro-org/kedro/blob/955bc935d709ee85ecbb4c36e987162c2ae4f0ca/kedro/config/omegaconf_config.py#L394-L400

**Comment by merelcht** [comment]
When addressing this we'd ideally find a solution for this problem as well as https://github.com/kedro-org/kedro/pull/2977. That fix seems to be the cause of this.

**Comment by IngerMathilde** [comment]
I fixed this locally as a quick bugfix like this. 

```
    def _is_hidden(self, path: str):
        """Check if path contains any hidden directory or is a hidden file."""
        path = Path(path).resolve()
        conf = Path(self.conf_source)
        relative_path = path.relative_to(conf).as_posix()
        # filesystem specific separator
        parts = relative_path.split(self._fs.sep)
        HIDDEN = "."
        # Check if any component (folder or file) starts with a dot (.)
        return any(part.startswith(HIDDEN) for part in parts)
```

Maybe a usefull starting point :). Believe it also still works for the original problem. Could make a PR if you would like.

**Comment by ankatiyar** [comment]
@IngerMathilde Thank you for investigating this and sharing the solution! ⭐ 
Since this ticket is a part of the current sprint and a blocker for the next release, I'd like to take care of this PR!
If you do have the capacity, please check out [the Hacktober tickets](https://github.com/kedro-org/kedro/issues/3130)! We'd love to see contributions from you! :)

**Comment by ankatiyar** [comment]
@IngerMathilde I've opened a PR for this #3145, would you mind sharing your email id so we can add you as a co-author of that PR? :)

**Comment by IngerMathilde** [comment]
Hi!
Thanks a lot! You can put it on: 42641352+IngerMathilde@users.noreply.github.com
