### ISSUE TITLE
`AbstractDataSet` and `AbstractVersionedDataSet` should be printed meaningfully

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#3006]
## Description

> <kedro_datasets.pandas.csv_dataset.CSVDataSet object at 0x7f7f69bde2e0>}

It is always frustrating to see this when debugging. In addition, `_describe()` is a mandatory method so I would expect this is the default `__repr__` of a dataset. What is it used for?

## Context

The developer experience with dataset in interactive mode is sub-optimal. This is a quick win without much drawback

## Possible Implementation

Add default `__repr__` to the AbstractClasses

## Possible Alternatives

Take one extra step to make them dataclass. In this case I think it still make sense to call `_describe` in `__repr__`, but maybe the default could be fallback to dataclass __repr__

(noted: Dataclass here isn't referring to a specific library, could be `dataclasses`, `attrs` or `pydantic`)

**Comment by astrojuanlu** [comment]
One caveat: printing should avoid printing credentials at all costs IMHO

**Comment by noklam** [comment]
@astrojuanlu Good point, we can always try to mask the `credentials` key. Any insight how tools like Github Action magically mask environment credentials?

**Comment by merelcht** [comment]
Closing because this was done in https://github.com/kedro-org/kedro/pull/3987
