### ISSUE TITLE
Move Kedro documentation CSS to package allow sharing across subprojects

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#3016]
## Description
Following on from parent task kedro-org/kedro#2600, there is one subtask that we need to do to fix the styling so any new subprojects for Viz, Datasets, Starters etc use exactly the same theme as the Kedro docs.

<s>I'm not sure what is involved with this (I naively thought we could just copy the CSS around but I guess that's not exactly maintainable). </s> Edit: Now have a plan.

Please can I add to your queue @tynandebold for consideration & prioritisation.

**Comment by tynandebold** [comment]
Does it need to be pip installable? Could we instead host these two files in a centralized place and then use those URLs to reference the CSS via RTD?

Prerequisite for this is that we're able to add a custom `<link>` tag in the `<head>` section of a RTD project. I haven't looked into if this is possible.

**Comment by stichbury** [comment]
> Does it need to be pip installable? Could we instead host these two files in a centralized place and then use those URLs to reference the CSS via RTD?
> 
> Prerequisite for this is that we're able to add a custom `<link>` tag in the `<head>` section of a RTD project. I haven't looked into if this is possible.

I _think_ it's OK to use a link, from looking at this: https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html

<img width="743" alt="image" src="https://github.com/kedro-org/kedro/assets/5180475/92dd7989-3e6c-42f7-920d-62ea437838ca">

What you are suggesting is a "fully qualified path", right?

**Comment by tynandebold** [comment]
Yes indeed! Then I think we're in business and need not create a new Python package. We can dump these files on S3 or maybe even GitHub pages, adding them to a new repo in our organization.

Haven't thought it through too far other than to say this sounds like a wiser option.

**Comment by astrojuanlu** [comment]
Notice that it's not only CSS files we'd like to distribute: we're starting to have duplication in `conf.py`. Compare

https://github.com/kedro-org/kedro/blob/e949c6c7d8814ba5fc97c7204c69103a3e9ad21a/docs/source/conf.py#L345

with

https://github.com/kedro-org/kedro-plugins/blob/7d092dbdb9344af58435ed6a696331ecb80ae553/kedro-datasets/docs/source/conf.py#L240

The more Sphinx projects we add (and soon we'll need kedro-viz and others), the more stuff we need to copy-paste to `conf.py` that could be distributed as functions.

In addition, if we ever want to change the theme base from sphinx-rtd-theme to something else (which we absolutely want, see https://github.com/kedro-org/kedro-viz/issues/1474) we'd need to again change the `html_theme` value in `conf.py` as well as the dependencies in every single package, which will become tedious soon.

As a result I'm all in favour of creating a new Python package.

**Comment by tynandebold** [comment]
I didn't notice that, thank you for pointing that out. 

Since it's more than only CSS a new Python package seems best, as JuanLu said.

I know much less about that, though am still happy to help with the styling part.

**Comment by stichbury** [comment]
Hmm, I'm still not convinced though. Is the complexity of adding another package for reuse really worth the occasional `conf.py` edit when we aren't likely to be changing theme _that_ often (I hope!). It also means each project is then bound to share a conf.py and this may not be ideal in some cases (e.g. link checker exclusions, extensions).

I'm not sure, but I still like the idea of keeping things simple, and not getting into reuse because "we can" 🤷

**Comment by astrojuanlu** [comment]
To clarify, projects would not share a `conf.py` (I don't think that's possible) but could optionally load the modifications we make on demand.

Regardless, I don't want to become the bottleneck of this 😄 so if this is on the critical path towards #2600, then I'm okay with uploading the CSS assets somewhere and using those directly for now.

**Comment by stichbury** [comment]
Oh OK, that sounds better, but still a bit complicated for my poor 🧠 to compute. Let's just go with basic CSS as per @tynandebold's original suggestion on S3 or similar.  Makes it simple and when/if we later need to dig ourselves out of the technical debt I'm dumping us in, I promise to be humble 😊

**Comment by stichbury** [comment]
Now at https://kedro-shared-files.s3.eu-west-2.amazonaws.com/theme-overrides.css

**Comment by tynandebold** [comment]
I've uploaded both theme files now: 

- https://kedro-shared-files.s3.eu-west-2.amazonaws.com/qb1-sphinx-rtd.css
- https://kedro-shared-files.s3.eu-west-2.amazonaws.com/theme-overrides.css

**Comment by stichbury** [comment]
We can close this as done now. The CSS is used in the Viz docs project and I will make a branch on develop for the same.
