### ISSUE TITLE
Affiliation of Kedro TSC members is not clear

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3039]
## Description

Kedro prouds itself on being a Linux Foundation AI & Data multi-stakeholder project, but the question of who those stakeholders are is difficult to answer by looking at our current docs or website.

## Expected Result
Something similar to what Delta Lake does: https://delta.io/community/

![image](https://github.com/kedro-org/kedro/assets/316517/b540452d-9c45-4d75-98f3-52458487883a)

## Actual Result
https://docs.kedro.org/en/stable/contribution/technical_steering_committee.html#kedro-maintainers

![image](https://github.com/kedro-org/kedro/assets/316517/9b6aee7d-78ac-46e4-85a2-ebfafbf1109c)

**Comment by stichbury** [comment]
Sort of agree but I also like the flat equality of our alphabetical list. I guess it was obvious in the early days because we were all QB but maybe as time goes by there's more of a need to show this. I don't particularly like assigning focal areas though, but WDYT?

**Comment by deepyaman** [comment]
> Sort of agree but I also like the flat equality of our alphabetical list. I guess it was obvious in the early days because we were all QB but maybe as time goes by there's more of a need to show this. I don't particularly like assigning focal areas though, but WDYT?

I think alphabetical + organization (no need for focal areas) would work?

**Comment by astrojuanlu** [comment]
Yeah the Delta was just an example, I don't think we need focal areas either

**Comment by stichbury** [comment]
Here's a PR, I took the opportunity to make this change while I was adding @MehdiNV https://github.com/kedro-org/kedro/pull/3046

**Comment by astrojuanlu** [comment]
For future reference, https://github.com/kedro-org/kedro/pull/3046#discussion_r1330534681 some discussion about how to structure this.

**Comment by stichbury** [comment]
This is now done.
