### ISSUE TITLE
Update `kedro new` add-ons flow to match design additions

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#3047]
## Description
As discussed with @merelcht, #2987 is just the first iteration of the implementation of the add-ons flow. As the design process continues, we may see some changes to the feature, and as a result, it's implementation. This issue is to serve as a catch-all for these changes once this design process is concluded.

## Context
TODO: This issue should be fleshed out with the details of what is to be changed before being added to the sprint. 

## Pending
https://github.com/kedro-org/kedro/issues/3054

Ref: #2850 

CC @amandakys

**Comment by merelcht** [comment]
Closing this in favour or #3054 and #3216
