### ISSUE TITLE
Update documentation to reflect the new `kedro new` add-ons flow

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#3048]
## Description
Make sure any references to `kedro new` are updated in accordance with the new changes. Additionally a section should be added detailing this new flow, what it means to users, and how to use it (in CLI and via config file).

These docs should mention all add-ons added in the tickets:
- https://github.com/kedro-org/kedro/issues/2850
- https://github.com/kedro-org/kedro/issues/3073
- https://github.com/kedro-org/kedro/issues/3074
- https://github.com/kedro-org/kedro/issues/3076

**Comment by AhdraMeraliQB** [comment]
There are a couple placeholders in the files as well - make sure to do a search and replace the `# TODO; Insert actual link to the documentation.` and `kedro.org/{insert-documentation}`

**Comment by astrojuanlu** [comment]
@stichbury can give a more informed opinion in a few days, but maybe if we were to start writing these docs, shall we put them under https://docs.kedro.org/en/stable/kedro_project_setup/? For example `https://docs.kedro.org/en/stable/kedro_project_setup/addons.html` (hence `docs/source/kedro_project_setup/addons.md`)

cc @AhdraMeraliQB @amandakys

**Comment by stichbury** [comment]
I don't think something as significant should go into `/kedro_project_setup` which is one of the docs sections that is still in need of general attention and improvement. This is surely an update for the early onboarding content?

**Comment by astrojuanlu** [comment]
Good point, I hadn't realized that was listed under "Advanced". But that's where the starters are explained, so I thought it would be the natural place. Feel free to suggest otherwise.

**Comment by stichbury** [comment]
Yeah I think https://docs.kedro.org/en/stable/kedro_project_setup/starters.html needs to be split into two:

* Introduction to Kedro starters (which moves into the "Kedro projects" section
* [How to create a Kedro starter](https://docs.kedro.org/en/stable/kedro_project_setup/starters.html#how-to-create-a-kedro-starter) which stays in the Advanced section

**Comment by astrojuanlu** [comment]
Sounds perfect to me 👍🏽

**Comment by stichbury** [comment]
See also https://github.com/kedro-org/kedro/issues/3201 (to improve 'project setup' docs) and https://github.com/kedro-org/kedro/issues/3161 (to improve starters docs) as related tickets.

**Comment by merelcht** [comment]
This needs engineering input, so tagging/assigning the engineers who have done most of the add-ons work so far to help out with this @noklam @SajidAlamQB @AhdraMeraliQB @lrcouto @DimedS.

**Comment by stichbury** [comment]
I have now created a PR which has marked where changes are necessary to address the add-ons flow changes.

Please can I pass this to one or more of @noklam @SajidAlamQB @AhdraMeraliQB @lrcouto @DimedS (as noted by @merelcht) to do a pass over the docs. Look for comments  notes in the following:onboarding docs, tutorial and addons_and_starters folder of the docs/source folder.

**Comment by AhdraMeraliQB** [comment]
Closed by https://github.com/kedro-org/kedro/pull/3331

**Comment by DimedS** [comment]
Apologies for the delayed response. New docs section looks really great 👍 .
But it appears we should add a mention of "example_pipeline" in the documentation [here](https://github.com/kedro-org/kedro/blob/9dcc1523d5c7aef2bf737ea3db918c25fc0ece8c/docs/source/starters/new_project_tools.md?plain=1#L129C5-L129C5)
This clarification is necessary because, as it stands, users might not realize they need to specify "example_pipeline" in the config.yml file, rather than just "example" as when using the CLI.
