### ISSUE TITLE
Make `settings.py`  optional

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#3050]
## Description

Currently `settings.py` must be provided for a Kedro Project. `kedro new` always ship a `settings.py` with commented default. We should update the functionality so that when a user deleted `settings.py`, `kedro run` still works. 

## Context

Reduce assumptions of what makes a "Kedro Project". Since the file by default doesn't do anything, we shouldn't enforce user to have it if they don't need to customise settings.

In addition, we can discuss whether we should allow user to customise where Kedro search for the "settings.py".

## Implementation
This should be backwards compatible and a non-breaking change, so kedro should work with or without a `settings.py` file.

**Comment by astrojuanlu** [comment]
+1, creating an empty `settings.py` always feels like a burden.

This nudges Kedro more towards "convention over configuration", which might be a philosophical change we might want to discuss.

**Comment by miguel-ortiz-marin** [comment]
I have an idea around it! Can I please be assigned to it?

**Comment by astrojuanlu** [comment]
Hi @miguel-ortiz-marin, feel welcome to work on it! We don't assign issues to external contributors, just share the idea with us or better yet, open a PR directly :) If you need any help, let us know.

**Comment by miguel-ortiz-marin** [comment]
Hi @astrojuanlu. Awesome! I opened a draft PR, I still have to update some comments and go through all the PR checklist but the core functionality is there!.

Happy Hacktoberfest 👻
