### ISSUE TITLE
Simplify Packaged Kedro Project entrypoint __main__.py, move `_find_run_command` to Framework

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#3051]
## Description

`kedro new` ship a `__main__.py` which is the default way to run a packaged Kedro Project with `python -m <project>`. Currently we expose a function that loads the run command in the project. This should be move to the framework.

https://github.com/kedro-org/kedro-starters/blob/87715c48977bdfe1c64dd1d924a9f3e6c0933951/pandas-iris/%7B%7B%20cookiecutter.repo_name%20%7D%7D/src/%7B%7B%20cookiecutter.python_package%20%7D%7D/__main__.py#L11-L36

## Context

This make upgrading Kedro Project is hard because we leave code in user project.

**Comment by noklam** [comment]
Cc @idanov Could you supplement what was the challenge that we need to solve to move this back to framework?

**Comment by idanov** [comment]
I believe that the only challenge is to figure out what is the best and most user-friendly way to import the `run` function from `kedro.framework.project` and if we can make it behave in the same way as `kedro.framework.pipelines`, i.e. lazily loaded and configured only after `configure_project` is called before it is used.
