### ISSUE TITLE
Update docs about building plugins to use `pyproject.toml` instead of `setup.py`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3053]
## Description
The [docs about building plugins for Kedro](https://docs.kedro.org/en/stable/extend_kedro/plugins.html) still mentions `setup.py`. We should update that to use `pyproject.toml` instead.

## Context
This is inline with making the python packaging/plugin flow up to date with the current industry standards.

**Comment by astrojuanlu** [comment]
Maybe remilestone to https://github.com/kedro-org/kedro/milestone/36?

Otherwise, for general doc improvements, I think we have https://github.com/kedro-org/kedro/issues/1539 (and a duplicate I opened, #2685)

**Comment by merelcht** [comment]
That milestone is closed because the majority of the work is done. This could actually be a nice small ticket for Hacktoberfest.

**Comment by stichbury** [comment]
Parent ticket #1539

**Comment by abhishek-nigam** [comment]
Hi team at Kendo-Org, I would like to pick this up. Though I have about 4 years of experience in software engineering, I haven't really worked with medium-large Python projects. Also, this would be my first contribution in open-source projects, and I feel excited about it.

Shall I work on it? Thank you for building Kendro!

**Comment by astrojuanlu** [comment]
Hi @abhishek-nigam , welcome! Of course - no need to assign the issue, feel free to send a pull request for it whenever you're ready

**Comment by stichbury** [comment]
Hi @abhishek-nigam Just checking in to see how this is going for you? I've assigned you to it and marked as "In progress" but do let us know if you prefer to put it back in the backlog.

**Comment by abhishek-nigam** [comment]
Hi @stichbury ! The past week has been slightly hectic for me since I've been interviewing for jobs. Now, that I've made it past them, I am looking forward to starting with this task from Friday. I'll keep you posted about any questions that I have, my progress here.

**Comment by stichbury** [comment]
Hi @abhishek-nigam I'm not sure if you've had any time to tackle this issue but today is the last day of October, so just in case you've the work ready to go, but not yet got it in to our queue, now's the time to do so 🏃 💨

**Comment by merelcht** [comment]
I just realised this was already done as part of https://github.com/kedro-org/kedro/pull/3013. So I'll close this issue.
