### ISSUE TITLE
Remove all deprecated CLI from develop

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#3064]
## Description

We had a few CLI deprecated in 0.18.x but it haven't been removed from `develop`.

**Comment by merelcht** [comment]
Do you mean the development CLI commands? We've got https://github.com/kedro-org/kedro/issues/1617 for that, or do you mean other ones on top of that?

**Comment by noklam** [comment]
Ah, I overlooked this issue. Closing as duplicate #1617
