### ISSUE TITLE
Fix test coverage after removing kedro.extras.datasets

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#3068]
# Context

>               A separate PR to address the coverage/test problem. Noted I change `coverage` temporarily because we now missing some coverage as we removed the `kedro.extra.datasets`
> 
> _Originally posted by @noklam in https://github.com/kedro-org/kedro/issues/3057#issuecomment-1731672694_

After removing kedro.extras.dataset, the coverage drop to 99.4%. #3057 tepmorarily suppress the coverage for 2 extra files. This should be fixed before 0.19.

# Possible implementation
- Either moved/duplicate some test to `kedro` or create some new tests.

**Comment by ankatiyar** [comment]
Closed by #3154
