### ISSUE TITLE
Add `pyspark` to add-ons options

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3073]
## Description
`pyspark` should be added to the add-ons options, allowing users to get setup for pyspark (see https://github.com/kedro-org/kedro/issues/2506#issuecomment-1717432995). This option should make use of the new `spaceflights-pyspark` starter: https://github.com/kedro-org/kedro/issues/2984

When a user select `pyspark` they should get the config needed to run Kedro project with pyspark. This shouldn't include the example pipelines. This will happen in a follow up ticket. 

## Possible Implementation
This solution is likely going to be the same as for the other `add-ons` work, leveraging the post-project hooks. Since we'd use the spaceflights-pyspark starter and not the regular template, we probably need to copy some of the logic from the post-project hook in the regular template to the starter. 

## Possible Alternatives
N/A

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro/pull/3169
