### ISSUE TITLE
Add `kedro-viz` to add-ons options

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3074]
## Description
`Kedro Viz` should be added to the add-ons options, allowing users to get setup for viz (see https://github.com/kedro-org/kedro/issues/2506#issuecomment-1717432995). This option should make use of the new `spaceflights-pandas-viz` starter: https://github.com/kedro-org/kedro/issues/2985

When a user selects `viz` they should get the config/requirements needed to run Kedro viz on their project. This shouldn't include the example pipelines. This will happen in a follow up ticket. 

## Possible Implementation
This solution is likely going to be the same as for the other `add-ons` work, leveraging the post-project hooks. Since we'd use the spaceflights-pandas-viz starter and not the regular template, we probably need to copy some of the logic from the post-project hook in the regular template to the starter. 

## Possible Alternatives
N/A

**Comment by SajidAlamQB** [comment]
Completed in https://github.com/kedro-org/kedro/pull/3228
