### ISSUE TITLE
Make it possible for users to select both `pyspark` and `viz` in add-ons

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3075]
## Description
Follow up to https://github.com/kedro-org/kedro/issues/3073 and https://github.com/kedro-org/kedro/issues/3074

It should be possible for users to select both `pyspark` and `viz` as add-ons options and pull all the right requirements and config to enable both tools in the Kedro project. This should make use of the new `spaceflights-pyspark-viz` starter https://github.com/kedro-org/kedro/issues/2986.

## Context
This doesn't include adding an example pipeline yet.

## Possible Implementation
- Use post project hooks: see #3073 and #3074 for the approach

**Comment by SajidAlamQB** [comment]
Completed in https://github.com/kedro-org/kedro/pull/3228
