### ISSUE TITLE
Remove deprecated `project_version`

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3084]
`project_version` was deprecated in favour of `kedro_init_version` in https://github.com/kedro-org/kedro/issues/2118 and https://github.com/kedro-org/kedro/pull/2219, but hasn't been removed yet.

**Comment by noklam** [comment]
I intend to do this first because I find that I need to update ProjectMetadata for https://github.com/kedro-org/kedro/pull/3188. It would be cleaner to update ProjectMetadata in 1 complete PR

**Comment by merelcht** [comment]
Completed in https://github.com/kedro-org/kedro/pull/3222
