### ISSUE TITLE
Incorrect Pipeline Visualization in Iris Kedro Tutorial 

### ISSUE THREAD

**Issue by Volcanes** [kedro-org/kedro#3108]
Hi, I've noticed in the Iris starter tutorial a screenshot, but the screenshot apparently belongs to the spaceflights starter. The Iris screenshot is this one.

![image](https://github.com/kedro-org/kedro/assets/56490866/801a312e-89b3-44bc-98c0-872cf229a244)

Appologies if I missunderstood the project.

**Comment by astrojuanlu** [comment]
Thanks @Volcanes! You mean this page right? https://docs.kedro.org/en/stable/get_started/new_project.html#iris-example-visualisation

Indeed, that's the wrong screenshot. Do you want to send a pull request fixing this page yourself?

**Comment by Volcanes** [comment]
Yes that is the page. I prefer to leave you to do the change. Please go ahead! 

Thank you!
