### ISSUE TITLE
Inconsistencies in spaceflights data

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3110]
### Description
- When merging `rated_shuttles` with `companies`, both dataframes have an `id` column, and this creates `id_x` and `id_y`, which could be avoided by selectively dropping `id` before merging
- `companies` has duplicate rows, so when merging `rated_shuttles` with `companies`, some rows are repeated and this might distort the result, which could be avoided by doing a `.drop_duplicates()` on companies

**Comment by Celsuss** [comment]
I see that the code fix for starter project got fixed, so is this about updating the documentation which I can see is no longer correct?

**Comment by stichbury** [comment]
This is fixed by #3119
