### ISSUE TITLE
Update all starter docs/READMEs 

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3111]
## Description
After the new `spaceflights` starters have been added and old starters removed, we should make sure the remaining starters contain up to date information:
- Remove any mentions to old CLI commands/best practices
- Add mentions to the project creation `add-ons` flow where relevant

## Context
The readme's on the starters are all slightly different. For `0.19.0` we should review and make sure they all contain up to date readme's and docs.

**Comment by stichbury** [comment]
Parent ticket #3158
