### ISSUE TITLE
Add new `spaceflights` starters to `--starter` flag options

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3112]
## Description
Users should be able to use the [new `spaceflights` starters](https://github.com/kedro-org/kedro/issues/2838) through `kedro new --starter=...`.  
With the starter flag they would get to full project. If they use `--add-ons` instead they can select only the parts of the project they want. 

Note that users cannot use the `--starter` and `--add-ons` flags together. It’s either or and if they use `--starter` they get the full template.

## Context
The [new starters](https://github.com/kedro-org/kedro/issues/2838) are mainly added to facilitate the [new project creation flow](https://github.com/kedro-org/kedro/issues/2388). Existing starters can be used through the `--starter` flag, we'll add the new ones as well for consistency.

**Comment by ankatiyar** [comment]
Closed by #3211
