### ISSUE TITLE
Release Kedro + starters 0.18.14

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3123]
### Description

Release Kedro and Kedro-Starters (happens automatically) `0.18.14`

### To do:

`kedro`
- [x] https://github.com/kedro-org/kedro/pull/3095
- [x] https://github.com/kedro-org/kedro/issues/3114
- [x] https://github.com/kedro-org/kedro/issues/3004
- [x] https://github.com/kedro-org/kedro/issues/3125
- [x] https://github.com/kedro-org/kedro/pull/3176
- [x] https://github.com/kedro-org/kedro/issues/3107

`kedro-starters`
- [x] https://github.com/kedro-org/kedro-starters/pull/152

**Comment by ankatiyar** [comment]
Reminder to add all community contributors (especially since there's a lot of small PRs) to the release notes before the release.

**Comment by stichbury** [comment]
> Reminder to add all community contributors (especially since there's a lot of small PRs) to the release notes before the release. CC @astrojuanlu

[There's an outstanding PR open for release notes if anyone wants to commit directly onto that branch](https://github.com/kedro-org/kedro/pull/3176)
