### ISSUE TITLE
READ ME FIRST! Join Kedro for Hacktoberfest!

### ISSUE THREAD

**Issue by ankatiyar** [kedro-org/kedro#3130]
![Kedro-Hacktoberfest promo -1600x900](https://github.com/kedro-org/kedro/assets/110245118/ea9f9c20-7991-4cf3-b21e-79e2e10a9194)

If you want to contribute to Kedro for Hacktoberfest, this issue will help get you started!
* Sign up for [Hacktoberfest](https://hacktoberfest.com/)!
* Find the Kedro issue you want to work on [tagged with the "Hacktoberfest" label](https://github.com/kedro-org/kedro/labels/hacktoberfest).
* Write a comment on the issue to indicate that you want to tackle it, and then get working! (You won't be able to assign it to yourself but we can do that for you). 
* If you need to, ask us for information, clarification or help in the comments of the issue you are working on or give us a shout on [our Slack workspace](https://slack.kedro.org).

## Contribute to our code
* Read the [Guidelines for contributing developers](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers). This has all the instructions on getting you set up for code contribution to Kedro.
* For some of the tickets, you will need to check out the `develop` branch instead of `main` and open PRs against the `develop` branch! Read the instructions on the issues carefully!
* Make sure all the tests pass on your PR and the documentation is update in line with your changes.

## Contribute to our documentation
* Find tickets that are labelled "Hacktoberfest" as well as "Component: Documentation 📄".
* Read the [Guidelines for contributing to docs](https://github.com/kedro-org/kedro/wiki/Contribute-to-the-Kedro-documentation).
* Also read the [Kedro documentation style guide](https://github.com/kedro-org/kedro/wiki/Kedro-documentation-style-guide).

## Contribute to our plugins
* We also maintain some plugins over at our [`kedro-plugins` repository](https://github.com/kedro-org/kedro-plugins). [Find issues labelled "Hacktoberfest" over there as well](https://github.com/kedro-org/kedro-plugins/labels/Hacktoberfest)!

**Comment by stichbury** [comment]
Tickets open:

- [ ] #3109 
- [ ] #3108 
- [ ] #3053 
- [ ] #2978 
- [ ] #2870 
- [ ] #2691 
- [ ] #2643 
- [ ] #2618 
- [ ] #2604 
- [ ] #2527 
- [ ] #2305 
- [ ] #2224 
- [ ] #2008 
- [ ] #479

**Comment by ggermade** [comment]
> If you want to contribute to Kedro for Hacktoberfest, this issue will help get you started!
> 
> * Sign up for [Hacktoberfest](https://hacktoberfest.com/)!
> * Find the Kedro issue you want to work on [tagged with the "Hacktoberfest" label](https://github.com/kedro-org/kedro/labels/hacktoberfest).
> * Assign yourself the issue and get working! Ask us for information, clarification or help in the comments of the issue you are working on or give us a shout on [our Slack workspace](https://slack.kedro.org).

Hello! It says here contributors should assign themselves the issue they want to work on, but shouldn't it say to open a PR when a fix is ready for review, without actually assigning themselves the issue? (Seeing as permissions for self-assignation aren't present)

**Comment by stichbury** [comment]
Oh, thanks for letting us know @ggermade! While your suggestion makes sense, it would also be a shame if two people chose the same issue to work on and didn't find out until one made a PR that they were working to solve the same thing. 

Maybe it makes sense to write a comment on whichever issue you choose to say you've picked it up (and I'll look into whether we can change permissions so self-assignation is possible). I'll amend the issue to say that. Thanks again!

**Comment by astrojuanlu** [comment]
Although, let's watch out for "cookie licking" 🍪 https://www.redhat.com/en/blog/dont-lick-cookie

**Comment by stichbury** [comment]
Indeed, who wants a soggy 🍪 ?

We'll see the comments come in and I think we can then assign the issues, so can ensure only 1 assigned per person at a time and maybe create some calendar reminders to check in after a week and see how it's going?

**Comment by shreyadatar** [comment]
Hi @stichbury! I'd love to contribute to Kedro for Hacktoberfest. However, I am finding it hard to figure out which issues are assigned and which aren't. Should I go off of the comments on the issue to confirm that? Or should we expect to see assignments for issues? Thanks, and happy hacking!

**Comment by stichbury** [comment]
@shreyadatar Good point, is hard to see. I've just added some names to those tickets where people have volunteered (or have PRs in flight) and marked them as "In progress". So I'd look more at tickets that are unassigned and check the comments. Once you've an idea of which one you want to tackle, pls let me know as a comment, and I can assign it to you. If nothing appeals but you'd still like to help, let me know and I'll see if I can find something else, particularly if you're interested in docs work 😄

**Comment by merelcht** [comment]
Closing as Hacktoberfest 2023 has finished.
