### ISSUE TITLE
`build-docs.sh` not exactly the same as Read the Docs

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3132]
For some time I have been unable to build the docs locally, but I've been ignoring the issue because Read the Docs was working fine. This was reported by @lrcouto when she started however.

Now I paid more attention and noticed that `build-docs.sh` (hence `make build-docs`) does

```
sphinx-build -WETa -j auto -D language=en -b html -d docs/build/doctrees docs/source docs/build/html
```

whereas RTD does the equivalent of

```
python -m sphinx -WET --keep-going -D language=en -b html -d docs/build/doctrees docs/source docs/build/html
```

Key thing being `--keep-going`:

```
--keep-going      with -W, keep going when getting warnings
```

(so, even if warnings are treated as errors, at least the build proceeds)

I think Sphinx is obscure enough that we can just add `--keep-going` to our script so that contributors can just not worry about this.

**Comment by Celsuss** [comment]
I can take a look at this.

**Comment by Celsuss** [comment]
I found a problem while working with this.
The Guidelines for contributing developers says that kedro supports python>=3.7, however when trying to run `make build-docs` with python3.7 I get the error.

```
ERROR: Cannot install kedro-datasets[all]==1.7.0 and kedro-datasets[all]==1.7.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    kedro-datasets[all] 1.7.1 depends on snowflake-snowpark-python~=1.0.0; extra == "all"
    kedro-datasets[all] 1.7.0 depends on snowflake-snowpark-python~=1.0.0; extra == "all"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
make: *** [Makefile:39: build-docs] Error 1
```

Looking at snowflake-snowpark-python documentation it says it only supports python>=3.8.
Upgrading to python 3.8 fixed the problem.
