### ISSUE TITLE
Make GitHub Discussions read-only

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3134]
Every now and then there's activity on GitHub Discussions, but questions are addressed in Slack way more quickly. Since we're indexing the content in public https://linen-slack.kedro.org/, they can be accessed indefinitely and without an account.

Maintaining the Discussions open gives false expectations to users, because interactions there tend to be missed. The activity is not so intense, so I think we should be good with GitHub Issues + Slack.

Thoughts?

**Comment by stichbury** [comment]
More than happy to do this. We have a few pointers to how to get help there but we can put those on the wiki so they're retained, but otherwise there's nothing much that can't be removed. Most discussions are quite old now but if any are valuable we could artificially add them to Slack in the absence of a knowledgebase.  

(I still really want to consider "Kedrobot" as a way to record all the useful conversations but I doubt there is much in Discussions anyway).

**Comment by astrojuanlu** [comment]
Yeah would be cool to set it to read-only if possible. I'll investigate in a few days.

**Comment by astrojuanlu** [comment]
We decided to _not_ close Discussions because it attracts some traffic and also because it's a good way to point people towards the supported channels (mostly Slack).

However, we can look into ways of restricting who can post so that we can "lock" or "freeze" Discussions without actually deleting all the material.

**Comment by astrojuanlu** [comment]
Needs to be done by an admin https://github.com/organizations/kedro-org/settings/member_privileges and can only be done at the organisation level

![image](https://github.com/kedro-org/kedro/assets/316517/fe77a8fa-9808-4bfe-bce1-4704624caded)

(info https://docs.github.com/en/organizations/managing-organization-settings/managing-discussion-creation-for-repositories-in-your-organization#allowing-or-disallowing-users-with-read-access-to-create-discussions)

**Comment by astrojuanlu** [comment]
We decided against this with @merelcht , we're actually going to turn some of the past issues to discussions (because that's what they are).

cc @Galileo-Galilei the preferred community discussion platform is still Slack though, but we will let discussions that start on Github stay on Github.

Our plan is to use the issue tracker more efficiently.
