### ISSUE TITLE
Post 19.0 Tools Flow Tracker 

### ISSUE THREAD

**Issue by amandakys** [kedro-org/kedro#3135]
## Description
This ticket tracks feedback items for the project creation tools flow that we might like to address in a later release 

Improvements to the tools 
- ability to create own tools
- advanced tools (github actions, docker, precommit)
- ability to access tools beyond the project creation flow 
- able to define a preset group of tools
- interactive sandbox UI for generating kedro commands in the docs 

Improvements to starters 
- improved starter creation and maintenance
- able to add one line to the starter (make tweaks) 
- want an easier way to create a starter (as a way to preset tools)

**Comment by astrojuanlu** [comment]
The only feedback we're getting so far is https://github.com/kedro-org/kedro/issues/3689, from time to time. I'm closing this issue for now.
