### ISSUE TITLE
'kedro package' and 'kedro test' don't work

### ISSUE THREAD

**Issue by abhishek-nigam** [kedro-org/kedro#3137]
## Description

- Sub-Issue 1

I was following the Kedro spaceflights tutorial and in the section on [Package a Kedro project](https://docs.kedro.org/en/stable/tutorial/package_a_project.html#package-a-kedro-project), it mentions to run the command `kedro package`. When I tried that it failed with the following error message:
```
Usage: kedro [OPTIONS] COMMAND [ARGS]...
Try 'kedro -h' for help.

Error: No such command 'package'.
```

- Sub-Issue 2

I was reading through [Kedro concepts](https://docs.kedro.org/en/stable/get_started/kedro_concepts.html). It at the end, it mentions that we can run `kedro test` to run tests using `pytest`, but when I ran it in the above spaceflights projects, it gave a similar error as above saying that there is no such command as 'test'.

## Context
I was working through the spaceflights tutorial.

## Steps to Reproduce
Initialize a new Kedro project using spaceflights starter and run `kedro package` and `kedro test`.

## Expected Result

- Sub-issue 1
To generate a .whl file packaging the pipeline

- Sub-issue 2
To run test cases using `pytest`

## Actual Result
_Please refer to description_

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): v0.18.13
* Python version used (`python -V`): 3.10.13
* Operating system and version: PopOS (based on Ubuntu 22.04 LTS)

**Comment by astrojuanlu** [comment]
Hello @abhishek-nigam ! The "no such command" indicates that probably you weren't running those commands from the root of the directory. Can you please confirm?

See https://github.com/kedro-org/kedro/issues/2541 for discussion.

**Comment by abhishek-nigam** [comment]
You're right! I think I made the mistake of not running the command from project root. Sorry about that. When I try both commands now from the project root, they work. Closing this issue.
