### ISSUE TITLE
Remove all old `DataSet` classes

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3159]
## Description
Remove all old datasets ending in `DataSet` + any other remaining mentions to `DataSet` should be changed to `Dataset`.

## Context
This should go into `kedro-datasets` `2.0.0`. 

## To do
- [x] Remove aliases from datasets
- [x] [RST docs for datasets](https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/docs/source/kedro_datasets.rst)
- [x] [`setup.py`](https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/setup.py)

**Comment by MinuraPunchihewa** [comment]
Hey @merelcht, @lrcouto,
I am happy to take this up if no one has started working on it already!

**Comment by merelcht** [comment]
Hi @MinuraPunchihewa , thank you for the offer, but this ticket isn't a community ticket as its currently blocked by a pending release. Have a look at tickets marked with [the "hacktoberfest" label](https://github.com/kedro-org/kedro/issues?q=is%3Aopen+is%3Aissue+label%3AHacktoberfest) which have been specifically been groomed to be taken up by our community 🙂

**Comment by MinuraPunchihewa** [comment]
Understood, no problem.
