### ISSUE TITLE
Revise documentation that uses the iris starter

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#3160]
Parent ticket #3158 

Pages impacted:

* [x] docs/source/kedro_project_setup/starters.md
* [x] docs/source/get_started/new_project.md (significant)
* [x] docs/source/notebooks_and_ipython/kedro_and_notebooks.md (significant)
* [x] docs/source/notebooks_and_ipython/kedro_as_a_data_registry.md (being removed anyway)
* [x] docs/source/deployment/airflow_astronomer.md <-- the starter is retained
* [x] docs/source/deployment/databricks/databricks_notebooks_development_workflow.md <-- the starter is retained
* [x] docs/source/deployment/databricks/databricks_deployment_workflow.md <-- the starter is retained
* [x] docs/source/deployment/databricks/databricks_visualisation.md <-- the starter is retained
* [x] docs/source/deployment/databricks/databricks_ide_development_workflow.md <-- the starter is retained
* [x] docs/source/hooks/examples.md
* [x] docs/source/nodes_and_pipelines/run_a_pipeline.md (insignificant)
* [x] docs/source/nodes_and_pipelines/nodes.md (affects the Generators section)
* [x] docs/source/extend_kedro/plugins.md

**Comment by stichbury** [comment]
There's a section of documentation about generators here: https://docs.kedro.org/en/stable/nodes_and_pipelines/nodes.html#how-to-use-generator-functions-in-a-node

It uses the `pandas-iris` starter and I'm not sure how to remove that without rewriting the section. Some ideas from most effort to least:

* Update the docs to use a different starter
* Temporarily tie this to a fixed version of the starter (so give instructions for using the archived starter code with Kedro 0.18.14 or earlier, and link to docs about the iris starter in 0.18.14 set).
* Remove entirely in 0.19.0 and make into new documentation when time permits.

I would vote for the first or second option but it's not my time needed to do the changes. What do you think @noklam @merelcht? cc @astrojuanlu

**Comment by astrojuanlu** [comment]
I support (2) hence temporarily tie this to the 0.18.14 starter, and maybe add an admonition on top that says "these docs use an old version, we will update them soon" or something like that. Otherwise if we remove them the link is broken. And updating the docs is a distraction right now.

**Comment by merelcht** [comment]
I would also vote for option 2!

**Comment by stichbury** [comment]
@merelcht How would I invoke the starter, is something like:

```bash
kedro new --starter=pandas-iris --checkout=0.18.14
```

**Comment by merelcht** [comment]
> @merelcht How would I invoke the starter, is something like:
> 
> ```shell
> kedro new --starter=pandas-iris --checkout=0.18.14
> ```

Yes that works. It might be good to add that the user would need to have kedro `0.18.14` installed in their environment. This doesn't work if they are on `0.19.0` when it's released.

**Comment by astrojuanlu** [comment]
This was done in https://github.com/kedro-org/kedro/pull/3317
