### ISSUE TITLE
Consolidate credentials documentation

### ISSUE THREAD

**Issue by datajoely** [kedro-org/kedro#3164]
## Description

There is lots of useful credential related information in the docs, but it's not actually all in the  main credentials page.

Env vars and hooks are our recommended pattern for advanced users - we don't make this clear in the [main credentials page](https://docs.kedro.org/en/stable/configuration/credentials.html).

- [Env vars](https://docs.kedro.org/en/stable/configuration/advanced_configuration.html#how-to-load-credentials-through-environment-variables) are linked in this page, but it's not actually very visible.
- [After context created](https://docs.kedro.org/en/stable/hooks/common_use_cases.html#use-hooks-to-load-external-credentials) hooks are our recommended pattern for advanced users and this is not linked at all in the docs.

I **propose we move all the examples and details of the above patterns to the main credentials page** and link to that from the advanced config and hook examples pages respectively.

**Comment by astrojuanlu** [comment]
Duplicate (or at least related) to #2669 ?

**Comment by datajoely** [comment]
Dupe will close
