### ISSUE TITLE
Update `demo_project` used for Kedro-Viz demo to use `OmegaConfigLoader`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3172]
## Description
[Kedro-Viz](https://github.com/kedro-org/kedro-viz) uses a project called [`demo_project`](https://github.com/kedro-org/kedro-viz/tree/main/demo-project) for testing and for the hosted demo on: https://demo.kedro.org/

This demo uses the `TemplatedConfigLoader`, but this is going to be removed in Kedro `0.19.0`. The demo project needs to be updated to use `OmegaConfigLoader` instead. 

## Context
[You can use the config loader migration guide to help with this process.](https://docs.kedro.org/en/stable/configuration/config_loader_migration.html#templatedconfigloader-to-omegaconfigloader)

**Comment by aanghelidi** [comment]
Hello @merelcht, I would like to tackle this PR. One clarification please, is the change expected to be pushed to the [Kedro-Viz](https://github.com/kedro-org/kedro-viz) repository?

**Comment by merelcht** [comment]
Hi @aanghelidi, that's great thank you! Yes this change should indeed go on the `Kedro-Viz` repository. Let me know if you have any more questions and feel free to ask for my review when your PR is ready 🙂

**Comment by aanghelidi** [comment]
Thank you for the quick response @merelcht 🙂 As I progress through the PR, I may have questions that arise but I think I'm ready to work on it.

**Comment by aanghelidi** [comment]
Hello @merelcht , I have a first draft for this PR that implements the migration. 

I have one question for you, regarding the visualization of the pipeline with `kedro-viz`, what are the steps to visualize it? I'm having trouble with either `kedro viz` or `make build`.

**Comment by merelcht** [comment]
Hi @aanghelidi, have you already had a look at the Viz contribution docs? This section https://github.com/kedro-org/kedro-viz/blob/main/CONTRIBUTING.md#development-guidelines explains how to setup a development server to run your local version.
