### ISSUE TITLE
Bug in kedro new add-ons flows 

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#3185]
## Description

This is in `develop` branch only.

See 
![image](https://github.com/kedro-org/kedro/assets/18221871/8e8095d7-ffd1-4fb7-8ea2-0ffadc0e5c44)

I try two different CLI and the result is unexpected.

1. `kedro new`, then `1,33`
2. `kedro new`, then `1, 6` 

Both are invalid options, the first one fail immediately but the second didn't. I believe the 1. is the correct behavior. Cc @amandakys Can you confirm this?

**Comment by noklam** [comment]
Noted I have a space in the screenshot with `1, 33`, I try again and it fails without space.
![image](https://github.com/kedro-org/kedro/assets/18221871/c7defc99-0a55-43e9-b62d-b674a25ae71d)

**Comment by merelcht** [comment]
Great catch! I have been able to replicate this behaviour. I think it's as soon as you add a double digit choice, so anything above 10.

**Comment by AhdraMeraliQB** [comment]
This issue has been extended to include extending the flexibility of the case and whitespace sensitivity

**Comment by merelcht** [comment]
Fixed in https://github.com/kedro-org/kedro/pull/3263
