### ISSUE TITLE
Improve documentation section that covers "Project setup"

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#3201]
Child of https://github.com/kedro-org/kedro/issues/2799 This is a parent itself and will cover all the changes necessary to popular pages in the "Project setup" section. Won't be addressed until 0.19.0 and is relatively low priority compared to #3200

**Comment by astrojuanlu** [comment]
That section definitely could use some love but without specific things to do or a timeframe this ticket will likely linger forever. I'm closing for now, we can open at a later time.
