### ISSUE TITLE
Typos under a note section in `https://docs.kedro.org/en/stable/data/data_catalog.html`

### ISSUE THREAD

**Issue by iamhassaan** [kedro-org/kedro#3217]
In Kedro stable documentation under data-catalog.

There is a `[note](https://docs.kedro.org/en/stable/data/data_catalog.html#:~:text=Note%20that%20HTTP(S)%20is%20a%20supported%20file%20system%20in%20the%20dataset%20implementations%2C%20but%20if%20you%20it%2C%20you%20can%E2%80%99t%20also%20use%20versioning.)` with ambiguous context. 

**It says:**

"Note that HTTP(S) is a supported file system in the dataset implementations, but if you it, you can’t also use versioning."

It should be changed to:

"Note that HTTP(S) is a supported file system in the dataset implementations, but if you use it, you can’t also use versioning."

**Comment by astrojuanlu** [comment]
Hi @iamhassaan , thanks for reporting! Do you want to fix this typo yourself? Feel free to submit a pull request.

**Comment by miikkuu** [comment]
please assign me!

**Comment by astrojuanlu** [comment]
Hi @miikkuu , no need to assign the issue - whoever sends the PR first and is more responsive to maintainer feedback will get it merged!

**Comment by JayOaks** [comment]
Hello,
Please I would like to submit a PR for this.

**Comment by astrojuanlu** [comment]
Hi @JayOaks, go ahead!

**Comment by merelcht** [comment]
Closed in https://github.com/kedro-org/kedro/pull/3239
