### ISSUE TITLE
Update status badges in docs to check GA instead of CCI

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3223]
## Description
The branch status badges for `main` and `develop` in the docs are based on the CircleCI builds. This should be updated to check Github Actions builds instead.

## Possible Implementation
The target in `index.rst` needs to be updated.

**Comment by ankatiyar** [comment]
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge
