### ISSUE TITLE
Improve documentation around `OmegaConfigLoader` assumptions

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3247]
## Description
This is the outcome of #2819.

The documentation will need to cover:

- Why is OmegaConf different to Kedro's ConfigLoader and when to use either one?
- How to load a single file? plain `OmegaConf.load`
- How to load a data catalog when you have a credentials? Kedro `OmegaConfigLoader`
- How to load a data catalog when you have templating? Kedro `OmegaConfigLoader`

**Comment by stichbury** [comment]
Do you need this for 0.19.0?

**Comment by astrojuanlu** [comment]
In terms of priority I'd say this is a "High" but not a "Blocker"

**Comment by stichbury** [comment]
> In terms of priority I'd say this is a "High" but not a "Blocker"

OK, great, thanks. I don't think this is one I can write, so I'll ask @merelcht to schedule some engineering time on it when it's appropriate and I can help get it completed and into the docs.
