### ISSUE TITLE
Add e2e tests for `add-ons` flow

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3268]
## Description
For most of the add-ons flow I've been testing the work manually: create a new project with a combination of add-ons, install requirements and try a `kedro run`. This process has uncovered several bugs already.

## Context
We should add automated tests to test at least some of the add-ons flow.

## Implementation
At a minimum have tests for:
1. `kedro new --addons=none` 
2. `kedro new --addons=lint,docs,data,logging,...` (everything but not viz and pyspark)
3. `kedro new --addons=all`
4. `kedro new --addons=pyspark`
5. `kedro new --addons=viz`

All of the above should have an example so `kedro run` can be tested.

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro/pull/3325
