### ISSUE TITLE
Add docs page to link to the video course and links in tutorial

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#3302]
## Description
To ensure discoverability we need to add a landing page to the docs for the new course. We should also have some links in the spaceflights tutorial and also add to `awesome-kedro` and beyond. Blog post is already planned ofc.

**Comment by stichbury** [comment]
https://github.com/kedro-org/kedro/pull/3305

**Comment by astrojuanlu** [comment]
Done https://docs.kedro.org/en/latest/course/index.html
