### ISSUE TITLE
Add-ons: Minor issues/improvements

### ISSUE THREAD

**Issue by ankatiyar** [kedro-org/kedro#3333]
## Description
Collecting stuff I found during bug bash related to the add-ons/tools workflow here -

### Add ons info in `pyproject.toml`
This currently gets added to the project's `pyproject.toml` as a string -
```toml
add_ons = "['Linting', 'Custom Logging', 'Documentation']"
```
Could this be a list for easier analytics on Heap side -
```toml
add_ons = ['Linting', 'Custom Logging', 'Documentation']
```

Additionally, could the selection of "example pipeline" be included in this?

**Comment by merelcht** [comment]
Quickly discussed this and it would be nicer to have "example" as a separate entry.

**Comment by ankatiyar** [comment]
Also found this while testing -
`kedro new --addons=lint,test,lint,test`
or entering repeat numbers in the prompt does not fail but ends up adding this to the `pyproject.toml`:
```toml
add_ons = "['Linting', 'Testing', 'Linting', 'Testing']"
```
