### ISSUE TITLE
`--addons=all` doesn't behave as expected

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3334]
## Description
When I use `--addons=all` or `--addons all` in `kedro new` directly I don't get all addons as expected.
You can also see in the message: 
```
You have selected the following add-ons:
```

## Steps to Reproduce
1. Checkout the `develop` branch
2. Run `kedro new --addons=all` or `kedro new --addons all`
3. Follow the rest of the prompts adding the name and example yes or no
4. Check the resulting project

```
(dev) M-C02XN0V5JHD5:Testing merel_theisen$ kedro new --addons=all --example=yes --name=allbug

You have selected the following add-ons:

The project name 'allbug' has been applied to:
- The project title in /Users/merel_theisen/Projects/Testing/allbug/README.md
- The folder created for your project in /Users/merel_theisen/Projects/Testing/allbug
- The project's python package in /Users/merel_theisen/Projects/Testing/allbug/src/allbug

A best-practice setup includes initialising git and creating a virtual environment before running 'pip install -r requirements.txt' to install project-specific dependencies. Refer to the Kedro documentation: https://kedro.readthedocs.io/

Change directory to the project generated in /Users/merel_theisen/Projects/Testing/allbug by entering 'cd /Users/merel_theisen/Projects/Testing/allbug'
```
## Expected Result
The resulting project should have tests folder and requirements for linting, testing and logging etc. 

## Actual Result
It doesn't have all the expected files and folder structures

❗ If I follow the prompts when doing `kedro new` and use `all` the project gets created as expected.

**Comment by merelcht** [comment]
Should also test: `kedro new --addons=lint,log,data,docs,test,viz,pyspark`

**Comment by lrcouto** [comment]
> Should also test: `kedro new --addons=lint,log,data,docs,test,viz,pyspark` and why didn't the test pick this up?

just tested it and it generates the files, the issue is happening only with the `all` option. Looking into it now.

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro/pull/3361
