### ISSUE TITLE
Inconsistency on `add_ons` metadata in `pyproject.toml` when `none`

### ISSUE THREAD

**Issue by SajidAlamQB** [kedro-org/kedro#3336]
## Description

There is an inconsistency on what value `add_ons` in `pyproject.toml` is assigned.

Case 1:

`kedro new --addons=none`

pyproject.toml:

```
[tool.kedro]
add_ons = ""
```

Case 2:
`kedro new` (Use default value for add-ons, `none`, by pressing enter without typing any add-ons)

pyproject.toml:

```
[tool.kedro]
add_ons = "[]"
```

We should keep consistency in how to label none.

**Comment by AhdraMeraliQB** [comment]
Closing as no longer applicable, all none selections will result in a value of ["None"] in the project's `pyproject.toml`. xref [the file refactor](https://github.com/kedro-org/kedro/pull/3499), [the developer docs](https://github.com/kedro-org/kedro/wiki/Kedro-new-project-creation-%E2%80%90-how-it-works).
