### ISSUE TITLE
Test the migration guide for `0.19.0`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3347]
### Description
Go through the migration guide with a project created with Kedro `0.18+` and upgrade it to use `0.19.0` following the instructions in the guide. Update guide where instructions are wrong/unclear/missing.

**Comment by AhdraMeraliQB** [comment]
Tested migration guide, as well as hooks and custom cli commands. Mostly good, made updates to the docs [here](https://github.com/kedro-org/kedro/pull/3428)
