### ISSUE TITLE
Separate `kedro new --help` flag for add-ons/tools info

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#3348]
## Description

Introduce a command to list the tools available for selection via command-line, separate from `kedro new --help` which lists information for all `kedro new` flags.

## Possible Implementation

`kedro tools list` (see `kedro starter list`, `kedro registry list`, `kedro catalog list`)

## Possible Alternatives

`kedro new --list-tools`
`kedro new --tools list`

**Comment by merelcht** [comment]
AFAIK we haven't had this request from any users since `0.19.0` was released. Do we still want to do this? cc: @astrojuanlu

**Comment by astrojuanlu** [comment]
Not really. Let's close this, at least for now.
