### ISSUE TITLE
Do we still need to remove `conf.py` and `index.rst` following `build-docs` removal 

### ISSUE THREAD

**Issue by SajidAlamQB** [kedro-org/kedro#3376]
## Description

Following our work with the new docs tool it doesn't align with what https://github.com/kedro-org/kedro/pull/2304 has written out. 

>also we need remove the code for build-docs, and we need to update the project template/starter to remove the docs/source subfolder so there's no existing conf.py and index.rst to confuse things (then we can update these docs again).

Our templates still keep the `conf.py` and `index.rst` do we plan to remove these still?

As of now when we create a new project with the docs tool in order to get it working properly I have to `pip install ".[docs]"` which installs `sphinx` from `pyproject.toml`. Next we go into `docs/source` and move `conf.py` and `index.rst` to a backup location. 
Then I can run `sphinx-quickstart docs` and replace the generated files with the backups and run `make html` to generate the docs in the project.

This was mostly following the instructions on our current stable docs: https://docs.kedro.org/en/stable/tutorial/package_a_project.html#build-html-documentation 

- `conf.py` and `index.rst` do we plan to remove these still?
- If so what does the docs tool provide? just the requirements?
- If not then documentation needs to be updated to reflect how users can get docs running properly via the tools selection. (We might need a better way then telling them to backup `conf.py` and `index.rst` and replacing, maybe some code that automates this?)

Cc: @stichbury @astrojuanlu @merelcht @AhdraMeraliQB

**Comment by stichbury** [comment]
This is a tricky one because 

Either:
* We _do_ provide the setup files for Sphinx, but it breaks `sphinx quickstart` for those that didn't use the `docs` flag at `kedro new` time. And not everyone will use it.

Or:
* We don't provide those files, then anyone using `kedro new --tools=docs` will still have to do `sphinx quickstart` to get them.

**Comment by stichbury** [comment]
I would suggest the less invasive option is to not provide the files. Can we update `kedro new --tools=doc` to itself make a call to `sphinx quickstart` for us, or cookiecutter those two files into the right place?

**Comment by SajidAlamQB** [comment]
> I would suggest the less invasive option is to not provide the files. Can we update `kedro new --tools=doc` to itself make a call to `sphinx quickstart` for us, or cookiecutter those two files into the right place?

We would need sphinx already installed beforehand unfortunately.

**Comment by stichbury** [comment]
I think it's better to document that the user must call `sphinx quickstart` after they've done a `kedro new --tools=docs` since that's basically just following our existing docs so suggest we remove the `conf.py` and `index.rst` from the project template that we have added them to. However, I suggest you also as @astrojuanlu to consider this before you proceed.

**Comment by astrojuanlu** [comment]
Two more ideas:

- We do create those files themselves without Sphinx preinstalled. They can be really barebones, would be low maintenance. And we can use markdown instead ;)
- We take a tool-agnostic approach and only populate docs/ with a README.md that says "your docs go here" with some prose recommending tools (Sphinx, MkDocs, nothing at all)

**Comment by stichbury** [comment]
Do those ideas address the disconnect between readers that use the `--tools=docs` flag and those that don't? 

If they don't use the flags and follow [our documentation in the tutorial section](https://docs.kedro.org/en/stable/tutorial/package_a_project.html#add-documentation-to-a-kedro-project), they'll get in a mess I think. Maybe we have to simply remove that section of our documentation just to avoid this .

**Comment by merelcht** [comment]
Addresses in https://github.com/kedro-org/kedro/pull/3331
