### ISSUE TITLE
Kedro new creates an invalid catalog file.

### ISSUE THREAD

**Issue by akash-agniQB** [kedro-org/kedro#3403]
## Description
When running `kedro new --starter pandas-iris` the `conf/base/catalog.yml` file created is invalid, see sample below.
```
example_iris_data:
  type: pandas.CSVDataset
  filepath: data/01_raw/iris.csv
```

## Context
When building kedro-glass, our notebooks fail as creating a sample pipeline dynamically generated is failing during docs build.

## Steps to Reproduce
1. `pip install "kedro==0.18.14"`
2. `create conda -n "my_env" python=3.9`
3. `kedro new --starter pandas-iris`

## Expected Result
Catalog file should look like this.
```
example_iris_data:
  type: pandas.CSVDataSet
  filepath: data/01_raw/iris.csv
```

## Actual Result
```
example_iris_data:
  type: pandas.CSVDataset
  filepath: data/01_raw/iris.csv
```

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`):
* Python version used (`python -V`):
* Operating system and version:

**Comment by merelcht** [comment]
Hi @akash-agniQB , do you still need help resolving this issue?

**Comment by merelcht** [comment]
I'm closing this issue due to lack of response. Feel free to re-open this if you need more help solving it 🙂
