### ISSUE TITLE
Update authors in CITATION.cff

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#3412]
## Description
Post `0.19.0` we should update the list of authors in CITATION.cff

## Context
- `CITATION.cff` contains all maintainers it should reflect who actively work on the project 
- The docs https://docs.kedro.org/en/stable/contribution/technical_steering_committee.html makes a difference between current TSC members and previous. Changes to this must be subject to a vote. 

## Implementation
Double check what the expectation is for `CITATION.cff`. Should contributors be added to this per release?

**Comment by merelcht** [comment]
I've done some investigation about what "authors" means in the `CITATION.cff` file and it seems that it's up to the project itself. There's no clear guidance on whether contributors outside of the core maintenance team should be added to it per release or not. So it's really up to us who we add in here. I think we have the following options:

1. Add the same people as on the TSC
2. Add the people who have actively contributed to a release including outside contributors. (The difficulty I see with this is how we'd properly credit design and product efforts)
3. Add the people who we'd consider as _active_ maintainers, IMO that's a subset of the complete TSC.

**Comment by astrojuanlu** [comment]
I think the easiest is to make authors = TSC
