### ISSUE TITLE
Get rid of GitHub magic in README [Quick Win] 

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3416]
@marrrcin reported that he saw the README like this

![image](https://github.com/kedro-org/kedro/assets/316517/d886e9fc-ed95-4dca-ad4a-90798c0bb457)

and it's because of a bad combination of the magic we're using to detect light/dark theme

https://github.com/kedro-org/kedro/blob/8257d55ec96abbc1ce18ae229da8c773c60bfc1b/README.md?plain=1#L1-L2

and how GitHub assumes night = dark

![image](https://github.com/kedro-org/kedro/assets/316517/52972d47-4ae7-4bd0-8d05-0a01a7abe8e0)

This has created other problems in the past https://github.com/kedro-org/kedro/pull/2961#issuecomment-1688542270

Given that this is broken on PyPI and half-broken on GitHub, I'd say let's get rid of this.

A strawman proposal would be something like

![image](https://github.com/kedro-org/kedro/assets/316517/e4e1963d-987a-4eb6-8bb3-09839b28d453)

But better to have this properly designed.

**Comment by stichbury** [comment]
Moving this to Viz as it'll be part of design initially and quite likely require web savvy too.

**Comment by rashidakanchwala** [comment]
@SajidAlamQB  also reported this issue on pypi - https://pypi.org/project/kedro/

**Comment by astrojuanlu** [comment]
We don't need tech design for this. We need to just do it.

**Comment by ravi-kumar-pilla** [comment]
I encountered this when publishing github action. The way we do conditional images is deprecated. This [link](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to) should help.

**Comment by astrojuanlu** [comment]
@ravi-kumar-pilla could you check if the `<picture>` thing is rendered correctly on PyPI?

**Comment by ravi-kumar-pilla** [comment]
> @ravi-kumar-pilla could you check if the `<picture>` thing is rendered correctly on PyPI?

@astrojuanlu I see an open ticket - https://github.com/pypi/warehouse/issues/11251 . Needs some more searching/testing when we work on the ticket.

**Comment by astrojuanlu** [comment]
The way to test this would be to upload a test version to https://test.pypi.org/project/kedro/ or a newly registered package only for testing purposes.

**Comment by rashidakanchwala** [comment]
We tried to replicatr this issue and it doesn't exist anymore for readme  anymore. It does exist for Pypi which we will work on fixing.
