### ISSUE TITLE
Setup a security policy for Kedro

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#3427]
## Description
I think we can improve our security scores and create a `SECURITY.md` document for Kedro, Kedro-Viz, Kedro-Starters and Kedro-Plugins. 

## Context
It will improve our scores on [Snyk](https://snyk.io/advisor/python/kedro).

## Possible Implementation
Click on the security tab and set it up.

**Comment by astrojuanlu** [comment]
Link: https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

**Comment by astrojuanlu** [comment]
Closing in favour of #2338.
