### ISSUE TITLE
Revise the Kedro concepts page that covers project structure

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#3532]
## Description
I think we forgot about this https://docs.kedro.org/en/stable/get_started/kedro_concepts.html#kedro-project-directory-structure in the 0.19 release docs changes, my bad! We need to make a few tweaks to link to the new project flow and say that this is just the suggested structure if you select all the tools, and maybe give some examples of what the structure looks like with all tools and no tools, to compare them.

## Context
I was writing a blog post and remembered that the page existed. I don't think it's a massively used page but it should be in step with our messaging about the fact you can now control what you get.

* Documentation page (if applicable): [](https://docs.kedro.org/en/stable/get_started/kedro_concepts.html#kedro-project-directory-structure)

**Comment by astrojuanlu** [comment]
Good call @stichbury , do you need eng support for this?

**Comment by stichbury** [comment]
I don't need engineering support but equally I do not need to cover this one. I shall leave it to you to prioritise and assign as you prefer.
