### ISSUE TITLE
Child task: Create documentation about Kedro vs (or with) MLFlow

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#3541]
## Description
Child of https://github.com/kedro-org/kedro/issues/3012

## Context
The context of this issue was to start to populate the Kedro docs with comparative content as it's an important part of a documentation set for users and for SEO. This is specifically for MLFlow.

**Comment by stichbury** [comment]
[This was a useful find while I was researching what to include](https://kedro-mlflow.readthedocs.io/en/stable/source/01_introduction/01_introduction.html#a-brief-comparison-between-kedro-and-mlflow).

I've decided to put this back in the backlog. I spent some time on it in Notion and thinking about how to rearrange existing docs to include a section for comparative/collaborative content about other products, but I'll be moving onto other areas so won't have time to take it forward at present.

**Comment by astrojuanlu** [comment]
@noklam already compiled some internal notes and I will try to get to draft the document structure this sprint.
