### ISSUE TITLE
Unable to configure the spark session 

### ISSUE THREAD

**Issue by gpierard** [kedro-org/kedro#3545]
## Description
I am unable to set the kedro spark session config via spark.yml

## Context / steps to reproduce
On Kedro 0.17.6, I am trying to setup a spark session with the following config, but it seems that this config is not correctly applied to the spark session, which causes out of memory errors.

```
# conf/base/spark.yml
spark.scheduler.mode: FAIR
spark.driver.memory: 15g
spark.executor.memory: 15g
spark.executor.cores: 10
spark.driver.memory: 100g
spark.executor.memory: 20g
spark.driver.maxResultSize: 20g
spark.ui.port: xxxx
spark.ui.enabled: true]
```
```
# src/mypackage/hooks.py
class SparkHooks:
    @hook_impl
    def after_context_created(self, context) -> None:
        """Initialises a SparkSession using the config
        defined in project's conf folder.
        """

        # Load the spark configuration in spark.yaml using the config loader
        parameters = context.config_loader.get("spark*", "spark*/**")

        spark_conf = SparkConf().setAll(parameters.items())
        # print("spark_conf" + spark_conf.toDebugString())
        # Initialise the spark session
        spark_session_conf = (
            SparkSession.builder.appName(context.project_path.name)
            .master("local[50]")  # Set local mode with 6 CPU cores
            .enableHiveSupport()
            .config(conf=spark_conf)
        )
        _spark_session = spark_session_conf.getOrCreate()
        _spark_session.sparkContext.setLogLevel("WARN")
```

```
src/mypackage/settings.py
"""Project settings."""
from mypackage.hooks import PipelineMonitoringHooks, ProjectHooks, SparkHooks

# Instantiate and list your project hooks here
HOOKS = (ProjectHooks(), PipelineMonitoringHooks(), SparkHooks(),)
```

## Steps to Reproduce
```
kedro ipython
spark  = catalog.datasets.mydataset._get_spark()
spark.conf.get('spark.driver.maxResultSize')
# java.util.NoSuchElementException: spark.driver.maxResultSize
```
Note that `context.config_loader.get("spark*", "spark*/**")` returns correctly 

```
{'spark.driver.maxResultSize': '20g',
 'spark.scheduler.mode': 'FAIR',
 'spark.driver.memory': '100g',
 'spark.executor.memory': '20g',
 'spark.executor.cores': 10,
 'spark.ui.port': xxxx,
 'spark.ui.enabled': True}
```
How to correctly apply this config to the spark session please?
related: [stackoverflow question](https://stackoverflow.com/questions/77859763/kedro-spark-session-configuration-values-not-found)

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`): 0.17.6
* Python version used (`python -V`): 3.8.5
* Operating system and version: Ubuntu 20.04.6 LTS

**Comment by gpierard** [comment]
Okay, there seemed to be a custom_context.py.bak file that was interfering with the spark session init.

Any explanation on custom contexts is welcome

https://github.com/kedro-org/kedro/issues/676

**Comment by gpierard** [comment]
Okay, there seemed to be a custom_context.py.bak file that was interfering with the spark session init.

Any explanation on custom contexts is welcome

**Comment by astrojuanlu** [comment]
Hi @gpierard, is this related to https://github.com/kedro-org/kedro-starters/issues/210, https://stackoverflow.com/q/77859763/554319 and https://stackoverflow.com/q/77846687/554319 ?

**Comment by gpierard** [comment]
> Hi @gpierard, is this related to [kedro-org/kedro-starters#210](https://github.com/kedro-org/kedro-starters/issues/210), https://stackoverflow.com/q/77859763/554319 and https://stackoverflow.com/q/77846687/554319 ?

Hi, it is related to both stackoverflow questions but the kedro starters issue is fully separate in terms of environment, versions and project - basically trying to solve this spark session not being correctly configured by `spark.yml` by upgrading kedro on my personal PC to latest versions and trying out with a starter - without success. 
The current issue at hand is fully related to spark issue on `0.17.6` and yes I agree it is very old, but that's the current version we have at work.

One other funny thing is, if I unregister the spark hooks, and basically remove any spark-related config in `settings.py` and `hooks.py`, I still get the same behaviour ! A spark session is started somewhere and I have no idea how.

**Comment by merelcht** [comment]
Hi @gpierard , do you still need help solving this issue?

**Comment by merelcht** [comment]
I'm closing this issue for now. Feel free to re-open if this is still an issue you need help with.
