### ISSUE TITLE
Improve runtime params documentation

### ISSUE THREAD

**Issue by Galileo-Galilei** [kedro-org/kedro#3562]
## Description
The documention about ``runtime_params`` does not even mention the resolver and how to configure the catalog: 
This is very confusing and not very informative. 

### Documentation page (if applicable)

https://docs.kedro.org/en/latest/configuration/parameters.html

## Context

When looking for "kedro runtime_params" on google, above page is the first result and it is not where we want users to be redirected (not sure why because this page also exists and is the right one : https://docs.kedro.org/en/latest/configuration/advanced_configuration.html). We should at least redirect to the correct page. 

## Implementation 
Copying @astrojuanlu's comment here to make the ask of this ticket clear -
 > We agreed to add an admonition from the bottom of https://docs.kedro.org/en/latest/configuration/parameters.html#how-to-specify-parameters-at-runtime linking to https://docs.kedro.org/en/latest/configuration/advanced_configuration.html#how-to-override-configuration-with-runtime-parameters-with-the-omegaconfigloader, mentioning runtime_params explicitly (for discoverability)

**Comment by stichbury** [comment]
We aren't mentioning `runtime_params` on that page, so we have no influence on how Google has come to rank that one second on the SERP. There are no redirects to it from us either, so not a lot we can do to stop it showing up for that query. 

[A separate issue, I think, is that probably `latest` shouldn't be indexed and I'm going to remove it from the `robots.txt` but that isn't relevant to this discussion].

To help engineering determine if there's anything they need to change in terms of content, a couple of queries:

* Is there anything incorrect about the content on the [Parameters](https://docs.kedro.org/en/latest/configuration/parameters.html) page? 
* How could it be improved?
* Is there anything missing about `runtime_params` from elsewhere in the docs?
* If so, what, and where should it go?

These aren't questions necessarily for you @Galileo-Galilei but you're welcome to supply any thoughts. @merelcht will work with the team to prioritise any changes needed.

**Comment by astrojuanlu** [comment]
> [A separate issue, I think, is that probably latest shouldn't be indexed and I'm going to remove it from the robots.txt but that isn't relevant to this discussion]

+1 no need to let users land from search engines to docs for unreleased features

**Comment by stichbury** [comment]
https://github.com/kedro-org/kedro/pull/3564

**Comment by astrojuanlu** [comment]
We agreed to add an admonition from the bottom of https://docs.kedro.org/en/latest/configuration/parameters.html#how-to-specify-parameters-at-runtime linking to https://docs.kedro.org/en/latest/configuration/advanced_configuration.html#how-to-override-configuration-with-runtime-parameters-with-the-omegaconfigloader, mentioning `runtime_params` explicitly (for discoverability)
