### ISSUE TITLE
Add RTD docs redirects following next release

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro#3567]
## Description
Once `latest` becomes `stable` we need to add the following redirects:

### API docs changes
We can't add redirects for every page but makes sense to change the top level:
* https://docs.kedro.org/en/stable/kedro.html --> https://docs.kedro.org/en/stable/api/kedro.html

From Heap, the most popular API pages
* /en/stable/kedro.io.DataCatalog.html	--> /en/stable/api/kedro.io.DataCatalog.html
* /en/stable/kedro.framework.session.session.KedroSession.html --> /en/stable/api/kedro.framework.session.session.KedroSession.html
* /en/stable/kedro.framework.context.KedroContext.html --> /en/stable/api/kedro.framework.context.KedroContext.html
* /en/stable/kedro.pipeline.html --> /en/stable/api/kedro.pipeline.html		
* /en/stable/kedro.config.OmegaConfigLoader.html --> /en/stable/api/kedro.config.OmegaConfigLoader.html
* /en/stable/kedro.pipeline.node.html --> /en/stable/api/kedro.pipeline.node.html
* /en/stable/kedro.io.AbstractDataset.html --> /en/stable/api/kedro.io.AbstractDataset.html	
* /en/stable/kedro.pipeline.Pipeline.html --> /en/stable/api/kedro.pipeline.Pipeline.html	
* /en/stable/kedro.pipeline.node.Node.html	--> /en/stable/api/kedro.pipeline.node.Node.html
* /en/stable/kedro.framework.hooks.html --> /en/stable/api/kedro.framework.hooks.html
* /en/stable/kedro.framework.hooks.specs.PipelineSpecs.html --> /en/stable/api/kedro.framework.hooks.specs.PipelineSpecs.html
* /en/stable/kedro.framework.hooks.specs.html --> /en/stable/api/kedro.framework.hooks.specs.html

### Other docs page changes
To come as needed

**Comment by astrojuanlu** [comment]
Thanks for pulling the most popular ones 👍🏽 Looks sensible enough. Our redirect debt is already quite grim...

**Comment by astrojuanlu** [comment]
Prioritising this as "high" directly, since it's affected by the release timing

**Comment by stichbury** [comment]
> Our redirect debt is already quite grim...

I consolidated a load recently but it is still painfully bad. Maybe remove the URLs with numbers since it's been a while and only the 0.17.7 release uses them.

It's a shame we can't see from Heap and/or RTD who is hitting pages from redirects, and what those redirects are.

**Comment by astrojuanlu** [comment]
Done!
