### ISSUE TITLE
Document Kedro's dependency on git

### ISSUE THREAD

**Issue by AhdraMeraliQB** [kedro-org/kedro#3571]
## Description

As we're not moving away from using `git`, we need to communicate that users are expected to have git installed when working with Kedro. Addressing this issue should cover the following:
- Make sure documentation is clear that git is a pre-requisite for the `kedro new` flow
- Include the [workaround for when git is not installed](https://github.com/kedro-org/kedro/issues/2051#issuecomment-1477541508) as either a [FAQ](https://docs.kedro.org/en/latest/faq/faq.html) or in the [starters documentation](https://docs.kedro.org/en/latest/starters/starters.html#)

xref: https://github.com/kedro-org/kedro/issues/2051#issuecomment-1915220734

**Comment by yashexe** [comment]
Hey guys, pretty new here, would love to take care of this one if its not already being resolved!

**Comment by merelcht** [comment]
Addressed in https://github.com/kedro-org/kedro/pull/4006
