### ISSUE TITLE
Refactor jupyter magic unit tests with conftest

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#3585]
The current tests has a lot of hardcode string assertion.

Two things that we can improve:
1. Move dummy functions to a conftest/, so when we need to retrieve the function body we can directly read the file as text, it's also easier to edit the test because the indention will not be weird indented string with `"""`.
![image](https://github.com/kedro-org/kedro/assets/18221871/1b958765-df05-4438-ab78-bcb816dd44dd)

2. Refactor the function itself, so it returns data instead of the string of a function. We can then refactor our test to only test against the data. This should leave only 1 or 2 tests to assert with hardcoded string.
![image](https://github.com/kedro-org/kedro/assets/18221871/898490de-79b2-4b45-bce2-3cfad1e8ce88)

Assert the function arguments instead of the whole `# Prepare necessary inputs for debugging.......`

**Comment by astrojuanlu** [comment]
Nitpick (to clarify the terminology for potential observers): `conftest.py` is just the default location for pytest fixtures https://docs.pytest.org/en/stable/explanation/fixtures.html there can be module-specific fixtures too
