### ISSUE TITLE
Duplication and inconsistencies exist across different documentation subprojects

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3586]
## Description

We are starting to have lots of duplicated work across our 3 subprojects: core, viz, and datasets. This includes

- CSS files (now in an external storage for reuse, see https://github.com/kedro-org/kedro/issues/3016)
- Template files
- JavaScript code that enables Heap Analytics
- JavaScript code that enables search-as-you-type
- JavaScript code that enables `Cmd+K` as a keyboard shortcut for search
- Sphinx dependencies and plugins

## Context

This situation is starting to pose some problems. For example, now making small adjustments to the CSS requires access to an object storage and they are not under version control. In addition, we now have inconsistent documentation dependencies across repositories, and maintaining them in sync is a burden.

We'd need to tackle this before https://github.com/kedro-org/kedro-viz/issues/1474.

## Possible Implementation

Create a custom Sphinx theme, so we can do

```toml
# pyproject.toml
[project.optional-dependencies]
docs = [
    "kedro-sphinx-theme==0.1.0",
]
```

And that already contains everything we need.

## Possible Alternatives

❓

**Comment by stichbury** [comment]
Agreed. However, does it make sense to wait and make the theme based on docs redesign or can we make a theme now for what we have and then upgrade it? And, also, who makes this theme -- is it front end work for the Viz developers?

**Comment by astrojuanlu** [comment]
More inconsistencies across projects: https://github.com/kedro-org/kedro-viz/issues/1734

**Comment by tynandebold** [comment]
> CSS files (now in an external storage for reuse, see https://github.com/kedro-org/kedro/issues/3016)

I opened a PR in the brand identity repo to solve this first point: https://github.com/kedro-org/kedro-brand-identity/pull/7

**Comment by astrojuanlu** [comment]
Okay, it's happening https://github.com/kedro-org/kedro-sphinx-theme

**Comment by astrojuanlu** [comment]
Adding this to our backlog so we can prioritize accordingly.

**Comment by astrojuanlu** [comment]
Waiting for reviews on https://github.com/kedro-org/kedro/pull/3675

**Comment by astrojuanlu** [comment]
- [x] Kedro https://github.com/kedro-org/kedro/pull/3675
- [ ] kedro-datasets https://github.com/kedro-org/kedro-plugins/issues/662
- [ ] kedro-viz https://github.com/kedro-org/kedro-viz/issues/1882

**Comment by astrojuanlu** [comment]
This has now been addressed across all 3 subprojects. Closing.

**Comment by astrojuanlu** [comment]
Follow-up #3864
