### ISSUE TITLE
JSON Schema needs update

### ISSUE THREAD

**Issue by lordsoffallen** [kedro-org/kedro#3590]
## Description

With the change of DataSet -> Dataset naming, currently https://raw.githubusercontent.com/kedro-org/kedro/develop/static/jsonschema/kedro-catalog-0.18.json contains the wrong configuration. This needs an update.

## Actual Result

```
-- If you received an error, place it here.
```

```
-- Separate them if you have more than one.
```

## Your Environment

* Kedro version used (`pip show kedro` or `kedro -V`):
* Python version used (`python -V`):
* Operating system and version:

**Comment by astrojuanlu** [comment]
Thanks @lordsoffallen! Would you like to send a PR yourself?

**Comment by lordsoffallen** [comment]
hey @astrojuanlu, I would have but unfortunately i am super busy at the moment. I am also not sure if there was other breaking changes from 0.18 -> 0.19 so I suppose having a new file would be better here. If it's not solved in a month or so, I would probably have time to pick it up.

**Comment by astrojuanlu** [comment]
No rush! We added this to our backlog. Anyone else feel free to pick it up in the meantime.
