### ISSUE TITLE
Update `kedro pipeline create` to match starters template for tests

### ISSUE THREAD

**Issue by ankatiyar** [kedro-org/kedro#3614]
## Description

The pipeline tests in the starters are in `<project_root>/tests/pipelines> and when you create a new pipeline using the `kedro pipeline create`, the test files are created in `src/tests/pipelines`. 

## Context
For eg - the project was created with `spaceflights-pandas` starter and `pipeline2` and `pipeline3` were created with `kedro pipeline create` and this is the resulting project structure -
![Screenshot 2024-02-12 at 11 51 20](https://github.com/kedro-org/kedro/assets/110245118/55d62d4e-31be-4a1d-91ba-0c7e19daee7e)

## Expected Result
Quoting @astrojuanlu -

> in my opinion we should put them under <project_root>/tests, and avoid shipping them. that was the spirit of the template rework at least, probably we forgot to update kedro pipeline create accordingly

**Comment by astrojuanlu** [comment]
`tests` was moved out of `src` in https://github.com/kedro-org/kedro/pull/2926
