### ISSUE TITLE
Release Kedro `0.19.3`

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3631]
### Description 

Will be released in the w/c 26/2

### Blockers

- [x] https://github.com/kedro-org/kedro/issues/2011
- [x] https://github.com/kedro-org/kedro/issues/3629
- [x] https://github.com/kedro-org/kedro/issues/3638
- [x] https://github.com/kedro-org/kedro/pull/3641

**Comment by ankatiyar** [comment]
Closed by #3655
