### ISSUE TITLE
Kedro `0.19.3` Bug Bash

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3632]
### Description
We'll spend 21/2 trying to find any bugs in the upcoming `0.19.3` release. The more issues you find, the better!

**Features that should be tested**

1. The new notebook and ipython debugging feature.
2. Dataset factories with `PartitionedDataset`

**How to test?**

- Create new Kedro projects
- Run kedro projects
- Package & run kedro projects
- Use the starters
- Build your own pipelines
- Use Kedro with jupyter/notebook/ipython
- Run Kedro on Databricks
- Read the docs and any other text that users are exposed to. 

**How to report findings?**
- Create a regular Github issue the describing the bug you found. 

### Context
[What is a bug bash?](https://medium.com/@iamfaisalkhatri/what-is-a-bug-bash-c8ac3fd81661)

**Comment by merelcht** [comment]
Bug bash completed on 21/2 🎉
