### ISSUE TITLE
Not super clear from docs that `%load_node` can be used with ipython

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3638]
## Description
While testing the new `%load_node` feature and reading the docs, I found that it's not entirely clear that `%load_node` can also be used for IPython. Everywhere we mention the feature we talk about "in a notebook", see:

1. [In your notebook, run %load_node <name-of-failing-node> to load the contents of the problematic node with the %load_node line magic](https://docs.kedro.org/en/latest/notebooks_and_ipython/kedro_and_notebooks.html#debugging-a-kedro-project-within-a-notebook)
2. [This is still an experimental feature and is currently only availble for Jupyter Notebook (>7.0) and Jupyter Lab.](https://docs.kedro.org/en/latest/notebooks_and_ipython/kedro_and_notebooks.html#load-node-line-magic)
3. [Debugging a Kedro project within a notebook for information on how to debug using the %load_node line magic and an interactive debugger.](https://docs.kedro.org/en/latest/development/debugging.html)
4. [Currently this feature has better supports with Jupyter Notebook (>7.0) and Jupyter Lab and VSCode Notebook.](https://docs.kedro.org/en/latest/api/kedro.ipython.magic_load_node.html)

**Comment by lrcouto** [comment]
I had the same impression while trying to imagine running the debugger from a new user's perspective. I think the IPython feature is a little "hidden".

**Comment by noklam** [comment]
https://github.com/kedro-org/kedro/blob/30ae2c7ec9726c5f6b0cb11deeb3e30f026299c2/kedro/ipython/__init__.py#L218-L225

Should update the docstring too
