### ISSUE TITLE
Review all the `.gitignore` files in the templates and the starters

### ISSUE THREAD

**Issue by ankatiyar** [kedro-org/kedro#3653]
### Discussed in https://github.com/kedro-org/kedro/discussions/3635

<div type='discussions-op-text'>

<sup>Originally posted by **grofte** February 20, 2024</sup>
If I make a new Kedro project the lines 

```
# keep also the example dataset
!data/01_raw/*
```

are in .gitignore file. At the same time you have written in the README that users should not delete any of the lines you have added to .gitignore. I feel like this is going to hurt a lot of newbies that accidentally add a big dataset to git and then struggle to get rid of it. Even for the example with spaceflights I think it's a terrible idea to add the data to git.

PS I have not installed the example.

PPS I could not find it in your codebase or I would have written a PR. At the same time it's not a bug, just a terrible choice.</div>

**Comment by ankatiyar** [comment]
@noklam  https://github.com/kedro-org/kedro/discussions/3635#discussioncomment-8557925

**Comment by Galileo-Galilei** [comment]
While we're at it, we should check for the `mlruns/` of mlflow. I think the project template has been updated, but not the starters

**Comment by ankatiyar** [comment]
Completed in https://github.com/kedro-org/kedro/pull/4302 & https://github.com/kedro-org/kedro-starters/pull/250
