### ISSUE TITLE
Documentation improvement about create a custom dataset

### ISSUE THREAD

**Issue by avonarret** [kedro-org/kedro#3654]
## Description
The documentation at [Advanced: Tutorial to create a custom dataset](https://docs.kedro.org/en/stable/data/how_to_create_a_custom_dataset.html) describes how custom datasets can be created. However, the documentation still lacks some details on how to "register" your own dataset, so it can be imported and used by the catalog.load method.

### Documentation page (if applicable)
[https://docs.kedro.org/en/stable/data/how_to_create_a_custom_dataset.html](https://docs.kedro.org/en/stable/data/how_to_create_a_custom_dataset.html)

## Context
According to the current documentation I have created the following file structure:

```
src/projectname/datasets
├── __init__.py
└── custom_dataset.py
```

After configuring the catalog.yml as described in the docs and running the catalog.load method in a jupyter notebook, the custom dataset didn't get recognized. The following errors occured:

`DatasetError: An exception occurred when parsing config for dataset 'catalogname':
Class 'projectname.datasets.CustomDataset' not found, is this a typo?`

When using this structure, according to @astrojuanlu there is a `pip install .` required [Slack Conversation](https://linen-slack.kedro.org/t/16598542/hello-everyone-wave-i-am-new-here-and-currently-i-am-evaluat#8882e4bf-750c-429c-88a8-63edef4404fb). 

Possible steps to consider for the docs:
1. create the custom Dataset according to the recent docs in `src/projectname/datasets/datasetname.py` with the `__init__.py` alongside.
2. Exclude a possible pitfall by explicitely mentioning the (in my case required) lines in  `__init__.py`, this file probably needs
```
from .custom_dataset.py import CustomDataset
__all__ = ["SFTPCapableCSVDataset"]
```

  3. `cd projectname`
  4. `pip install .`
  5. In `conf/base/catalog.yml` the `type` should be `projectname.datasets.CustomDataset`
  Whereas projectname and CustomDataset have to be exchanged with the according names of the respective project.

With these steps I was able to sucessfully call catalog.load within the jupyter notebook.

**Comment by astrojuanlu** [comment]
Thanks for opening this issue @avonarret ! Adding it to our backlog

**Comment by noklam** [comment]
@avonarret Could you create a minimal project that we can reproduce? I have done this many times and it doesn't require `pip install .`, so I am surprised if this does not work now. I test it quickly with the current `main` branch and work as expected.

If the modules are importable, datasets is just one of the module so there is nothing special about it. i.e. 
`'projectname.datasets.CustomDataset'` is this an importable object if you run it from `kedro ipython`?

**Comment by laurensversluis** [comment]
I am running in the same issue when accessing the catalog while debugging the standard `test_project_path` function.

**Comment by avonarret** [comment]
> @avonarret Could you create a minimal project that we can reproduce? I have done this many times and it doesn't require `pip install .`, so I am surprised if this does not work now. I test it quickly with the current `main` branch and work as expected.
> 
> If the modules are importable, datasets is just one of the module so there is nothing special about it. i.e. `'projectname.datasets.CustomDataset'` is this an importable object if you run it from `kedro ipython`?

@noklam Sorry for the late reply. In the course of our internal developments, we have realized that we currently do not need any preprocessing for our needs. We realized that the use of Kedro would be a bit overkill and that we are already well served with Airflow DAGs for our “simpler” tasks. At least in the current project - who knows what's to come. 

I have now tried again to reproduce the problem I originally described. I followed the recent (most probably unchanged) documentation at [https://docs.kedro.org/en/stable/data/how_to_create_a_custom_dataset.html#project-setup](https://docs.kedro.org/en/stable/data/how_to_create_a_custom_dataset.html#project-setup) again in a new setup environment:

```mkdir kedro-custom-dataset && cd kedro-custom-dataset
python3 -m venv .venv
source .venv/bin/activate
pip install kedro
kedro new 
> my-project
> all
> yes
cd my-project/
pip install -r requirements.txt
kedro run
```
The created starter examples ran cleanly without any problems.

Then I created the `src/my_project/datasets` folder, as described in the documentation incl. empty `__init__.py`, as well as `image_dataset.py` ([https://docs.kedro.org/en/stable/data/how_to_create_a_custom_dataset.html#the-complete-example](https://docs.kedro.org/en/stable/data/how_to_create_a_custom_dataset.html#the-complete-example)) and placed the according configuration ([https://docs.kedro.org/en/stable/data/how_to_create_a_custom_dataset.html#integration-with-partitioneddataset](https://docs.kedro.org/en/stable/data/how_to_create_a_custom_dataset.html#integration-with-partitioneddataset)) in `conf/base/catalog.yml`.  

Result: I was able to successfully load the catalog with the custom dataset with `kedro ipython` in the CLI, as well as with a Jupyter notebook and `%load_ext kedro.ipython`, without the error occurring again. So I can't reproduce it anymore and there was no need for `pip install .` or explicitely including the custom dataset class in `__init__.py` as of today, at least to get the `pokemon example custom dataset` up and running. Sorry for the inconvenience.


> Also, eventually we should move towards higher level tools like `uv` that take care of doing the `pip install -e .` step for you.

@astrojuanlu Since I didn't have to run a separate pip install when retesting, this probably won't be necessary for now? But basically I support the approach, should a similar need arise in other situations.

**Comment by merelcht** [comment]
Thanks for letting us know you managed to make this work @avonarret . I'll close the issue!
