### ISSUE TITLE
Missing Transcoding dataset in docs

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#3676]
## Description
Bring back the docs for transcoding dataset, which still existed in the 0.18.x docs: 
0.18.12: https://docs.kedro.org/en/0.18.12/data/data_catalog.html#transcode-datasets

### Context 
The current docs have a few mentions of the transcoding, but no clear explanation anymore. This was likely removed by accident. 

0.19.3: 
![image](https://github.com/kedro-org/kedro/assets/18221871/22b2a4ff-2fe7-41ad-9d49-e10d76e2d413)

There are few example using transcoding dataset, but there should be a dedicate section explaining what is it and why is it useful (the pyspark example should be a good one).

**Comment by ElenaKhaustova** [comment]
Some extra context:

1. Section that presented in the docs before: https://docs.kedro.org/en/0.18.5/data/data_catalog.html#a-typical-example-of-transcoding
2. Previously in starters we had examples of using transcoding datasets that causing cyclic dependencies and shouldn't be allowed: https://github.com/kedro-org/kedro/issues/3799#issuecomment-2054091313
3. Based on the above we should return a separate section and clarify the docs, particularly: provide some details on how the mechanism works, keep the example with pyspark, provide some examples of what is not supported with the corresponding explanations
