### ISSUE TITLE
Add documentation about the combined use of `$globals` and `$runtime_params`

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#3706]
## Description

**Read https://github.com/kedro-org/kedro/issues/2531 for the full context.**

There are many [questions](https://kedro-org.slack.com/archives/C03RKP2LW64/p1709019999364139) asked in the slack such as "how to override global with runtime parameters", we explicitly block this but we don't have the reason document.

The docs should document 2 things:
1. The rationale of the design, WHY we block this
2. How to do this in the preferred way (nested globals{xxx, {$runtime_param}))

### Documentation page (if applicable)

- https://docs.kedro.org/en/latest/configuration/advanced_configuration.html
- FAQ

(Try to search from the console see if you can find the section easily with keywords)
## Possible solution
Summary #2531, the discussion was mostly documented already in the issue, we just need to make that available in docs.

**Comment by datajoely** [comment]
[Another user touching this question](https://linen-slack.kedro.org/t/16757928/hello-team-i-d-like-to-know-if-i-can-change-the-data-directo#72f17b03-ac3f-4d30-9e0c-e929a7eec687)

**Comment by noklam** [comment]
Make sure to read #2531 for the discussion.
