### ISSUE TITLE
Add info about tag names convention/limitation

### ISSUE THREAD

**Issue by Lasica** [kedro-org/kedro#3727]
## Description
Add info about this part of code
https://github.com/kedro-org/kedro/blob/0fc8089b637a0679f71e2bddc91f0676fc2914a2/kedro/pipeline/node.py#L126-L129

### Documentation page (if applicable)
https://docs.kedro.org/en/stable/api/kedro.pipeline.node.html - implies any string is fine
https://docs.kedro.org/en/stable/nodes_and_pipelines/nodes.html#how-to-tag-a-node - info box here

## Context
Slack conversation:
https://linen-slack.kedro.org/t/16720002/are-there-any-special-characters-that-should-be-avoided-in-t#591ec378-8ea7-4fd2-9f80-c7fefea3d1aa

**Comment by noklam** [comment]
@Lasica Would you be interested to open a PR to fix it? We are happy to take PR for this.

**Comment by boringbyte** [comment]
@Lasica I can create fix it and open PR.

**Comment by astrojuanlu** [comment]
@boringbyte go ahead!
