### ISSUE TITLE
Release `kedro` 0.19.4

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3768]
### Description
Release Kedro `0.19.4`

### Blockers

- [x] https://github.com/kedro-org/kedro/pull/3719
- [x] https://github.com/kedro-org/kedro/pull/3742
- [x] `kedro-dataset` `3.0.0` release
- [x] https://github.com/kedro-org/kedro/pull/3664
- [x] https://github.com/kedro-org/kedro-starters/pull/212
- [x] https://github.com/kedro-org/kedro/pull/3731
- [x] https://github.com/kedro-org/kedro-starters/issues/214
- [x] https://github.com/kedro-org/kedro/issues/3799
- [x] https://github.com/kedro-org/kedro/pull/3803
- [x] https://github.com/kedro-org/kedro/pull/3782

**Comment by ankatiyar** [comment]
Also https://github.com/kedro-org/kedro-starters/pull/212

**Comment by Lasica** [comment]
I'd fix the small issues within kedro starters before next release:
- docs generation broken,
- linting issues with the provided code (ruff default recommended settings),
- hard coded value in `logging.yml` config
- broken unit tests in starter (instructions to properly link module to tests, api change in kedro session)
- update readme on how to run the unit tests with this setup/pytest and build the docs

^ Is what I've found. I'll prepare a PR fixing these issues this week.

**Comment by noklam** [comment]
I added https://github.com/kedro-org/kedro/issues/3708 - not absolutely blocking but we would like to send some changes before release because it seems that `robots.txt` only get updated on new release.
