### ISSUE TITLE
Can't build docs in starter - need to update sphinx version

### ISSUE THREAD

**Issue by Lasica** [kedro-org/kedro#3774]
## Description
Can't build docs in starter - need to update sphinx version

## Context
Install requirements from the package `pip install -e '.[docs]'` and try to build docs with sphinx - it's old version and the conf provided requires at least version >5 (plugins).

## Steps to Reproduce
```
kedro new #... enable docs, enter the project
pip install -e '.[docs]'
mkdir docs/_build
python -m sphinx docs/source docs/_build
```

## Expected Result
The docs builds without issues.

## Actual Result
It throws an error that sphinx needs to be at version >5.

## Your Environment
Kedro 0.19.3, python 3.10, Linux

**Comment by noklam** [comment]
I see your [comment](https://github.com/kedro-org/kedro/issues/3768#issuecomment-2034286475) here, are you going to open a PR for this?

**Comment by Lasica** [comment]
Yes

**Comment by merelcht** [comment]
Hi @Lasica, are you still interested in creating a PR for this?
