### ISSUE TITLE
Deprecate (mark for future removal) `get_pkg_version` from the public API

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#3789]
## Context

              @merelcht It didn't change by #3742. 

https://github.com/kedro-org/kedro/blob/a91ccdbecb5541490b5146b6179ab4c621b9ea73/kedro/framework/cli/utils.py#L204-L218

I just check again, this function is not used anywhere in framework, but only tests. (last change is 4 years ago). Maybe at some points it was used for `kedro build-reqs`? I suggest we deprecate this function since it's a public function and move it to test.

_Originally posted by @noklam in https://github.com/kedro-org/kedro/issues/2912#issuecomment-2031643218_

Remove the function from public API and move it to test only.

**Comment by noklam** [comment]
One question here, we tend to do the breaking change later in `develop` to avoid the code diverge too much. At the same time should we add the `deprecated` warnings earlier in 0.19 to inform user?

This is not important for this particular issue, because I think no one use it (hopefully), but it is a valid question for what should we do in general?

**Comment by astrojuanlu** [comment]
> should we add the deprecated warnings earlier in 0.19 to inform user?

Yes

**Comment by noklam** [comment]
Do we need a subticket for deprecation? Or this is ready to go in backlog
grooming.

**Comment by astrojuanlu** [comment]
I'd say let's rename this ticket to "Deprecate `get_pkg_version`" and groom it

**Comment by noklam** [comment]
Actually the tests are obsoleted and we should remove it altogether `class TestCliUtils` in `test_cli.py`.

**Comment by astrojuanlu** [comment]
Funny bit of insight found in the source code of `kedro-mlflow`:

```
            # if it is a local relative path, make it absolute
            # .resolve() does not work well on windows
            # .absolute is undocumented and have known bugs
            # Path.cwd() / uri is the recommend way by core developpers.
            # See : https://discuss.python.org/t/pathlib-absolute-vs-resolve/2573/6
```

Not sure how up to date it is though (the thread is from 2019).
