### ISSUE TITLE
Deprecate micropackaging

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3854]
After some cool-off period in #3750, we saw no indication that users have a desire of keeping our micropackaging functionality, so we decided to eventually remove it.

The first step is to deprecate it for the present 0.19.x cycle.

> Every time a user uses `kedro micropkg` a `DeprecationWarning` should be shown (or equivalent, see discussion about `FutureWarning` and `DeprecationWarning` in various places, for example https://github.com/kedro-org/kedro/issues/2744#issue-1779342165)

Since `kedro.framework.cli.micropkg` is public API too, this warning should also be shown when importing anything from that subpackage.

The warning should communicate to users that this functionality is no longer maintained and will be deleted in Kedro 0.20, and point them to https://github.com/kedro-org/kedro/issues/3750 in case they want to voice a dissenting opinion.

**Comment by yury-fedotov** [comment]
+, I think it's a nice initiative.

**Comment by arek544** [comment]
what's an alternative to micropackaging?

**Comment by astrojuanlu** [comment]
@arek544 Could you detail your use case?

**Comment by arek544** [comment]
I have multiple modular pipelines that l like to share between projects, so I thought micropackaging would be the best solution so far

**Comment by merelcht** [comment]
@astrojuanlu you wrote in the description: 
> Since kedro.framework.cli.micropkg is public API too, this warning should also be shown when importing anything from that subpackage.

The only public method aside from the CLI commands in kedro.framework.cli.micropkg is `safe_extract`: https://github.com/kedro-org/kedro/blob/main/kedro/framework/cli/micropkg.py#L393, does that really warrant an import deprecation warning? I'd be _very_ surprised if anyone is using that since it's a pretty generic utility method.

**Comment by astrojuanlu** [comment]
Good to see most of that module is private API, wrote my comment without looking. I also doubt that anybody is using that specific function, but strictly speaking we should, right?

**Comment by daniel-ressi** [comment]
that's a shame, we started adopting it and with the changes in version 18 the use got smoother. Our use case is pulling preconfigured pipelines into new projects as a starting point for "similar" projects.

**Comment by merelcht** [comment]
> that's a shame, we started adopting it and with the changes in version 18 the use got smoother. Our use case is pulling preconfigured pipelines into new projects as a starting point for "similar" projects.

Hi @daniel-ressi, thanks for your comment. For the use case you're describing we actually have Kedro Starters: https://docs.kedro.org/en/stable/starters/starters.html, this is a way to create project templates to standardise projects in a way that fits your organisation's setup.
