### ISSUE TITLE
[Stress Testing] - Create example projects to assess Kedro performance for complex pipelines

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3866]
### Description

https://github.com/kedro-org/kedro/issues/3957 needs to be done first as pre-work.

There are several features across the Kedro organisation that could benefit from manual testing on large projects to evaluate performance. The proposal is to create several kedro projects of varying size that can be used to test and experiment with.

The example projects don't have to be "legit" as in tackling real data science problems. It can be toy examples. The main point here is creating projects with scale. 

This could be particularly useful for testing Viz features, CC @rashidakanchwala, @NeroOkwa 

### Context
The Kedro-Viz team carried out a performance analysis using an internal QB pipeline, with preliminary results shown here https://github.com/kedro-org/kedro-viz/issues/1064

> * It takes a long time to initialise the Kedro modules and reach the actual `kedro viz run` command (already sort of known, [Improve Kedro CLI startup time kedro#1476](https://github.com/kedro-org/kedro/issues/1476))
> * The expensive operation before starting the viz server is loading the data from the Kedro session (possibly related to [Lazy Loading of Catalog Items  kedro#2829](https://github.com/kedro-org/kedro/issues/2829) ?)
> * Most of the time taken to load the data is from catalog and `pipelines_dict` resolution, which worsens as the pipeline count increases

(from https://github.com/kedro-org/kedro-viz/issues/1064#issuecomment-2100489744, summary of [internal report](https://mckinsey.box.com/s/rgi7ipvjbk420mn3tendl63vr7vcu3aw)).

There is preliminary evidence that the Kedro Framework CLI is a bottleneck for Kedro Viz.

This is on top of the already existing evidence that Kedro takes a lot of time to load even for trivial commands or almost empty projects #1476 

We noted that there are several factors that make a pipeline "complex":

- Lots of nodes
- Lots of pipelines
- Lots of datasets

In I expanded on @AhdraMeraliQB's original proposal and suggested that we create a family of pipelines, comprising

>  * An empty project (so that we can measure just "cold startup" time, essentially what I did in [Kedro initialization is slow #3033 (comment)](https://github.com/kedro-org/kedro/issues/3033#issue-1895014637))
>  * 1 pipeline with increasingly large number of nodes (essentially what @AhdraMeraliQB proposed in [Create QA Kedro test projects for stress testing and performance and evaluation #3790 (comment)](https://github.com/kedro-org/kedro/discussions/3790#discussion-6478228))
>  * N pipelines of 1 node
>  * 1 pipeline and 1 node with increasingly large number of datasets
>  * ...possibly more?

Comes from https://github.com/kedro-org/kedro/discussions/3790

<div type='discussions-op-text'>

<sup>Originally posted by **AhdraMeraliQB** January  6, 2024</sup>

**Comment by noklam** [comment]
Speak to @rashidakanchwala today and we conclude that size of the pipeline is usually not the bottleneck for viz, so we will forgo creating project with complex (nested) modular pipeline. There are some evidence that [Improve resume pipeline suggestion for SequentialRunner by jmholzer · Pull Request #1795 · kedro-org/kedro · GitHub](https://github.com/kedro-org/kedro/pull/1795#issuecomment-1232014807) pipeline usually scales reasonably well with size of node, up to 1000.

This is my initial idea, I would like to tackle this in two parts:
1. Pipeline stress test
2. Component stress test

## Pipeline stress test


The goal of this is to reduce overhead of setting up realistic complex project. This usually include remote storage, pyspark connection etc.

We can use this as an example:
- https://github.com/astrojuanlu/workshop-from-zero-to-mlops
This could help to address issue like:
- https://github.com/kedro-org/kedro/issues/1476
- https://github.com/kedro-org/kedro-viz/pull/1920
- https://github.com/kedro-org/kedro-viz/pull/1966

## Component stress test:
- The main goal for this is to benchmark performance of individual component, this will inform if refactoring work has positive/negative impact. Currently we only check if test pass, so we have no idea if a change may slow down performance. We have done this in the past but usually ad-hoc basis, we should run this regularly (or at least per release).

The direction of this is simple, we want to make measure the change of time against # number of entries. We would start with Datasets and Catalog, as this fits in the `DataCatalog2.0` work and will be immediately useful.


- DataCatalog (test # of datasets with catalog.yml & dataset factory)
- ConfigLoader(# of parameters)
- Optional: pipelines generated in loops (Dynamic pipeline)

This can address:
- https://github.com/kedro-org/kedro/issues/3893
- DataCatalog 2.0

While we are creating the pipeline, we should think about how to scale this in the future (if we have new thing to test, where & how? This may need some flags to turn on/off and documentation)

**Comment by noklam** [comment]
Since this is in sprint already, I update the title so this will be the ticket for pipeline stress testing. I will create separate tickets for the component part.
