### ISSUE TITLE
Investigate performance of config loading for big projects

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro#3893]
## Description
Earlier this week a user reached out to me in private saying that it was taking 3 minutes for Kedro to load their configuration (`KedroContext._get_catalog`).

Today another user mentioned that "Looking at the logs, it gets stuck at the kedro.config.module for more than 50% of the pipeline run duration, but we do have a lot of inputs and outputs"

I still don't have specific reproducers, but I'm noticing enough qualitative evidence to open an issue about it.

**Comment by datajoely** [comment]
I'd like to see us add a CLI command which users can run to produce a flamegraph. It would massively reduce the guesswork here.

`kedro profile {kedro command}` -> `.html` / `.bin`

**Comment by yury-fedotov** [comment]
> I'd like to see us add a CLI command which users can run to produce a flamegraph. It would massively reduce the guesswork here.
> 
> 
> 
> `kedro profile {kedro command}` -> `.html` / `.bin` 

@datajoely flamegraph for the entire pipeline run (how much time each node takes) or just the config resolution / pipeline initialization?

**Comment by datajoely** [comment]
In my mind, it would run the whole command as normal, but also generate the profiling data. 

Perhaps if we were to take this seriously, a full on [memray](https://github.com/bloomberg/memray) integration would incredible.

**Comment by astrojuanlu** [comment]
Continuing the discussion on creating custom commands here https://github.com/kedro-org/kedro/discussions/3908

**Comment by astrojuanlu** [comment]
> Many users have been complaining about the slowness of Kedro with big projects and that can be attributed to many different causes. However one of the most prevailing cause is big parameter files that get expanded into hundreds of datasets on their own. That process takes a lot of time and if the files become too big (a couple of MB), it presents as significant slowdown.

_Originally posted by @idanov in https://github.com/kedro-org/kedro/pull/3732#issue-2202743592_

The solution works, but couples the `DataCatalog` with `OmegaConf`. From the discussion in the PR:

> Shouldn't we redesign the `DataCatalog` API instead so that parameters are first class citizens, and not fake datasets?

There were a few thumbs up to the idea, and it was brought up again in https://github.com/kedro-org/kedro/pull/3973 (@datajoely please do confirm that this is what you had in mind 😄)

@merelcht pointed out that there's a pending research item on how users use parameters and for what #2240 

@ElenaKhaustova agreed that this is relevant in the context of the ongoing `DataCatalog` API redesign #3934.

Ideally, if there's a way we can tackle this issue without blocking it on #2240, the time to look at it would be now. But I have very little visibility on what are the implications, or whether we would actually solve the performance problem at all. So, leaving the decision to the team.

**Comment by astrojuanlu** [comment]
Sorry to keep moving the conversation but I'd rather not discuss the specifics of a particular solution outside the corresponding PR, addressed your question in context at https://github.com/kedro-org/kedro/pull/3732#discussion_r1662727430

**Comment by astrojuanlu** [comment]
Now that we're working on this, some goals for this ticket:

- understand under what circumstances `omegaconf` becomes the dominant bottleneck of loading configuration
- find where the hotspots are, in terms of functions called (function profiling) but also where in the Kedro code are they being called (line profiling)
- understand the scaling properties, for example
  - what happens with 1 config file with 10, 100, 1 000 variables?
  - what happens with 1 config file with 10, 100, 1 000 dataset factories?
  - what happens with 10 config files with a given pattern, 100, 1 000?
    - in other words: `catalog1.yml`, `catalog2.yml`, ..., `catalog1000.yml` when the pattern is `catalog*.yml`
  - are all the scaling laws above linear? are some of them superlinear?
- in the absence of additional context from the original reporter (reached out to them by email), how many files, variables etc are needed to reach 3 minutes of config loading on modern hardware?

The outcomes should be

- an analysis of what functions dominate with "big" configuration
- an analysis of what lines of code in the Kedro codebase dominate with "big" configuration
- scatter plots that showcase the scaling properties of configuration loading with respect to different properties as outlined above, see https://github.com/kedro-org/kedro/issues/3167#issue-1939776342 for an example

Hopefully by the end of the analysis we should either have

- a clear recommendation of what part of the code we can optimise, or
- a mandate to look for something faster than `omegaconf` 😬

**Comment by noklam** [comment]
@astrojuanlu My worry is that we will likely find nothing actionable unless there is a project that is actually slow with OmegaConfigLoader. With the [benchmark result](https://kedro-org.github.io/kedro-benchmark-results/#/summarylist), it seems that it is reasonable fast.

We can still do the exponential scaling (not necessary a combination of all) to better understand the performance of configloader (this should probably move into the benchmark once done):
1. Scaling with number of files, i.e. file1, file2, file - maybe issues with globbing or related to small files
2. Scaling number of entry (benchmark covers already), we can increase the number of entries see how well it scales.
3. #number of factories

The result of this should be a table (one axis being the thing to be test, the other axis is the number of entry) + profiling

**Comment by deepyaman** [comment]
> * a mandate to look for something faster than `omegaconf` 😬

I had started working on something for fun a few months ago to solve this (potential) problem.  So if you can find cases where `omegaconf` is slow, I'd be very interested. 😉

**Comment by datajoely** [comment]
Did someone hear a 🦀 walking?

**Comment by datajoely** [comment]
I'm not sure if it's worth the engineering overhead, but its cool

https://github.com/SergioBenitez/Figment

**Comment by datajoely** [comment]
Some more on the same theme:

https://github.com/leptonyu/cfg-rs
https://github.com/LukasKalbertodt/confique

**Comment by astrojuanlu** [comment]
Thanks a lot for the analysis @ravi-kumar-pilla , the analysis looks good. Looks like everything scales linearly.

We're still waiting for feedback from a user that was struggling with high latency.

**Comment by noklam** [comment]
Thanks @ravi-kumar-pilla , this aligns with the result here https://kedro-org.github.io/kedro-benchmark-results/#benchmark_ocl.TimeOmegaConfigLoader.time_loading_catalog

This looks reasonably fast enough (1000 datasets in 1 second). Let's wait for the feedback from the user.

**Comment by merelcht** [comment]
Great analysis, thanks @ravi-kumar-pilla ! Is there by any chance any parts of the Kedro code that are also introducing latency or is it only the `omegaconf` stuff? 

And for number 3 `Multiple catalog files following catalog* pattern`, did these catalogs have variable interpolation or not? This one is clearly the slowest, but any project with close to 100 catalogs sounds a bit crazy 😅 I think it's reasonable to assume that's not a very realistic setup and the timings for around 10 catalogs are still reasonable IMO.

**Comment by merelcht** [comment]
I'm also curious to hear how you think we can add this kind of profiling to the QA/benchmarking tests @ravi-kumar-pilla ? And did you find the newly added benchmarking setup useful for this kind of testing at all?

**Comment by ravi-kumar-pilla** [comment]
> I'm also curious to hear how you think we can add this kind of profiling to the QA/benchmarking tests @ravi-kumar-pilla ? And did you find the newly added benchmarking setup useful for this kind of testing at all?

The benchmark setup does show similar performance trajectory and is useful for testing these cases. We can definitely iterate and add more use cases of generating the catalog.

**Comment by ravi-kumar-pilla** [comment]
Hi Team,

Based on the materials we received, it is evident that the bottleneck is OmegaConf usage (`to_container` method). Testing this locally, we observed that the method takes time in resolving variable interpolations i.e., if the catalog contains any global or variable references and if the referenced file has complex hierarchical structure then the method `get_node_value` in `omegaconf/basecontainer.py` takes considerably long time which is called inside `to_container`. Please find below observations -


<img width="2045" alt="image" src="https://github.com/user-attachments/assets/b98ddf1e-2ecf-4fdf-82c0-a6eb81114518">

![image](https://github.com/user-attachments/assets/742e589d-961d-46ed-afbe-c41f7ecdadc1)

These observations are in-line with the above benchmark test [plots](https://github.com/kedro-org/kedro/issues/3893#issuecomment-2460629752). `OmegaConf` seems to be the bottleneck in resolving complex variable references. Happy to hear any suggestions. Thank you

**Comment by ravi-kumar-pilla** [comment]
Closing this as the investigation is completed. Opened a follow up issue to improve time taken by OmegaConf in resolving global interpolations [here](https://github.com/kedro-org/kedro/issues/4322)
