### ISSUE TITLE
Move PySpark to end of Tools prompt

### ISSUE THREAD

**Issue by bpmeek** [kedro-org/kedro#3903]
## Description
I'm always frustrated when creating a new Kedro project because I generally want all of the features _except_ PySpark.

## Context
Most of the `new project tools` available are carry-overs from previous standard starters except PySpark, I think it makes sense then to switch PySpark and Kedro-Viz options to allow users to input 1-6 to get all tools other than PySpark, which I imagine would be used less frequently than Kedro-Viz. 

## Possible Alternatives
You could add an "except" flag to be `all except 6` or something along those lines.

**Comment by DimedS** [comment]
Thanks, @bpmeek . That makes sense to me as well. I will add it to the sprint planning

**Comment by merelcht** [comment]
Hi @bpmeek, do you know you can also do `1-5,7` as a selection option when going through the `kedro new` flow?

**Comment by bpmeek** [comment]
@merelcht I was not aware of that, that certainly helps!

**Comment by merelcht** [comment]
Great! Moving PySpark to the end of the tools prompt is a breaking change, so we'd rather not do it unless a large part of our user base wants it. We can leave the issue open to gather opinions, or if you're happy with the selection syntax above, we'll close it. @bpmeek

**Comment by merelcht** [comment]
Closing this for now, since no more comments have come in.
