### ISSUE TITLE
[DataCatalog]: Error message is confusing if the `catalog.yaml` is invalid

### ISSUE THREAD

**Issue by ElenaKhaustova** [kedro-org/kedro#3910]
## Description
If one has an invalid entry in the `catalog.yml`, they get a confusing error message like `AttributeError: 'str' object has no attribute 'items'`

![image (13)](https://github.com/kedro-org/kedro/assets/157851531/9f6fea5d-1f48-48b8-8096-59633cc7616f)

Relates to https://github.com/kedro-org/kedro/issues/2401

**Comment by astrojuanlu** [comment]
Some extra context in #3555
