### ISSUE TITLE
[DataCatalog]: Error message is confusing when kedro-dataset is not installed

### ISSUE THREAD

**Issue by ElenaKhaustova** [kedro-org/kedro#3911]
## Description
When `kedro-datasets` is not installed the error message one gets is not informative.

We propose enhancing the error message to provide a clear message on the root cause of the failure - when dataset dependencies are missing.

Relates to https://github.com/kedro-org/kedro/issues/2401

## Context
Currently, users are required to install all dependencies even for unused datasets (in case you want to run pipeline partially or do not load some datasets when standalone catalog usage). The error message generated when some datasets are not installed is unclear, making it difficult for users to understand why the pipeline fails. 

Example of the current error message:

```
DatasetError: An exception occurred when parsing config for dataset 'companies':
Class 'pandas.CSVDataset' not found, is this a typo?
```

This error occurs during dataset configuration parsing and lacks clarity, not suggesting the straightforward solution of installing the necessary package. This can lead to confusion and delays as users may not immediately realize that the issue is due to missing software rather than a typo in their configuration.

**Comment by astrojuanlu** [comment]
Also, as much as I'd like to see a more explicit call for users to `pip install kedro-datasets[whatever]`, it's also true that `kedro-datasets` is not, and should not, be the only package providing the datasets the user is looking for...

The phrasing of the error message & call to action here is important.

**Comment by Noobzik** [comment]
Just got the same issue, with Kedro v0.19.10 with my own project,
But the space tutorial works fine, I dont know what I am missing

**Comment by astrojuanlu** [comment]
Hi @Noobzik , could you please open another issue, detailing what error did you get and how to reproduce it?
