### ISSUE TITLE
[DataCatalog]: `add_feed_dict()` performance bottleneck

### ISSUE THREAD

**Issue by ElenaKhaustova** [kedro-org/kedro#3912]
## Description
The current implementation of `add_feed_dict()` leads to performance bottlenecks because it calls `add()` method which duplicates the structure of `_FrozenDatasets`, resulting `O(N^2)` complexity thus unnecessary slowdowns, especially in case of many catalog entries.

We propose implementing a more efficient approach that directly updates datasets collection without the need for copying `_FrozenDatasets` structures.

## Context
https://github.com/kedro-org/kedro/blob/27f5405cefd6701ffac4c6243030486fb7d3c942/kedro/io/data_catalog.py#L694

https://github.com/kedro-org/kedro/blob/27f5405cefd6701ffac4c6243030486fb7d3c942/kedro/io/data_catalog.py#L626

https://github.com/kedro-org/kedro/blob/27f5405cefd6701ffac4c6243030486fb7d3c942/kedro/io/data_catalog.py#L108

## Steps to Reproduce
```
from time import monotonic


f = _FrozenDatasets({f"k_{i}": i for i in range(100)})
now = monotonic()
for i in range(10000):
    f = _FrozenDatasets(f, {f"new_{i}": i})
print(monotonic() - now)
# 0.191298125020694

f = _FrozenDatasets({f"k_{i}": i for i in range(100)})
now = monotonic()
for i in range(100000):
    f = _FrozenDatasets(f, {f"new_{i}": i})
print(monotonic() - now)
# 21.588158333004685

f = _FrozenDatasets({f"k_{i}": i for i in range(100)})
now = monotonic()
for i in range(120000):
    f = _FrozenDatasets(f, {f"new_{i}": i})
print(monotonic() - now)
# 33.06306695801322
```

## Suggested Implementation
Modify `_FrozenDatasets` constructor, so it only inputs a `dict[str, AbstractDataset]`. Keep using `self.__dict__.update()` in the constructor to add datasets into the  `_FrozenDatasets`. In case of extending `_FrozenDatasets` collection as in `add()` method use `_FrozenDatasets.__dict__.update()`. We can also consider adding `_FrozenDatasets._update()` method wrapping `_FrozenDatasets.__dict__.update()` logic and use it in the constructor and upon `add()`.

**Comment by astrojuanlu** [comment]
In light of #2728, more context is needed around how and why people try to mutate the catalog. It's clear that there's a need to inject datasets by plugin authors, see for example:

- https://github.com/Galileo-Galilei/kedro-mlflow/blob/64b8e94e1dafa02d979e7753dab9b9dfd4d7341c/kedro_mlflow/mlflow/kedro_pipeline_model.py#L108-L116 (@Galileo-Galilei)
- https://github.com/DAGWorks-Inc/hamilton/blob/2ae6d471cba72299cb681a14ed6a38ee236975ee/examples/kedro/kedro-code/tests/pipelines/data_science/test_pipeline.py#L54-L61 (@zilto)
- https://github.com/Minyus/pipelinex/blob/a60d32a07c3bf545f5b25273574a4be72a49a39e/src/pipelinex/extras/hooks/add_catalog_dict.py#L29-L30 (@Minyus)
- https://github.com/NameArtem/deployml_course/blob/main/README.md#airflow--kedro (my Russian is a bit rusty)

There's general agreement that we don't necessarily want to make _all_ mutations of the catalog easy (like crazy injection of datasets in the middle of the lifecycle) but maybe there's more ways we can open up the collection of datasets just before the catalog is first instantiated for the rest of the run.

For interactive use on the other hand, building the `DataCatalog` in an imperative way seems unnecessary and there are other possibilities we can offer https://github.com/kedro-org/kedro/issues/3612#issuecomment-2034961020

**Comment by astrojuanlu** [comment]
xref #3930 which also discusses catalog mutability

**Comment by ankatiyar** [comment]
Interestingly I found this from 2021 :P https://github.com/kedro-org/kedro/issues/951

**Comment by DimedS** [comment]
As I understand it, we use the `_FrozenDatasets` class to achieve immutability for the `datasets` attribute of the `DataCatalog` class. This means that if someone wants to modify the `datasets`, it will take `O(n)` complexity because a new `_FrozenDatasets` instance is created by copying the previous one.

In my opinion, to solve this issue, we should first consider cancelling immutability. Regarding the current ticket, it's unclear to me why the current situation is a problem. Do we frequently encounter scenarios where `add_feed_dict()` is called multiple times?

**Comment by astrojuanlu** [comment]
> Do we frequently encounter scenarios where `add_feed_dict()` is called multiple times?

Indeed, that's the topic of https://github.com/kedro-org/kedro/issues/3930

**Comment by DimedS** [comment]
@ElenaKhaustova, could you please comment: Is it correct that the solution proposed in that ticket leads to the loss of dataset immutability? Before implementing it, we need to agree on this loss as described in #3930 ?

**Comment by ElenaKhaustova** [comment]
> As I understand it, we use the `_FrozenDatasets` class to achieve immutability for the `datasets` attribute of the `DataCatalog` class. This means that if someone wants to modify the `datasets`, it will take `O(n)` complexity because a new `_FrozenDatasets` instance is created by copying the previous one.
> 
> In my opinion, to solve this issue, we should first consider cancelling immutability. Regarding the current ticket, it's unclear to me why the current situation is a problem. Do we frequently encounter scenarios where `add_feed_dict()` is called multiple times?

That's the case when people use multi-runner for tuning parameters which under the hood creates numerous similar datasets with namespaces and thus extensively uses the `add_feed_dict()` method. It's indeed different from the typical usage of pipelines.

**Comment by ElenaKhaustova** [comment]
> @ElenaKhaustova, could you please comment: Is it correct that the solution proposed in that ticket leads to the loss of dataset immutability? Before implementing it, we need to agree on this loss as described in #3930 ?

Well, technically one can modify it now using private methods as well. The suggestion for now is just to use `_FrozenDatasets.__dict__.update()` instead of recreating an object. So for users, it's still immutable since it doesn't have a setter but we modify it internally inside `add()` method.  But in future, it will probably be redesigned.

**Comment by DimedS** [comment]
> > @ElenaKhaustova, could you please comment: Is it correct that the solution proposed in that ticket leads to the loss of dataset immutability? Before implementing it, we need to agree on this loss as described in #3930 ?
> 
> Well, technically one can modify it now using private methods as well. The suggestion for now is just to use `_FrozenDatasets.__dict__.update()` instead of recreating an object. So for users, it's still immutable since it doesn't have a setter but we modify it internally inside `add()` method. But in future, it will probably be redesigned.

@ElenaKhaustova, thank you for the explanation. I have two questions:

1. Is it correct that we do not need to modify the `_FrozenDatasets` class constructor to solve the current issue?
2. Is your proposal to modify the `add()` function inside the `DataCatalog class` from:
`self.datasets = _FrozenDatasets(self.datasets, {dataset_name: dataset})`
to:
`self.datasets.__dict__.update({dataset_name: dataset})`
If we make this modification, we would start treating the datasets attribute as mutable within the Kedro codebase. I am concerned about this change because the immutability of datasets might be important not only for user experience but also for the internal logic of Kedro. I don't know the full list of reasons behind the decision to make them immutable initially. Could you clarify if this approach is acceptable for the Kedro DataCatalog architecture?

**Comment by ElenaKhaustova** [comment]
Solved in https://github.com/kedro-org/kedro/pull/4218
