### ISSUE TITLE
[DataCatalog]: Revise methods and properties names for `DataCatalog`

### ISSUE THREAD

**Issue by ElenaKhaustova** [kedro-org/kedro#3931]
## Description
Users find the naming of public functions, such as `add_feed_dict,` unclear and confusing, making it difficult to understand their purpose.

We propose to:
1. Review and revise methods and properties names for `DataCatalog` to make them more descriptive and intuitive, clearly indicating their purpose and functionality.
2. Revisit our usage examples to make them more informative for users and replace `io` with `catalog`.

Relates to https://github.com/kedro-org/kedro/issues/3612

## Context

- Some user feedback: "I didn't even know what `add_feed_dict` did until someone explained it to me."
- Currently, in some of our examples, we use `io` instead of `catalog` while the last is meant.

https://github.com/kedro-org/kedro/blob/27f5405cefd6701ffac4c6243030486fb7d3c942/kedro/io/data_catalog.py#L681

![Screenshot 2024-06-05 at 18 15 46](https://github.com/kedro-org/kedro/assets/157851531/db6a4d41-66ce-4a61-81ca-6ef5a881d565)

**Comment by merelcht** [comment]
We could tackle this either by changing the current `DataCatalog` function names in the next breaking release, or by making sure that the public API for a new `DataCatalog2` has better names. If we decide to build `DataCatalog2` (obviously with a better name) alongside `DataCatalog` we don't actually need to do anything with this ticket, just keep in mind we name our methods clearly 🙂

**Comment by ElenaKhaustova** [comment]
Solved in https://github.com/kedro-org/kedro/pull/4218
