### ISSUE TITLE
`kedro new` includes empty `data_science` folder in `pipelines`

### ISSUE THREAD

**Issue by yury-fedotov** [kedro-org/kedro#3955]
## Description
`kedro new` includes empty `data_science` folder in `pipelines` even if I say to not include a pipeline example during `kedro new` workflow.

## Steps to Reproduce
1. Initialize kedro new with all defaults except pyspark, and reply no when it asks about example pipeline
2. See that an empty `data_science` folder in `pipelines` has been created as part of the project

## Expected Result
It should not be created.

## Your Environment
* Kedro version used (pip show kedro or kedro -V): 0.19.6
* Python version used (python -V): 3.10
* Operating system and version: MacOS

**Comment by merelcht** [comment]
Hi @yury-fedotov, thanks for reporting this issues. I tried to reproduce the issue and can see there's an empty `data_science` folder inside `tests/pipelines/`. This should indeed not be there. Feel free to open a PR to fix this, but otherwise the team will take it on.

**Comment by merelcht** [comment]
Actually this was quite a small change so I've opened a PR for it here: https://github.com/kedro-org/kedro/pull/3956

@yury-fedotov can you confirm you are also talking about the `tests` directory?

**Comment by yury-fedotov** [comment]
Hi @merelcht ! nope, actually this is not at all related to `tests`. In my case I got generated in `pipelines` folder as if it is a folder of an example pipeline. Just an empty folder named `data_science` (not even a Python package, i.e. had no `__init__.py` inside).

**Comment by merelcht** [comment]
@yury-fedotov in that case can you specify how you created the project? I did `kedro new --name=reprtest --example=no --tools=lint,test,viz,data,log,docs` and the same through the interactive flow, but I don't get a `data_science` folder in `src/pipelines` only in `tests` as I mentioned before.

**Comment by yury-fedotov** [comment]
@merelcht hey! Sorry I disappeared for a while. So I did another check and you were right: the bug I described **exists** but **only in tests**. See here:

![Screenshot 2024-06-29 at 8 37 40 PM](https://github.com/kedro-org/kedro/assets/102987839/29dc9ef6-54e6-47ef-9d7d-cff71b38459c)

It it `kedro 0.19.6` and I did a test on Jun 29 2024.

#3956 should close it, so whenever it gets released, this bug should be gone.

Thanks for fixing it!

I am closing this issue as resolved.
