### ISSUE TITLE
Pretty printing: `AbstractDataset.__repr__`

### ISSUE THREAD

**Issue by ElenaKhaustova** [kedro-org/kedro#3980]
## Description
Parent ticket: https://github.com/kedro-org/kedro/issues/3913

Implement `__repr__` for `AbstractDataset` for better dataset representation and printing and further use it within `DataCatalog.__repr__`

## Context
https://github.com/kedro-org/kedro/issues/3913#issue-2330910213
https://github.com/kedro-org/kedro/issues/1721

## Possible Implementation

- We already have an implementation of `__str__` method for `AbstractDataset` based on the dataset's `_describe` which can be adjusted and moved to `__repr__`.
- Update `_describe` for `MemoryDataset`, `LambdaDataset`, `SharedMemoryDataset`, and `CachedDataset` if needed.
- One of the potential solutions is to extend the built-in `pprint.PrettyPrinter`.

**Comment by ElenaKhaustova** [comment]
I've prototyped two different approaches for printing:

- both approaches implement `__repr__()` method for `AbstractDataset` based on the implementation of `_describe()` method for the specific dataset. Since the `__str__` method is not implemented `__repr__()` is called when converting object to string, so we have the same results when `print(obj)`, `repr(obj)`,` obj`.
- https://github.com/kedro-org/kedro/pull/3990 - the first approach prints datasets in one line in a format `module.Class(arg1=val_1, ..., arg_n=val_n)` where argument values are formatted with `pprint.pformat` and then joined as strings, so we construct the resulting string from formatted strings.

![Screenshot 2024-07-05 at 00 27 12](https://github.com/kedro-org/kedro/assets/157851531/d359381d-680d-4eac-b6fa-42b78b115afe)

- https://github.com/kedro-org/kedro/pull/3992 -  the second approach represents dataset in dict format `{'module.Class': {'arg_1:' val_1}, ..., {}}`, so at first the end dictionary is created and then it is formatted with `pprint.pformat` thus we can control indentation but it looks less compact.

![Screenshot 2024-07-05 at 00 16 11](https://github.com/kedro-org/kedro/assets/157851531/da576613-a90b-4e7d-99c8-2bc1ec9af4e5)

- for both approaches, we can control depth, so we can hide arguments after a certain indentation level
- they also both look representative enough compared to what we had before but the first is more compact, while the second keeps the indentation

I'm curious about what you think. Does it feel good enough? Do we want more or less information provided? Which approach seems better?

**Comment by noklam** [comment]
One caveats if you are doing `pprint` https://github.com/kedro-org/vscode-kedro/pull/33

**Comment by ElenaKhaustova** [comment]
The non-indented version was preferred to the indented, closing https://github.com/kedro-org/kedro/pull/3992

**Comment by datajoely** [comment]
One other piece - does your implementation @ElenaKhaustova expose encrypted database connection strings?

would this YAML:

```
shuttle_id_dataset:
  type: pandas.SQLQueryDataSet
  sql: "select shuttle, shuttle_id from spaceflights.shuttles;"
  credentials: db_credentials
  layer: raw
```

render our the constructed connection string or not?

**Comment by ElenaKhaustova** [comment]
> One other piece - does your implementation @ElenaKhaustova expose encrypted database connection strings?
> 
> would this YAML:
> 
> ```
> shuttle_id_dataset:
>   type: pandas.SQLQueryDataSet
>   sql: "select shuttle, shuttle_id from spaceflights.shuttles;"
>   credentials: db_credentials
>   layer: raw
> ```
> 
> render our the constructed connection string or not?

What is exposed depends on the implementation of `_describe()`: https://github.com/kedro-org/kedro-plugins/blob/be99fecf6cf5ac8f6a0a717c56b06dbc148b26eb/kedro-datasets/kedro_datasets/pandas/sql_dataset.py#L558

So none of the credentials or connection string are exposed.
