### ISSUE TITLE
Close all (or as many as possible) open PRs!

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#3996]
### Description
Let's do a bit of housekeeping in the coming sprint(s) and close/merge as many open PRs as possible. 

### Context
Focussing on the `kedro` repo: some PRs have been open for a long time. Let's close or merge them, so we get our repo in a healthier looking state.

- [ ] https://github.com/kedro-org/kedro/pull/2734
- [x] https://github.com/kedro-org/kedro/pull/3528
- [x] https://github.com/kedro-org/kedro/pull/3707
- [X] https://github.com/kedro-org/kedro/pull/3732 @merelcht Closed, because it's a breaking change and no agreement on approach. This should instead be tackled during sprint work as part of either the catalog redesign or performance improvements.
- [ ] https://github.com/kedro-org/kedro/pull/3744 -> there's `kedro-databricks` now, so might not be needed to merge this.
- [x] https://github.com/kedro-org/kedro/pull/3785
- [ ] https://github.com/kedro-org/kedro/pull/3819
- [ ] https://github.com/kedro-org/kedro/pull/3852
- [ ] https://github.com/kedro-org/kedro/pull/3905 -> Needs more work, not close to being merged. 

Next we can focus on `kedro-plugins`

**Comment by astrojuanlu** [comment]
+1000!!

**Comment by merelcht** [comment]
Closed/merged several, the others need more work and aren't ready to be merged yet.
