### ISSUE TITLE
Replace `io` with `catalog` in `DataCatalog` docstrings

### ISSUE THREAD

**Issue by ElenaKhaustova** [kedro-org/kedro#4033]
## Description
Relates to https://github.com/kedro-org/kedro/issues/4024

## Context
Recently we updated docs and replaced `io` with `catalog` for clarity: https://github.com/kedro-org/kedro/pull/3924/files

The same should be done for `DataCatalog` docstrings for consistency and clarity. Currently, we use a mixture of two names: catalog: https://github.com/kedro-org/kedro/blob/5e1504487d9c5c0d210bc231669f68049c0ca213/kedro/io/data_catalog.py#L718 and io: https://github.com/kedro-org/kedro/blob/5e1504487d9c5c0d210bc231669f68049c0ca213/kedro/io/data_catalog.py#L572

**Comment by yury-fedotov** [comment]
Can I try to take this one?

**Comment by yury-fedotov** [comment]
> Can I try to take this one?

See: https://github.com/kedro-org/kedro/pull/4034

**Comment by ElenaKhaustova** [comment]
> Can I try to take this one?

Absolutely!
