### ISSUE TITLE
Support archiving/deleting old/unused datasets

### ISSUE THREAD

**Issue by deepyaman** [kedro-org/kedro#406]
## Description
I would like a `kedro catalog delete` command to make removing old data easy. For example, `kedro catalog delete before:5/18/2020 layer:model_output` will delete all model outputs generated by pipelines run before May 18.

The syntax can get extremely expressive, but even just a date filter is a great start.

## Context
I'm running pipelines on a shared server and getting complaints that I'm using too much disk space (169 GB and rising), as each pipeline run generates hundreds of megabytes of versioned datasets. This use case is not unique to a shared server; cleaning up old run data can be necessary on a local computer and even on cloud storage.

I could write a shell script to clean old data myself, but then I need to manage:

1. Version parsing, so that I can only delete data beyond my archival period.
2. Different filesystems (for S3 datasets, I need to delete like `aws s3 rm <path>`; locally, `rm -rf <path>`).

I also need to do this for each and every project, and others will do the same thing in myriad ways.

## Possible Implementation
Add a `_delete` method to datasets, and make `_delete` functionality available for any versioned, writable dataset. (And then implement the other stuff, too. ;))

**Comment by Robert-Muil** [comment]
Another use-case for this feature is changed catalog configuration: currently, if, say, the `versioned` flag is changed, the pipeline will break for those who have already got the affected datasets existing, until they manually delete them.

**Comment by deepyaman** [comment]
I think this issue is still valid.

**Comment by merelcht** [comment]
Closing this in favour of https://github.com/kedro-org/kedro/issues/1799
