### ISSUE TITLE
Rich markup regression in 0.19.7

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#4094]
# Context

The regression happened in 0.19.7.

before 0.19.7:
![image](https://github.com/user-attachments/assets/94c9e3cd-2af5-46a1-85ad-92118adcc0e2)

In 0.19.7:
![Uploading image.png…]()

> 
> However, I think the change introduced in #3682 never really worked properly. The logic to detect the rich handler doesn't seem to work. When I have `rich` installed the orange colouring isn't there, and I added some print statements and it seems like the `RichHandler` isn't ever set. 
> 
> _Originally posted by @merelcht in https://github.com/kedro-org/kedro/issues/4090#issuecomment-2291081005_
>

**Comment by lrcouto** [comment]
I've found that the logger object being used in testing has nothing in its `handlers` parameter, this is why it's not working.

`{'filters': [], 'name': 'kedro.io.data_catalog', 'level': 0, 'parent': <Logger kedro (INFO)>, 'propagate': True, 'handlers': [], 'disabled': False, '_cache': {20: True}, 'manager': <logging.Manager object at 0x7fea88d9d010>}`

**Comment by noklam** [comment]
@lrcouto See #4097

The original tests are not that useful because they are not testing the actual logger (root) that do the work. I removed the cache as I don't think it's useful and simply move it as an internal attribute (`self._use_rich_markup`).

The original function try to be generic but I think it is a bit over-complicated for things that no one is using.
