### ISSUE TITLE
Remove support for Python 3.8

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#4115]
## Description

Python's [active support for version 3.8 ends in October 2024](https://devguide.python.org/versions/). Therefore I would suggest we drop official support for 3.8 end of September/beginning of October. As we established last year, when a python version reaches end of life we don't consider dropping support as a breaking change (https://github.com/kedro-org/kedro?tab=readme-ov-file#python-version-support-policy)

## Context

To make sure we move along in pace with the rest of the ecosystem in Python.

**Comment by kevin1kevin1k** [comment]
I can work on this!
I saw previous issue #2158 and PR #3060 for dropping 3.7, so the process should be similar to follow.

**Comment by astrojuanlu** [comment]
Python 3.8 is now officially EOL https://discuss.python.org/t/python-3-8-is-now-officially-eol/66983
