### ISSUE TITLE
[Stress Testing] - Design and document an approach for maintaining performance tests 

### ISSUE THREAD

**Issue by noklam** [kedro-org/kedro#4128]
## Description

Design and document an approach for maintaining performance tests to ensure their effectiveness and reliability over time

Tasks
- Analyze the current performance testing framework and identify areas for improvement.
- Develop a comprehensive maintenance plan, including regular updates and reviews.
- Document best practices for maintaining performance tests.
- Create guidelines for identifying and addressing performance test failures.
- Ensure compatibility with new software updates and changes.

The scope of the ticket include:
- Decide how to trigger these tests. Is it on demand, per
- Document how tests should be maintained or extend
- Test should be easy to run locally but also on CI (with Github Action)
  - Idea: Maybe we can use tag or branch name, for example, `performance_xxxx_xxxx`, if the branch name contains a keyword, that will trigger an additional performance CI automatically.
- (Bonus) How to report the performance benchmark? If it's run periodically, can we have it automatically report as a table? For example, consider some benchmark tools like: https://github.com/kedro-org/kedro/issues/4128#issuecomment-2338171827

As a long term goal, It would be really nice to keep a benchmark table like this, so when developer working on individual feature, they can easily compare the result and know if the PR has caused performance issue.

| Release | task1 (ConfigLoader) | task2 | task3 |
|--------|--------|--------|--------|
| 0.19.1 | 10s | 10s | 10s |
| 0.19.2 | 10s | 30s | 9s |
| 0.19.3 | 8s | 10s | 9s |
| 0.19.4 | 11s | 10s | 9s |

**Comment by astrojuanlu** [comment]
In a past life I was using asv for this https://github.com/airspeed-velocity/asv/

![benchmarks](https://github.com/user-attachments/assets/12c39f63-8bb1-47f3-b859-4b3cdc1f7805)

**Comment by lrcouto** [comment]
I like the idea of triggering the workflows with a PR comment. I'd make it do it automatically for releases. I also like the idea of using github pages to visualize the results.

My only concern is if it would be cumbersome to mantain, since it'd be several separate repos.

**Comment by noklam** [comment]
The tests are now triggered as a Github Action job:
- [pipeline-performance-test.yml](https://github.com/kedro-org/kedro/blob/main/.github/workflows/pipeline-performance-test.yml)
- [benchmark-performance.yml](https://github.com/kedro-org/kedro/blob/main/.github/workflows/benchmark-performance.yml)
