### ISSUE TITLE
kedro autocompletion bad pattern

### ISSUE THREAD

**Issue by incoggnito** [kedro-org/kedro#4141]
Hello, I am using zsh and would like to add kedro autocompletion. Is there a trick?

❯ eval "$(_KEDRO_COMPLETE=source_zsh kedro)"
zsh: bad pattern: [09/01/24

[Slack Message](https://kedro-org.slack.com/archives/C03RKP2LW64/p1725214362573319?thread_ts=1725214362.573319&cid=C03RKP2LW64)

**Comment by merelcht** [comment]
It looks like the command syntax has been updated (https://click.palletsprojects.com/en/8.1.x/shell-completion/)

@incoggnito can you try:
```bash
eval "$(_KEDRO_COMPLETE=zsh_source kedro)"
```

In my case I still get the bad pattern error, but the autocompletion does work after running the above.

**Comment by merelcht** [comment]
Hi @incoggnito Do you still need help with this?

**Comment by incoggnito** [comment]
Thanks, I will try this :)

**Comment by merelcht** [comment]
I've opened a ticket to updates these docs: https://github.com/kedro-org/kedro/issues/4179

**Comment by merelcht** [comment]
Completed in #4179
