### ISSUE TITLE
[DataCatalog2.0]: Extend `KedroDataCatalog` with dict interface

### ISSUE THREAD

**Issue by ElenaKhaustova** [kedro-org/kedro#4175]
## Description
As a continuation of a work on `DataCatalog` redesign (https://github.com/kedro-org/kedro/issues/3995#issuecomment-2329528221) we suggest simplifying the interface for `KedroDataCatalog` and make it similar to [UserDict](https://docs.python.org/3/library/collections.html#collections.UserDict)

The reasoning: this way we want to make the catalog functioning as a collection of datasets with an interface familiar to users.

Related tickets that will be addressed:

- https://github.com/kedro-org/kedro/issues/3916
- https://github.com/kedro-org/kedro/issues/3931

## Context
[](https://github.com/kedro-org/kedro/pull/4151)

## Possible Implementation
Change the `KedroDataCatalog` API to support `__iter__`, `__getitem__`, `__setitem__`, `keys()`, `items()` similar to the dict.

Replace old API such as `save()`, `load()`, `list()`, etc.

The first iteration can be done without breaking changes if keep old interface and reuse newly added methods.

**Comment by datajoely** [comment]
I'm actually less excited about this than a lot of the other proposed ideas for this redesign. 

What about putting it inside a property or something like a `.dict_like()` method

**Comment by ElenaKhaustova** [comment]
> I'm actually less excited about this than a lot of the other proposed ideas for this redesign.
> 
> What about putting it inside a property or something like a `.dict_like()` method?

That's an attempt to align on the interface changes before introducing new features, so it doesn't cancel the rest of the redesign idea. But since this is a proposal of a possible interface, it will be helpful at this stage if you can expand your thoughts about why it feels not good.

**Comment by noklam** [comment]
Related idea discussed in the past: https://github.com/kedro-org/kedro/issues/3914#issuecomment-2152697336

**Comment by astrojuanlu** [comment]
We discussed this on backlog grooming. To clarify, the user impact of this one is that rather than doing

```
>>> catalog.list()
>>> catalog.load("my_dataset")
>>> catalog.save("my_dataset", data)
>>> for dataset in catalog.datasets: pass
```

the user would do

```
>>> list(catalog)  # __iter__
>>> catalog["my_dataset"]  # __getitem__
>>> catalog["my_dataset"] = data  # __setitem__
>>> for dataset in catalog: pass  # __iter__
```

While I'm not opposed to have the dict-like interface, I think it's worth discussing whether we should keep the method-based interface. We're not _forced_ to include it, because it's a new class and we allow ourselves to do breaking changes between minor releases. But if we do include it, I expect migration between 0.19.* and 0.20.* will definitely be easier.

**Comment by ElenaKhaustova** [comment]
With this update, we aimed to rework the existing interface to improve naming, remove repeating methods, clarify the differences between methods working with datasets and data, and suggest functionality to iterate through the catalog and access datasets.

## Suggested changes to the interface

1. We provide dict-like interface to work with `Dataset`s - `keys()`, `values()`, `items()`, `__iter__()`, `__getitem__()`, `__setitem__()`, `__len__()`, `get()`
2. We keep some method-based interface to work with `Dataset`s -  `from_config()`, `release()`, `confirm()`,` exists()` - the rest three will also be reworked in future.
3. We keep method-based interface to work with data - `load_data()`, `save_data()`. Now we have `data` postfix for methods working with data rather than `Dataset`s. By default method will be considered to work with `Dataset`s if it doesn't have `data` postfix.

## Implementation

We intentionally do not inherit from `dict` or `UserDict` but rather add the implementation of some methods as we do not expect to maintain all dict-specific functionality like `pop()`, `popitem()`, del by key, etc

## Examples

### Initialization

```python
catalog = KedroDataCatalog(datasets={"test": dataset})

catalog = KedroDataCatalog.from_config(**correct_config)
```

### Properties
```python
config_resolver = catalog.config_resolver

logger = catalog._logger
```

### Interface to work with datasets
```python
print(catalog)  # __repr__

if ds_name in catalog:  # __contains__
    pass

if catalog_first == catalog_second:  # __eq__
    pass

for ds_name in catalog:  # __iter__
    pass

for ds_name in catalog.keys(regex_search="reviews"):  # keys()
    pass

for ds in catalog.values(regex_search="reviews"):  # values()
    pass

for ds_name, ds in catalog.items(regex_search="reviews"):  # items()
    pass

ds = catalog["reviews"]  # __getitem__
ds = catalog.get("reviews", default=default_ds)  # get()

catalog["reviews"] =  ds  #__setitem__
catalog["reviews"] = 123

# _filter_keys() - newly added private method to filter keys

# _validate_dataset() - newly added private method to validate dataset is not None

# release(), confirm(), exists() remained for now but will be re-worked

```

### Interface to work with data
```python

df = catalog.load_data("cars")  # load_data
catalog.save_data("cars", df)  # save_data
```

**Comment by datajoely** [comment]
> `for ds_name, ds in catalog.items(regex_search="reviews"):  # items()`

Is it keys, values or both that are subject to the regex filter?

**Comment by ElenaKhaustova** [comment]
> > `for ds_name, ds in catalog.items(regex_search="reviews"):  # items()`
> 
> Is it keys, values or both that are subject to the regex filter?

Only keys so far, but subject to change: https://github.com/kedro-org/kedro/issues/3917

**Comment by rashidakanchwala** [comment]
Thanks, @ElenaKhaustova. This works for us on Kedro-Viz and will help us access the catalog information without needing to resort to private methods

**Comment by marrrcin** [comment]
Thanks @ElenaKhaustova for the summary. In general, the interface looks nice.
A few questions, concerns:

* `__setitem__` - do you plan to perform type validation at runtime to prevent setting non-dataset objects? Same for keys - enforce `str` type.
* what about "old" interfaces such as `shallow_copy` / `add_feed_dict` etc?

**Comment by ElenaKhaustova** [comment]
> Thanks @ElenaKhaustova for the summary. In general, the interface looks nice. A few questions, concerns:
> 
> * `__setitem__` - do you plan to perform type validation at runtime to prevent setting non-dataset objects? Same for keys - enforce `str` type.
> * what about "old" interfaces such as `shallow_copy` / `add_feed_dict` etc?

Thanks @marrrcin,

- `__setitem__` will handle setting both datasets and non-datasets as it was for `add_feed_dict`
- `add_feed_dict` and `shallow_copy` will be removed

**Comment by marrrcin** [comment]
What will be an alternative to `shallow_copy` though? Kedro-Boot uses it for example (https://github.com/takikadiri/kedro-boot/blob/b9cd2d0c4bb9dbe4f65b1c9b37a3af5cf33dd77b/kedro_boot/framework/adapter.py#L58)

**Comment by ElenaKhaustova** [comment]
> What will be an alternative to `shallow_copy` though? Kedro-Boot uses it for example (https://github.com/takikadiri/kedro-boot/blob/b9cd2d0c4bb9dbe4f65b1c9b37a3af5cf33dd77b/kedro_boot/framework/adapter.py#L58)

`shallow copy` was mainly used to add runtime patterns but an actual copy is not needed to run: https://github.com/kedro-org/kedro/blob/82c1223dd905981d0a728d42c36e59667c98c269/kedro/runner/runner.py#L115

We added a dedicated method to add runtime patterns to catalog and it will be used instead when introducing breaking changes: https://github.com/kedro-org/kedro/blob/82c1223dd905981d0a728d42c36e59667c98c269/kedro/io/kedro_data_catalog.py#L336
