### ISSUE TITLE
Update CLI autocompletion docs

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#4179]
## Description
The docs explaining how to add autocompletion for Kedro CLI commands are outdated. The syntax has changed on the Click side: It looks like the command syntax has been updated (https://click.palletsprojects.com/en/8.1.x/shell-completion/)

The docs need to be updated with this new syntax.

### Documentation page (if applicable)
https://docs.kedro.org/en/stable/development/commands_reference.html#autocompletion-optional

## Context
https://github.com/kedro-org/kedro/issues/4141

**Comment by hyew0nChoi** [comment]
Can I solve this issue? 

+ Is there any document to contribution this project?
+ Can you give more guide to solve this issue? (I'm beginner of contribution with github 🤣)

**Comment by merelcht** [comment]
> Can I solve this issue?
> 
> * Is there any document to contribution this project?
> * Can you give more guide to solve this issue? (I'm beginner of contribution with github 🤣)

Hi @hyew0nChoi, of course you can! 

This is our contribution guide: https://github.com/kedro-org/kedro/blob/main/CONTRIBUTING.md. This specific task requires you to update our documentation. Specific guidance on how to work on our docs is here: https://github.com/kedro-org/kedro/wiki/Contribute-to-the-Kedro-documentation

**Comment by bhavanaeh** [comment]
Hi just checking if this is up for grabs, since no is assigned

**Comment by hyew0nChoi** [comment]
> Hi just checking if this is up for grabs, since no is assigned

Hi! I'm currently working on this. I kindly ask for your understanding.

**Comment by hyew0nChoi** [comment]
https://github.com/kedro-org/kedro/pull/4213
