### ISSUE TITLE
Clarification on OutputNotUniqueError for shared Nodes across Pipelines

### ISSUE THREAD

**Issue by nejox** [kedro-org/kedro#4183]
## Description
 I’m working with Kedro in a project where we have both an inference pipeline and a deployment pipeline. The deployment pipeline uses some nodes from the inference pipeline, and I’ve encountered an OutputNotUniqueError. This error occurs because the output dataset names in both pipelines are the same -> outputting the same catalog entry.

I wanted to clarify it this is intentional, that i can't use the same catalog entry in two pipelines as node output? I see that i could have two catalog entries referencing the same file or adding this as a modular pipeline but it feels weird for me with unnecessary overhead.

## Steps to Reproduce
- pipeline inference -> node save_prediction -> output 07_predictionData
- pipeline deployment -> node save_prediction_deployment -> output 07_predictionData
=> OutputNotUniqueError 

## Your Environment
* Kedro version used: 0.19.8
* Python version used: 3.10

**Comment by nejox** [comment]
So this seems to be caused by the `pipeline_registry.py`:
```pipelines["__default__"] = sum(pipelines.values() ``` 
I do not fully understand this but it seems to add the pipelines together which leads to the duplicate outputs in the same pipeline.
```
kedro/pipeline/pipeline.py", line 177, in __add__
    return Pipeline(set(self._nodes + other._nodes))
   ```

**Comment by ankatiyar** [comment]
Hey @nejox, I believe the error is intentional, you can't have the same output from different nodes in the same pipeline. The `__default__` pipeline is a sum of all the pipelines in the project, by default but you could modify this in your `pipeline_registry.py` to be any other pipeline in your project that runs when `kedro run` is called without `--pipeline` flag.

**Comment by nejox** [comment]
Okay, thank you @ankatiyar for your response!
