### ISSUE TITLE
DataCatalog to support listing generic datasets

### ISSUE THREAD

**Issue by lordsoffallen** [kedro-org/kedro#4184]
## Description

Generic dataset definitions are quite useful to avoid too many entries in the catalog.yml. 

One downside is that `catalog.list() `does not return them. It would be nice to resolve catalog entries from existing pipelines inputs/outputs and show potential catalog names? Right now, when i forget the name of a dataset, i have to go back to the code and find its name so it would be nice to see them in the list function.

Example:

```
"{layer}.{dataset_name}#df":
  type: pandas.ParquetDataset
  filepath: data/{layer}/{dataset_name}.parquet
```

When I have a node that outputs/inputs a string called `01_raw.data#df` this should appear in the data catalog list method.

**Comment by lordsoffallen** [comment]
Thanks, didn't work but can that run on a notebook? that's where im experimenting with the datasets. Ideally i can run this on terminal and copy paste it yes but i was sort of thinking why not include this in `.list()` method. Was there a reason for it? Perhaps we enable via a param that runs catalog resolve and then list?

**Comment by merelcht** [comment]
Interesting! When we were doing user research and validation on this feature the use case of resolving in the notebook didn't  come up, so we only added the CLI command. @ElenaKhaustova can the above be done in an easy way using the new `CatalogResolver`?

**Comment by ElenaKhaustova** [comment]
`catalog.list()` lists datasets in the catalog which different from patterns.

With the `CatalogConfigResolver` it will be possible to list the patterns like so:

```
In [20]: catalog.config_resolver.list_patterns()
Out[20]: ['{name}_data', 'out-{dataset_name}', '{dataset_name}#csv', 'in-{dataset_name}']
```

But we now can output the full pattern configuration with the private properties

```
In [21]: catalog.config_resolver._dataset_patterns
Out[21]:

{
    '{name}_data': {
        'type': 'pandas.CSVDataset',
        'filepath': 'kedro-tests/default/data/01_raw/{name}_data.csv'
    },
    'out-{dataset_name}': {
        'type': 'pandas.CSVDataset',
        'filepath': 'kedro-tests/default/data/test/{dataset_name}.csv'
    },
    '{dataset_name}#csv': {
        'type': 'pandas.CSVDataset',
        'filepath': 'kedro-tests/default/data/01_raw/{dataset_name}.csv'
    },
    'in-{dataset_name}': {
        'type': 'pandas.CSVDataset',
        'filepath': 'kedro-tests/default/data/test/{dataset_name}.csv'
    }
}
```

We definitely can consider making this interface public if there's a demand but rather via `CatalogConfigResolver` than `catalog.list()`

**Comment by lordsoffallen** [comment]
I am only interested in the resolved catalog names actually. Given my example pattern, if my node inputs or outputs something called `01_raw.data#df` I wanna be able to see it in the `catalog.list()`. I often forget the name so i fallback to listing and copying the catalog name but with generic patterns it is not quite possible. If not by default, maybe something like `catalog.list(resolve_patterns=True)` so that it extracts names from nodes that refers to it.

**Comment by noklam** [comment]
Can we close this as duplicated with https://github.com/kedro-org/kedro/issues/331?

**Comment by lordsoffallen** [comment]
> Can we close this as duplicated with #331?

I guess you have the wrong link, that points to a PR from 4 years ago regarding documentation fix :)

**Comment by noklam** [comment]
Sorry, I mean Can we close this as duplicated with https://github.com/kedro-org/kedro/issues/3312

**Comment by lordsoffallen** [comment]
> Sorry, I mean Can we close this as duplicated with #3312

Ah yes, looks duplicated. We can close it yes
