### ISSUE TITLE
Release `kedro`

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#4198]
### Description

Release Kedro version `0.19.9`

To do:

- [x] Clarify that `KedroDataCatalog` is an experimental feature and users should still expect breaking changes while we're developing it.
- [ ] Merge https://github.com/kedro-org/kedro/pull/4145

**Comment by ankatiyar** [comment]
Reminder to update `kedro-sphinx-theme` version here for the release
https://github.com/kedro-org/kedro/blob/f1d37513097471fa868e0b1e0d917c1ba7c35894/pyproject.toml#L89

**Comment by lrcouto** [comment]
Waiting on https://github.com/kedro-org/kedro/pull/4216 as well.

**Comment by ElenaKhaustova** [comment]
> Waiting on #4216 as well.

Merged
