### ISSUE TITLE
READ ME FIRST! Join Kedro for Hacktoberfest 2024!

### ISSUE THREAD

**Issue by ankatiyar** [kedro-org/kedro#4203]
![image](https://github.com/user-attachments/assets/25213713-f551-468c-bb86-9b6e28d0876d)

If you want to contribute to Kedro for Hacktoberfest, this issue will help get you started!

* Sign up for [Hacktoberfest](https://hacktoberfest.com/)!
* We have the following repositories that we are accepting contributions for:
    * [kedro](https://github.com/kedro-org/kedro)
    * [kedro-plugins](https://github.com/kedro-org/kedro-plugins)
    * [kedro-viz](https://github.com/kedro-org/kedro-viz) 
    * [kedro-starters](https://github.com/kedro-org/kedro-starters)
* Find the Kedro issue you want to work on [from the "To Do" section of our Hacktoberfest issue tracker](https://github.com/orgs/kedro-org/projects/9). 
* Write a comment on the issue to indicate that you want to tackle it, and then get working!

> [!IMPORTANT]  
> Let's avoid ["cookie licking"](https://www.redhat.com/en/blog/dont-lick-cookie) 🍪! If you're unable to continue working on any issues, please say so and let someone else take a stab at it!

If you need to ask us for information, clarification, or help in the comments of the issue you are working on or give us a shout on [our Slack workspace](https://slack.kedro.org/).

### Contribute to our code
* Read the following contribution guides depending on the repository you're working on:
    * [Guidelines for contributing to **kedro**](https://github.com/kedro-org/kedro/wiki/Guidelines-for-contributing-developers)
    * [Guidelines for contributing to **kedro-viz**](https://github.com/kedro-org/kedro-viz/blob/main/CONTRIBUTING.md)
    * [Guidelines for contributing to **kedro-datasets**](https://github.com/kedro-org/kedro-plugins/blob/main/kedro-datasets/CONTRIBUTING.md)
* Make sure all the tests pass on your PR and the documentation is update in line with your changes.

### Contribute to our documentation
* Find tickets that are labelled "Hacktoberfest" as well as "Component: Documentation 📄".
* Read the [Guidelines for contributing to docs](https://github.com/kedro-org/kedro/wiki/Contribute-to-the-Kedro-documentation).
* Also read the [Kedro documentation style guide](https://github.com/kedro-org/kedro/wiki/Kedro-documentation-style-guide).

🎃 Happy hacking! 🎃

**Comment by ankatiyar** [comment]
Should we close this as well as this project - https://github.com/orgs/kedro-org/projects/9? @astrojuanlu @merelcht

**Comment by astrojuanlu** [comment]
Now it's [Closember](https://web.archive.org/web/20230923004619/https://closember.org/) 😉 

![image](https://github.com/user-attachments/assets/c941e392-d678-41b5-8fc3-4c83b2020ff4)

Closing!
