### ISSUE TITLE
Feature: Support python interpreter arguments in kedro run?

### ISSUE THREAD

**Issue by galenseilis** [kedro-org/kedro#4245]
# Description

I would like to propose adding support for passing additional parameters to the Python interpreter within the `kedro run` command. Currently, there is no straightforward way to run a Kedro pipeline with custom interpreter flags (e.g., running in optimized mode with `-O`). This limitation makes it difficult for users who want to leverage specific Python interpreter features or optimizations when executing their pipelines.

# Context

This change is important because certain Python interpreter options can impact the performance or behavior of a pipeline. 

For example, running in optimized mode can lead to faster execution times, which can be crucial for time-sensitive deliveries. Having 'extra validation' that is too expensive to run repeatedly in production still be easy to globally turn off would be appealing to me. Such validations would be recommended only for very expensive checks (e.g. checking properties of network data models using metrics that involve expensive search algorithms).

Additionally, users may want to pass other flags. By enabling the passing of these parameters, Kedro would offer greater flexibility and control over the execution environment, benefiting not only individual users but also teams working on large-scale data projects.

# Possible Implementation

I would have to look more at Kedro's source to provide meaningful suggestions on implementation. It is a bit easier to describe what a user would see (as below).

The implementation could involve introducing a new command-line option, such as `--python-args`, to the `kedro run` command. This option would accept a string of additional arguments that would be passed directly to the Python interpreter. For instance:

```bash
kedro run --python-args "-O -m some_module"
```

```bash
kedro run --python-args "-OO -m some_module"
```

Under the hood, Kedro would modify the command used to invoke the Python interpreter to include these additional arguments. Careful attention should be paid to ensure that existing functionalities remain intact and that the parsing of arguments is handled gracefully. It isn't my intent to break any current functionality with this feature, but only to extend. My greatest concern about this recommendation is how unexpected behaviour could occur from modifying the runtime environment.

# Possible Alternatives

At least for equivalent functionality of Python's optimized mode, I think the main alternatives that are already provided by Kedro would be based on using the [existing modifications](https://docs.kedro.org/en/stable/development/commands_reference.html#modifying-a-kedro-run) to `kedro run` to filter what parts of the project are run. 

Another option for adjusting what parts of the code are run in the project could be done with a `parameters.yml` file.

I'm not sure what would be an existing replacement for adjusting the interpreter behaviour in general.

If supporting all python interpreter parameters is not feasible or reasonable, then another alternative is to just support `-O` and `-OO` for optimized mode and optimized mode with docstrings stripped (respectively).

**Comment by galenseilis** [comment]
Although, I should have a closer look at [runners](https://docs.kedro.org/en/stable/nodes_and_pipelines/run_a_pipeline.html)...

**Comment by SajidAlamQB** [comment]
Thank you @galenseilis for the detailed feature request! This is an interesting proposal but as you said, the feature could involve changes to how Kedro invokes the Python interpreter. We’ll add this to our backlog for discussion.

**Comment by astrojuanlu** [comment]
Hi @galenseilis ! You can try

```
$ python -OO -m kedro run --pipeline data_processing
```

I don't know what other modules you want to call, but for example you can do this as well:

```
$ python -OO -m pdb -m kedro run -p data_processing
> /Users/juan_cano/Projects/QuantumBlackLabs/tmp/test-kedro-vertexai/.venv/lib/python3.10/site-packages/kedro/__main__.py(1)<module>()
-> """Entry point when invoked with python -m kedro."""  # pragma: no cover
(Pdb) 
```

Would that work for your use case?

**Comment by galenseilis** [comment]
@astrojuanlu It absolutely does! Thank you!
