### ISSUE TITLE
.parquet not .pq

### ISSUE THREAD

**Issue by gdmcbain** [kedro-org/kedro#4253]
## Description

[As discussed on the Slack yesterday](https://kedro-org.slack.com/archives/C03RKP2LW64/p1729651965925399), the tutorial at the step [Create a data processing pipeline](<https://docs.kedro.org/en/stable/tutorial/create_a_pipeline.html#preprocessed-data-registration>) writes Parquet as `.pq` which doesn't seem to be the standard suffix, which is `.parquet`; it's not recognized by, for example, [Data Wranger](<https://code.visualstudio.com/docs/datascience/data-wrangler#_launch-data-wrangler-directly-from-a-file>).

I propose changing all uses of `.pq` to the standard `.parquet`.

### Documentation page (if applicable)

Searching for `.pq` matches five files, two in tests and three in docs; e.g.:

https://github.com/kedro-org/kedro/blob/c2d7100a6bdf0dd51e80a2eade0b5d3f3a71184b/docs/source/tutorial/create_a_pipeline.md?plain=1#L203

**Comment by deepyaman** [comment]
@gdmcbain Do you want to open a PR to address this? I agree that .pq is nonstandard (or at least .parquet is much more common) and see no reason not to make this docs change.

**Comment by gdmcbain** [comment]
Yes, just running the test suite locally now.  Ta.

**Comment by SajidAlamQB** [comment]
Completed in: https://github.com/kedro-org/kedro/pull/4254
