### ISSUE TITLE
Can we remove `LambdaDataset`?

### ISSUE THREAD

**Issue by merelcht** [kedro-org/kedro#4292]
## Description
I'm wondering if anyone is using the `LambdaDataset` at all.

## Context
While going through the codebase to see what parts need work before Kedro `1.0.0` I came across `LambdaDataset`. Other than linting/typing changes, it hasn't been touched since 2019.

**Comment by Galileo-Galilei** [comment]
Just my two cents - I never ever see someone use it.

**Comment by astrojuanlu** [comment]
We are giving the community a few days to weigh in ahead of deprecating `LambdaDataset`, pending removal in Kedro 0.20.

To note, this section https://docs.kedro.org/en/stable/nodes_and_pipelines/run_a_pipeline.html#output-to-a-file needs to be deleted or completely rewritten.
