### ISSUE TITLE
While running multiple nodes, option to let kedro run non-dependent nodes (on failed node) in case of a node failure

### ISSUE THREAD

**Issue by debugger24** [kedro-org/kedro#503]
## Description
While running multiple nodes, as of now, kedro stops running if any node encounters any error. It would be nice to have an option to let kedro run the rest of the nodes which are not dependent on the failed node. An optional args in kedro cli to enable this would be great. Let me know what you think about this.

## Context
As of now, we run multiple nodes in dev overnight, each job takes hours to execute if any node fails we don't even run nodes which are not dependent on the failed node and our program sits idle until we take action on it. It would be great if it executes rest, and later we can run only failed and nodes dependent on the failed node.

**Comment by lorenabalan** [comment]
Hi @debugger24 wouldn't switching the runner to `ThreadRunner` or `ParallelRunner` fix this? Or is it not a viable option for you here?

**Comment by debugger24** [comment]
@lorenabalan Yes I am using `ThreadRunner` only. But the problem is when one node fails. It stops the complete pipeline and doesn't even run the other nodes which were not dependent on anyway on the failed node.

**Comment by lorenabalan** [comment]
Ah okay it took me a while to visualise it I'm with you now. Sadly there's no way to do this out-of-the-box, you'll need to define and use a custom runner that has that capability. I'll make a note of this scenario though for future discussions, leaving this open for others to contribute their thoughts/ideas/use cases/etc.

**Comment by rafaelgildin** [comment]
How can i create this custom runner?

**Comment by deepyaman** [comment]
@rafaelgildin We want to modify the exception handling when running nodes in `ThreadRunner` (see https://github.com/kedro-org/kedro/blob/0.18.3/kedro/runner/thread_runner.py#L133-L135). Instead of suggesting how to resume execution reraising the exception, we should `continue` (after perhaps logging out the error). Finally, even though this would achieve the desired result, it would hang in an infinite loop after all "reachable" nodes have been run. To resolve this, we should remove any dependencies of the failed node from `todo_nodes` during exception handling.

**Comment by noklam** [comment]
I think it's a reasonable request, but how would one continue with the partially executed DAG?

Naturally, you want to fix the failing node and execute the unfinished pipeline, and eventually, you will execute the full DAG. The danger of this is that within a kedro run, kedro make sure all your dependency are correct, but manually tracking the DAG and trying to re-execute some node is **error-prone**. This is almost like doing the Orchestrator job manually (In my mind, I see a full Airflow DAG, some are green (executed), some are red (failed), and we want to eventually make it all green)

**Comment by rafaelgildin** [comment]
@deepyaman 
I'll try this out, thanks!

@noklam 
I'm thinking in airflow too but sometimes you won't have all nodes green.
E.g. multiple models to make batch predictions.  Some will have data to predict and will finish as green, while others might not have any data, so will run into error and finish in red.

**Comment by jmholzer** [comment]
Technical Design discussion 30/11/2022

1. What is the status of this feature on `SequentialRunner`?

-

2. For which runners should this be implemented? 

-

3. Next steps

-

**Comment by noklam** [comment]
To move this to `airflow.provdiers`, we will have to move the implementation of `KedroOperator` to the `airflow` repository. 

Questions:
* Can we move only the `KedroOperator`, but not the other `hooks` implementation? What's the requirement to become an official provider

**Comment by astrojuanlu** [comment]
This now exists at https://github.com/kedro-org/kedro/blob/feat/softfail-runner/kedro/runner/softfail_runner.py - what does the team think of including it in the framework?

And if we don't feel like including it, is there a chance maybe @noklam publishes it as a separate project that can be pip-installed separately? So we don't signal that we're officially maintaining it.

**Comment by jmnunezd** [comment]
> * Kedro is mostly useful for experimentation, many users have need for 'all or nothing'.

what do you mean with "many users have need for 'all or nothing." can you please elaborate more?

I don't totally agree with this "Kedro is mostly useful for experimentation"
For what I have seen with clients, Kedro is increasingly being seen as a good tool not only for experimenting but for reliably running pipelines in production. (maybe I misunderstood you?)

Also with time, pipelines tend to increase in size, sometimes covering more than just one objective, for example in current study I have a kedro project with some pipelines that perform a task "A" and now in the near future I'll be using the same kedro project to develop new pipelines that will cover a new independent task "B". I would love to use the SoftFailRunner when running to ensure my task "A" is never disrupted by a fault on the new and less tested task "B"

**Comment by noklam** [comment]
> This now exists at https://github.com/kedro-org/kedro/blob/feat/softfail-runner/kedro/runner/softfail_runner.py (and the blog post is https://kedro.org/blog/build-a-custom-kedro-runner) - what does the team think of including it in the framework?

> And if we don't feel like including it, is there a chance maybe @noklam publishes it as a separate project that can be pip-installed separately? So we don't signal that we're officially maintaining it.

I am happy to do so, it would be a good example for Runner plugin (which I am not aware of any yet).

**Comment by noklam** [comment]
> I don't totally agree with this "Kedro is mostly useful for experimentation"
> For what I have seen with clients, Kedro is increasingly being seen as a good tool not only for experimenting but for reliably running pipelines in production. (maybe I misunderstood you?)

I forgot who leave that comment, but I think what we mean is:
- During "development mode", you want to fail eagerly.
- During "deployment mode", you want to delay the failure i.e. SoftfailRunner
  - It can also be used for debugging, if you have multiple faulty inputs,  you can discover all the fail nodes at once, where as the eager mode would terminated ASAP and you need to iterate to fix all the problem. 

See the Kedro SoftfailRunner blog post: https://kedro.org/blog/build-a-custom-kedro-runner

**Comment by astrojuanlu** [comment]
And now lives in a repo https://github.com/noklam/kedro-softfail-runner

Please use it and let us know if it fulfills your use case.

In the meantime, I'm closing this issue.
