### ISSUE TITLE
Include yaml examples in dataset docs

### ISSUE THREAD

**Issue by WaylonWalker** [kedro-org/kedro#579]
## Description
The most common way I look up the docs for a DataSet is to google search for things like `kedro csv`, which lands me in the [kedro.extras.datasets.pandas.CSVDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.pandas.CSVDataSet.html) docs.  This is great to see the api, but it is a bit confusing that the suggested catalog method is to use yaml, but the docs are in python.

### Search for the docs

![image](https://user-images.githubusercontent.com/22648375/96754392-db49c880-1396-11eb-928e-9c7da420c033.png)

### Current page

Currently the docs look like this, and do not include good examples for creating real catalog entries with the dataset.

![image](https://user-images.githubusercontent.com/22648375/96754068-65456180-1396-11eb-8461-55ae629c5ddd.png)

But the suggested way to add datasets to the catalog is with the yaml api, which looks like this.

![image](https://user-images.githubusercontent.com/22648375/96754215-96be2d00-1396-11eb-8998-15dc64ecd476.png)

## Context
Aligning the preferred/suggested method of creating catalogs with likely entrypoints into the docs would encourage users to use that method and have less confusion for those who aren't quite sure of the difference between the python api and yaml api.

## Possible Implementation
Include yaml examples in the DataSet docstrings, with backlinks to how to implement the catalog in anyway that is documented.  If the python api is left in as an example there should be a link to show how to implement that example into the project.

**Comment by yetudada** [comment]
I've always wondered about this too. I think it would be great to see YAML equivalent examples for the datasets. I'll create hacktoberfest tickets for this.

**Comment by WaylonWalker** [comment]
Seems that there is interest in the change?  How would you want this proposed change to look?


## Suggestion

``` rst
    Example Using Python API:
    ::

        >>> from kedro.extras.datasets.pandas import CSVDataSet
        >>> import pandas as pd
        >>>
        >>> data = pd.DataFrame({'col1': [1, 2], 'col2': [4, 5],
        >>>                      'col3': [5, 6]})
        >>>
        >>> # data_set = CSVDataSet(filepath="gcs://bucket/test.csv")
        >>> data_set = CSVDataSet(filepath="test.csv")
        >>> data_set.save(data)
        >>> reloaded = data_set.load()
        >>> assert data.equals(reloaded)
        
    Example Creating a catalog entry with the YAML API:
    ::
        
        data_set
            type: pandas.CSVDataSet
            filepath:  gcs://bucket/test.csv  
         


```

**Comment by lorenabalan** [comment]
I like this suggestion. We welcome PRs on this. 🙂

**Comment by nicpayne713** [comment]
> I like this suggestion. We welcome PRs on this. 🙂

Loren,
I'm interested in participating in this issue... What is the format I should follow for PRs? One per dataset example or should I add a bunch and open one PR for them all?
If there's docs on this feel free to just "lmgtfy" your response with the link and I'll read up - it's late and I'm on mobile so I wanted to commit before losing motivation in the morning :)

**Comment by noklam** [comment]
I think we have the YAML API doc for CSVDataSet now, but we still need help with a few more datasets. Here is the list of Datasets that we need help with. 

PRs are very welcomed🙏🏼! 

(I try to order it base on usages)
- [ ] [ParquetDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.dask.ParquetDataSet.html#kedro.extras.datasets.dask.ParquetDataSet)
- [ ]  [APIDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.api.APIDataSet.html#kedro.extras.datasets.api.APIDataSet)
- [ ] [pandas.FeatherDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.pandas.FeatherDataSet.html#kedro.extras.datasets.pandas.FeatherDataSet)
- [ ] [yaml.YAMLDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.yaml.YAMLDataSet.html#kedro.extras.datasets.yaml.YAMLDataSet)
- [ ] [tracking.JSONDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.tracking.JSONDataSet.html#kedro.extras.datasets.tracking.JSONDataSet)
- [ ] [tracking.MetricsDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.tracking.MetricsDataSet.html#kedro.extras.datasets.tracking.MetricsDataSet)
- [ ] [TensorFlowModelDataset](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.tensorflow.TensorFlowModelDataset.html#kedro.extras.datasets.tensorflow.TensorFlowModelDataset)


Less common datasets:
- [ ] [TextDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.text.TextDataSet.html#kedro.extras.datasets.text.TextDataSet)
- [ ] [networkx.JSONDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.networkx.JSONDataSet.html#kedro.extras.datasets.networkx.JSONDataSet)
- [ ] [GraphMLDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.networkx.GraphMLDataSet.html#kedro.extras.datasets.networkx.GraphMLDataSet)
- [ ]  [GMLDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.networkx.GMLDataSet.html#kedro.extras.datasets.networkx.GMLDataSet)
- [ ] [MatplotlibWriter](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.matplotlib.MatplotlibWriter.html#kedro.extras.datasets.matplotlib.MatplotlibWriter)
- [ ] [HoloviewsWriter](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.holoviews.HoloviewsWriter.html#kedro.extras.datasets.holoviews.HoloviewsWriter)
- [ ]  [GeoJSONDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.geopandas.GeoJSONDataSet.html#kedro.extras.datasets.geopandas.GeoJSONDataSet)
- [ ] [EmailMessageDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.email.EmailMessageDataSet.html#kedro.extras.datasets.email.EmailMessageDataSet)
- [ ] [BioSequenceDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.biosequence.BioSequenceDataSet.html#kedro.extras.datasets.biosequence.BioSequenceDataSet)

**Comment by levimjoseph** [comment]
@noklam are y'all still looking for help with YAML API examples? If so, I think this is something I could work.

**Comment by noklam** [comment]
@levimjoseph Yes! Help are very welcome! The list above is still valid.

**Comment by levimjoseph** [comment]
@noklam working on a PR right now. 

I count 35 unique datasets.
- 15 have JSON
- 16 are in your priority list above
- 4 are **not** in your priority list above

These four are:
1. [XMLDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.pandas.XMLDataSet.html#kedro.extras.datasets.pandas.XMLDataSet)
2. [ImageDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.pandas.XMLDataSet.html#kedro.extras.datasets.pandas.XMLDataSet)
3. [plotly.PlotlyDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.plotly.PlotlyDataSet.html#kedro.extras.datasets.plotly.PlotlyDataSet)
4. [plotly.JSONDataSet](https://kedro.readthedocs.io/en/stable/kedro.extras.datasets.plotly.JSONDataSet.html#kedro.extras.datasets.plotly.JSONDataSet)

I am going to include these in the "less common datasets" group and prioritize accordingly unless you instruct me otherwise.

**Comment by noklam** [comment]
@levimjoseph Awesome, I have just included the 4 datasets in the list. Ideally, all datasets should have a working YAML/Python API example, but don't feel pressured that you have to update all.

**Comment by levimjoseph** [comment]
@noklam sounds good!

I am probably going to do them in two PRs. One for priority, one for the other list. 

This would be my first contributor commit on this repo. Do y'all prefer forks or branches?

**Comment by noklam** [comment]
Closing this since the `CSVDataSet` example is in place.
#1762 will be the new issue to track the progress of enhancing DataSet API Docs

CC @levimjoseph
