### ISSUE TITLE
Tutorial walk-through 🎥

### ISSUE THREAD

**Issue by yetudada** [kedro-org/kedro#606]
## Description
We're running usability tests and would love for you to record walking through our tutorials. The idea for this ticket is that you do a screen capture walking through one of more of the following examples: 
- [Hello World!](https://kedro.readthedocs.io/en/stable/02_get_started/03_hello_kedro.html) (15 minutes)
- [Iris Dataset](https://kedro.readthedocs.io/en/stable/02_get_started/05_example_project.html) (30 minutes)
- [Spaceflights](https://kedro.readthedocs.io/en/stable/03_tutorial/01_spaceflights_tutorial.html) (90 minutes)

Please talk us through what you're trying to do, so maintain sound on and then remember to send us the link to the recording if you upload it on Google Drive or Box 🎥 . You might even want to try use a new dataset, or do a different example, in this case then please check out #541. 

## Context
This is not a test of your Python abilities at all. It's focused on really evaluating how easy Kedro is to use. If you struggle with points then it likely means we have some to work to do with making it easier.

**Comment by navh** [comment]
I recorded myself wandering through the [Space Flight Tutorial](https://youtu.be/RugiARGNLbE). I'd already started once so you don't get to see me struggling to get conda to cooperate. No real problems other than tripping over whitespace problems a couple of times. Great tutorial, thanks for putting it together :)

**Comment by WaylonWalker** [comment]
I started the spaceflights tutorial this morning, before I even had my coffee.

https://www.twitch.tv/videos/1045469259


----

## Notes

* I think I completely botched it as I started with the starter rather than an empty kedro new
* initial push to non-main branch makes that branch default
* no virtual environment was suggested

Adding the following line caused pyright to complain that `create_pipeline` was not used.  This is more on pyright as it should respect #NOQA

``` python
from .pipeline import create_pipeline  # NOQA
```

A better way might be the following.

``` python
__all__ = ['create_pipeline']
from .pipeline import create_pipeline  # NOQA
```

I'll continue in another session.  I spent way too long creating a virtual environment while recording.

**Comment by WaylonWalker** [comment]
I had my mic on mute 2x but finished the tutorial regardless.

https://www.twitch.tv/videos/1048621738

---

## Notes
* ~Above should be below https://kedro.readthedocs.io/en/stable/03_tutorial/04_create_pipelines.html#extend-the-data-processing-pipeline~ FIXED
* Might be worth noting that you can see your parameters in `context.params` https://kedro.readthedocs.io/en/stable/03_tutorial/04_create_pipelines.html#configure-the-input-parameters
* Consider editing requirements.in only https://kedro.readthedocs.io/en/stable/04_kedro_project_setup/01_dependencies.html#project-specific-dependencies
* it was not clear that the tutorial was complete from clicking next after each page https://kedro.readthedocs.io/en/stable/03_tutorial/06_visualise_pipeline.html


At the end I converted all the imports to use `find-kedro`

**Comment by yetudada** [comment]
I'm going to close this issue in favour of #2091. We're going to prioritise interventions. Thank you so much @WaylonWalker and @navh!
