### ISSUE TITLE
Adding execution_options to kedro.extras.datasets.pandas.SQLQueryDataSet

### ISSUE THREAD

**Issue by jacobweiss2305** [kedro-org/kedro#752]
## Description
Is it possible to add execution_options to kedro.extras.datasets.pandas.SQLQueryDataSet?

For example, I would like to add stream_results=True to the connection string.
```python
  engine = create_engine(
      "postgresql://postgres:pass@localhost/example"
  )
  conn = engine.connect().execution_options(stream_results=True)
```
## Context
This article https://pythonspeed.com/articles/pandas-sql-chunking/ displays that its helpful to read large amounts of data using pandas with stream_results. I would like to use this method with SQLQueryDataSet.

**Comment by lorenabalan** [comment]
Hi @jacobweiss2305 thank you for raising this, and thank you for including the article link for context - that was definitely an interesting read! This makes sense to me, I'll discuss it with the team but tagging @deepyaman too in the meantime, who I think might be interested in this too?

**Comment by mzjp2** [comment]
For visibility, this was also asked on SO: https://stackoverflow.com/questions/67182358/adding-stream-results-true-execution-options-to-kedro-extras-datasets-pandas-s/67182708#67182708

**Comment by jacobweiss2305** [comment]
@mzjp2, per your SO response, would I need to create a custom dataset using Kedro IO?

**Comment by MerelTheisenQB** [comment]
Hi @jacobweiss2305, are you still interested in having this feature? And if so, would you be able to make a contribution PR for it?

**Comment by jacobweiss2305** [comment]
Yep I can make a pr

**Comment by clotildeguinard** [comment]
Hello! I see that this issue received no contribution so far. I am preparing a PR, will submit soon.

**Comment by MerelTheisenQB** [comment]
Wonderful! Thank you so much @clotildeguinard 😄
