### ISSUE TITLE
[KED-2726] Enhance documentation on how to execute a packaged kedro pipeline via a python script

### ISSUE THREAD

**Issue by ppsimatikas** [kedro-org/kedro#804]
## Description
It would be great to add an example on how to execute a packaged kedro pipeline via a python script in this [documentation page](https://kedro.readthedocs.io/en/stable/03_tutorial/08_package_a_project.html)

## Context
I had to execute my packaged kedro pipeline via a python script, on a Databricks Job production environment.

## Possible Implementation
Enhance this [documentation page](https://kedro.readthedocs.io/en/stable/03_tutorial/08_package_a_project.html)

By adding an example on how to execute the pipeline via python.

```
import sys
from kedro_spaceflights.__main__ import main

sys.argv += ["--pipeline", "default"]
main()
```

**Comment by datajoely** [comment]
Good suggestion - will add to our backlog!

**Comment by lorenabalan** [comment]
Closing this as resolved in https://github.com/kedro-org/kedro/pull/1364
